### ISSUE TITLE
Make the font size larger in the API section

### ISSUE THREAD

**Issue by pdobsan** [janet-lang/janet#100]
The documentation is great, I ran through it when I discovered _janet_.

My only complaint is that the font size of the description paragraphs are too small in the Core API section. Would it be possible to use the same font size for the API part as everywhere else in the docs?

**Comment by bakpakin** [comment]
Sure, that looks fine to me

**Comment by bakpakin** [comment]
Updated.

**Comment by pdobsan** [comment]
Thank you. That really looks larger although the font in the descriptions is still not the same as in other places, more fragile, thinner.  See the difference for example at https://janet-lang.org/api/array.html
Just nitpicking, maybe I need glasses.

**Comment by bakpakin** [comment]
The docstrings are in a monospaced font so they look a bit different. This is because they are preformatted via the pre tag.

**Comment by pdobsan** [comment]
> The docstrings are in a monospaced font so they look a bit different.

I know, they just look ugly in a docs, IMHO.
