### ISSUE TITLE
Add library function to check if array contains item

### ISSUE THREAD

**Issue by autumnull** [janet-lang/janet#1000]
A library function to check if an array contains an item would be really helpful I think. Maybe called something like `array/contains?`. I don't know if this exists already and I am just not finding the documentation for it but it would be good to know either way!

It could even take multiple input types e.g. a tuple or a table and just be called `contains?`.

Currently I have been using something like this but it's a bit clunky:
```janet
(defn contains? [arr item]
  (not= nil (find
    (fn [x] (= item x))
    arr)))
```

**Comment by bakpakin** [comment]
The core function `index-of` can be used for this purpose.

**Comment by autumnull** [comment]
That's a good point and i'd forgotten about `index-of`, thank you.

I guess `index-of` still requires it to be wrapped in a `nil?` function because if it's the first element in the array then the index `0` is not truthy. I still feel like it's a little clunky to have this be the standard way to check containment:

```janet
(defn contains? [arr item]
  (not= nil (index-of item arr)))
```

It's definitely better than the example I gave above though.

**Comment by pepe** [comment]
I do not think so.. `0` is truthy `(truthy? 0)`. And `nil` is falsy, so there is no need to check it.

**Comment by autumnull** [comment]
You're right, that's my bad! That's useful to know though, thank you both
