### ISSUE TITLE
`ffi/context` not delegating to system search paths

### ISSUE THREAD

**Issue by jeannekamikaze** [janet-lang/janet#1001]
`ffi/context` only works with either absolute or relative library paths, it does not delegate the search to the OS. This seems to be caused by [`get_processed_name`](https://github.com/janet-lang/janet/blob/master/src/core/util.c#L889), which currently assumes that if you don't specify a relative ("./") or an absolute ("/") path, you want a relative path. The request is to let the OS do the search when we only specify the library name, e.g. "libglfw.so.3". Thank you.

Example:

```
(ffi/context "libglfw.so.3" :lazy true)

error: ./libglfw.so.3: cannot open shared object file: No such file or directory

openat(AT_FDCWD, "./libglfw.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "error: ./libglfw.so.3: cannot op"..., 81error: ./libglfw.so.3: cannot open shared object file: No such file or directory
```

Should be working otherwise:

```
$ ldconfig -p | grep glfw
libglfw.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/libglfw.so.3
libglfw.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libglfw.so
```

**Comment by jeannekamikaze** [comment]
Thank you. With the latest Janet I can now do:

```
(ffi/context "libglfw.so" :lazy true)
```

I think an extra step would be to make this cross-platform by being able to type:

```
(ffi/context "glfw" :lazy true)
```

On unix systems this would prepend `lib` and append `.so` to the path; on Windows just append `.dll`.

**Comment by bakpakin** [comment]
I suppose you could write a function to do just that manually, but you should still be able to pass strings unprocessed to dlopen/LoadLibrary to avoid the original problem. Perhaps something like:

```
(ffi/context (fii/libname "glfw") :lazy true)
```

to make it explicit. I wouldn't expect all libraries to follow this pattern.
