### ISSUE TITLE
unref needs to be documented

### ISSUE THREAD

**Issue by masukomi** [janet-lang/janet#1004]
in v1.15.3  unref combinator was added to pegs. 

Alas, it was not documented anywhere that I can find, and I only found out about its existence via a blog post where someone mentioned it. 

I'm still not clear on how it works.

**Comment by sogaiu** [comment]
IIRC, @pyrmont's https://github.com/janet-lang/janet/issues/641 issue was a trigger for this addition.

The commit that added `unref` includes a test that demonstrates some usage too: https://github.com/janet-lang/janet/commit/96513665d6538c5fee287ea71596e7d5332008c3#diff-efeb1736cf40499ec87a9ef2ded19f1f4304718d7d6553d74abafad028a31e0c

Although not official, here's some documentation along with a bit of sample code: https://github.com/sogaiu/margaret/blob/master/examples/unref.janet

On a side note, possibly this issue might be better off living in the janet-lang.org repos: https://github.com/janet-lang/janet-lang.org

**Comment by bakpakin** [comment]
Yes, I may have changed the name last minute to match with `backref`. Just added the documentation to janet-lang.org in this commit, almost verbatim from the original commit message. https://github.com/janet-lang/janet-lang.org/commit/7aa41e827b3ab03a929825599a4647e437ed14f3
