### ISSUE TITLE
Assert failure in ffi test

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#1009]
I am trying the ffi example from the file `test.janet` and the assertion on line 102 fails with:

```
error: assert failure in (= 9876543210 (double-lots-2 0 1 2 3 4 5 6 7 8 9))
  in _thunk [examples/ffi/test.janet] (tailcall) on line 102, column 1
```

`tracev` call from line 90 prints:

```
trace [examples/ffi/test.janet] on line 90, column 9: (double-lots-2 0 1 2 3 4 5 6 7 8 9) is 8976543210
```

When I put:

```
printf("%f %f %f %f %f %f %f %f %f %f", a, b, c, d, e, f, g, h, i, j);
```

on line 59 in file `so.c`, it prints:

```
0.000000 1.000000 2.000000 3.000000 4.000000 5.000000 6.000000 7.000000 9.000000 8.000000
```

As always, it could be a user problem, and I will try to investigate a little more, but I thought I would let you know.

**Comment by sogaiu** [comment]
I got the same error output from executing:
```
janet examples/ffi/test.janet
```
from the repository root directory.

**Comment by bakpakin** [comment]
There were some fixes for windows that I guess had an effect on Linux, although they shouldn't have. I will investigate

**Comment by bakpakin** [comment]
On second look, an added function in the test code may have exposed a latent bug with the sysv64 abi when there are a lot of parameters. Still definitely a bug, though.

**Comment by sogaiu** [comment]
With https://github.com/janet-lang/janet/commit/1aea5ee00784ced3ce1ddde7d72f135aa900c33b I don't get the error output anymore.

**Comment by pepe** [comment]
The latest version doesn't fail anymore. Thank you very much!
