### ISSUE TITLE
Parse errors for "mismatched delimiters are unhelpful"

### ISSUE THREAD

**Issue by Techcable** [janet-lang/janet#1014]
I have an 100 line file and I get the following error

```
foo.janet:45:60: parse error: mismatched delimiter
```

This is not helpful :(

**Comment by Techcable** [comment]
Related error: `foo.janet:48:0: parse error: unexpected end of source, ( opened at line 5, column 1`

Maybe Janet could somehow backtrack and do a second pass to give more detailed errors. We should look at how other lisps do this :)

**Comment by bakpakin** [comment]
There isn't really a more descriptive error to give - you are given the line and column number - I guess we could also say what delimiter was found and what was expected?

No backtracking will be done, this is a parse error. The related error looks fine to me, I don't know what you have in mind.

**Comment by Techcable** [comment]
> I guess we could also say what delimiter was found and what was expected?

Yes please, this would be very helpful :)

Ideally I would like line and column indicators too. From what I can tell, this should already be possible based on the existing stack of internal state in the parser.

I did some looking at other lips (Racket, Clojure, Chicken Scheme, Chibi Scheme, and Guile) to see how they handle this.

Most of them actually give much less informative error messages than Janet does.

Clojure gives only marginally better errors, I would say Racket is the only one that is actually "good".
I would probably try to emulate this if reasonably possible.

<details>
    <summary> Comparison of errors</summary>

#### Janet
```
Janet 1.24.0-9ce7a2c linux/x64 - '(doc)' for help
repl:1:14: parse error: mismatched delimiter
repl:1:15: parse error: unexpected delimiter
```

 #### Racket
```
$ echo '[(])' | racket

> ; stdin:1:2: read-syntax: missing `)` to close preceding `(`, found instead `]`
;   [,bt for context]
> ; stdin:1:3: read-syntax: unexpected `)` [,bt for context]
> 
```

#### Clojure
```
$ echo "([)]" | clojure
Clojure 1.11.1
user=> Syntax error reading source at (REPL:1:4).
Unmatched delimiter: )
Syntax error reading source at (REPL:1:5).
Unmatched delimiter: ]
user=> 
Clojure 1.11.1
user=> Syntax error reading source at (REPL:1:4).
Unmatched delimiter: )
Syntax error reading source at (REPL:1:5).
Unmatched delimiter: ]
user=> 
```

#### Chicken Scheme
Gives a pretty [horrible backtrace](https://gist.github.com/Techcable/02845b2a47c35857b0e2e062b801d663), which only says that `[` and `)` don't match (no line info).
</details>

**Comment by Techcable** [comment]
Thank you so much. This is very helpful :)
