### ISSUE TITLE
cmt in PEGs does not work as expected

### ISSUE THREAD

**Issue by Spirati** [janet-lang/janet#1024]
It's possible that this may just be an issue of confusing documentation and I'm misusing this PEG feature, but I am unable to make even the most basic working example of `cmt` when trying to write PEGs; passing both anonymous and named functions as the third argument results in errors.
A basic example:
```janet
(defn test-function [& captures] true)

(def named-function-grammar '{
    :main (cmt (any :w) test-function)
})

(def anonymous-function-grammar '{
    :main (cmt (any :w) (fn [& captures] true))
})
```
Running `(pp (peg/match named-function-grammar "abc"))` yields
```
error: grammar error in (cmt (any :w) test-function), expected function|cfunction, got test-function
  in peg/match [src/core/peg.c] on line 1672
```
and running `(pp (peg/match anonymous-function-grammar "abc"))` yields
```
error: grammar error in (cmt (any :w) (fn [& captures] true)), expected function|cfunction, got <tuple 0x02D0E2A2A520>
  in peg/match [src/core/peg.c] on line 1672
```
To confirm, I checked `(type test-function)` and `(type (fn [&captures] true))`, both of which naturally returned `:function`. If I'm simply misusing the `cmt` function, an example in the documentation might be valuable to add, as the description as written feels misleading.

**Comment by bakpakin** [comment]
This kind of thing is better suited for the gitter help room - the issue is you need to use quasi quote around the entire grammar and then unquote the anonymous function.

**Comment by sogaiu** [comment]
Perhaps the discussions area is ok too?

@Spirati FWIW, there are some examples here for `cmt`: https://github.com/sogaiu/margaret/blob/master/examples/cmt.janet
