### ISSUE TITLE
`peg/replace-all` does not check `backmatch` captures properly

### ISSUE THREAD

**Issue by autumnull** [janet-lang/janet#1027]
I would expect the following 2 lines to give the same result (excepting the buffer vs string and array differences):

```janet
repl:1:> (peg/replace-all '(* (<- 1) 1 (backmatch)) "xxx" "aba cdc efa")
@"xxx cdc xxx"
repl:2:> (peg/match '(% (any (+ (/ (* (<- 1) 1 (backmatch)) "xxx") (<- 1)))) "aba cdc efa")
@["xxx xxx efa"]
```

In particular i consider the second of these results to be the correct one for both instances.

**Comment by bakpakin** [comment]
Thanks for the find, issue is that PEG state is not reset properly between rule applications when iterating over the match string.
