### ISSUE TITLE
FFI: sysv64 calling convention incorrectly handles 9-16 byte structs

### ISSUE THREAD

**Issue by soxfox42** [janet-lang/janet#1034]
The System V AMD64 ABI specifies that structs larger than eight bytes (but no more than 16 bytes, as those are passed in memory), should be separated into two chunks of eight bytes, and each should be classified separately:
> If the size of the aggregate exceeds a single eightbyte, each is classified separately. Each eightbyte gets initialized to class NO_CLASS.

The current implementation of FFI in Janet doesn't seem to account for this, and attempts to pass the entire struct in a single register. This does work in some cases, as long as there are no arguments passed in the following registers. This is why `intintint_fn` works correctly in the test. If the following registers are used, the struct will be partially overwritten, and the later arguments will be passed in the wrong registers.

Code to help reproduce and test this:

`examples/ffi/so.c`
```c
int intintint_fn_2(intintint iii, int i) {
    return i * (iii.a + iii.b + iii.c);
}
```
`examples/ffi/test.janet`
```janet
(ffi/defbind intintint-fn-2 :int [iii intintint i :int])
(tracev (intintint-fn-2 [10 20 30] 3))
```

**Comment by soxfox42** [comment]
An additional test case, which tests the case where the two eightbytes have different classes and should be passed in different register types:

```c
typedef struct {
    int a, b;
    float c, d;
} split;

float split_fn(split s) {
    return s.a * s.c + s.b * s.d;
}
```
```janet
(def split (ffi/struct :int :int :float :float))
(ffi/defbind split-fn :float [s split])
(tracev (split-fn [5 6 1.2 3.4]))
```

According to the calling convention, and verified by inspecting assembly output, fields `a` and `b` should be passed in `rdi`, while `c` and `d` should be passed in `xmm0`.

**Comment by bakpakin** [comment]
Thanks for the work investigating this, @soxfox42. Certainly the sysv64 abi here is a bit trickier to implement but we will need to get this fixed.

**Comment by bakpakin** [comment]
9-16 byte structs should be better handled now, both as parameters to functions and as return values in the sysv64 abi. @soxfox42 verify this and close at your discretion.

**Comment by soxfox42** [comment]
Yep, looks good. Latest build from master works fine with all the bindings I've thrown at it, so I'd say this is fixed.
