### ISSUE TITLE
FFI win64: passing a struct at slot 1 (arity >= 2) may overwrite the structs first field with 64 (0x40)

### ISSUE THREAD

**Issue by kamisori** [janet-lang/janet#1037]
```
repl:25:> (def ts (getTestStruct))
(6666 1111 2222 3333 4444 5555)
repl:26:> (printTestStructONLY (tracev ts))
trace on line 26, column 22: ts is (6666 1111 2222 3333 4444 5555)
zero 6666 one 1111 two 2222 three 3333 four 4444 five 5555nil     
repl:27:> (printTestStructAndInt (tracev ts) 9999999)
trace on line 27, column 24: ts is (6666 1111 2222 3333 4444 5555)
zero 64 one 1111 two 2222 three 3333 four 4444 five 5555, and six 9999999nil
repl:28:>
repl:29:> (printIntAndTestStruct 9999999 (tracev ts))
trace on line 29, column 32: ts is (6666 1111 2222 3333 4444 5555)
six 9999999 and zero 6666 one 1111 two 2222 three 3333 four 4444 five 5555nil
repl:30:>
```

using this C code:
```

#include "pch.h"
#include <stdio.h>
#include <cstdint>

#include <iostream>

BOOL APIENTRY DllMain(HMODULE hModule,
    DWORD  ul_reason_for_call,
    LPVOID lpReserved
)
{
    return TRUE;
}

typedef struct TestStruct {
    int zero;
    int one;
    int two;
    int three;
    int four;
    int five;
} TestStruct;

#define OUTAPI __declspec(dllexport)
extern "C" {
    OUTAPI TestStruct getTestStruct() {
        return { 6666, 1111, 2222, 3333, 4444, 5555 };
    }

    OUTAPI void printTestStructONLY(TestStruct ts) {
        printf("zero %d one %d two %d three %d four %d five %d", ts.zero, ts.one, ts.two, ts.three, ts.four, ts.five);
    }

    OUTAPI void printTestStructAndInt(TestStruct ts, int six) {
        printf("zero %d one %d two %d three %d four %d five %d, and six %d", ts.zero, ts.one, ts.two, ts.three, ts.four, ts.five, six);
    }

    OUTAPI void printIntAndTestStruct(int six, TestStruct ts) {
        printf("six %d and zero %d one %d two %d three %d four %d five %d", six, ts.zero, ts.one, ts.two, ts.three, ts.four, ts.five);
    }
}
```

and following janet source:
```
(ffi/context "C:\\bin\\_repos_\\FFITest\\x64\\Debug\\FFITest.dll")

(def ffiTestStruct
    (ffi/struct
        :int32 #0
        :int32 #1
        :int32 #2
        :int32 #3
        :int32 #4
        :int32)) #5

(ffi/defbind getTestStruct ffiTestStruct [])
(ffi/defbind printTestStructONLY :void [ts ffiTestStruct])
(ffi/defbind printTestStructAndInt :void [ts ffiTestStruct six :int])
(ffi/defbind printIntAndTestStruct :void [six :int ts ffiTestStruct])

(def ts (getTestStruct))
(printTestStructONLY (tracev ts))
(printTestStructAndInt (tracev ts) 9999999)
(printIntAndTestStruct 9999999 (tracev ts))
```

**Comment by kamisori** [comment]
i was able to work around this by patching raylib.dll by adding an unused field in id's place:

// Texture, tex data stored in GPU memory (VRAM)
typedef struct Texture {
    int WORKAROUND_JANET;
    unsigned int id;        // OpenGL texture id
    int width;              // Texture base width
    int height;             // Texture base height
    int mipmaps;            // Mipmap levels, 1 by default
    int format;             // Data format (PixelFormat type)
} Texture;

which made my ffi raylib test script run as expected:

![grafik](https://user-images.githubusercontent.com/293332/191038313-a697436c-ef7f-4fd2-b549-0eab06865380.png)

**Comment by bakpakin** [comment]
This is a very strange bug and I'm not sure if the exact preconditions for it are exactly what you have found, but requires taking a look.

**Comment by bakpakin** [comment]
I expect the bug has more to do with our code interpreting the win64 calling convention, especially related to structs and other items passed on the stack which could potentially be clobbered by other code since we are using some hacks to avoid assembly, which is not allowed inline in msvc on x64.

**Comment by bakpakin** [comment]
Continuing discussion from matrix chat, the issue with 64 bit integers in the FFI was likely just an issue with an `ifdef` in the implementation of janet_getuinteger64 and janet_getinteger64 functions.

**Comment by kamisori** [comment]
> Continuing discussion from matrix chat, the issue with 64 bit integers in the FFI was likely just an issue with an `ifdef` in the implementation of janet_getuinteger64 and janet_getinteger64 functions.

indeed, i found the s64/u64 issue to be fixed (probably due to that ifdef commit)

but, my structs' data is mangled even worse now, and regardless what arity or slot#:
expected "zero 6666 one 1111 two 2222 three 3333 four 4444 five 5555"

```
repl:46:> (def ts (getTestStruct))
(6666 1111 2222 3333 4444 5555)


#expected "zero 6666 one 1111 two 2222 three 3333 four 4444 five 5555nil"

repl:47:> (printTestStructONLY (tracev ts))
trace on line 47, column 22: ts is (6666 1111 2222 3333 4444 5555)
zero 4444 one 5555 two 844951904 three 6 four 4444 five 5555nil


#expected "zero 6666 one 1111 two 2222 three 3333 four 4444 five 5555, and six 9999999nil"

repl:48:> (printTestStructAndInt (tracev ts) 9999999)
trace on line 48, column 24: ts is (6666 1111 2222 3333 4444 5555)
zero 4444 one 5555 two 844951904 three 6 four 4444 five 5555, and six 9999999nil


#expected "six 9999999 and zero 6666 one 1111 two 2222 three 3333 four 4444 five 5555nil"

repl:49:> (printIntAndTestStruct 9999999 (tracev ts))
trace on line 49, column 32: ts is (6666 1111 2222 3333 4444 5555)
six 9999999 and zero 4444 one 5555 two 844951904 three 6 four 4444 five 5555nil
```

**Comment by kamisori** [comment]
actually it works on my machine, when i comment out line 1120 in ffi.c:

```
// if (stack_size) memmove(stack - 2, stack, stack_size);
```

**Comment by andrewchambers** [comment]
Minor observation - this is probably something we can enumerate or fuzz with a small bit of helper code to generate C functions.

**Comment by bakpakin** [comment]
Note: there was a regression that messed up pass by reference arguments that should now be fixed - I'm leaving this bug open though until I add some more test cases for these kinds of parameters, which clearly should be caught by our test suite.
