### ISSUE TITLE
`os/date` reporting wrong month and month-day

### ISSUE THREAD

**Issue by autumnull** [janet-lang/janet#1042]
Example:
```
$ date --date='@1667782699'
Mon  7 Nov 00:58:19 GMT 2022

$ janet -e "(pp (os/date 1667782699))"
{:dst false :hours 0 :minutes 58 :month 10 :month-day 6 :seconds 19 :week-day 1 :year 2022 :year-day 310}
```

**Comment by tionis** [comment]
(as well as week-day and year-day)

**Comment by autumnull** [comment]
you're right.

is this based on any underlying system representation, or is it just an arbitrary decision that janet makes?

**Comment by pepe** [comment]
Judging by these lines https://github.com/janet-lang/janet/blob/master/src/core/os.c#L1352, it is the first case.

**Comment by autumnull** [comment]
@pepe that seems like a mix actually, month-day is decremented from the system value.
