### ISSUE TITLE
Need Help With Hello World C Example

### ISSUE THREAD

**Issue by Pebaz** [janet-lang/janet#1044]
> **Root Question:** How do I pass and maintain a value from C to Janet?

It should be maintained between invocations. My goal is to set values of an environment table from C and then pass it to Janet so that those values can be used in scripts. However, this code fails with **`compile error in main: unknown symbol message`** and I'm not sure why:

```c
#include "janet.c"

int main(int argc, char ** argv)
{
    janet_init();
    const uint8_t * key = janet_cstring("message");  // Trying to bind a string to var `message`
    const uint8_t * msg = janet_cstring("Hello World From Janet!");
    JanetTable * env = janet_core_env(NULL);
    janet_table_put(env, janet_wrap_string(key), janet_wrap_string(msg));
    janet_dostring(env, "(print message)", "main", NULL);  // Just trying to access the environment
    janet_deinit();
    return 0;
}
```

What's wrong with the code example given? Why can't the code within the `janet_dostring()` call access the `message` variable?

**Comment by sogaiu** [comment]
@Pebaz The following seemed to work here:
```
#include "janet.h"

int main(int argc, char ** argv)
{
    janet_init();
    const uint8_t * key = "message";  // Trying to bind a string to var `message`
    const uint8_t * msg = "Hello World From Janet!";
    JanetTable * env = janet_core_env(NULL);
    janet_def(env, key, janet_cstringv(msg), NULL);
    janet_dostring(env, "(print message)", "main", NULL);  // Just trying to access the environment
    janet_deinit();
    return 0;
}
```

Possibly it's helpful to look at and near `janet_def`'s definition: https://github.com/janet-lang/janet/blob/07fe9bcdf6c85754b10fda74cd2d909120d9ea98/src/core/util.c#L397-L405

and the following repl session:
```
repl:1:> (def message "greetings")
"greetings"
repl:2:> (get (curenv) (symbol "message"))
@{:source-map ("repl" 1 1) :value "greetings"}
```

So at minimum, may be for `(print message)` to work:

1. the key in the core table needs to be a symbol, and
2. to end up with an "associated" value for `message`, the value in the core table needs to be another table (call it a "subtable" perhaps) that has at least a key `:value` (that gets associated in the subtable with the originally desired value -- in the example, the string "greetings")

**Comment by Pebaz** [comment]
Thank you so much this got me started! 😃
