### ISSUE TITLE
ldconfig does not exist on OSX

### ISSUE THREAD

**Issue by PaulBatchelor** [janet-lang/janet#106]
The current install target in the Makefile makes a call to `ldconfig`. If run on OSX, you get the following error:

```
ldconfig /usr/local/lib
make: ldconfig: Command not found
```

In the spirit of keeping things portable, I would suggest removing this line. It can always be called explicitly.

Thoughts?

**Comment by bakpakin** [comment]
The `-` in front of `-ldconfig` indicates that the command can still fail and not cause the make target to fail. This makes the make target cross platform.

**Comment by PaulBatchelor** [comment]
Good enough for me.
