### ISSUE TITLE
conflicting parameter types between janet.h and source for some IO functions 

### ISSUE THREAD

**Issue by AlecTroemel** [janet-lang/janet#1062]
these 4 functions use `int` for their flags arg in `util.c`, but `int32_t` in theirr `janet.h` definitions 

```
janet_getfile
janet_makejfile
janet_makefile
janet_unwrapfile
```

looking through some commits, at least for getfile everything was matched up when it was introduced https://github.com/janet-lang/janet/commit/1753f8bc189639e0c103b647a77e09c40ecca201, however the drift happened here https://github.com/janet-lang/janet/commit/617ec7f5652864ef3eff100b07c2f365015db0c5

Obviously this difference doesnt seem to matter for more environments (from the fact that it works), but looks to be causing build failures for more niche systems, for example baremetal raspberry pi https://github.com/nesbox/TIC-80/actions/runs/3976508893/jobs/6817036992#step:6:555

Is there a reason for the difference?

**Comment by bakpakin** [comment]
No good reason, not sure why this was added in the first place. Likely from debugging some compilation errors on Windows.
