### ISSUE TITLE
Add compiler flag to disable File IO

### ISSUE THREAD

**Issue by AlecTroemel** [janet-lang/janet#1067]
flag will most likely be named  `JANET_REDUCED_IO`

needed for this issue -> https://github.com/nesbox/TIC-80/issues/2108

The tricky part here is to make sure bootstrapping works correctly. Since print and eprint can be redirected to buffers and functions, the default IO could simply be to do nothing instead of writing to standard handles in that case.

import/use/require functions will still be included, but the well make some changes to the default module loaders to remove actual file IO. Basically just read from module cache.

(Janet would still include stdio.h, but would not expose most of the functionality to programmers)

((these notes are a mostly a summary of comments by bakpakin in gitter)

**Comment by AlecTroemel** [comment]
here's a sketch of relevant functions & calls by sogaiu https://gist.github.com/sogaiu/d50ae376ccff9948bd75c0a773b56fdf

**Comment by bakpakin** [comment]
I've done some preliminary work on adding a `janet_sandbox` function to Janet to disable this sort of thing. The idea is similar to BSD `pledge`, or to Deno's permission API (albeit newer and frankly less granular at this point). This is is easier than compiler defines for a number of reasons:

* Compiler defines are intended for portability - they are frankly a pain to change and cannot be very granular - this add inflexibility to a  project that uses them for security.
* Janet relies on IO for it's bootstrapping process and it's main executable.
* Compiler defines cannot be changed at runtime - this makes it impossible to disable file system access programmatically only after certain setup code has been run.

Adding compiler defines to disable IO did not pan out into something that was either clean or useful, so hopefully this will address the issues in tic-80 (and more generally embedding Janet in applications).

1. https://man.openbsd.org/pledge.2
2. https://deno.land/manual@v1.29.1/basics/permissions
