### ISSUE TITLE
Function name shadows its own arguments

### ISSUE THREAD

**Issue by ianthehenry** [janet-lang/janet#1076]
This is easily worked around, but I found this very surprising, as I don't know of any other language that works this way.

```
repl:1:> (defn foo [foo] foo)
<function foo>
repl:2:> (foo "hello")
<function foo>
```

I would expect that to return `"hello"`.

(Equivalent code returns `"hello"` in Lua, Python, Ruby, and JavaScript.)

**Comment by pepe** [comment]
That is an interesting find. I would have the exact expectations, to be honest.
