### ISSUE TITLE
looping macros have surprising shadowing behavior

### ISSUE THREAD

**Issue by ianthehenry** [janet-lang/janet#1077]
Encountered this today, which surprised me:

```
repl:1:> (def x [1 2 3])
(1 2 3)
repl:2:> (loop [x :in x] (print x))
1
error: expected iterable type, got 1
  in _thunk [repl] (tailcall) on line 4, column 1
```

I don't *think* this is intentional? The fact that the first iteration works makes me think this is just a bug.

Works as expected with different symbols:

```
repl:1:> (def x [1 2 3])
(1 2 3)
repl:2:> (loop [y :in x] (print y))
1
2
3
nil
```

Looks like an over-eager `idempotent?`?

**Comment by pepe** [comment]
I would say user error :-D. Or better, how would you fix this?

Just for the debate:

```
repl:1:> (pp (macex1 '(loop [x :in x] (print x))))
(do nil (var _00001Z (<function next> x nil)) (while (<function not=> nil _00001Z) (def x (<function in> x _00001Z)) (do (print x)) (set _00001Z (<function next> x _00001Z))))
```

I am curious, not ironic.

**Comment by ianthehenry** [comment]
I'd expect it to `gensym` the thing you're looping over unconditionally:

```
repl:1:> (macex1 '(each x [1 2 3] (print x)))
(do (def _000002 [1 2 3]) (var _000001 (<function next> _000002 nil)) (while (<function not=> nil _000001) (def x (<function in> _000002 _000001)) (print x) (set _000001 (<function next> _000002 _000001))))

repl:2:> (macex1 '(each x x (print x)))
(do nil (var _000003 (<function next> x nil)) (while (<function not=> nil _000003) (def x (<function in> x _000003)) (print x) (set _000003 (<function next> x _000003))))
```

But it looks like it only gensyms if not `idempotent?`: https://github.com/janet-lang/janet/blob/master/src/boot/boot.janet#L441

You can work around this with a silly equivalent-but-not-`idempotent?` construct:

```
repl:1:> (each x [;x] (print x))
1
2
3
nil
```

Also I thought this only affected `loop` macros because that's where I happened to run into it, but it looks like it affects all of the `each` macros.

I'll make a PR for this sometimes this weekend.

**Comment by ianthehenry** [comment]
To be clear I think that "this is an error" is a reasonable stance, and it seems fine to detect that in the macro and fail compilation. But the current behavior of "the first iteration runs successfully, but subsequent iterations crash" feels worse than that.

**Comment by pepe** [comment]
Thank you very much for your explanation. It all makes a sense.

**Comment by pepe** [comment]
I guess we can use macro linting messages for the solution in your last comment.

**Comment by bakpakin** [comment]
This is fixed in the latest Janet - the bytecode optimizations also offset the cost of macro change.
