### ISSUE TITLE
implement conj aka cons

### ISSUE THREAD

**Issue by Inc0n** [janet-lang/janet#1091]
Janet has no `cons` cells similar to Clojure, however, Clojure has `conj` effectively that functionality-wise similar to `cons`.

They are useful to have for Functional Programming.

**Comment by cvanloo** [comment]
In Lisp `(1 2 3)` is a linked list.
This makes `cons` a very simple operation: create a new node and make it point back to the last node.

In Janet `(1 2 3)` is called a tuple and implemented as an array: https://github.com/janet-lang/janet/blob/d9ed7a77f889f632ebbee1c111419170e201548c/src/include/janet.h#L969-L977

A `cons` would have to allocate a new array and copy over the elements of the previous array.
This seems a bit expensive.

What are your particular use-cases for a `cons`?
Isn't there a more Janet-y way to do it?

**Comment by Inc0n** [comment]
I reckon allocate a mutable array would do.
I wonder how clojure made `conj` possible without having `cons` cells or linked list.

**Comment by cvanloo** [comment]
They do actually: 
https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/ISeq.java (Linked List)
and https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/Cons.java (Cons cell)
