### ISSUE TITLE
Add functions to change objects to be mutable and immutable

### ISSUE THREAD

**Issue by Inc0n** [janet-lang/janet#1092]
This would be effectively `transient` and `persistent!` in Clojure. 
`persistent!` would be `freeze` of Janet but with the deep freeze.

For example, let's define them as `mutable` and `freeze` (shallow version).
tuple and array `(mutable [1 2])` = `@[1 2]`
struct and dict `(mutable {1 2})` = `@{1 2}`
string and buffer ...

And `freeze` in the inverse operator of `mutable`

This would also imply that `@` is made into a macro reader character

**Comment by bakpakin** [comment]
Reasonable idea. Perhaps for symmetry the function could be called `thaw` or `unfreeze` - maybe a bit too cutesy

**Comment by sogaiu** [comment]
@Inc0n #1142 added by @tionis has `thaw` in it now, do you think that addresses the original issue?

**Comment by Inc0n** [comment]
Hi, thanks for the new patch.

Originally I was trying to do this I believe (now with `thaw` in place, hopefully this would work now):
```
(defn cons [x xs]
  (freeze
   (array/push (thaw xs) x)))
```
For the reason that I did not enjoy the idea passing a mutable array across my functions, however, I also wanted linked list essentially...

**Comment by CosmicToast** [comment]
Couldn't you just do `[;xs (freeze x)]` instead?

**Comment by sogaiu** [comment]
Nice idea with the splice :+1: 

Perhaps though to emulate `cons` one might want the order to be `[(freeze x) ;xs]`?

**Comment by Inc0n** [comment]
> Couldn't you just do `[;xs (freeze x)]` instead?

For my problem, this is a much better solution.

And for the details of the `xs` in my case.
Really, I was trying to make alist happen (Or a list of structs). As data structure characteristics, I was looking for:
- maintain insertion order, i.e. newest always at last or first, second newest always second or second to last
- adding new element is done without mutating the last list

It's screaming linked-list isn't it :)

And would the corresponding accessors looking like the following, if I were to use `[(freeze x) ;xs]`?
```
(def car [[p & more]] p)
(def cdr [[p & more]] more)
```

**Comment by CosmicToast** [comment]
> And would the corresponding accessors ...

Yup.
Just be careful with first/last semantics, but 5 minutes in a REPL clears those up.

**Comment by sogaiu** [comment]
> And would the corresponding accessors looking like the following, if I were to use [(freeze x) ;xs]?

Those seem like they could work, but...

`[(freeze x) ;xs]` looks like it would be a tuple of sorts.

Wouldn't using `first` for `car` and `(drop 1 ...)` for `cdr` also work?  Further, it seems possible that using `[p & more]` here might lead to unneeded processing.

Not sure I'm following along well enough (^^;

**Comment by Inc0n** [comment]
> Yup.
> Just be careful with first/last semantics, but 5 minutes in a REPL clears those up.

Thank you!

**Comment by Inc0n** [comment]
> Wouldn't using first for car and (drop 1 ...) for cdr also work? It seems possible that using [p & more] here might lead to unneeded processing.

Good point! Thanks sogaiu :)
