### ISSUE TITLE
*executable* dyn isn't set when building a binary with jpm

### ISSUE THREAD

**Issue by joeatwork** [janet-lang/janet#1098]
Please close if this is as-designed, or if I'm using the value incorrectly :)

I've written the following script

```janet
(defn main [$]
  (pp (dyn *args*))
  (pp (dyn *executable*)))
```

When I run it with `janet main.janet`, I get the following (expected) result
```console
$ janet main.janet
@["main.janet"]
"janet"
```

But when I build an executable and run it, I get the following (unexpected) result
```console
$ jpm build
$ ./build/reproduce
@["./build/reproduce"]
nil
```

I've attached a zipfile with a minimal project that can reproduce the issue (including the script above and a minimal "project.janet" that works to build the executable) [here](https://github.com/janet-lang/janet/files/11186674/executable-dyn-missing.zip)

I expected the value of `*executable*` in the second case to be `"./build/reproduce"`.

Thanks so much for making janet! Such a wonderful tool!

**Comment by sogaiu** [comment]
I tried the content of your zip file and observed the same results.

I don't have a definitive answer, but some poking around in `mainclient.c` turned up: https://github.com/janet-lang/janet/blob/bef5bd72c2a6f6d00d4f31b0b06c98e23a78ba87/src/mainclient/shell.c#L1156-L1157

It seems that for the `janet` binary, `*executable*` is something that gets setup at startup.  

Perhaps `jpm` doesn't arrange for something similar when creating an executable via `declare-executable`.

May be someone else knows for sure :)

**Comment by bakpakin** [comment]
Added to jpm commit f97f73e33d9d860f9f129b058dd8e74d6ea8ef79. Note that this will not point to the `janet` binary, but to the created executable itself.
