### ISSUE TITLE
Can't seem to figure out how to load/use ffi module

### ISSUE THREAD

**Issue by rinfz** [janet-lang/janet#1104]
On MacOS and installed with brew. `janet -v` gives 1.27.0-meson

```
repl:1:> (doc ffi/context)
symbol ffi/context not found.
nil
repl:2:> (import ffi)
error: could not find module ffi:
    /opt/homebrew/Cellar/janet/1.27.0/lib/janet/ffi.jimage
    /opt/homebrew/Cellar/janet/1.27.0/lib/janet/ffi.janet
    /opt/homebrew/Cellar/janet/1.27.0/lib/janet/ffi/init.janet
    /opt/homebrew/Cellar/janet/1.27.0/lib/janet/ffi.so
  in require-1 [boot.janet] on line 2891, column 20
  in import* [boot.janet] on line 2930, column 15
  in _thunk [repl] (tailcall) on line 2, column 1
```

**Comment by sogaiu** [comment]
I dont' see anything obviously problematic in [the brew formula for janet](https://formulae.brew.sh/api/formula/janet.json), but may be there's some issue there I missed or with pre-built binaries.

AFAIU, the formula is not maintained by janet-lang project members, but there are a fair number of contributors (18 at the time of writing this) that can be see a bit above the code [here](https://github.com/Homebrew/homebrew-core/blob/6d4b82de9086948973f2ea926729ea24fb801e48/Formula/janet.rb).

I don't have access to macos to test, but here are some thoughts:

* For brew, it looks like using `--build-from-source` could be one way to build the package from source and thus avoid a pre-built binary (which possibly isn't quite right).
* If on an Intel-based machine, may be the artifact for macos x64 (from [here](https://github.com/janet-lang/janet/releases/tag/v1.27.0)) could be tried to see if it has the same issue.  Perhaps this can work even on an arm-based machine via Rosetta.
* Building from source after cloning with git and trying to see if the same issue exists might be another thing to try.

**Comment by pepe** [comment]
One more thing: ' ffi` is part of the boot—no need to import it. The missing doc is weird tho.

**Comment by rinfz** [comment]
`brew` with `--build-from-source` had the same issue:

```
Janet 1.27.0-meson macos/aarch64/clang - '(doc)' for help
repl:1:> (doc ffi/context)
symbol ffi/context not found.
nil
```

Building manually from source according the the readme file with meson/ninja also did not fix the issue (tried on HEAD and v.1.27.0 tag):
```
Janet 1.27.0-bef5bd72 macos/aarch64/clang - '(doc)' for help
repl:1:> (doc ffi/context)
symbol ffi/context not found.
nil
```
```
Janet 1.27.0-01aab666 macos/aarch64/clang - '(doc)' for help
repl:1:> (doc ffi/context)
symbol ffi/context not found.
nil
```

FWIW I am on an M1 mac.

**Comment by sogaiu** [comment]
Thanks for trying the various options and reporting back.

I think [this bit](https://github.com/janet-lang/janet/blob/bef5bd72c2a6f6d00d4f31b0b06c98e23a78ba87/.github/workflows/release.yml#L13-L31) describes how the release artifact is built.

IIUC, according to that, meson / ninja is not used for it but rather just make with the distributed Makefile.

I just tried the meson / ninja approach for a Linux box and it worked there.  Curious...may be it has to do with Apple Silicon...

May be @bakpakin has some insignt into the situation.

---

For reference, I'll put the output I saw down below.

```
$ meson setup build \
          --buildtype release \
          --optimization 2 \
          --libdir /usr/local/lib \
          -Dgit_hash=$(git log --pretty=format:'%h' -n 1)
WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options
The Meson build system
Version: 0.61.2
Source dir: /tmp/janet
Build dir: /tmp/janet/build
Build type: native build
Project name: janet
Project version: 1.27.0
C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Library m found: YES
Library dl found: YES
Library android-spawn found: NO
Run-time dependency threads found: YES
Configuring janetconf.h using configuration
Compiler for C supports arguments -fvisibility=hidden: YES 
Build targets in project: 8

janet 1.27.0

  User defined options
    buildtype   : release
    libdir      : /usr/local/lib
    optimization: 2
    git_hash    : 01aab666

Found ninja-1.10.1 at /usr/bin/ninja

$ ninja -C build
ninja: Entering directory `build'
[54/54] Generating patched-janeth with a custom command

$ ./build/janet
Janet 1.27.0-01aab666 linux/x64/gcc - '(doc)' for help
repl:1:> (doc ffi/context)


    function
    boot.janet on line 3661, column 3

    (ffi/context &opt native-path &named map-symbols lazy)

    Set the path of the dynamic library to implictly bind, as well as 
    other global state for ease of creating native bindings.


nil
repl:2:> 
```

**Comment by CosmicToast** [comment]
FFI is manually disabled in `janet.h` on non-x86 platforms: https://github.com/janet-lang/janet/blob/master/src/include/janet.h#L182
You can try enabling it manually by building from source with `-Dc_args=-DJANET_FFI` passed to meson or via a patch to `janet.h`.
This doesn't work because FFI requires calling convention support.
If you do that, you'll get an error in the tests:
```
stderr:
Starting suite 12...
error: calling convention not supported
  in ffi/call [src/core/ffi.c] on line 1358
  in memcpy [/private/tmp/t/janet/build/../test/suite0012.janet] on line 38, column 3
  in _thunk [/private/tmp/t/janet/build/../test/suite0012.janet] (tailcall) on line 42, column 3
```

In short: support for the aarch64 calling convention would need to be added in order for FFI to work on apple silicon macbooks.
IIRC the calling convention is actually slightly different on those than on aarch64 linux, so support should likely be considered separately.

**Comment by pepe** [comment]
I did not know this info but had that gut feeling. Thank you for clearing it out @CosmicToast

**Comment by bakpakin** [comment]
Since FFI has other functionality in it besides calling conventions, it might be a good idea to enable the module universally.
