### ISSUE TITLE
Segmentation fault triggered via printf

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet#1105]
I mistyped a format string and got a segfault:
```
$ janet
Janet 1.27.0-bef5bd72 linux/x64/gcc - '(doc)' for help
repl:1:> (printf "hello %" `dave`)
Segmentation fault (core dumped)
```

**Comment by pepe** [comment]
Can confirm observed behavior on Alpine with musl.

**Comment by CosmicToast** [comment]
This is an unchecked strlen against a null pointer in `scanformat`.
I've submitted a fix.
