### ISSUE TITLE
Misbehavior of logical operators and/or with splice

### ISSUE THREAD

**Issue by primo-ppcg** [janet-lang/janet#1117]
Logical operators misbehave when passed a splice. For example:

```janet
(var a [nil nil nil 1 2])

# find the first truthy value in the tuple
(or (splice a))
```
Expected: `1`
Actual: `(nil nil nil 1 2)`

This behavior is documented only in the form of a community example: <https://janetdocs.com/or>
```janet
# note that `or` does not behave as you might expect
# when used with `apply` and `splice`:
(or 1 2 3)             # => 1
(or (splice [1 2 3]))  # => (1 2 3)
(apply or [1 2 3])     # => (if 1 1 (if 2 2 3))
```
However, this is not exactly correct. The result is not a tuple, but the splice of the tuple.

Witness:
```janet
(type (or (splice a)))
# error: arity mismatch, expected 1, got 5
```
Of course, the initial example could rewritten - arguably more legibly - as `(find truthy? a)`, but that's beside the point. This behavior appears to be inconsistent with the rest of the Core API. Both `and` and `or` are basic operators, and not special forms (or at least shouldn't be).

**Comment by bakpakin** [comment]
This is expected behavior - if anything were to change, this perhaps should be compiler error. Splice only has meaning in certain locations, and notably macros can do whatever they want the splice form.

**Comment by primo-ppcg** [comment]
I appreciate the responds.

> This is expected behavior
Is there any sound argument why the current behavior is intended or desirable?

**Comment by bakpakin** [comment]
Here is some discussion for Clojure which is similar in this regard: https://stackoverflow.com/questions/2969543/why-doesnt-apply-or-true-false-work-in-clojure

Janet has as similar functions `any?`, `some`, and `all` for doing this in a functional, non-short circuiting manner.  Perhaps something like `all?` could be added to complement `any?`, but it is quite easy to call:

```janet
(any? a b ;(my-function-call) c) # functional form of `or`
(all identity a b ;(my-function-call) c) # functional form of `and`
```

**Comment by primo-ppcg** [comment]
Thanks for the clarification. Perhaps I didn't read the docs closely enough, but I would have expected `any?` to always return a boolean. As it is, it covers this use case entirely. An `all` form without a predicate does seem like a missing symmetry to `some`/`any?`.
