### ISSUE TITLE
Standard documentation generator

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#112]
The janet docs are quite pretty, but my html skills are terrible. With go I can run a single command and get a standard and nice documentation page, it might be nice for janet.

**Comment by bakpakin** [comment]
Such a tool would be very useful. Perhaps mendoza could be extended to add this functionality out of the box.

**Comment by bakpakin** [comment]
Mendoza now has this functionality, see https://janet-lang.github.io/jhydro/ for some example documentation.
