### ISSUE TITLE
Disallow splice in semantically useless positions rather than silently ignoring.

### ISSUE THREAD

**Issue by bakpakin** [janet-lang/janet#1121]
Currently, the compiler simply ignores the splice special form if use in a position where dynamically adapting to the number of parameters does not make sense - for example:

```janet
(if (splice [false 2 3]) 10 20)
```
will be compiled as
```janet
(if [false 2 3] 10 20)
```
which is confusing. Fixing this to a compilation error will break a small number of currently working programs that have this extraneous splice form. A few other examples of malformed programs that currently compile and run:

```janet
(def a (splice [1 2 3]))
(type (splice [1 2 3]))
(while (splice [1 2 3]) (splice [4 5 6]))
((splice [1 2 3]) 0)
```

Splice only has any function in the follow scenarios:
- as a parameter to a function call
- as a parameter to a data literal constructor
- inside an unquote form

The compiler should at the very least issue a compiler warning, but ideally error out in this case. Refining from #1117 which attributes this confusion to the `and` and `or` macros.

**Comment by bakpakin** [comment]
Another question is should code like `(+ 1 (do ;[2 3 4]) 5)` be allowed. Currently this evaluates to 15.

The `do` and `upscope` special forms inherit the `spliciness` to their final position. While I don't see anything terribly wrong with this, I don't know if it particularly useful and to me at least, it is a bit surprising that it works. The only way that the docs promise this should work is

```
(+ 1 ;(do [2 3 4]) 5)
```
where the splice is moved outside `do`.

**Comment by CosmicToast** [comment]
I think the doc promise form makes more sense. As for breaking existing programs, the error message should be helpful; something like “splice has no effect here [position], it can be safely removed”, so those programs can be trivially patched even if one hasn’t reviewed the code in a while.

**Comment by bakpakin** [comment]
A fix should be in place, but leaving this open until next release for further discussion in case more code breaks than expected.

**Comment by sogaiu** [comment]
For reference I got an error when doing `jpm build` like the following:

```
$ jpm build
generating executable c source build/freja.c from /home/user/src/freja/freja/main.janet...
error: /home/user/src/freja/freja/file-explorer.janet:24:7: compile error: splice can only be used in function parameters and data constructors, it has no effect here
```

I think the line in question is [this one](https://github.com/saikyun/freja/blob/9b95dba0c9f09da913ce9a82fc51fa19631b5894/freja/file-explorer.janet#L24).

I don't know if this code worked as intended before.  May be @saikyun could comment.

**Comment by sogaiu** [comment]
For the record, [janet-playground](https://github.com/MikeBeller/janet-playground) seems to be affected.

In particular, [this line](https://github.com/MikeBeller/janet-playground/blob/1395259c352684c416c6012b428b00c3f728f5e7/public/play.html#L26) has a semi-colon after `(import ./spork)`:

```js
let code = "(import ./spork);" + "\n(def usercode ``````````" + userCode + "``````````) (spork/fmt/format-print usercode)";
```

I've submitted a [PR](https://github.com/MikeBeller/janet-playground/pull/6) that touches on it.
