### ISSUE TITLE
Possible live-lock in ev/select with threaded channels

### ISSUE THREAD

**Issue by bakpakin** [janet-lang/janet#1125]
Running this program https://gist.github.com/sogaiu/0dfdbecde340a4c747c7b39b6f53b746#file-runner-simpler-janet-L49 results in hangs some of the time. However, replace the call to ev/select with just `ev/take` fixes the issue.

**Comment by sogaiu** [comment]
Thanks for taking a look, the `ev/take` suggestion, and 2360164.

I've tried to reproduce the hang using the changes in 2360164 with a variety of numbers using the script mentioned above.  I have not seen any more hangs :+1:
