### ISSUE TITLE
Windows color

### ISSUE THREAD

**Issue by cup** [janet-lang/janet#113]
~~~
janet:0:> (print "abcde")
abcde
 [36mnil [0m
~~~

**Comment by bakpakin** [comment]
Use the -n flag to turn of color, or enable ANSI escape codes in your terminal

**Comment by cup** [comment]
@bakpakin thank you but that is not the correct solution to this problem:

https://superuser.com/questions/413073/-/1300251

**Comment by bakpakin** [comment]
I’m aware we can write code that will work on certain windows consoles to turn on ANSI functionality. This is a solution that works right now.

**Comment by bakpakin** [comment]
The latest master now has a fix for this, enabling color for Windows 10 consoles. However, there is no support for color in older windows consoles without any ANSI escape support.

**Comment by cup** [comment]
@bakpakin that was fast! thank you!

it is possible to have color for older windows version - but i can understand if you dont want to support that
