### ISSUE TITLE
mod swaps its arguments when mixing types :number and :core/s64

### ISSUE THREAD

**Issue by primo-ppcg** [janet-lang/janet#1130]
If the first argument to `mod` is of type `:number` and the second of type `:core/s64`, the function appears to swap their order.

```janet
(var d (int/s64 7))
(each n (range -21 0) (prin (mod n d) " "))
```

Expected: `0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6`
Actual: `-14 -13 -12 -11 -10 -9 -8 -7 -6 -5 -4 -3 -2 -1 0 -5 -3 -1 -2 -1 0`

The result is as if we had taken 7 mod -21, then mod -20, etc.

Moreover, the following results in a `SIGFPE`:

```janet
(var d (int/s64 7))
(mod 0 d)
```

Similar behavior can be observed with `%`, and also when using `:core/u64` as the second argument. Although, the only case which results in an interpreter crash is the one above (as noted by @CosmicToast). The rest produce a division by zero error.

The other arithmetic functions appear to accept mixed types without issue.

**Comment by CosmicToast** [comment]
An important distinction for debugging: `(mod 0 (int/s64 7))` works, while `(mod 0 (int/u64 7))` does not.
Notably, `cfun_it_s64_mod` is written by hand rather than generated with one of the macros of `src/core/inttypes.c`.
Consequently, I think it's safe to conclude that the generating macros are faulty in some way.

**Comment by primo-ppcg** [comment]
I'm not entirely confident this is a correct fix, but I think this may be the issue. Certainly, `mod` and `rmod` shouldn't be mapped to the same function.

```diff
diff --git a/src/core/inttypes.c b/src/core/inttypes.c
index 364d9ea8..0bf5d79d 100644
--- a/src/core/inttypes.c
+++ b/src/core/inttypes.c
@@ -542,9 +542,9 @@ static JanetMethod it_s64_methods[] = {
     {"/", cfun_it_s64_div},
     {"r/", cfun_it_s64_divi},
     {"mod", cfun_it_s64_mod},
-    {"rmod", cfun_it_s64_mod},
+    {"rmod", cfun_it_s64_modi},
     {"%", cfun_it_s64_rem},
-    {"r%", cfun_it_s64_rem},
+    {"r%", cfun_it_s64_remi},
     {"&", cfun_it_s64_and},
     {"r&", cfun_it_s64_and},
     {"|", cfun_it_s64_or},
@@ -567,9 +567,9 @@ static JanetMethod it_u64_methods[] = {
     {"/", cfun_it_u64_div},
     {"r/", cfun_it_u64_divi},
     {"mod", cfun_it_u64_mod},
-    {"rmod", cfun_it_u64_mod},
+    {"rmod", cfun_it_u64_modi},
     {"%", cfun_it_u64_mod},
-    {"r%", cfun_it_u64_mod},
+    {"r%", cfun_it_u64_modi},
     {"&", cfun_it_u64_and},
     {"r&", cfun_it_u64_and},
     {"|", cfun_it_u64_or},
```
