### ISSUE TITLE
bug hidden by NAN

### ISSUE THREAD

**Issue by kamisori** [janet-lang/janet#1135]
https://github.com/janet-lang/janet/blob/3b353f1855dc61bf87eb6661778b462c13cf204e/src/core/math.c#LL320C15-L320C15

i suppose this doesnt make it to the compiler often thanks to NAN usually being defined?

**Comment by bakpakin** [comment]
This is a last ditch attempt to get NaN. It should usually work with ieee754 semantics. I image some compilers have NAN expand to this.

**Comment by bakpakin** [comment]
Although I don't know why it is a backslash :laughing: . I swear I saw and fixed this before...
