### ISSUE TITLE
os/clock mismatch between documentation and implementation

### ISSUE THREAD

**Issue by zevv** [janet-lang/janet#1144]
The documentation of `os/clock` states "Return the number of whole + fractional seconds since some fixed point in time. The clock is guaranteed to be non-decreasing in real time."

The implementation uses `janet_gettime()`, which (on Linux) gets the time with `clock_gettime` using the `CLOCK_REALTIME` source. `CLOCK_REALTIME` is not guaranteed to be monotonic though (man page: "This clock is affected by discontinuous jumps"), so `CLOCK_MONOTONIC` might be a better choice here.

I'd be happy to provide a fix, either in the documentation or implementation - let me know which one :)

**Comment by zevv** [comment]
The documentation of `os/clock` states "Return the number of whole + fractional seconds since some fixed point in time. The clock is guaranteed to be non-decreasing in real time."

The implementation uses `janet_gettime()`, which (on Linux) gets the time with `clock_gettime` using the `CLOCK_REALTIME` source. `CLOCK_REALTIME` is not guaranteed to be monotonic though (man page: "This clock is affected by discontinuous jumps"), so `CLOCK_MONOTONIC` might be a better choice here.

I'd be happy to provide a fix, either in the documentation or implementation - let me know which one :)

**Comment by sogaiu** [comment]
`CLOCK_MONOTONIC` does sound better.
