### ISSUE TITLE
catching stdout/stderr (embedding issue)

### ISSUE THREAD

**Issue by velkyel** [janet-lang/janet#115]
I'm missing mechanism how to catch (or redirect) stdout and stderr.  for example janet_printf(), janet_stacktrace() or janet_panicv() should call optional custom hook or another solution.

**Comment by bakpakin** [comment]
`janet_panicv` is probably very difficult to add a hook for, but `janet_printf` and `janet_stacktrace` definitely could. Currently, janet_printf just calls `fwrite` to stdout. `janet_stacktrace` has a janet mechanism for directing output to different files (`(setdyn :err (file/open "mytraces.txt"))`), but that's not the most convenient for embedding, especially in the case where we don't want to write to a file.

**Comment by bakpakin** [comment]
Janet actually has a mechanism for substituting c functions in the core library with custom versions. `janet_core_env` takes one parameter, replacements, which is a JanetTable containing functions to be replaced by custom functions. You could replace print, stdout, stdin, etc  with your own custom functions. The default client program actually replaces the function "getline" in such a way, see https://github.com/janet-lang/janet/blob/64a80c57e31506d65af10f20936946aa30f12db0/src/mainclient/main.c#L54

**Comment by velkyel** [comment]
thank you, I'll use this technique.  Not all janet output goes into stdout/stderr btw, for example janet_dobytes() prints "compiler error in ..." directly into system stderr.  That's quite important in remote repl.

**Comment by bakpakin** [comment]
Some more work has gone into improving this, and now both error and normal output can be directed
to buffers or ignored as of 99ef4c751059b26f4db52a5885709691a5dee352.

For example:
```clojure
(def output @"")
(def errout @"")
(with-dyns [:out output
            :err errout]
  (print "This would normally go to stdout.")
  (eprint "This would normally go to stderr."))
(print "output: " output)
(print "errout: " errout)
```

This should also work for `debug/stacktrace`, and the C functions `janet_printf` and `janet_eprintf` (new), which should covered pretty much any output by Janet.
