### ISSUE TITLE
Color not working on Windows 10 in janet.exe repl

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet#1156]
It appears that since [6e9cde8a](https://github.com/janet-lang/janet/commit/6e9cde8ac17ce01011d8889b7af39422c02f75da), color display isn't working so well via a cmd.exe or a powershell window.

```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.4.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools>janet
Janet 1.28.0-dev-local windows/x64/msvc - '(doc)' for help
repl:1:> {:a 1}
{[33m:a[0m [32m1[0m}
repl:2:>
```

Both @kamisori and I have observed the above sort of thing (both on Windows 10, though with different janet builds).  The latest commit I've seen it happen at is 909c9060.

With the [commit immediately before (by date)](https://github.com/janet-lang/janet/commit/a9fae49671891ae524a78740fb29d7b383f34515) or [the parent of 6e9cde8a](https://github.com/janet-lang/janet/commit/440af9fd647f81446be8bb14160059ab8fce9ed3) I see color fine.

A temporary work-around is to use [ansicon](https://github.com/adoxa/ansicon) which can be started via cmd.exe or a powershell window.

**Comment by bakpakin** [comment]
Interesting, this was supposed to make things more portable and help with Windows 7 issues. Perhaps it is better just control this with an environment variable or similar than people can modify - Microsoft's docs here are not obvious to me.

**Comment by bakpakin** [comment]
(We now have support for the `NO_COLOR` environment variable, but part of the issue was that the unicode support that worked for windows 10 was causing issues in older versions of Windows.

**Comment by sogaiu** [comment]
I tested 7acb5c6 and things work for me now :+1: 

@kamisori How about for you?

**Comment by kamisori** [comment]
looks neat again :D

**Comment by sogaiu** [comment]
I'm going to close this issue then.

Thanks for the quick fix @bakpakin!
