### ISSUE TITLE
Nil values iterating table

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#116]
```
$ (each v @{"foo" true "bar" false} (print v))
nil
nil
```

**Comment by bakpakin** [comment]
Each doesn't iterate tables. Use `(each (pairs {...}) ...)`

**Comment by andrewchambers** [comment]
Sure - I was just confused when it sort of worked, but not fully.

**Comment by bakpakin** [comment]
Closing this. If you want, open an issue for clearer docs.
