### ISSUE TITLE
Why is forv so much faster than for (and should something be done about it)?

### ISSUE THREAD

**Issue by primo-ppcg** [janet-lang/janet#1163]
A bodyless `forv` loop appears to be over 20% faster than the equivalent `for` loop. This surprised me. Perhaps it's just my experience with other languages, but I would have expected immutable forms to always be faster than mutable forms.

If we expand these loops, we can see why this is:

```janet
(for i 0 100)
# ->
(do (var _000034 0) (def _000035 100) (while (<function <> _000034 _000035) (def i _000034) (set _000034 (<function +> _000034 1))))
```
```janet
(forv i 0 100)
# ->
(do (var i 0) (def _000034 100) (while (<function <> i _000034) (set i (<function +> i 1))))
```

A `for` loop defines a locally scoped variable every single iteration, and therefore has more overhead. My question is: must it necessarily be so?

I don't really have a concrete suggestion. Although, one idea that might work is to add some sort of meta-data to the `var` special form, that exposes its current value, immutably, under another name. Something like a symbolic link. For example:

```janet
(var _000034 0 :alias i)
```

So that when `i` is looked up in the symbol table, it would return the current value of `_000034`, without ever needing to be explicitly set.

**Comment by primo-ppcg** [comment]
So, variable references are captured as references, and not as their current value. Not so surprising, really, just something that the implementer (which, if it's going to be anyone, it's going to be you 😉) would need to keep in mind.

I also think that other forms could benefit from this as well. `eachp` in particular seems like a great candidate for a performance boost.

**Comment by bakpakin** [comment]
So the cleanest way to do this sort of thing is actually just add some simple optimization passes to the bytecode to remove redundant reads - and to do this in a way that doesn't impede debugging.

For example:

```janet
(setdyn *pretty-format* "%.99M")

(pp (disasm |(for i 0 100)))
(pp (disasm |(forv i 0 100)))
```
Outputs the following:

```
{ :arity 0
  :bytecode @[(ldi 0 0) (ldi 1 100) (lt 2 0 1) (jmpno 2 4) (movn 3 0) (addim 0 0 1) (jmp -4) (retn)]
  :constants @[]
  :defs @[]
  :environments @[]
  :max-arity 0
  :min-arity 0
  :slotcount 4
  :source "temp2.janet"
  :sourcemap @[(3 13) (3 13) (3 13) (3 13) (3 13) (3 13) (3 13) (3 13)]
  :structarg false
  :symbolmap @[(0 8 0 _000037) (1 8 1 _000038) (4 7 3 i)]
  :vararg false}
{ :arity 0
  :bytecode @[(ldi 0 0) (ldi 1 100) (lt 2 0 1) (jmpno 2 3) (addim 0 0 1) (jmp -3) (retn)]
  :constants @[]
  :defs @[]
  :environments @[]
  :max-arity 0
  :min-arity 0
  :slotcount 3
  :source "temp2.janet"
  :sourcemap @[(4 13) (4 13) (4 13) (4 13) (4 13) (4 13) (4 13)]
  :structarg false
  :symbolmap @[(0 7 0 i) (1 7 1 _00003U)]
  :vararg false}
```

The difference is the extra `(movn 3 0)` instruction (Move Near) - which just does an unneeded move of a virtual value from slot 0 to slot 3. One could add an optimization pass that would remove code like this in functions, as well as recognizing that in some cases, further code could replace operands of slot 3 with operands of slot 0. Also keeping debug information intact and consistent, of course.

**Comment by primo-ppcg** [comment]
I think it might be a lot easier to hint to the compiler that you want it to perform a particular optimization, than for it to recognize the opportunity for optimization on its own. Either/both would be good, of course.

**Comment by bakpakin** [comment]
> I think it might be a lot easier to hint to the compiler that you want it to perform a particular optimization, than for it to recognize the opportunity for optimization on its own. Either/both would be good, of course.

In this particular case, not really. You never really know until you try the thing out, but in this particular case the difficulty is not in detecting if the optimization can be done, but in detecting when it is _not_ applicable. I don't want `(def i :alias v)` to generated bad code if this optimization can't be made - simply having `(def i v)` should be enough of a hint to the compiler that some coalescing could possibly be done here. This would also have much bigger perf wins than the hinting syntax.

**Comment by primo-ppcg** [comment]
Initial testing looks good. I wasn't expecting an update on this so quickly 👍 Timings on my local system are below.

master:
```janet
(for i 0 500_000_000)
elapsed     00:00:04.8573365

(forv i 0 500_000_000)
elapsed     00:00:03.9954295

(repeat 100_000 (each x (range 500)))
elapsed     00:00:02.3770812

(repeat 100_000 (eachk i (range 500)))
elapsed     00:00:02.0361187

(repeat 100_000 (eachp [i x] (range 500)))
elapsed     00:00:08.1919645
```

bytecode_opt:
```janet
(for i 0 500_000_000)
elapsed     00:00:03.9907836

(forv i 0 500_000_000)
elapsed     00:00:03.9849740

(repeat 100_000 (each x (range 500)))
elapsed     00:00:01.8969160

(repeat 100_000 (eachk i (range 500)))
elapsed     00:00:02.0130586

(repeat 100_000 (eachp [i x] (range 500)))
elapsed     00:00:07.8668622
```

Performance wins across the board, as you suggested. `each` became faster than `eachk`, which I certainly wouldn't have expected, and I would have expected a much bigger gain for `eachp`. Examining `eachp` specifically might give some more insights about possible opportunities for optimization.

**Comment by primo-ppcg** [comment]
Actually, `eachp` should probably just be reworked.

```janet
(defmacro eachp
  "Loop over each (key, value) pair in `ds`. Returns nil."
  [[i x] inx & body]
  (with-syms [k]
    (def ds (if (idempotent? inx) inx (gensym)))
    ~(do
       ,(unless (= ds inx) ~(def ,ds ,inx))
       (var ,k (,next ,ds nil))
       (while (,not= nil ,k)
         (let [,i ,k
               ,x (,in ,ds ,k)]
           ,;body)
         (set ,k (,next ,ds ,k))))))
```

master:
```janet
(repeat 100_000 (eachp [i x] (range 500)))
elapsed     00:00:02.5974994
```

bytecode_opt:
```janet
(repeat 100_000 (eachp [i x] (range 500)))
elapsed     00:00:02.2510916
```

**Comment by primo-ppcg** [comment]
Regarding `eachp`:

fast:
```janet
(do
  (def idx (range 500))
  (var k (next idx nil))
  (while (not= nil k)
    (let [i k x (in idx k)])
    (set k (next idx k))))
```

very slow:
```janet
(do
  (def idx (range 500))
  (var k (next idx nil))
  (while (not= nil k)
    (def p [k (in idx k)])
    (set k (next idx k))))
```

It seems that it's not the destructuring, but the tuple creation that's the culprit.

```janet
(setdyn *pretty-format* "%.99m")

(def idx (range 1))
(var k (next idx nil))

(pp (disasm |(let [i k x (in idx k)])))
(pp (disasm |(def p [k (in idx k)])))
# ->
{ :arity 0
  :bytecode @[(ldc 0 0) (geti 0 0 0) (ldc 2 1) (ldc 3 0) (geti 3 3 0) (in 1 2 3) (movn 2 1) (ret 1)]
  :constants @[@[0] @[0]]
  :defs @[]
  :environments @[]
  :max-arity 0
  :min-arity 0
  :slotcount 4
  :source "test-eachp.janet"
  :sourcemap @[(6 13) (6 13) (6 13) (6 13) (6 13) (6 13) (6 13) (6 13)]
  :structarg false
  :symbolmap @[(1 8 0 i) (6 8 2 x)]
  :vararg false}
{ :arity 0
  :bytecode @[(ldc 1 0) (ldc 2 1) (geti 2 2 0) (in 0 1 2) (ldc 1 1) (geti 1 1 0) (push2 1 0) (mktup 0) (movn 1 0) (ret 0)]
  :constants @[@[0] @[0]]
  :defs @[]
  :environments @[]
  :max-arity 0
  :min-arity 0
  :slotcount 3
  :source "test-eachp.janet"
  :sourcemap @[(7 13) (7 13) (7 13) (7 13) (7 13) (7 13) (7 13) (7 13) (7 13) (7 13)]
  :structarg false
  :symbolmap @[(8 10 1 p)]
  :vararg false}
```

**Comment by primo-ppcg** [comment]
> I think an optimization that would be really easy to make and really helpful for perf would be to undo as much destructuring as possible before compilation.

Agreed. This is essentially what I attempted, except by using a macro to perform the destructuring precisely once, rather than every iteration. The performance gains are very noticeable. It doesn't, however, improve this case any:
```janet
(def p [1 2])
```
which is precisely the case that slows `eachp`. I wonder if there shouldn't be some sort `nextp` core function, because the tuple does need to come from somewhere.

**Comment by primo-ppcg** [comment]
I'm happy to close this one if you are. You've done an incredible job with this. Timings are from a different machine than previously.

`for` vs. `forv`:
```janet
(for i 0 500_000_000)
1.28.0    2.412457s
master    2.142373s

(forv i 0 500_000_000)
1.28.0    2.169622s
master    2.126162s
```

destructuring assignment:
```janet
(repeat 500_000_000 (def [a b c] [1 2 3]))
1.28.0    8.586751s
master    1.97403s

(repeat 500_000_000 (upscope (def a 1) (def b 2) (def c 3)))
1.28.0    3.257633s
master    1.976364s
```

`each`, `eachk`, `eachp`:
```janet
(repeat 200_000 (each x (range 500)))
1.28.0    2.157444s
master    2.121743s

(repeat 200_000 (eachk i (range 500)))
1.28.0    1.859821s
master    1.831845s

(repeat 200_000 (eachp [i x] (range 500)))
1.28.0    7.117541s
master    2.118644s

(repeat 200_000 (eachp p (range 500)))
1.28.0    7.127844s
master    5.595903s
```

Some very significant performance wins. The only remaining outlier is `eachp p`, but even then it's significantly faster than before. If tuple creation could be made faster it would help a lot in the case, and many others.

**Comment by bakpakin** [comment]
Probably good to close for now, although there is always more work to be done with bytecode optimization. Currently there are some definitely more "easy" performance wins to be had from eliminating move instructions in generated bytecode - mainly removing moves, prevention of double loading of constants, not-needs `ldn` instructions, reducing the slotcount of functions, and likely more.

While Janet's bytecode isn't really in SSA form, a lot of the same optimization can be made here (albeit with a bit more work). But yeah, that is part of a more general discussion.
