### ISSUE TITLE
emacs support

### ISSUE THREAD

**Issue by velkyel** [janet-lang/janet#117]
just fyi

good&working janet-mode (not mine): https://github.com/ALSchwalm/janet-mode

https://github.com/velkyel/inf-janet
universa janet inferior mode.  when embedding (my case) it can connect to remote machine (my case, I'm embedding janet repl into ios game).

**Comment by bakpakin** [comment]
I've been trying out emacs with these modes, they work pretty well. I'll add some references to the website. Also https://github.com/SerialDev/ijanet-mode
