### ISSUE TITLE
The asymmetry of drop and take

### ISSUE THREAD

**Issue by primo-ppcg** [janet-lang/janet#1178]
The current implementations of `drop` and `take` are asymmetric:

`drop`
Allows dropping from the end.
Accepted types: bytes, indexed

`take`
Does not allow taking from the end.
Accepted types: bytes, indexed, dictionary, fiber, any other data type for which `next` is valid (aside: can we agree to call these all `iterable?`)

This is more of a request for comments than an open issue, although I do think that these functions should be symmetrically defined. My thoughts are the following:

1. For data types with a clearly defined end (bytes or indexed), taking or dropping from the end is a sensible thing to want to do, and should be allowed.
2. For data types without a clearly defined end (dictionary or fiber), taking or dropping from the end is not a sensible thing to want to do and should either:
  a. return the argument unmodified (`drop`), return an empty array (`take`)
  b. produce an error.
3. Taking or dropping from the front is a sensible thing to want to do for any data type for which `next` is valid, and should be allowed.

I could be swayed on any of these points (with exception to perhaps point 3), although as stated previously, I do think that these functions should be symmetrically defined.

**Comment by primo-ppcg** [comment]
> If you consider the dictionary to have a clearly defined front, it also has a clearly defined end, and vice versa.

I don't disagree, necessarily. Except that the core library defines `next` (and `next nil` as first), but does not define `last` or `previous`. As a result, a dictionary types can be easily iterated front to back, in some perhaps arbitrary order, but not back to front. And because this front to back ordering exists, it is sensible to allow it for  both drop and take.

> I'm curious, what exactly is the utility of dropping from the front on a dictionary?

I don't know that either of these functions must work with dictionary types. However, a consistent behavior between `take n` and `drop n` could definitely be useful in the implementation of various algorithms.

**Comment by primo-ppcg** [comment]
To elaborate a bit more on what I mean by asymmetry, if `take` were defined analogously to `drop`, the following assertions would hold in any applicable case:

```janet
(defn take
  ``Take the first `n` elements in an indexed or bytes type. Returns a new tuple or string
  instance, respectively. If `n` is negative, takes the last `n` elements instead.``
  [n ind]
  (def use-str (bytes? ind))
  (def f (if use-str string/slice tuple/slice))
  (def len (length ind))
  (def nonnegn (>= n 0))
  (def start (if nonnegn 0 (max 0 (+ len n))))
  (def end (if nonnegn (min n len) len))
  (f ind start end))

(var items-list ['abcde :abcde "abcde" @"abcde" [1 2 3 4 5] @[1 2 3 4 5]])

(each items items-list
  (def len (length items))
  (for i 0 (+ len 1)
    (assert (deep= (take i items) (drop (- i len) items)) (string/format "%q %d" items i))
    (assert (deep= (take (- i) items) (drop (- len i) items)) (string/format "%q %d" items i))))
```

And it does seem to me that these functions should be entirely analogous. It would be nice if both could work on fibers, and `take` currently does (with `drop` to exclude the first few results). I don't know that either would necessarily need to work with dictionary types.

**Comment by sogaiu** [comment]
I don't know if the following comments really cover anything new, but may be they can be forgiven as notes for my future self (^^;

> Except that the core library defines next (and next nil as first), but does not define last or previous. As a result, dictionary types can be easily iterated front to back, in some perhaps arbitrary order, but not back to front.

For the non-dictionary iterables (in the suggested terminology) cases, I think the notion of "front" and "back" have natural interpretations.  For dictionaries I wonder whether to think of them as having a "front" or "back" even if the underlying implementation suggests so -- could that not be seen as incidental?  Of course it always depends on definitions, right?

It does seem useful to be able to say "give me something from a dictionary" and "now give me something that you haven't given me already" (what `next` does) as this type of operation allows one to gradually consume some "collection" and in the non-fiber case, definitely get one closer to "having nothing left to look at".

> I don't know that either of these functions must work with dictionary types.

If one were starting from scratch with no existing code in the wild I would tend to agree as far as naming is concerned, but as far as the substance of what can be done is concerned, being able to work with dictionaries does seem useful (even if that's currently only `take`).

OTOH, AFAICT, the docs don't seem to advertise that `take` works with dictionaries:

>     Take the first n elements of a fiber, indexed or bytes type. 
>     Returns a new array, tuple or string, respectively.

so perhaps the option of not supporting them going forward is palatable / practical [1]?

May be for dictionaries, functions with different names could be considered or one could wait until there is an explicit request for supporting such constructs.

---

[1] Where's my nice code querying to run across my locally collected Janet code to make an assessment?

**Comment by primo-ppcg** [comment]
I believe this is the minimum change to allow taking from the end as `drop` does:

```diff
diff --git a/src/boot/boot.janet b/src/boot/boot.janet
@@ -1102,10 +1102,10 @@
 (defn- slice-n
   [f n ind]
   (def len (length ind))
-  # make sure end is in [0, len]
-  (def m (if (> n 0) n 0))
-  (def end (if (> m len) len m))
-  (f ind 0 end))
+  (def negn (< n 0))
+  (def start (if negn (max 0 (+ len n)) 0))
+  (def end (if negn len (min n len)))
+  (f ind start end))
```

With this change, the assertions above all hold true.

What isn't so clear, is the correct behavior for `take` with a dictionary type.

```janet
(var dict {:a 1 :b 2 :c 3 :d 4})
(pp (take 2 dict))
```
```janet
# currently
@[1 2]
# should be?
@{:a 1 :b 2}
```
Or if the same behavior should be implemented for `drop`.

**Comment by sogaiu** [comment]
> With this change, the assertions above all hold true.

Right.  Just providing confirmation here, but I tried it out and found the same.

> What isn't so clear, is the correct behavior for take with a dictionary type.

Indeed.

My gut reaction is to favor the dictionary value.  I have a feeling that only having the values (i.e. no corresponding keys) may be insufficient for some situations.

I think there is some merit in the idea of just not supporting dictionaries for the time being (so that would mean removing support [1]) and see if anyone (including ourselves) eventually find actual use cases.  We might have more time and data to consider at a later point to make a more informed decision.

Since `drop` doesn't currently support dictionaries, what to do about that case for it could be revisited later (along with `take`).

Looking over history info for `take`, it appears that in 34019222, "fiber-awareness" was added and then a few commits later in bb5c3773, some changes were made to make things less "fiber-specific".  The author of the latter changes might be queried regarding intentions or perhaps just whether removal is a real possibility :)

---

[1] As mentioned before, the docstrings never seemed to have promised dictionary support so may be this isn't too bad?

**Comment by primo-ppcg** [comment]
> Looking over history info for `take`, it appears that in [3401922](https://github.com/janet-lang/janet/commit/34019222c2420e77971fd102e029d41c8297c6e8), "fiber-awareness" was added and then a few commits later in [bb5c377](https://github.com/janet-lang/janet/commit/bb5c3773f17ef80e1fc098ed1830c667bb0efde9), some changes were made to make things less "fiber-specific".

Given that edit history, it doesn't seem that dictionaries were specifically intended. However, it wouldn't be particularly difficult to tailor it specifically to dictionaries, especially now that `eachp` is as efficient as `each`:

```janet
(defn- take-n-dict
  [n xs]
  (def res @{})
  (when (> n 0)
    (var left n)
    (eachp [i x] xs
      (set (res i) x)
      (-- left)
      (if (= 0 left) (break))))
  res)
```

However, this would result in code duplication for both `take-n-fallback` and `take-until-fallback`.

**Comment by sogaiu** [comment]
Thanks for sharing your use case.

Yeah, I think fiber use cases are easier for me to imagine [1] than those for dictionaries.  When working with potentially infinite things (well the countable sort anyway), fibers seem like a natural candidate for consideration.

Regarding dictionaries, I guess in Clojure what's returned by `take` for a map value is essentially what would be a tuple of pairs [2]:

```
(take 3 {:a 1 :b 2 :c 3 :x 0})
# =>
([:a 1] [:b 2] [:c 3])
```

I don't know if that's evidence that using `take` with a map is not so common there and/or it's an efficiency thing (or something else even).

Incidentally, for sets, the return value is again like a tuple:

```
(take 2 #{:a :b :c})
# =>
(:c :b)
```

Looking at those I guess what's nice is that after the first `take`, subsequent invocations of `take` on the returned values don't bother to "package things up" -- possibly with the idea that that could be a waste across iterations?

You mentioned potential code duplication for supporting dictionaries.  I don't know if that would be considered an issue, but the case for supporting dictionaries at this point still seems kind of unclear to me.

---

[1] Though now that you shared your use case I can save energy ;)

[2] Actually a `LazySeq` I guess, so may be even somewhat akin to a fiber?
