### ISSUE TITLE
Proposal: a shorthand for partial

### ISSUE THREAD

**Issue by primo-ppcg** [janet-lang/janet#1184]
As argumented below, a shorthand for `partial` would be very nice to have, and the idea at least seems to have broad support. I believe that zero argument `short-fn` could be used for this purpose.

In particular, this would not break or change existing zero-argument `short-fn`s:

```janet
(|(*)) # -> 1
((partial *)) # -> 1
```
The change required to the `short-fn` macro is also minimal:
```diff
diff --git a/src/boot/boot.janet b/src/boot/boot.janet
@@ -2302,7 +2302,9 @@
   (def expanded (macex arg on-binding))
   (def name-splice (if name [name] []))
   (def fn-args (seq [i :range [0 (+ 1 max-param-seen)]] (symbol prefix '$ i)))
-  ~(fn ,;name-splice [,;fn-args ,;(if vararg ['& (symbol prefix '$&)] [])] ,expanded))
+  (if (or (> max-param-seen -1) vararg)
+    ~(fn ,;name-splice [,;fn-args ,;(if vararg ['& (symbol prefix '$&)] [])] ,expanded)
+    ~(fn ,;name-splice [& ,prefix] (,;expanded ;,prefix))))
```

The one minor issue that this has, is that forms like `|4` would no longer be valid. Unfortunately, I don't think this could be rectified merely by adjusting the macro. However, the use case for anonymous functions that accept no arguments and return a constant value is not so clear to me. I think that it may be an acceptable compromise to forego one in favor of the other.

Additionally, being implemented as a macro also makes `partial` far more efficient:
```janet
(for i 0 10_000_000 ((partial * 2) i)))
elapsed 3.108453s, 0.3108µs/body

(for i 0 10_000_000 (|(* 2) i))
elapsed 1.559186s, 0.1559µs/body
```
so that's also a consideration.
...
On second thought, `partial` could also be rewritten as a macro for the same performance gain, which makes the point somewhat moot:
```janet
(defmacro partial
  "Partial function application."
  [f & more]
  (if (zero? (length more)) f
    (with-syms [r]
      ~(fn [& ,r] (,f ,;more ;,r)))))
```
and the changes refactored to use it:
```diff
-    ~(fn ,;name-splice [& ,prefix] (,;expanded ;,prefix))))
+    ~(partial ,;expanded)))
```
which is definitely more clear. The same limitations apply, though.

---
### _This is the previous proposal, left for context_

> This may be a matter of preference, but I personally find forms like the following:
```janet
(count (partial = val) items)
```
> to be far more appealing _functionally_ than either of the following:
```janet
(count (fn [x] (= val x)) items)
(count |(= val $) items)
```
> However, I do think that the use of `partial` distracts from the intent slightly, which makes me somewhat hesitant to use it. As an example, if you were to show someone unfamiliar with Janet the following:
```janet
(count \(= val) items)
```
> they would be able to tell you precisely what it does with very high likelihood. Whereas if you were to show them one of the three examples above, they might stumble over it, and in particular the first example (I've used `\` here for the purpose of illustration. I don't know that it's a good choice, although Haskell also uses backslash for anonymous functions, so there is some precedent. It also seems like a close parallel to `|`).

> Other examples might include:
```janet
(take-until |(< val $) items)
(filter |(not= val $) items)
(map |(* 2 $) items)
```
> which, in my opinion would all look much cleaner written as:
```janet
(take-until \(< val) items)
(filter \(not= val) items)
(map \(* 2) items)
```
> or other sensible shorthand.

> I've already implemented this on my [local fork](https://github.com/primo-ppcg/janet/commit/56ba529a8cb45016c7ec95f5d433ec5168d56582), mainly to illustrate the extent of the change required, and it isn't much. All of the following assertions pass:
```janet
(assert (= (macex ~\f) (macex ~(partial f))) "shorthand partial argless 1")
(assert (= (macex ~\(f)) (macex ~(partial f))) "shorthand partial argless 2")
(assert (= (macex ~\(f arg)) (macex ~(partial f arg))) "shorthand partial 1 arg")
(assert (= (macex ~\(f arg0 arg1)) (macex ~(partial f arg0 arg1))) "shorthand partial 2 args")
(assert (= (macex ~\(f arg0 arg1 arg2)) (macex ~(partial f arg0 arg1 arg2))) "shorthand partial 3 args")
(assert (= (macex ~\\\f) (macex ~(partial partial partial f))) "nested shorthand partial 1")
(assert (= (((\\\+ 1)2)3) 6) "nested shorthand partial 2")
```

**Comment by pepe** [comment]
I like the idea. I even understand the implementation. I will go through my codes and check where it makes sense.

**Comment by CosmicToast** [comment]
I'm greatly in favor of the general concept (what I've been doing is a `def- isX (partial = x)`), but would bikeshed the character itself.
`\` is commonly used in imperative languages as an "escape" character, including inside of strings, so using it here is non-ideal.
I don't have any better suggestions, though.

**Comment by pepe** [comment]
The precious symbol characters :-). I have no better suggestions, also.

**Comment by primo-ppcg** [comment]
> I think `\` is the last unused printable ASCII character in Janet [2] so I'm not in favor of using it lightly (or any time soon). I don't know what bakpakin's thoughts are on this topic, but if there is only one thing left then I think a natural candidate for how it might get used would be for some kind of general extension mechanism -- possibly like how in Clojure `#` is used [3].


A reasonable consideration. Of all the [non-symbol characters](https://github.com/janet-lang/janet/blob/master/src/core/parse.c#L48-L51) `` "#'(),;[\]`{|}~``, I think you're right that only `\` doesn't have a special meanting.

I also quite like `&` (mnemonic: this function is expecting _more_ arguments, also a logical parallel to `|`), although I think that being a valid identifier might cause problems.

**Comment by pepe** [comment]
I am unsure about the implementation, but what about double `||`?

Thanks, @sogaiu, for reminding me about the last char. I have a sentence about "one of the last characters" in my first post but removed it not to sound too negative again.

**Comment by sogaiu** [comment]
@pepe Re: `||` -- see the last line [here](https://github.com/sogaiu/tree-sitter-janet-simple/blob/bd9cbaf1ea8b942dfd58e68df10c9a378ab3d2b6/grammar.js#L220-L238).

**Comment by pepe** [comment]
@sogaiu, you are correct, as always. I checked my codes and only found `|(fn arg $ )`. I have not found the `partial` in once, so I am not a target group.

**Comment by sogaiu** [comment]
Neat!

**Comment by primo-ppcg** [comment]
[This](https://github.com/janet-lang/janet/commit/a270213a6c9029d376e8c70b06d4345775cb2b3d) appears to be sufficient:

```diff
diff --git a/src/boot/boot.janet b/src/boot/boot.janet
@@ -2302,7 +2302,9 @@
   (def expanded (macex arg on-binding))
   (def name-splice (if name [name] []))
   (def fn-args (seq [i :range [0 (+ 1 max-param-seen)]] (symbol prefix '$ i)))
-  ~(fn ,;name-splice [,;fn-args ,;(if vararg ['& (symbol prefix '$&)] [])] ,expanded))
+  (if (or (> max-param-seen -1) vararg)
+    ~(fn ,;name-splice [,;fn-args ,;(if vararg ['& (symbol prefix '$&)] [])] ,expanded)
+    ~(fn ,;name-splice [& ,prefix] (,;expanded ;,prefix))))
```

... with one minor caveat. Something like `|4` will no longer return a function that returns a constant. I don't know that this is necessarily a problem, though.

**Comment by sogaiu** [comment]
FWIW, I searched across the 4000 or so `.janet` files [1] collected locally and the test file in janet is pretty much the only place I come across the "problematic" construct.

---

[1] There are likely some duplicates so the number is inflated.

**Comment by pepe** [comment]
I vote for this change even if the constant returning functions are gone :-)

**Comment by CosmicToast** [comment]
I've used the constant-returning functions, but we could simply add a "constantly" or similar function to boot.janet that's simply `(defn constantly [x] (fn [] x))`

**Comment by CosmicToast** [comment]
Actually, thinking of it, would it affect code like this?
`|{:a :b}` and `|{:a $}`?

**Comment by primo-ppcg** [comment]
> Actually, thinking of it, would it affect code like this?

> `|{:a :b}`

yes.

> `|{:a $}`

no.

Ok, I'll tweak the macro more to preserve the current behavior.

**Comment by primo-ppcg** [comment]
> Ok, I'll tweak the macro more to preserve the current behavior.

Actually, I don't think this can be done. Cases like `|(do 4)` couldn't be easily detected.

@CosmicToast 
This use case is clear.
```janet
|{:a $}
```
This use case is not so clear.
```janet
|{:a :b}
```
Can you give an example of a practical application for an anonymous function that accepts no parameters and returns a constant value?

**Comment by primo-ppcg** [comment]
> I do also want to push back slightly against the new proposal, however (sorry). In most cases this only saves about 2 characters compared to using `$`, but I see multiple small downsides.

For me, `partial` vs `short-fn` is more about the _ugliness_ of the positional arguments.

> It breaks backwards compatibility

I'm still optimistic that a solution can be found that doesn't. At worst, code that used to error would fail to do so (by passing an argument to `short-fn` that takes none).

> More subjectively, this proposal uses varargs by default

That is the point of a partial invocation, a function that produces a function that is waiting for additional arguments. In functional programming languages it is a fundamental construct.

**Comment by bakpakin** [comment]
I've had a few ideas for what to do with this last precious character in the Janet syntax, and  as nice as the feature could be, it is a bit underwhelming. If anything, some sort or shorthand for custom literals that expanded a pair of the form constructor\data (a simple form of something like dotted pairs, but instead of a cons cell just a 2-tuple) - perhaps the backslash could be generalized from this to be a tuple separator that doesn't need surrounding brackets, but there are some caveats here.

But really it just isn't that necessary. Partial is not general enough to warrant the special syntax and I'm not sure the dotted pair shorthand is useful enough either.

**Comment by primo-ppcg** [comment]
> For me, adding a special case to `short-fn` is more ugly than adding an explicit `$`.

I don't disagree. I also would have preferred a separate form.

> The current proposed change breaks code like `|@{:a :b :c :d}`,

```janet
(fn [] |@{:a :b :c :d})
# vs
(fn [&] |@{:a :b :c :d})
```
Not broken, but admittedly less efficient.

Closing this, perhaps to revisit at a later time.

@bakpakin 
Do you think it would be acceptable to change partial to a macro? In most languages, partial invocation is a syntax. I don't know that it's necessary or useful to be a function itself.

**Comment by primo-ppcg** [comment]
> But really it just isn't that necessary. Partial is not general enough to warrant the special syntax and I'm not sure the dotted pair shorthand is useful enough either.

Just about anything can be expressed solely in terms of `partial` and `comp` (with perhaps an occasional `flip`), but I understand your point. It's certainly not as versatile as the current `short-fn` syntax. That function invocation (and in particular for variadic functions) has so much overhead does make the whole matter somewhat less attractive as well.

**Comment by primo-ppcg** [comment]
It would still work either way:
```janet
(fn [] (worker "sally" 20))
# vs
(fn [&] (worker "sally" 20))
```
but ultimately, I don't think the second proposal is all that good either. It's hacky and unintuitive.

I've spent some time thinking about this, less in terms of what would be easy to implement, and more in terms of what would be ideal, and offer additional utility beyond just making functional predicates look nicer.

To me, I think the ideal would simply be this:
```janet
(take-until (< val) items)
```
In other words, all variadic function calls would be partial by default, lazily collecting arguments until a value is actually needed. However, I don't think that this can actually work in a dynamically typed language. The compiler has no way to determine that the value needed isn't the partially invoked function itself.

Another good alternative might have been this:
```janet
(take-until '(< val) items)
```
This would imply that a tuple invoked as a function would be treated as partial invocation:
```janet
('(< val) x)
# ->
(< val x)
```
or as a left hand invocation:
```janet
(x '(< val))
# ->
(< x val)
```
or curried:
```janet
('('(< val) x) y)
# ->
(< val x y)
```
Something like `->` and `->>` rolled into one, except that it's a functional form that can be reused, rather than expanding in place. Of course, treating a tuple as a function is already a shorthand for `in`, which wouldn't have been necessary in my opinion, but that's how it is.

**Comment by pepe** [comment]
I had some time to code in Janet lately, and I love to have ways for an anonymous function shorthand notation to ignore arguments. So I can call `(|[:a :b] 1)`, and it will not error with an expected number of arguments met—something akin to `[&]` in a function definition. Maybe `|&` is possible?

**Comment by primo-ppcg** [comment]
> Sorry for hijacking here :-).

No worries, this has more or less turned into a discussion thread anyway.

> I love to have ways for an anonymous function shorthand notation to ignore arguments.

Not exactly what `partial` would do, I think you would need to wrap it as a variadic function. A constant function that accepts any number of arguments seems like a rare use case, or maybe I'm wrong?

I also think that `|&(stuff)` would be relatively difficult to parse. The parse chain would be reader macro `|`, identifier `&`, tuple, which I think would require some pretty significant special-casing (reader macros currently see only the immediately following parsed form).

**Comment by pepe** [comment]
@primo-ppcg, thank you. The thing is, I am not that sure about all the Janet internals and generally the C :-). 

And yep, not partial at all. That's why I apologized :-).

**Comment by primo-ppcg** [comment]
Here's an implementation of `partial` as `|&`: https://github.com/primo-ppcg/janet/commit/a27247fe3d9388da32785af16ae21801f467cee7

```janet
(pp ~|&[:a :b])
# ->
(partial [:a :b])

(pp ~||&[:a :b])
# ->
(short-fn (partial [:a :b]))

(pp ~|&|[:a :b])
# ->
(partial (short-fn [:a :b]))
```

I think that should cover just about everything ;)
