### ISSUE TITLE
if-let behavior appears different in #1188

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet#1189]
The following code used to not error for me:

```janet
(if-let [[l r] (peg/match "a" "b")]
  :a
  :b)
```

With https://github.com/janet-lang/janet/commit/2c3ca2984ec731f9804abee1f6b52031bbbd62a4 I get:

```
$ janet
Janet 1.28.0-dev-2c3ca298 linux/x64/gcc - '(doc)' for help
repl:1:> (if-let [[l r] (peg/match "a" "b")]
repl:2:(>   :a
repl:3:(>   :b)
error: expected string, symbol, keyword, array, tuple, table, struct or buffer, got nil
  in _thunk [repl] (tailcall) on line 1, column 1
```

With https://github.com/janet-lang/janet/commit/94722e566c6f9bab9b0c8e630b0fd1aed4e10739 I get:

```
$ ./build/janet
Janet 1.28.0-dev-94722e56 linux/x64/gcc - '(doc)' for help
repl:1:> (if-let [[l r] (peg/match "a" "b")]
repl:2:(>   :a
repl:3:(>   :b)
:b
```

**Comment by sogaiu** [comment]
Note that `when-let` (as it's implemented in terms of `if-let`) is also affected as well:

```
$ janet
Janet 1.28.0-dev-2c3ca298 linux/x64/gcc - '(doc)' for help
repl:1:> (when-let [[a b] nil] :a)
error: expected string, symbol, keyword, array, tuple, table, struct or buffer, got nil
  in _thunk [repl] (tailcall) on line 1, column 1
```

For comparison its older behavior was:

```janet
$ ./build/janet
Janet 1.28.0-dev-94722e56 linux/x64/gcc - '(doc)' for help
repl:1:> (when-let [[a b] nil] :a)
nil
```

**Comment by sogaiu** [comment]
I'm pretty sure I came to rely on the not-erroring behavior because it seemed more convenient.  I didn't look into why it was working and I didn't check that this wasn't intended (at least I didn't look closely at various docstrings nor did I ask around).

I suppose if I'm alone in having gone this path then the good news is that there's only one person who needs to rewrite code :)

**Comment by primo-ppcg** [comment]
> I suppose if I'm alone in having gone this path then the good news is that there's only one person who needs to rewrite code :)

```janet
(if-let [a b] (possibly-nil-or-tuple) ...)
```
Seems like a perfectly valid use case, at least to me. I'll make an amendment.

**Comment by zevv** [comment]
But this will mean the rules for not being to able to deconstruct a `nil` will be different from not being able to deconstruct something else?

**Comment by primo-ppcg** [comment]
> But this will mean the rules for not being to able to deconstruct a `nil` will be different from not being able to deconstruct something else?

Yes, by definition really.

[if-let](https://janet-lang.org/api/index.html#if-let)
_If any are false or nil, evaluate the `fal` form._
