### ISSUE TITLE
if-let's else branch appears multiple times in its expansion

### ISSUE THREAD

**Issue by ianthehenry** [janet-lang/janet#1191]
This is unrelated to the recent `if-let` changes -- `if-let` has always worked this way, but I found this very surprising:

```
repl:1:> (defmacro hello [] (print "hello") 1)
<function hello>
repl:2:> (if-let [a true] "ok" (hello))
hello
"ok"
repl:3:> (if-let [a true b true] "ok" (hello))
hello
hello
"ok"
repl:4:> (if-let [a true b true c true] "ok" (hello))
hello
hello
hello
"ok"
```

I would expect the else branch to only appear once in the expansion of `if-let` -- which I believe is not compatible with the desire to be able to reference the first binding form in the else branch.

**Comment by primo-ppcg** [comment]
I could also be implemented differently. Since we've already touched it, it may be worth addressing.
