### ISSUE TITLE
`int/*64` does not support complement / not

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet#1208]
Currently, `int/s64` and `int/u64` support most of the common bit manipulation operations:

https://github.com/janet-lang/janet/blob/b125cbeac9e43ca7adb3f066fef679ac58a91c71/src/core/inttypes.c#L549-L597

Notably absent is `complement` / `not`.

Is there a technical reason this could / should not be implemented?

---

primo-ppcg shared [some considerations](https://github.com/janet-lang/janet/pull/1207#issuecomment-1615552101) regarding some implementation considerations.

**Comment by primo-ppcg** [comment]
I'm implemented this on my [local fork](https://github.com/janet-lang/janet/commit/ebbe471af911ec5167c13dd71c14f9aa17b61d6f), I don't believe there's any issue:
```janet
(for n -99 100
  (assert (compare= (bnot n) (bnot (int/s64 n)))))

(assert (= (int/u64 "0xFFFF_FFFF_FFFF_FFFF") (bnot (int/u64 0))))
```

**Comment by bakpakin** [comment]
Just an error of omission
