### ISSUE TITLE
c api question (janet_table_find)

### ISSUE THREAD

**Issue by velkyel** [janet-lang/janet#122]
I would like to call janet function (my-fn) from c/c++ like this:
```
JanetKV* kv = janet_table_find(env, janet_wrap_symbol("my-fn")));
JanetFunction* fn = janet_unwrap_function(kv->value);
Janet args[1] = {janet_wrap_number(1.23)};
Janet res = janet_call(fn, 1, args);
```
problem is that janet_table_find() returns {JANET_NIL, JANET_NIL} (tried janet_table_get, tried_janet_table_getraw too).
when I iterate **the same** env table by hand symbol my-fn is presented:
```
JanetKV* kv = env->data;
JanetKV* end = env->data + env->capacity;
while (kv < end) {
  if (!janet_checktype(kv->key, JANET_NIL)) {
    if (janet_type(kv->key) == JANET_SYMBOL) {
      printf("%s\n", janet_unwrap_symbol(kv->key);
    }
  }
}
```
what could be wrong please?

**Comment by bakpakin** [comment]
The problem is `janet_wrap_symbol("my-fn")`. This is only for wrapping a symbol already created via `janet_symbol` or some other means. You want `janet_csymbolv("my-fn")`. (The `c` means convert a c string to a janet string, and the `v` means return a `Janet` value instead of a `const uint8_t *`.

**Comment by velkyel** [comment]
yes, thank you.   but I still didn't call my-fn.  ```janet_table_rawget(env, janet_csymbolv("my-fn"))``` returns table with two keywords, value of ```:value``` is my function I guess but if I unwrap it to function and call it using janet_call(), it fails.  Can you please write short snippet how to call janet function in global namespace from c? (I know its name and arguments)

**Comment by bakpakin** [comment]
To wrap this all up, try the function `janet_resolve` It does almost exactly what you are doing above but wraps it up into a single call. The usage is something like:

```c
Janet returnval;
JanetBindingType result = janet_resolve(env, janet_csymbol("my-fn"), &returnval);
assert(result == JANET_BINDING_DEF);
/* Use whatever arguments you want. Below is my-fn is called with 0 arguments. */
returnval = janet_call(janet_unwrap_function(returnval), 0, NULL);
```

janet_call may not work if you are outside a Janet function call. If, for example, you get an error like `janet_call failed because there is no current fiber`, you probably want ti use janet_pcall.

**Comment by velkyel** [comment]
it works now (I have to use pcall too), thank you very much!
