### ISSUE TITLE
Multiple top-level forms in defmacro?

### ISSUE THREAD

**Issue by Ruin0x11** [janet-lang/janet#126]
Is there a way of getting back more than one top-level form from `defmacro`?  I think Clojure and Racket have this feature. I want to make a macro that can output this:

```clojure
(defn my-fn [& rest]
  (string "foo"))
(put all-fns :my-fn my-fn)
```

However, it seems `defmacro` only outputs the last form if more than one is given, so you can't do this:

```clojure
(defmacro my-defn [name & more]
  ~(defn ,name ,;more)
  ~(put all-fns ,(keyword name) ,name))
```

Wrapping it with `do` is problematic because I still want `my-fn` to be scoped to the top-level. Also, trying to use `splice` still creates a tuple of values.

As a background, I'm trying to learn the macro system by making a library that can be used as either a macro or a series of functions. The macro version will compile a series of sexps into a string literal at execution time, while there is an equivalent function for each that can be called to return a single string, like this:

```clojure
(lib/compile
  (foo)
  (bar)
  (baz))

(string/join
  (lib/foo)
  (lib/bar)
  (lib/baz))
```

**Comment by bakpakin** [comment]
> Is there a way of getting back more than one top-level form from defmacro? I think Clojure and Racket have this feature.

Clojure certainly cannot do this, at least without reader macros, if I am understanding this correctly. https://stackoverflow.com/questions/15796831/clojure-macro-to-return-two-or-more-s-expressions. Racket may, but Janet is unlikely to as we don't have multiple return values (nor do I plan on adding them). Multiple return values are a headache, and cause more problems than they solve, especially when you have proper destructuring of tuples.

Wrap it in a `do` and use the functions `defglobal` and `varglobal` to define your functions. These will define things at the top scope.

```clojure
(do
  (defglobal 'my-fn "docstring... " (fn 'my-fn [] ...))
  (defglobal 'my-fn "docstring... " (fn 'my-fn [] ...)))
```

**Comment by bakpakin** [comment]
As for splicing, that won't work here. Splice only works as an argument to a function call or inside a quasiquote. Splice as a top level form, or not as an argument to a function will do nothing and act as the identity function. Future version may even raise a compilation error.

**Comment by Inc0n** [comment]
What's the difference between `defn` and `defglobal`? Seeing that `defglobal` would be able to create top level binds whilst defn can't.

**Comment by Inc0n** [comment]
Hmm, it looks like `defn` can be nested within `defn`s, and the scope will limit what is accessible from outside.
