### ISSUE TITLE
if/while `(not= nil x)` doesn't always compile to `jmpni`

### ISSUE THREAD

**Issue by primo-ppcg** [janet-lang/janet#1267]
This isn't so much an issue, as an observation.

I've noticed that minor changes can make significant differences in execution speed. One of those is coercing the compiler into using `jmpni` or `jmpnn` for `not= nil` and `= nil`.

A minimal example:
```janet
(defmacro- not-nil-helper [a]
  ~(do
     (var res false)
     (while (not= nil ,a)
       (set res true)
       (break))
     res))

(defn not-nil? [a]
  (not-nil-helper a))

(pp ((disasm not-nil?) :bytecode))
```
```janet
@[(ldf 2) (ldn 4) (neq 3 4 0) (jmpno 3 4) (ldt 2) (jmp 2) (jmp -5) (ret 2)]
```
If we make one minor change, the compiler performs the appropriate optimization:
```diff
-     (while (not= nil ,a)
+     (while (,not= nil ,a)
```
```janet
@[(ldf 2) (jmpni 0 4) (ldt 2) (jmp 2) (jmp -3) (ret 2)]
```
In all variations of:
```janet
(while (not= nil ,a)
(while (,not= nil ,a)
(while (= nil ,a)
(while (,= nil ,a)
(if (not= nil ,a)
(if (,not= nil ,a)
(if (= nil ,a)
(if (,= nil ,a)
```
the only one that appears to optimize to a single op is `(while (,not= nil ,a)`.

An interesting consequence is that the `while` loop above (with unconditional `break`) compiles to more efficient code than `if`:
```janet
(defmacro- not-nil-helper [a]
  ~(do
     (var res false)
     (if (,not= nil ,a)
       (set res true))
     res))

(defn not-nil? [a]
  (not-nil-helper a))

(pp ((disasm not-nil?) :bytecode))
```
```janet
@[(ldf 2) (ldn 4) (neq 3 4 0) (jmpno 3 3) (ldt 2) (jmp 1) (ret 2)]
```
Hand-rolled, this could be written as just:
```janet
@[(ldf 1) (jmpni 0 2) (ldt 1) (ret 1)]
```

**Comment by bakpakin** [comment]
This makes sense mostly, as I specifically wrote a case for this so that fast loops could be compiled to break on `(not= nil x)`. We could certainly expand this check to include a few more forms fairly easily. What _is_ confusing to me is that `(,not= nil x)` and `(not= nil x)` behave differently.

**Comment by bakpakin** [comment]
Looks like it works to me. The extra `(jmp 1)` elimination also looks correct :+1:

**Comment by sogaiu** [comment]
Tried it out with some tests for various repositories and didn't notice any issues :+1:
