### ISSUE TITLE
How to "dynamically load C libraries"?

### ISSUE THREAD

**Issue by VedVid** [janet-lang/janet#127]
When I was reading the list of features on Janet's website, it sounded like Janet can load C dll / so and work with it straight out of the box, using some kind of FFI to call functions directly or to create a wrapper.
After checking docs and libui bindings it looks like I was mistaken and I need to write C code to create Janet bindings. Am I missing something?

Best regards,  
Ved

**Comment by bakpakin** [comment]
Yes, you would need to write a wrapper. Janet’s modules are very similar to those for Lua, and Janet does not have an FFI.

**Comment by VedVid** [comment]
OK, thanks for the clarification.
