### ISSUE TITLE
(comment) does not work as inline comment

### ISSUE THREAD

**Issue by iacore** [janet-lang/janet#1271]
`(comment x)` returns `nil`. I don't think it should be the case, since it should just be ignored like comment.

The following should work
```
(def a (comment hi) 1)
```

**Comment by sogaiu** [comment]
FWIW, that's how it also [works in Clojure](https://clojuredocs.org/clojure.core/comment).

A similar form in Emacs Lisp called [`ignore` also works that way](https://www.gnu.org/software/emacs/manual/html_node/elisp/Calling-Functions.html#index-ignore).

I would prefer that the current behavior not change.

I wouldn't mind an additional form that behaves differently though.

**Comment by iacore** [comment]
I don't think special form or `defmacro` can work like I proposed. It has to be in the parser.

**Comment by iacore** [comment]
Closing for now. #1272
