### ISSUE TITLE
Add `lengthable?`

### ISSUE THREAD

**Issue by primo-ppcg** [janet-lang/janet#1279]
I've [proposed this previously](https://github.com/janet-lang/janet/pull/1247), and determined that it wasn't necessary, but it [seems that it is](https://github.com/janet-lang/janet/commit/d9605c2856d1b4bc45fffc2b0e496fa9ca95970b).

[`JANET_TFLAG_LENGTHABLE`](https://github.com/janet-lang/janet/blob/bfb60fdb848bff60a465e607a7dd9bb36b850578/src/include/janet.h#L553-L558) is used within the capi to efficiently determine if a given `Janet` is a bytes, indexed, or dictionary - in other words, a vaild target for `length`. Many functions in `boot.janet` can be implemented more efficiently if the argument type is known to have a fixed length, primarily by creating an array of the correct length, rather than iteratively pushing to an empty array. I think it would be a good idea to expose `lengthable?` through the corelib.

I don't know that `lengthable?` is the best name, but it is certainly accurate and unambiguous.

What I'm trying to avoid with all of this is maintaining a user library which re-implements core functions more efficiently. Contributing faster implementations seems like a better idea to me.

**Comment by sogaiu** [comment]
Exposing doesn't seem bad also from a symmetry perspective with `bytes?`, `indexed?`, and `dictionary?`.  Though there doesn't seem to be a `callable?` (may be there isn't yet a need?).

I tried but failed to think of a better name.  If going forward with this, I am in favor of `lengthable?`.  I think it's better than `sizable?`, `has-length?`, or `i-can-has-length?`.

**Comment by pepe** [comment]
The name is OK, but I am not a native speaker, so :-D.

I would like to see `callable?` here: https://git.sr.ht/~pepe/gp/tree/master/item/gp/data/navigation.janet#L26 :-).

And 100% for the last sentence of the original post.

**Comment by sogaiu** [comment]
Regarding `callable?`, it looks like [the definition might end up not being exactly equivalent to the type being `:function` or `:cfunction`](https://github.com/janet-lang/janet/blob/bfb60fdb848bff60a465e607a7dd9bb36b850578/src/include/janet.h#L557-L558)?

```
#define JANET_TFLAG_CALLABLE (JANET_TFLAG_FUNCTION | JANET_TFLAG_CFUNCTION | \
        JANET_TFLAG_LENGTHABLE | JANET_TFLAG_ABSTRACT)
```

**Comment by pepe** [comment]
Oh my bad. Thank you @sogaiu.

**Comment by pepe** [comment]
But it could be more correct in that place. I will thing about it.
