### ISSUE TITLE
Makefile:275: *** target pattern contains no '%'.  Stop.

### ISSUE THREAD

**Issue by 717g301github** [janet-lang/janet#128]
~/Programming/git/janet $ make
Makefile:275: *** target pattern contains no '%'.  Stop.

**Comment by bakpakin** [comment]
What system are you on? The current makefile is non standard and requires GNU make. Or you can try the meson build.

**Comment by 717g301github** [comment]
Yes, I am using GNU, on GNU Hyperbola GNU/Linux-libre

**Comment by 717g301github** [comment]
There is no configure script.

**Comment by bakpakin** [comment]
If the current Makefile doesn't work, I recommend using the [Meson](https://mesonbuild.com/) build, which has the equivalent of a `./configure` step. Most distros have a meson package, and once installed, a typical build goes as follows.

```
cd ~/code/janet
meson setup build --buildtype=release
cd build
ninja
sudo ninja install
```
To add options, you can enable/or disable features during the setup phase. See `meson_options.txt` for a list of options.

```
meson setup build --buildtype=debug --Dpeg=false -Dsingle_threaded=true
```

**Comment by bakpakin** [comment]
Closing because using meson is the best solution here.
