### ISSUE TITLE
Add `:unless` loop modifier

### ISSUE THREAD

**Issue by primo-ppcg** [janet-lang/janet#1286]
I recently attempted to write something like this:
```janet
(seq [i :in vals :unless (f i)] ...)
```
and was surprised that isn't supported. Of course, this can be written as `:when (not (f i))`, but given the presence of both `:while` and `:until`, it seems like an omission.

It's also trivial to add:
```diff
@@ /src/boot/boot.janet -467,10 +467,11 @@
         (case binding
           :until ~(do (if ,verb (break) nil) ,rest)
           :while ~(do (if ,verb nil (break)) ,rest)
           :let ~(let ,verb (do ,rest))
           :after ~(do ,rest ,verb nil)
           :before ~(do ,verb ,rest nil)
           :repeat (with-syms [iter]
                     ~(do (var ,iter ,verb) (while (> ,iter 0) ,rest (-- ,iter))))
           :when ~(when ,verb ,rest)
+          :unless ~(unless ,verb ,rest)
           (error (string "unexpected loop modifier " binding))))))
```

**Comment by sogaiu** [comment]
I usually find code that uses `(unless ...` over `(when (not ...` harder to understand when I'm reading someone else's code.

I've used such code myself, but when returning to it, it hasn't been unusual to find it harder to understand and I sometimes resort to rewriting using `(when (not ...`.

That said, it seems easy to add (and maintain?) and `unless` is part of Janet, so it seems like a sensible change to me.
