### ISSUE TITLE
(gensym) occassionally generates non-unique values

### ISSUE THREAD

**Issue by fuxoft** [janet-lang/janet#1298]
During my Janet experiments with coroutines, fibers and channels, I found out that `gensym` does not always generate unique values (even when my script does not use threads).

I managed to isolate the problem in [this](https://gist.github.com/fuxoft/bda3ad93006f42233de64342f5e7130f) 50-line script.

When you run it, it endlessly prints `(gensym)` values (at line 30), which are **constant**:

```
_00000x
_00000x
_00000x
_00000x
_00000x
_00000x
...
```

When I attempt to simplify the code further, the printed values become unique again.

When I change the constant `10000` at line 46 to `10`, the printed values also become unique.

I am using `Janet 1.31.0-c31314be linux/x64/gcc`.

**Comment by sogaiu** [comment]
No real answers, but I found that changing the end of the code to be [1]:

```janet
(def wait
  (do
    (def render-fun
      (do
        (def cor (:renderer-coroutine track1))
        (fn [] (resume cor))))
    (fn []
      (repeat 600
        (render-fun)))))

(repeat 6
  (:note-on track1 60)
  (wait))
```

yields the output:

```
_00000y
_00000z
_00000A
_00000B
_00000B
_00000C
```

So it looks like `gensym` values are not constant the whole time.

Neither does the repetition seem to be from some point onwards.

```
$ janet
Janet 1.31.0-7b4c3bdb linux/x64/gcc
```

---

[1] So the `10000` has been replaced with `600` and the `forever` loop has been replaced with a `repeat 5` loop.

**Comment by bakpakin** [comment]
You have discovered the garbage collector cleaning up the old symbols :). If you keep references to the old symbols around in the program, our turn off gc via `(gcsetinterval 0xFFFFFFFF)`, the issue disappears.
