### ISSUE TITLE
Long-string parsing for `CR` `LF` vs `LF` eol sequences differ

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet#1302]
The following code yields different results [1] when it contains different end-of-line sequences (`CR` `LF` vs `LF`) [2] (tested with c708ff9708786f06744f92904dd5e2c0d2dd58a2):

```janet
(def long-string
  ``
  first line
  second line
  ``)

(pp long-string)
```

When using `CR` `LF`, the result I get is:

```
"\r\nfirst line\r\nsecond line\r"
```

When using just `LF`, the result I get is:

```
"first line\nsecond line"
```

I presume the latter form (when only `LF` is used) is correct in that it removes the leading and trailing eol sequences.

Presumably when `CR` `LF` is used for a file, one would want the result to be:

```
"first line\r\nsecond line"
```

_Update_: I think we may not want the `CR` in this example.  See [this comment below](https://github.com/janet-lang/janet/issues/1302#issuecomment-1748670882).

---

Below are a couple of attempts at adjustment, but perhaps there are better ways :)

A relatively minimal patch that seems to yield consistent results is:

<details>
<pre>
diff --git a/src/core/parse.c b/src/core/parse.c
index 40ccfbf2..a87d7c52 100644
--- a/src/core/parse.c
+++ b/src/core/parse.c
@@ -376,6 +376,12 @@ static int stringend(JanetParser *p, JanetParseState *state) {
                 }
             }
         }
+        /* Adjust things a bit if there is a leading \r\n eol sequence. */
+        if (buflen > 1 && (bufstart[0] == '\r') &&
+                (bufstart[1] == '\n')) {
+            buflen--;
+            bufstart++;
+        }
         /* Now reindent if able to, otherwise just drop leading newline. */
         if (!reindent) {
             if (buflen > 0 && bufstart[0] == '\n') {
@@ -400,9 +406,12 @@ static int stringend(JanetParser *p, JanetParseState *state) {
             }
             buflen = (int32_t)(w - bufstart);
         }
-        /* Check for trailing newline character so we can remove it */
+        /* Check for end of line sequence so we can remove it */
         if (buflen > 0 && bufstart[buflen - 1] == '\n') {
             buflen--;
+            if (buflen > 0 && bufstart[buflen - 1] == '\r') {
+                buflen--;
+            }
         }
     }
     if (state->flags & PFLAG_BUFFER) {
</pre>
</details>

A somewhat clearer (but I have doubts about equivalence) patch is:

<details>
<pre>
diff --git a/src/core/parse.c b/src/core/parse.c
index 40ccfbf2..a24d0875 100644
--- a/src/core/parse.c
+++ b/src/core/parse.c
@@ -376,32 +376,34 @@ static int stringend(JanetParser *p, JanetParseState *state) {
                 }
             }
         }
-        /* Now reindent if able to, otherwise just drop leading newline. */
-        if (!reindent) {
-            if (buflen > 0 && bufstart[0] == '\n') {
-                buflen--;
-                bufstart++;
-            }
-        } else {
+        /* Reindent if needed. */
+        if (reindent) {
             uint8_t *w = bufstart;
             r = bufstart;
+            uint8_t at_newline = 0;
             while (r < end) {
-                if (*r == '\n') {
-                    if (r == bufstart) {
-                        /* Skip leading newline */
-                        r++;
-                    } else {
-                        *w++ = *r++;
-                    }
+                at_newline = (*r == '\n') ? 1 : 0;
+                *w++ = *r++;
+                if (at_newline) {
                     for (int32_t j = 0; (r < end) && (*r != '\n') && (j < indent_col); j++, r++);
-                } else {
-                    *w++ = *r++;
                 }
             }
             buflen = (int32_t)(w - bufstart);
         }
-        /* Check for trailing newline character so we can remove it */
-        if (buflen > 0 && bufstart[buflen - 1] == '\n') {
+        /* Skip leading eol sequence if needed. */
+        if (buflen > 0 && bufstart[0] == '\n') {
+            buflen--;
+            bufstart++;
+        } else if (buflen > 1 && (bufstart[0] == '\r') &&
+                   (bufstart[1] == '\n')) {
+            buflen -= 2;
+            bufstart += 2;
+        }
+        /* Remove trailing eol sequence if needed. */
+        if (buflen > 1 && (bufstart[buflen - 2] == '\r') &&
+                (bufstart[buflen - 1] == '\n')) {
+            buflen -= 2;
+        } else if (buflen > 0 && bufstart[buflen - 1] == '\n') {
             buflen--;
         }
     }
</pre>
</details>

---

Thanks to @pyrmont for aid in investigation and working on patches.

---

[1] It's the leading and trailing parts differing that's a problem.  That end-of-line sequences that are "interior" differ is to be expected.

[2] In this issue, notationally, `CR` and "carriage return" mean the same, and likewise for `LF` and "line feed".

**Comment by sogaiu** [comment]
It may be that neither of the patches work.

Here's a case I think may not be handled:

```janet
(def long-string-2
  ``
  first line

  second line
  ``)

(pp long-string-2)
```

Expected:

```
"first line\r\n\r\nsecond line"
```

Actual:

```
"  first line\r\n\r\n  second line\r\n  "
```

**Comment by sogaiu** [comment]
Updated diffs below.  These seem to work better.

Top version:

```diff
diff --git a/src/core/parse.c b/src/core/parse.c
index 40ccfbf2..66046e3f 100644
--- a/src/core/parse.c
+++ b/src/core/parse.c
@@ -368,7 +368,8 @@ static int stringend(JanetParser *p, JanetParseState *state) {
         int reindent = 1;
         while (reindent && (r < end)) {
             if (*r++ == '\n') {
-                for (int32_t j = 0; (r < end) && (*r != '\n') && (j < indent_col); j++, r++) {
+                for (int32_t j = 0; (r < end) && (*r != '\n') &&
+                        (*r != '\r') && (j < indent_col); j++, r++) {
                     if (*r != ' ') {
                         reindent = 0;
                         break;
@@ -376,6 +377,12 @@ static int stringend(JanetParser *p, JanetParseState *state) {
                 }
             }
         }
+        /* Adjust things a bit if there is a leading \r\n eol sequence. */
+        if (buflen > 1 && (bufstart[0] == '\r') &&
+                (bufstart[1] == '\n')) {
+            buflen--;
+            bufstart++;
+        }
         /* Now reindent if able to, otherwise just drop leading newline. */
         if (!reindent) {
             if (buflen > 0 && bufstart[0] == '\n') {
@@ -393,16 +400,20 @@ static int stringend(JanetParser *p, JanetParseState *state) {
                     } else {
                         *w++ = *r++;
                     }
-                    for (int32_t j = 0; (r < end) && (*r != '\n') && (j < indent_col); j++, r++);
+                    for (int32_t j = 0; (r < end) && (*r != '\n') &&
+                            (*r != '\r') && (j < indent_col); j++, r++);
                 } else {
                     *w++ = *r++;
                 }
             }
             buflen = (int32_t)(w - bufstart);
         }
-        /* Check for trailing newline character so we can remove it */
+        /* Check for end of line sequence so we can remove it */
         if (buflen > 0 && bufstart[buflen - 1] == '\n') {
             buflen--;
+            if (buflen > 0 && bufstart[buflen - 1] == '\r') {
+                buflen--;
+            }
         }
     }
     if (state->flags & PFLAG_BUFFER) {
```

Bottom version:

```diff
diff --git a/src/core/parse.c b/src/core/parse.c
index 40ccfbf2..ee678814 100644
--- a/src/core/parse.c
+++ b/src/core/parse.c
@@ -368,7 +368,8 @@ static int stringend(JanetParser *p, JanetParseState *state) {
         int reindent = 1;
         while (reindent && (r < end)) {
             if (*r++ == '\n') {
-                for (int32_t j = 0; (r < end) && (*r != '\n') && (j < indent_col); j++, r++) {
+                for (int32_t j = 0; (r < end) && (*r != '\n') &&
+                        (*r != '\r') && (j < indent_col); j++, r++) {
                     if (*r != ' ') {
                         reindent = 0;
                         break;
@@ -376,32 +377,35 @@ static int stringend(JanetParser *p, JanetParseState *state) {
                 }
             }
         }
-        /* Now reindent if able to, otherwise just drop leading newline. */
-        if (!reindent) {
-            if (buflen > 0 && bufstart[0] == '\n') {
-                buflen--;
-                bufstart++;
-            }
-        } else {
+        /* Reindent if needed. */
+        if (reindent) {
             uint8_t *w = bufstart;
             r = bufstart;
+            uint8_t at_newline = 0;
             while (r < end) {
-                if (*r == '\n') {
-                    if (r == bufstart) {
-                        /* Skip leading newline */
-                        r++;
-                    } else {
-                        *w++ = *r++;
-                    }
-                    for (int32_t j = 0; (r < end) && (*r != '\n') && (j < indent_col); j++, r++);
-                } else {
-                    *w++ = *r++;
+                at_newline = (*r == '\n') ? 1 : 0;
+                *w++ = *r++;
+                if (at_newline) {
+                    for (int32_t j = 0; (r < end) && (*r != '\n') &&
+                            (*r != '\r') && (j < indent_col); j++, r++);
                 }
             }
             buflen = (int32_t)(w - bufstart);
         }
-        /* Check for trailing newline character so we can remove it */
-        if (buflen > 0 && bufstart[buflen - 1] == '\n') {
+        /* Skip leading eol sequence if needed. */
+        if (buflen > 0 && bufstart[0] == '\n') {
+            buflen--;
+            bufstart++;
+        } else if (buflen > 1 && (bufstart[0] == '\r') &&
+                   (bufstart[1] == '\n')) {
+            buflen -= 2;
+            bufstart += 2;
+        }
+        /* Remove trailing eol sequence if needed. */
+        if (buflen > 1 && (bufstart[buflen - 2] == '\r') &&
+                (bufstart[buflen - 1] == '\n')) {
+            buflen -= 2;
+        } else if (buflen > 0 && bufstart[buflen - 1] == '\n') {
             buflen--;
         }
     }
```

---

Thanks to @pyrmont for the fix!

**Comment by sogaiu** [comment]
So thinking over it some more, it seems problematic for literal long-strings to yield different values depending on the end-of-line sequence used within a source file.

As additional data, the REPL behavior is consistent between Linux and Windows:

```
repl:1:> (pp ``hello
repl:2:(``> there``)
"hello\nthere"
nil
```

Perhaps carriage returns that appear right before newlines in long-strings should be dropped?

That doesn't seem completely problem-free, but may be it's a better behavior than the current situation.

**Comment by sogaiu** [comment]
So perhaps something like this:

```diff
diff --git a/src/core/parse.c b/src/core/parse.c
index 40ccfbf2..59908f24 100644
--- a/src/core/parse.c
+++ b/src/core/parse.c
@@ -368,7 +368,8 @@ static int stringend(JanetParser *p, JanetParseState *state) {
         int reindent = 1;
         while (reindent && (r < end)) {
             if (*r++ == '\n') {
-                for (int32_t j = 0; (r < end) && (*r != '\n') && (j < indent_col); j++, r++) {
+                for (int32_t j = 0; (r < end) && (*r != '\n') &&
+                        (*r != '\r') && (j < indent_col); j++, r++) {
                     if (*r != ' ') {
                         reindent = 0;
                         break;
@@ -376,6 +377,12 @@ static int stringend(JanetParser *p, JanetParseState *state) {
                 }
             }
         }
+        /* Adjust things a bit if there is a leading \r\n eol sequence. */
+        if (buflen > 1 && (bufstart[0] == '\r') &&
+                (bufstart[1] == '\n')) {
+            buflen--;
+            bufstart++;
+        }
         /* Now reindent if able to, otherwise just drop leading newline. */
         if (!reindent) {
             if (buflen > 0 && bufstart[0] == '\n') {
@@ -393,16 +400,24 @@ static int stringend(JanetParser *p, JanetParseState *state) {
                     } else {
                         *w++ = *r++;
                     }
-                    for (int32_t j = 0; (r < end) && (*r != '\n') && (j < indent_col); j++, r++);
+                    for (int32_t j = 0; (r < end) && (*r != '\n') &&
+                            (*r != '\r') && (j < indent_col); j++, r++);
+                } else if ((*r == '\r') &&
+                           (r + 1 < end) && (*(r + 1) == '\n')) {
+                    /* Skip carriage return that is right before a newline */
+                    r++;
                 } else {
                     *w++ = *r++;
                 }
             }
             buflen = (int32_t)(w - bufstart);
         }
-        /* Check for trailing newline character so we can remove it */
+        /* Check for end of line sequence so we can remove it */
         if (buflen > 0 && bufstart[buflen - 1] == '\n') {
             buflen--;
+            if (buflen > 0 && bufstart[buflen - 1] == '\r') {
+                buflen--;
+            }
         }
     }
     if (state->flags & PFLAG_BUFFER) {
```

**Comment by sogaiu** [comment]
> Perhaps each carriage return that appears right before a newline character in a long-string literal should be dropped?

I think this is how Python's multiline strings work too.  For this code:

```python
s = """a
^Mj
z"""

print(len(s))
```

where `^M` represents a carriage return that is not immediately before a newline, the output is `6` whether the line endings are `\n` or `\r\n`.

I think the patch in the previous commit implements this behavior.

**Comment by sogaiu** [comment]
I found summaries regarding some programming languages  starting from [here](https://github.com/rust-lang/rust/issues/7946#issuecomment-21375355).

Languages mentioned include:

* C#
* Haskell
* Java
* Javascript
* Python3
* C++
* Go
* Ruby
* Rust

One unexpected issue seems to be [potential security implications of `\r`-handling](https://github.com/rust-lang/rust/issues/7946#issuecomment-21362938).

**Comment by sogaiu** [comment]
Trying to spell out some rationale for long-strings (and long-buffers).

So far I have:

* Reduce escaping
* Aid construction of multi-line text that typically a human might read (e.g. docstrings and source text)

ATM, the website docs have this text:

> Long-strings do not contain escape sequences; all bytes will be parsed literally until the ending delimiter is found. This is useful for defining multi-line strings containing literal newline characters, unprintable characters, or strings that would otherwise require many escape sequences. 

My suspicion at the moment is that the use-case of constructing a multi-line source string where the end-of-line delimiters are not converted to `\n` is not really addressed widely in other programming languages.

IIUC, in most C implementations(?), end-of-line sequences get converted to `\n` pretty early.  The following is from [5.2.1 from C99](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf#page=29) (at least a draft I found):

> In source files, there shall be some way of indicating the end of each line of text; this International Standard treats such an end-of-line indicator as if it were a single new-line character. 

I don't know if this set a precedent but wouldn't be surprised if it did.

**Comment by sogaiu** [comment]
ATM, it seems to me that parsing might be improved so that source produced in a typical Windows environment might work more consistently with that produced in a more Unix-y environment.

There are two obvious ways to me (may be I missed some) one might do this:

1. Drop `CR` when constructing a long-string
2. Replace `CR` `LF` sequences with `LF`

I think the former is simpler, but it seems less expressive as one cannot then include literal `CR` in one's long-string (or long-buffer) literals.

Below are a couple of bits about what Rust does for comparative purposes...

AFAICT, [Rust does 1. for `//` comments](https://github.com/rust-lang/rust/issues/7946#issuecomment-21375355).  Perhaps for that use case, it's sensible.

For raw string literals though, apparently [Rust only replaces `CR` if it isn't part of a `CR` `LF` sequence](https://github.com/rust-lang/rust/issues/82721).  Again, may be that makes sense for the use cases one might want to cover.

I bring these bits up to try to aid in reasoning about what to do for Janet.  My previous comment in this issue tries to spell out some rationale (which includes some use cases) in another attempt to help (^^;

**Comment by bakpakin** [comment]
This is all good discussion, and I do think we should strip out in some cases, but a goal of long strings is to be able to encode any binary sequence, so just dropping all CR doesn't quite work here.

There is some special case at the beginning and end of the strings to allow for the form:

```janet

``
Text here
``
```

to not have leading and trailing lines, and allow for indentation. So I'm not sure about how I feel about doing anything to the internal contents if there is no indentation

**Comment by sogaiu** [comment]
Thanks for the comments.

> So I'm not sure about how I feel about doing anything to the internal contents if there is no indentation

At the moment it seems important to me that what gets created (string or buffer) based on a long-string / long-buffer literal should be consistent across platforms.

I'm not sure if that can be made consistent in all cases without touching the internal contents.

As a specific example where no indentation is used, if I type the following long-string literal:

```
``
Alice
Bob
``
```

in the REPL, this yields the same result on Windows and Linux.

But if I type the same thing in a source file in a typical Windows editor vs a typical UNIX-y editor, the resulting strings produced by the parser differ.

**Comment by sogaiu** [comment]
Do you see problems with a transformation that replaces `CR` `LF` with `LF`?  (I think this might be doable while maintaining the other behavior for handling of indentation and the trimming of single leading / trailing end-of-line sequences.)

One thing I think isn't great about this idea is that it makes it awkward (and possibly brittle) to construct multiline strings that include `CR` `LF` [1].

It seems doable to me if one constructs the long-string by using `CR` `CR` `LF` as the bytes that come at the end of each line (so-to-speak).  The last 2 bytes (`CR` `LF`) per line would be replace by a single `LF` byte resulting in `CR` + `LF` (so 2 bytes instead of 3).

I'm not sure I'd want to write such long-strings if they have many lines because it doesn't seem ergonomic and I wonder if some editors (and perhaps version control systems) might mess with my source, corrupting my data...

---

[1] I haven't come across a programming language that supports ergonomic construction of this type of data -- so may be it doesn't come up so much in practice?  May be that's wishful thinking...

**Comment by bakpakin** [comment]
Closing this as a WNF. The behavior gets too complicated and annoying, mostly to deal with editors and system that try to change how your source code is formatted.
