### ISSUE TITLE
Feature Request: Support for exec(3) family of functions

### ISSUE THREAD

**Issue by nrser** [janet-lang/janet#1304]
Request to add support for [exec(3)][] family of functions.

[exec(3)]: https://www.man7.org/linux/man-pages/man3/exec.3.html

Filed in response to the discussion at

https://www.man7.org/linux/man-pages/man3/exec.3.html

## Thoughts & Notes

As a user it would be great if the implementation mirrored [os/execute][] for simplicity and ease of recall, choosing which of the `exec` family (`execl`, `execlp`, ..., `execvpe`) to invoke "under the hood" based on the provided options.

I'm always found it tiring and error-prone how Python for example exposes each of the `exec` family [directly](https://docs.python.org/3/library/os.html#os.execl), opposed to say Ruby which exposes a [single](https://docs.ruby-lang.org/en/3.0/Kernel.html#method-i-exec) method that makes the common, Bash-like use case easy. 

[os/execute]: https://janet-lang.org/api/os.html#os/execute

**Comment by CosmicToast** [comment]
1. A man page isn't a discussion.
2. You ask to mirror an API that already exists while adding "under the hood" controls...
3. Then complain about python having too much under the hood...
4. And note that you prefer Ruby's approach, which is fairly close to the existing API under 2.

This ask is nonsensical, and also wouldn't really fly in the stdlib, as the exec family is a set of POSIX functions, but Janet targets ISO C99, which has no such utilities.
You can't expose something that doesn't exist, and you already have access to `os/execute`, which is the kind of API you say you want.

Is this an AI submission?
The biggest indicator really is the "filed in response" bit, to me.

**Comment by bakpakin** [comment]
I think the ask here is more about exec as a function than can be used to replace the current process, like `exec` in the shell, rather then spawn a subprocess. This works on most systems besides windows, and is not unreasonable.

There was discussion on matrix, the link in the original bug is bad.

**Comment by sogaiu** [comment]
For reference, [here](https://github.com/janet-lang/janet/discussions/1303) is some previous related discussion.

**Comment by bakpakin** [comment]
I had already been working on `os/posix-fork` this weekend, and just finished an implementation `os/posix-exec`.

As noted though, these are not totally portable and will never exist on windows. There may also be other systems that cannot support them. Current implementation just checks `#ifndef JANET_WINDOWS`, but perhaps we should put them behind a configuration flag
