### ISSUE TITLE
Using janet_dostring with os/execute evaluates to nil

### ISSUE THREAD

**Issue by iacore** [janet-lang/janet#1307]
Reproduction: https://gist.github.com/iacore/6acbb2d98403e468c35dd835518b9be5

Related to https://github.com/janet-lang/janet/issues/926

This may be a spork bug or a janet bug.

**Comment by sogaiu** [comment]
May be it's not spork as compiling and executing the following:

```c
// build:
//
// gcc -O0 -g main.c -I$HOME/.local/include -L$HOME/.local/lib -ljanet

// run:
//
// export LD_LIBRARY_PATH=$HOME/.local/lib
// ./a.out

#include "janet.h"
#include <stdio.h>

int main() {
  JanetTable *env;

  janet_init();

  env = janet_core_env(NULL);

  int status;

  Janet out;
  
  status =
    janet_dostring(env,
                   "(os/execute [`ls`] :px)",
                   "source", &out);

  printf("os/execute status: %d\n", status);

  janet_gcroot(out);

  printf("janet_type: %d\n", janet_type(out));

  printf("\n");
  
  janet_deinit();
}
```

ends with the output:

```
os/execute status: 0
janet_type: 1
```

The expected output is:

```
os/execute status: 0
janet_type: 0
```

That is, I expect a [number `JANET_NUMBER` (0) but I'm seeing `nil` `JANET_NIL` (1)](https://github.com/janet-lang/janet/blob/f18ad36b1bd22a3b2a0888472b46bed9c252e65e/src/include/janet.h#L477-L478).

```
Janet 1.31.0-cb25a2ec linux/x64/gcc - '(doc)' for help
repl:1:> (os/execute ["ls"] :px)
...
0

```

**Comment by iacore** [comment]
https://github.com/janet-lang/janet/commit/e3f4142d2ae825ff4706ebe4970c389c8f087b77 seems to have fixed it.
