### ISSUE TITLE
Janet REPL forward-word keybinding (Alt-f) incorrectly moves to the beginning of a word

### ISSUE THREAD

**Issue by Andriamanitra** [janet-lang/janet#1309]
From `man readline`:

> forward-word (M-f)
> &nbsp;&nbsp;&nbsp;&nbsp;Move forward to the end of the next word.  Words are composed of alphanumeric characters (letters and digits).

In the Janet shell M-f instead moves to the *beginning* of the next word. All other terminal apps I know of that implement the `M-f` keybinding follow the readline behavior. It's easy to work around this issue by using readline wrapper (`rlwrap --always-readline janet`) but it would still be nice to be consistent with other terminal software.

**Comment by sogaiu** [comment]
I agree it would be nice.
