### ISSUE TITLE
PEG rule names can't be strings or symbols

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#131]
```
(peg/match '{:foo (capture "foo") :main :foo} "foo")
@["foo"]
(peg/match '{"foo" (capture "foo") :main "foo"} "foo")
@[]
```

Seems like an arbitrary limitation, moreover - the behavior is surprising if it isn't meant to be accepted.

**Comment by bakpakin** [comment]
This is because the string “foo” already a valid peg itself. It would be weirder if it worked.

**Comment by andrewchambers** [comment]
I thought it was key = name, value = peg.  no big deal.
