### ISSUE TITLE
`default-peg-grammar` lacks `*` and `+` versions of `:A`, `:D`, `:H`, `:S`, and `:W`

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet#1312]
Unlike `:a`, `:d`, `:h`, `:s`, and `:w`, the "capitalized" versions (negations - e.g. `:A`) in `default-peg-grammar` lack `*` and `+` versions:

https://github.com/janet-lang/janet/blob/cc5beda0d26c0b91fb28540291e950392cf59fc4/src/boot/boot.janet#L2333-L2355

I suspect that on some occasions some of us have missed `:S+` or similar.

May be it makes sense to "complete" the set?

**Comment by bakpakin** [comment]
Looks fine to me

**Comment by sogaiu** [comment]
Thanks for the merge!
