### ISSUE TITLE
After a stream is created ev/sleep takes 100% CPU.

### ISSUE THREAD

**Issue by bitcompost** [janet-lang/janet#1321]
Steps to reproduce:
```
Janet 1.32.1-meson linux/aarch64/gcc - '(doc)' for help
repl:1:> (net/connect "1.1.1.1" "80")
<core/stream 0xAAAACB3E0010>
repl:2:> (ev/sleep 42)

```

**Comment by bakpakin** [comment]
Cannot reproduce on linux/x64. Is this for some reason only arm? Also would be interested in your linux kernel version.

**Comment by bitcompost** [comment]
I can reproduce it on x64. Kernel 6.2.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bitcompost** [comment]
Did some more testing. It only hapens with the meson build.

**Comment by bakpakin** [comment]
Ok, looks like the meson build by default is using the `poll` event loop instead of the `epoll` event loop, so the bug is with the `poll` event loop.

With meson, you can fix this for now using

```
meson setup build -Depoll=true
```

when configuring the project (and get more efficient as well).
