### ISSUE TITLE
'put' with structs

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#133]
It could just return a new struct value (like put already does), but not update in place.

Note there would still be no efficient way to batch update many fields at once, which also seems useful to me.

**Comment by bakpakin** [comment]
For now, if you want to update structs, you should probably use a table. I'm not sure how I feel about making put, which is currently always a mutating operation, sometimes not mutating in the case of a struct. Also, it would be inefficient.

**Comment by andrewchambers** [comment]
That's ok, If you look at clojure https://clojuredocs.org/clojure.core/update-in is the sort of thing sometimes want. I just tend to prefer immutable stuff when I can.

**Comment by eko234** [comment]
Hello, I think maybe put is not a good candidate but I think we could use something like assoc/assoc-in from clojure
