### ISSUE TITLE
 environment path hell on windows installer

### ISSUE THREAD

**Issue by chenjianxin** [janet-lang/janet#134]
janet 1.0 windows installer  delete my original path environment variable

**Comment by bakpakin** [comment]
I think that the problem might have to do with [this](https://stackoverflow.com/questions/21897103/nsis-envvarupdate-overwrites-system-path-when-path-is-too-long-is-there-a-wor) issue. I will soon try to upload a 1.0.0 installer created with a special build of NSIS that allows longer strings.

**Comment by chenjianxin** [comment]
> Was your original PATH over 1024 characters, or close to that?

over 1024 characters

**Comment by chenjianxin** [comment]
it use "C:\janet\bin" overlay original path

**Comment by bakpakin** [comment]
I have replaced the original 1.0.0 installer on the releases page with the new installer that allows a longer maximum length for PATH (up to 8192, which is longer than the longest PATH allowed by windows I believe). Sorry about destroying your PATH.

**Comment by bakpakin** [comment]
This should be fixed in the 1.1.0 releases and onward so I will close for now.
