### ISSUE TITLE
let* please, possibly even letrec, letrec*

### ISSUE THREAD

**Issue by reuleaux** [janet-lang/janet#1352]
This is on my wishlist: let*

I am currently using nested let instead, which seems a little awkward:
```clojure
(let [
         foo ‘bar
     ]
 (let [
           baz (do-something-with foo)
      ]
    body))
```

with let* this would be as simple as

```clojure
(let [
            foo ‘bar
            bar (do-something-with foo)
     ]
   body)
```
Even one step further: recursive defs - with letrec/letrec* - have a look at the (Gauche- Guile-) Scheme src/docs for example.
Thanks!

**Comment by sogaiu** [comment]
Doesn't `let` already do what you want?

```
$ janet
Janet 1.33.0-f91e5994 linux/x64/gcc - '(doc)' for help
repl:1:> (let [x 1 y x] (+ x y))
2
```

**Comment by sogaiu** [comment]
Regarding `letrec` and friends, it's not the same, but [see this discussion](https://github.com/janet-lang/janet/discussions/1254).

**Comment by iacore** [comment]
`(def [x y] [1 2])`

**Comment by reuleaux** [comment]
Hm - my bad then, I guess, and sorry for the noise - I was pretty sure,
that I ran in a situation, where this did not work, but now, that
you are pushing me, and I am trying again, it seems to work for me.

I have these nested let in a couple of places now, and will
get rid of them one by one (and I will shout out, in case of some
issue remaining for me, i.e. if I keep quiet, than everything's fine).

Thanks for your feedback.
 -A
