### ISSUE TITLE
cannot marshal fiber with c stackframe

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet#1366]
I tried to pass error and fiber from `try` block to another thread through a threaded channel, but I got

```
error: cannot marshal fiber with c stackframe (<cfunction os/spawn>)
  in ev/give [src/core/ev.c] on line 971
  in <anonymous> [/path/to/j3blocks.janet] (tailcall) on line 28, column 45
```

Thus, I had to put a task that processes fiber errors on the thread. This is not good because I cannot serialize execution between three tasks on the same thread. I could only serialize execution between two tasks on the same thread.

**Comment by iacore** [comment]
can you send fiber across process?

**Comment by bakpakin** [comment]
There was another issue with this in an earlier issue - see https://github.com/janet-lang/janet/issues/1326
