### ISSUE TITLE
def special form bug

### ISSUE THREAD

**Issue by michal037** [janet-lang/janet#137]
I read and make examples from the documentation.
https://janet-lang.org/docs/specials.html

This piece of code does not work properly in relation to the description:
```
(def [a b c] (range 10))
(print a " " b " " c) # prints 0 1 2
```

### Example
```
Janet 1.0.0-local  Copyright (C) 2017-2019 Calvin Rose
janet:0:> (def [a b c] (range 10))
@[0
  1
  2
  3
  4
  5
  6
  7
  8
  9]
janet:25:> (print a " " b " " c) # prints 0 1 2
2 2 2
nil
janet:62:>

```

**Comment by bakpakin** [comment]
Ah, this is very much my bad. I added this regression recently and I remember doing it, I'm just surprised there were no test cases for it. I should have fixed soon, and will probably release 1.0.1 with the fix.
