### ISSUE TITLE
Zombie processes freeze spawned process streams and `os/proc-wait` for ever.

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet#1382]
I execute `(ev/read stream :all)` many times simultaneously in at least 6 threads.

If I don't give `ev/read` a definite timeout, some threads freeze for EVER.

If I give it a timeout, it gives me a result after timeout seconds...

Since I'm using threads anyway, I can use `janet-sh` by andrewchambers which works flawlessly because it is synchronous. However, I was trying to avoid relying on third party libraries. And, andrewchambers doesn't seem to have time to work on his janet libraries.

This looks like one of race conditions produced by threads...

**Comment by bakpakin** [comment]
Are you call `(ev/read stream :all)` on the same stream multiple times? Again, without code it's really hard to debug these kinds of issues or get important details.

**Comment by amano-kenji** [comment]
To reproduce the issue, you should have pipewire, wireplumber, and sway or i3.

**Comment by amano-kenji** [comment]
I think `ev/take` or `ev/give` freezes for ever, too.

Can you set up wireplumber and pipewire? Can you also set up i3 or sway?

**Comment by amano-kenji** [comment]
Okay, this is actually related to the behavior of pw-dump during the shutdown of pipewire and wireplumber.

My suspicion is that pw-dump freezes `ev/read` on the standard output stream of `os/spawn` if pipewire and wireplumber are starting up or shutting down.

There is no other place that seems to be freezing. `ev/give` and `ev/take` are fine.

**Comment by amano-kenji** [comment]
This one seems to also freeze when pipewire and wireplumber are shutting down.
```janet
(defn running?
  "Returns true if pipewire is running"
  []
  (try
    (let [proc (os/spawn ["pw-cli" "list-remotes"] :p {:out :pipe :err :pipe})]
      (= (os/proc-wait proc) 0))
    ([_] false)))
```

**Comment by amano-kenji** [comment]
Replacing the above `running?` function with the below function forced it to return false if `pw-cli list-remotes` takes longer than a second.
```janet
(defn running?
  "Returns true if pipewire is running"
  []
  (try
    (let [proc (os/spawn ["pw-cli" "list-remotes"] :p {:out :pipe :err :pipe})]
      (ev/with-deadline 1
        (= (os/proc-wait proc) 0)))
    ([_] false)))
```

**Comment by amano-kenji** [comment]
`pw-dump` can also be forced to return within 1 second with this.
```janet
(defn dump
  "Dumps information on a node. node is either node.name or node.id"
  [node]
  (try
    (let [proc (os/spawn ["pw-dump" node] :p {:out :pipe :err :pipe})]
      (get (json/decode (ev/read (proc :out) :all nil 1))
           0))
    ([_] nil)))
```
Notice
```
(ev/read (proc :out) :all nil 1)
```

**Comment by amano-kenji** [comment]
Is this the right way to deal with zombie processes? Or, should janet improve its handling of zombie processes?

**Comment by amano-kenji** [comment]
I'm closing this to create another one.
