### ISSUE TITLE
string/slice - common functionality is different from implemented

### ISSUE THREAD

**Issue by michal037** [janet-lang/janet#140]
[**Substrings**](https://janet-lang.org/docs/strings.html) - now
```
(string/slice "abcdefg" 2 -2) # -> "cdef"
(string/slice "abcdefg" -4 -2) # -> "ef"
```
This code is bugged. For a negative `beginIndex` value, the character is excluded, it should be included. For a negative `endIndex` value, the character is included, it should be excluded.

a | b | c | d | e | f | g
--- | --- | --- | --- | --- | --- | ---
0 | 1 | 2 | 3 | 4 | 5 | 6
-7 | -6 | -5 | -4 | -3 | -2 | -1

See how the slice function works on the example of JavaScript:

```
var str = "abcdefg";
console.log(str.slice(2, -2));
> "cde"
console.log(str.slice(-4, -2));
> "de"
```

**beginIndex** - The zero-based index at which to begin extraction.
**endIndex** - Optional. The zero-based index **before which to end extraction**. The character at this index will not be included.

---
MDN web docs: [String.prototype.slice()
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice)

### Syntax
`str.slice(beginIndex[, endIndex])`

### Parameters
**beginIndex**
The zero-based index at which to begin extraction. If negative, it is treated as `strLength + (beginIndex)` where `strLength` is the length of the string (for example, if `beginIndex` is `-3` it is treated as `strLength - 3`). If `beginIndex` is greater than or equal to the length of the string, `slice()` returns an empty string.

**endIndex**
Optional. The zero-based index before which to end extraction. The character at this index will not be included. If `endIndex` is omitted, `slice()` extracts to the end of the string. If negative, it is treated as `strLength + endIndex` where `strLength` is the length of the string (for example, if `endIndex` is `-3` it is treated as `strLength - 3`).

### Return value
A new string containing the extracted section of the string.

**Comment by bakpakin** [comment]
Although different than python or JS, the code behaves as intended. This lets -1 be used to include until the end of the string. All of the slice functions behave this way.

The proposed functionality may be more consistent with other runtimes, but this was not an accident.

**Comment by michal037** [comment]
@bakpakin Thank you for the answer, I thought it was a bug. Because, usually the mechanics of the function of this name look different.

**Comment by curist** [comment]
Sorry for reanimate this, but isn't the use case to include until the end of the string already covered by `(string/slice s ind)`? The only benefit of current behavior I can think of is we can always include an end index in the call, but in exchange of cognitive load for people familiar with other runtimes.
