### ISSUE TITLE
`if-let` breaks tail call optimization.

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet#1401]
`if-let` macro and all other macros that depend on `if-let` macro break tail call optimization.

I don't know what other macros break tail-call optimization.

**Comment by amano-kenji** [comment]
Tail call optimization doesn't apply to this
```janet
(fiber/new (fn recurse []
             (when-let [line (ev/take lines)]
               (yield line)
               (recurse)))
           :yi)
```

**Comment by sogaiu** [comment]
@amano-kenji May be you can see if https://github.com/janet-lang/janet/commit/9e0daaee095cea5837574f2181072dd32346787a fixed things for you?

**Comment by amano-kenji** [comment]
It fixes the tail call optimization, but the fiber call stack for false branch points to the top of `if-let` instead of the line where `debug/stacktrace` is called.

For the true branch, the call stack points to the line where `debug/stacktrace` is called.

Other than that, it's fine. It's only a minor issue.

**Comment by amano-kenji** [comment]
This is my test code.
```janet
(defn recurse
  [branch]
  (if-let [ha branch]
    (do
      (ev/sleep 1)
      (debug/stacktrace (fiber/current) "print stack for true branch" "")
      (recurse branch))
    (do
      (ev/sleep 1)
      (debug/stacktrace (fiber/current) "print stack for false branch" "")
      (recurse branch))))

(recurse false)
```

**Comment by sogaiu** [comment]
Ok, to spell out the details...with the following in `recurse.janet`:

```janet
(defn recurse
  [branch]
  (if-let [ha branch]
    (do
      (ev/sleep 1)
      (debug/stacktrace (fiber/current) "print stack for true branch" "")
      (recurse branch))
    (do
      (ev/sleep 1)
      (debug/stacktrace (fiber/current) "print stack for false branch" "")
      (recurse branch))))

(defn main
  [& args]
  (def arg
    (case (get args 1 "true")
      "true" true
      "false" false
      nil))
  (recurse arg))
```

For the invocation `janet recurse.janet true` I get:

```
alive: print stack for true branch
  in debug/stacktrace [src/core/debug.c] on line 388
  in recurse [recurse.janet] (tailcall) on line 6, column 7
alive: print stack for true branch
  in debug/stacktrace [src/core/debug.c] on line 388
  in recurse [recurse.janet] (tailcall) on line 6, column 7
...
```

where line 6, column 7 refers to the code:

```janet
(debug/stacktrace (fiber/current) "print stack for true branch" "")
```

which is fine, but, for the invocation `janet recurse.janet false` I get:

```
alive: print stack for false branch
  in debug/stacktrace [src/core/debug.c] on line 388
  in recurse [recurse.janet] (tailcall) on line 3, column 3
alive: print stack for false branch
  in debug/stacktrace [src/core/debug.c] on line 388
  in recurse [recurse.janet] (tailcall) on line 3, column 3
...
```

where line 3, column 3 refers to the code:

```janet
(if-let [ha branch]
```

which I guess would be nicer if this was actually pointing at:

```janet
(debug/stacktrace (fiber/current) "print stack for false branch" "")
```

(line 10, column 7).

**Comment by sogaiu** [comment]
I guess the location information reporting situation mentioned in [this comment](https://github.com/janet-lang/janet/issues/1401#issuecomment-1946094027) is a different issue.

**Comment by amano-kenji** [comment]
Closing this to create another issue.
