### ISSUE TITLE
false branch of `if-let` doesn't report the correct call stack information.

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet#1404]
```janet
(defn recurse
  [branch]
  (if-let [ha branch]
    (do
      (ev/sleep 1)
      (debug/stacktrace (fiber/current) "print stack for true branch" "")
      (recurse branch))
    (do
      (ev/sleep 1)
      (debug/stacktrace (fiber/current) "print stack for false branch" "")
      (recurse branch))))

(defn main
  [& args]
  (def arg
    (case (get args 1 "true")
      "true" true
      "false" false
      nil))
  (recurse arg))
```
With this, `debug/stacktrace` in the false branch doesn't report its own line in the call stack, but the line where `if-let` resides.

`debug/stacktrace` in the true branch reports its own line in the call stack.

**Comment by sogaiu** [comment]
For future readers, see [this comment](https://github.com/janet-lang/janet/issues/1401#issuecomment-1946166954) for example invocations along with output and some explanation.

**Comment by bakpakin** [comment]
So the issue here is there is an explicit macro expansion here inside the if-let macro that doesn't preserve the source location information. We can fix this issue by making slight modifications to `macex1` which does the explicit macro expansion. This should also fix source mapping information for any macros that explicitly expand sub forms manually, instead of the usual case of letting the be.

**Comment by sogaiu** [comment]
I tried [7a2868c](https://github.com/janet-lang/janet/commit/7a2868c1477c5430002547573cdc1fed756f1051) with the sample code.

Both invocations produced the expected output here:

```
$ janet recurse.janet true
alive: print stack for true branch
  in debug/stacktrace [src/core/debug.c] on line 388
  in recurse [recurse.janet] (tailcall) on line 6, column 7
...
```

```
$ janet recurse.janet false
alive: print stack for false branch
  in debug/stacktrace [src/core/debug.c] on line 388
  in recurse [recurse.janet] (tailcall) on line 10, column 7
...
```

@amano-kenji Does it work for you?

**Comment by amano-kenji** [comment]
I tested the latest commit, and the issue seems fixed.
