### ISSUE TITLE
`ev/select` should not resume a dead task.

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet#1405]
```janet
(def ch (ev/chan))
(def ch1 (ev/chan))

(def task (ev/spawn
            (defer (do
                     (print "exiting task")
                     (:close ch1))
              (forever
                (print 3)
                (ev/sleep 1)))))

(ev/sleep 2)

(ev/spawn
  (match (ev/select ch ch1)
    [:close _]
    (do
      (ev/cancel task :cancel)
      (error "error after calling ev/cancel"))))

(ev/sleep 1)
(:close ch)

(forever
  (ev/sleep 1))
```
`ev/select` tries to resume the second task that errored out because `ch1` is closed later in another task.

`ev/select` should not revive a dead task. `ev/select` effectively turns a task into an undead task. I don't like zombies.

**Comment by amano-kenji** [comment]
It seems that `ev/select` even tries to resume a running task....

**Comment by amano-kenji** [comment]
It seems that once I call `ev/select` on channels, those channels become unuseable with `ev/take` or `ev/give`.

**Comment by bakpakin** [comment]
> It seems that once I call ev/select on channels, those channels become unuseable with ev/take or ev/give.

That seems like a separate issue, but also seems incorrect. For example:

```janet
(def c (ev/chan 10))
(def d (ev/chan 10))

(ev/spawn
  (forever
    (match (ev/select c d)
      [:close x]
      (print "channel " x " closed")
      [:take x y]
      (print "got " y " from " x))))

(forever
  (ev/sleep 1)
  (if (> (math/random) 0.5)
    (ev/give c :item)
    (ev/give d :item)))
```

this works for me

**Comment by amano-kenji** [comment]
I'll come back to this tomorrow.

**Comment by amano-kenji** [comment]
I just tested the latest commit. This issue is fixed, but I may discover more issues with `ev/select` soon.
