### ISSUE TITLE
`(= @"update" @"update")` is `false`.

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet#1408]
This was a nasty surprise.

**Comment by pepe** [comment]
You should read at least the basic documentation then :-).

**Comment by sogaiu** [comment]
For potential future readers, I believe one place that covers this is [the Deep Equality Operator section of the Comparison Operators page](https://janet-lang.org/docs/comparison.html#Deep-Equality-Operator):

> The primitive = operator does not compare the contents of mutable structures (arrays, tables, and buffers). Instead, it checks if the two values are the same object.

**Comment by amano-kenji** [comment]
:cat2:
