### ISSUE TITLE
Disasm/asm doesn't round-trip for function with unused argument

### ISSUE THREAD

**Issue by thegeez** [janet-lang/janet#1424]
This doesn't round trip:
```
(asm (disasm 
    (fn [] 
       (def foo (fn [one two] one)) 
       (foo 100 200))))
```

This trips up this line in the bytecode verifier about slotcounts: https://github.com/janet-lang/janet/blob/6032a6d65874514f88690aaf35e97f53a0ab6176/src/core/bytecode.c#L409

This example does work when foo returns `two` instead of `one`:
```
(asm (disasm 
    (fn [] 
       (def foo (fn [one two] two)) 
       (foo 100 200))))
```

**Comment by bakpakin** [comment]
Fixed in 9e6abbf4d40b3ebe121147b9e51a68f6746e3848
