### ISSUE TITLE
Can it run on iOS? Thank you.

### ISSUE THREAD

**Issue by brucelevis** [janet-lang/janet#1437]
Can it run on iOS? Thank you.

**Comment by pepe** [comment]
I am unsure about the current Apple policy, but it used to be that you could not use your runtime, garbage collector, etc. So I would say no.

**Comment by bakpakin** [comment]
I thought that the policy on interpreted runtimes was about prohibiting JIT interpreters, but looking it up, the policy is a lot more vague than I remember. For example, I'm pretty sure that people use Lua on iOS, just not LuaJIT with the hit turned on.

So technically yes, you could make put janet.c into Xcode and make it work, but whether or not apple would let it happen is not something I know.

https://developer.apple.com/app-store/review/guidelines/

**Comment by brucelevis** [comment]
> 我以为关于解释运行时的政策是关于禁止 JIT 解释器的，但查了一下，该政策比我记得的要模糊得多。例如，我很确定人们在 iOS 上使用 Lua，而不是在打开热门的情况下使用 LuaJIT。
> 
> 所以从技术上讲，是的，你可以把 janet.c 放到 Xcode 中并让它工作，但苹果是否会让它发生还不是我不知道的事情。
> 
> https://developer.apple.com/app-store/review/guidelines/

thank you very much！
