### ISSUE TITLE
`os/strftime` doesn't respect environment variables.

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet#1443]
`%a` of `os/strftime` can change according to locale.

Setting locale through environment variables like `LANG` and `LC_ALL` doesn't work.

Even though my system uses glibc, `os/strftime` doesn't respect environment variables.

**Comment by bakpakin** [comment]
I don't know if there is something Janet should do here besides expose `setlocale` - we don't do anything to set or unset locales from environment variables, so if your OS or libc is not doing it, then Janet isn't doing it either.

**Comment by bakpakin** [comment]
Add `os/setlocale` as a very bare bones wrapper around [setlocale](https://pubs.opengroup.org/onlinepubs/009695399/functions/setlocale.html). I spent some time trying to make thread local setlocale work, but each platform has it's own way of doing it and it was hard to make it consistent.

Example with `os/strftime`:

```janet
(os/setlocale (os/getenv "LC_ALL" "C")) # call at script start
(print (os/strftime "%A %c" (os/time)))
```

**Comment by amano-kenji** [comment]
Thread local?
