### ISSUE TITLE
recent change kinda breaks lexical scope with multiple modules

### ISSUE THREAD

**Issue by ianthehenry** [janet-lang/janet#1447]
I think that this commit has some really confusing unintended consequences:

https://github.com/janet-lang/janet/commit/0350834cd3dab0491d79e90c473f678959bd97ce

As a completely contrived example:

```janet
# one.janet
(def + -)
(import ./two)
(print two/export)
```

```janet
# two.janet
(def export (+ 100 50))
```

Before that commit, this printed `150`. Afterwards, it prints `50`.

I definitely assume that I'm starting from the vanilla `root-env` when I make a new file, and even though I usually `import`/`use` at the top of a file this makes the order of those imports really significant.

As a less fake example, I have a package called `pat` that shadows the built-in `match`, but if I `(use pat)` and then import something else, I don't know if it will succeed or fail with `pat`'s semantics.

**Comment by sogaiu** [comment]
FWIW, bakpakin made the following comment [here](https://github.com/janet-lang/janet/issues/1434#issuecomment-2112407237):

> EDIT:
> As a work around for all recent Janet versions, you can also do (import ./other :env (make-env (curenv))). The default was that import, require, and dofile start with a pristine environment, including dynamic bindings when imported. We might want to go back to that.

I didn't quite follow, but I got the sense he thought some kind of reversion might be in order.

**Comment by bakpakin** [comment]
This change has been reverted and replaced with a better tool `*module-make-env*` which is used to dynamically construct the default environment when using `require`, `import`, and `dofile`.

On latest master, new usage would be like so:

main.janet
```janet

(def new-env (make-env))
(put new-env *module-cache* @{})
(put new-env *module-loading* @{})
(put new-env *module-make-env* (fn get-new-derived-env [&] (make-env new-env)))
(dofile "./my-custom-plugin.janet" :env new-env)
```

my-custom-plugin.janet
```janet
(import ./lib) # lib will be loaded with environment table created by get-new-derived-env
```
