### ISSUE TITLE
Any other libraries out there for common functions? (postgres / mariadb / json encoding and decoding etc.)

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#145]
Any other libraries out there for common functions? (postgres / mariadb / json encoding and decoding etc.)

I want to try out a web based API/microservice written in Janet (probably leveraging Circlet as the server) and am wondering what's out there for supporting.

**Comment by bakpakin** [comment]
There is not that much, but maybe of interest to you is the [JSON module](https://github.com/janet-lang/json) and the [Sqlite module](https://github.com/janet-lang/sqlite3) module. Both should be pretty simple and straight-forward to use. Current there are no crypto bindings, so if you want that you are on your own. Putting a circlet server behind a reverse proxy like nginx might be a good option if you want authentication and other more advanced features.

**Comment by ahungry** [comment]
That's great, thank you.  In both cases, did you write the modules from scratch, or use FFI to underyling C libs for those tasks?

Is there anything in the space of making http requests?  (libcurl)?  If not, does janet support networking tcp/udp at all atm?  (if so, would you recommend a janet module that is just an FFI around libcurl, or a reimplementation of an http client in straight janet?)

**Comment by bakpakin** [comment]
These were implemented from scratch, especially the JSON parser. FFI bindings are great for binding to a large number of libraries, but are unsafe and provide an API usually unsuited to a supposedly safe (segfault resistant) language like Janet. Janet doesn’t have anything like LuaJIT’s ffi.

There is a libcurl binding out there that - you can take a look at https://github.com/sepisoad/jurl.

**Comment by bakpakin** [comment]
There is also a libuv binding I have been working on intermittently - https://github.com/janet-lang/juv - but it is incomplete with only timers, a basic tcp stream, and a few file system operations implemented.

**Comment by swlkr** [comment]
Just wanted to update this with [jhydro](https://github.com/janet-lang/jhydro)

**Comment by bakpakin** [comment]
Closing. See https://github.com/janet-lang/pkgs for a growing list of known packages.
