### ISSUE TITLE
Linux event loop hanging

### ISSUE THREAD

**Issue by anastasiatimit** [janet-lang/janet#1452]
Can't upgrade janet version due to stream or event error, not sure, no error is thrown, just app can't finish loading files.
The app is built on alpine linux.

After some testing, noticed that [this](https://github.com/janet-lang/janet/commit/5f2e287efdbd0877751c346572e645b02f67b75a) is the first commit that made the application unresponsive, I think src/core/ev.c change started to change the behaviour, as building next commit and replacing this file from the working commit solved the issue in next commit.

 Do you have any suggestion please what to do?

Thank you

**Comment by bakpakin** [comment]
Hi @anastasiatimit, what version of Janet are you trying to run? Does trying the latest master fix the problem? There was a bug involving epoll that would sometimes miss connections that is only fixed on the latest master

**Comment by anastasiatimit** [comment]
@bakpakin, yes, I tried master, but same issue persists

**Comment by sogaiu** [comment]
Possibly related might be [this issue](https://github.com/janet-lang/spork/issues/184#issuecomment-2153773709) filed at the spork repository.

**Comment by bakpakin** [comment]
@anastasiatimit Please check the latest master and see if this fixes your problem

**Comment by anastasiatimit** [comment]
@bakpakin yes, such a great catch, can't reproduce the issue anymore, thank you!

**Comment by sogaiu** [comment]
@anastasiatimit Great to hear things are working!

May be the issue can be closed?
