### ISSUE TITLE
os/open fails to create a file unless it's opened read/write-only

### ISSUE THREAD

**Issue by sarna** [janet-lang/janet#1469]
When the file is opened in `O_RDWR` mode, the `O_CREAT` flag is discarded here: https://github.com/janet-lang/janet/blob/a5d6b2283834422a9fa9e79b5c7ad9b932b52568/src/core/os.c#L2671

So, this works:
```janet
repl:1:> (os/open "foo" :cr)
<core/stream <core/stream handle=6>>
repl:2:> (os/open "foo" :cw)
<core/stream <core/stream handle=7>>
```
But this doesn't:
```janet
repl:4:> (os/open "bar" :c)
error: No such file or directory
  in os/open [src/core/os.c] on line 2524
  in thunk [repl] (tail call) on line 4, column 1
repl:5:> (os/open "bar" :crw)
error: No such file or directory
  in os/open [src/core/os.c] on line 2524
  in thunk [repl] (tail call) on line 5, column 1
```

Kudos to @sogaiu for locating the bug on Zulip :)

**Comment by sogaiu** [comment]
@sarna May be as you hinted at [here](https://janet.zulipchat.com/#narrow/stream/409517-help/topic/can't.20create.20a.20new.20file.20with.20.60os.2Fopen.60/near/446834854), it is a matter of changing the mentioned line to be:

```c
 open_flags |= O_RDWR;
```

I tried the suggested change and it seemed to work better.

Care to make a PR?
