### ISSUE TITLE
short-fn and -> don't work together

### ISSUE THREAD

**Issue by na-sa-do** [janet-lang/janet#1477]
`short-fn` and `->` seem like they'd be quite useful together, but they interact in a way that seems to be a bug:

```janet
janet:1:> (-> "" identity)
""
janet:2:> (-> "" |(identity $))
<function 0x001069C0>
janet:3:> (_)
repl:3:1: compile error: <function 0x001069C0> expects at least 2 arguments, got 0
janet:4:> (_ 1 2)
""
```

I have no idea where this two-argument function comes from. Also, if the `short-fn`'s body contains more arguments, it doesn't even parse:

```janet
janet:5:> (-> 3 |(+ 1 $))
repl:5:7: compile error: unexpected type in destructuring, got 1
janet:6:> (-> 3 |(+ $ 1))
repl:6:7: compile error: unexpected type in destructuring, got 1
```

Ditto if you try to invoke a method in the `short-fn`:

```janet
janet:7:> (def object {:identity identity})
{:identity <function identity>}
janet:8:> (-> object |(:identity $))
repl:8:12: compile error: unexpected type in destructuring, got :identity
janet:9:> (-> object :identity) # for completeness
{:identity <function identity>}
```

**Comment by na-sa-do** [comment]
Oh, wait:

```janet
repl:1:> (macex '(-> "" |(identity $)))
(fn (identity $) [] "")
repl:2:> (macex '(-> 3 |(+ 1 $)))
(fn (+ 1 $) [] 3)
repl:3:> (macex '(-> object |(:identity $)))
(fn (:identity $) [] object)
```

This still seems like a bug -- if anything, a bigger one than before -- but at least I can sort of see why it happens now.

**Comment by ianthehenry** [comment]
When you write `(-> 3 |(+ 1 $))`, you're really writing `(-> 3 (short-fn (+ 1 $)))`. The pipe syntax desugars to that.

Then the `->` macro does what it does best, and throws a `3` in there, so the compiler sees:

```
repl:1:> (short-fn 3 (+ 1 $))
repl:1:1: compile error: unexpected type in destructuring, got 1
```

This is a confusing error but it's less confusing given what it expands to, which your second example shows.

```
repl:2:> (macex '(short-fn 3 (+ 1 $)))
(fn (+ 1 $) [] 3)
```

(I think of the first argument to `fn` as the name but it's being interpreted as a pattern? I don't actually know why that is.)

The key thing to understand is that `->` is a macro; its subsequent arguments are not functions, but pieces of syntax. (Although it assumes you're handing it a function if you supply a symbol.) So the fact that `short-fn` eventually "returns" a function doesn't matter -- `->` runs before that function is constructed.

Anyway this is working as intended, but there is a way to do what you want:

```
repl:3:> (as-> 3 $ (+ 1 $))
4
```

(Of course in that example you can just `(-> 3 (+ 1))` or `(->> 3 (+ 1))` but `as->` lets you inject the variable anywhere, which is useful.)

**Comment by na-sa-do** [comment]
I think "working as intended" is a bit strong, given that I can't imagine anyone thought of this exact outcome as desirable, but I'll grant that it isn't a bug. That said, I can't imagine I'll be the only one to make this mistake, so it should be noted in the docs. I'll open a PR.

> (I think of the first argument to `fn` as the name but it's being interpreted as a pattern? I don't actually know why that is.)

I think you're confusing it with `defn`.

**Comment by ianthehenry** [comment]
Functions have associates names, and while `defn` will create a named function and a binding, you can create a named function with no associated binding with `(fn name [] …)`. This is useful for getting better stack traces when you’re manipulating first-class functions.

**Comment by sogaiu** [comment]
On a minor note, IIUC, [that name can now be a keyword as well](https://github.com/janet-lang/janet/commit/eb21d4fff48ee657ef83b7b4b54b386dd4f919fd) -- [here](https://github.com/janet-lang/janet/blob/872b39cc327db562857defdd4ed7b0db7502f18b/src/boot/boot.janet#L292) is an example.

**Comment by CFiggers** [comment]
Naming a `fn` is also useful for recursion (otherwise how would you refer to that `fn` within itself):

```janet
Janet 1.35.2-872b39cc linux/aarch64/clang - '(doc)' for help
repl:1:> ((fn this [i]
repl:2:((> (cond
repl:3:(((> (> i 10) i
repl:4:(((> (do (print i) (this (inc i))))) 1)
1
2
3
4
5
6
7
8
9
10
11
```
