### ISSUE TITLE
Feature request (or is it possible) to have Clojure like keyword = accessor

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#148]
I would like this to work similarly to Clojure:

    (:x {:x 1 :y 2}) => 1

Where a keyword used as a function is equivalent to `(get _ kw)`.  I think having such a feature makes a lot of things very succint to write in Clojure, such as a pluck of all a key requiring no more than `(defn pluck [kw coll] (map kw coll))`

**Comment by bakpakin** [comment]
This has been asked multiple times, and there is a good reason why we can’t support it. Keywords are used as method selectors to do OO. This behavior is incompatible with using them like presented. Things like `(:close file)` would no longer work.

**Comment by ahungry** [comment]
I am speaking with no insight into the implementation details (apologies), but at a high Isn't it fundamentally the same?  If you were to consider a struct a type of object, and the keyword as a function as the accessor?

How does it differ to have a file object with a (:close file) that refers to a ":close" slot, and a struct that treats a keyword as a dispatch to an accessor?

**Comment by bakpakin** [comment]
No, they are different. The method selector gets the method AND invokes it. What is now `(:close file)` would need to be `((:close file))` or probably `((:close file) file)` if we used keywords as accessor functions. 

Currently, `(:close file)` is semantically equivalent to `((get file :close) file)`. This is not about implementation, but about semantics.

**Comment by ahungry** [comment]
So the semantic is get slot and immediately invoke, which is definitely a neat and useful shortcut.

Since it is (mostly) rare to store functions in structs, I think a really nice shorthand would be to do the get, and then if `(= (type _) :function)` invoke, otherwise just return the value stored there.

That way you would have the short syntax for OO and the Clojure like for moving around / accessing data.

Ultimately it seems like the setup like it is might have been because double nesting was considered too many parens / ugly to read - in which case, couldn't there be some general prefix / decorator to any sexp not just for the OO slots that worked like

    !(call-that-returns-fn)

Which would expand/be equivalent to: ((call-that-returns-fn)) ?  I think such a feature would be pretty neat.

**Comment by bakpakin** [comment]
It’s less about saving bytes and parens and more about making the OO better. It’s easy to cherry pick examples that support one idea or another, so here goes. To close an array of files:

```
(map :close some-files)
```

This will not work as easily with macros for OO as suggested. I did experiment with a macro prefix for OO, but I ended up not liking it very much and it made easy things harder and less clear. Also I was running out of prefix characters for reader macros :).

Janet is meant to be extended with C, or integrate with C. It’s pretty common to have an abstract C data type that has multiple methods associated with it and I wanted to make that as easy as possible to use these methods from the Janet side.

All together, I’m pretty happy with keywords as method selectors rather than accessors. While it does make some clojure idioms not as clean, we get prototype style polymorphism (using table prototypes and functionality of abstracts) with pretty clean syntax. I think that this is an important use case.

**Comment by ahungry** [comment]
I can respect that, I suppose it will grow on me as I dive deeper into Janet and am comparing both sides with more of an equivalent time investment in each. 

Thanks again for all your hard work, such a cool language!

**Comment by curist** [comment]
A quick and dirty impl.
```clojure
(defn make-data-object [obj]
  (def obj-keys (keys obj))
  (if-not (all keyword? obj-keys)
    (error "all key should be keyword"))
  (def value-obj @{})
  (defn accessor [k]
    (fn [_ & args]
      (if (empty? args)
        (get value-obj k)
        (put value-obj k (args 0)))))
  (def ret @{:value (fn [_] value-obj)})
  (loop [k :in obj-keys]
    (put value-obj k (obj k))
    (put ret k (accessor k)))
  ret)

(def data {:a 1
           :b "kkthx"
           :xyz [:x :y :z]})

# usage
(do
  (def data-model (make-data-object data))
  (pp data-model)
  (pp (:value data-model)) # :value returns all values
  (pp (:a data-model))
  (:a data-model nil)
  (pp (:value data-model))
  )
```
it's quite limiting, and only handle keys provided when initializing, but do work in certain scenario.

**Comment by bakpakin** [comment]
Another idea, pretty simple:

```clojure
(defn acsr [key &opt dflt]
  "Create an accessor function for a keyword. This function retrieves the value associated with key
  from a data structure."
  (fn [ds] (get ds key dflt)))

(map (acsr :type)
  [{:type :cat :name "Fluffy"} {:type :dog :name "Spot"}])

;#-> (:cat :dog)
```

**Comment by curist** [comment]
That's neat. But I think the original intention is to be able to `(map :key data)`, otherwise, using short-fn
```clojure
(map |($ :type)  [{:type :cat :name "Fluffy"} {:type :dog :name "Spot"}])
```
is already quite sufficient.
