### ISSUE TITLE
Add an option to os/pipe to create synchronous pipe

### ISSUE THREAD

**Issue by negrel** [janet-lang/janet#1481]
I'm currently building a shell DSL for Janet and I'm trying to pipe stdout of a process to stdin of another process.

I have the following code:
```janet
(def [pipe-r pipe-w] (os/pipe))

(pp (ev/gather
	(ev/spawn
		(def proc (os/spawn @["yes"] :epx { :out pipe-w }))
		(os/proc-wait proc)
		(ev/close pipe-w))
	(ev/spawn
		(def proc (os/spawn @["tr" "y" "Y"] :epx { :in pipe-r }))
		(os/proc-wait proc)
		(ev/close pipe-r))))
```

Here is the output:

```sh
$ janet main.janet |& uniq -c
      1 @[<fiber 0x000015E96C30> <fiber 0x000015E97140>]
      1 yes: standard output: Resource temporarily unavailable
  32768 Y
      1 tr: read error: Resource temporarily unavailable
```

The number of `Y` lines is always 32768 (2 << 14) or 0. After looking at the source code of Janet it seems that all pipe created using `(os/pipe)` are asynchronous (`O_NONBLOCK`).

The same code with a patched version of janet that returns synchronous pipe works well.

Does adding optional parameter to `(os/pipe)` to support synchronous pipe is conceivable ? Should I submit a PR ?

Context: https://janet.zulipchat.com/#narrow/stream/409517-help/topic/How.20to.20pipe.20output.20of.20process.20as.20input.20of.20another.20process.20.3F/near/456186185
This is related to https://github.com/janet-lang/janet/issues/592 I believe.

**Comment by negrel** [comment]
I'm not a windows developer but it seems that `janet_make_pipe` always return blocking pipe on windows, ignoring the mode argument.

**Comment by bakpakin** [comment]
Just pushed some changes to help address this by adding some extra options to `os/pipe`: https://github.com/janet-lang/janet/commit/accac6c6621bc7eb109aed50c8751c64ce0354f3

The following code should now work as both `yes` and `tr` should receive unmodified file descriptors and therefor avoid any strange behaviors.
```janet
(def [pipe-r pipe-w] (os/pipe :RW))

(pp (ev/gather
	(ev/spawn
		(def proc (os/spawn @["yes"] :epx { :out pipe-w }))
		(os/proc-wait proc)
                (ev/close pipe-w))
	(ev/spawn
		(def proc (os/spawn @["tr" "y" "Y"] :epx { :in pipe-r }))
		(os/proc-wait proc)
                (ev/close pipe-r))))
```

**Comment by sogaiu** [comment]
I saw a lot of Ys :)

**Comment by negrel** [comment]
It works well on my linux though it doesn't work on Windows because
`os_pipe` calls `janet_stream` that calls `janet_register_stream` which call `CreateIoCompletionPort`
with a handle that **doesn't** support overlapped IO.

**Comment by bakpakin** [comment]
This should now work on windows with some code to handle streams that don't support overlapped IO (they simply are not registered). Closing.
