### ISSUE TITLE
Change `filewatch/make` to `filewatch/new`

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#1487]
I know bikeshedding is nobody's favourite activity but since the feature was just added, I thought it might be appropriate.

A number of functions in Janet's core API that enclose state in an 'object' use `new` (`array/new`, `buffer/new`, `fiber/new`, `parser/new`, `table/new`). However, the new `filewatch` feature uses `filewatch/make`. I suggest this be changed to `filewatch/new` for consistency.

**Comment by bakpakin** [comment]
Good suggestion, fixed this in the latest master. Still a lot of changes in the filewatch module, I would be a bit hesitant on depending on it until the next release.

**Comment by pyrmont** [comment]
I got lazy and never finished this off but a couple of years back I was started [Watchful](https://github.com/pyrmont/watchful), a C library that provided file watching support. I never added support for ReadDirectoryChangesExW or kqueue but I wanted to mention it in case it's any help for macOS's FSEvents API.
