### ISSUE TITLE
Any way to do parallelism / concurrency with fibers? 

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#149]
I saw this thread:

https://github.com/janet-lang/janet/issues/75

Where it references using fibers for coop threading - with the current Janet version / fibers, is it possible to do something like:

```clojure
         (defn make-sleepy-fiber [n]
           (fiber/new (fn [] (os/sleep n) n)))

         (defn test-fiber []
           (let [fibers (map make-sleepy-fiber (reverse (range 5)))]
             # Fibers would all be resolving their sleeps concurrently                                                                                                   
             # So that the overall call time here would be 5 or so seconds, not 15 seconds.                                                                              
             (map resume fibers)))
```

**Comment by bakpakin** [comment]
Not yet, for real concurrency you need something like pthreads. This is still on the road map, at some point in the future. Probably soon though, as it opens up a lot of possibilities.

The easiest thing to do though would just be to add a cfunction that wraps `fork`. This should be fairly straightforward to do from C.

**Comment by ahungry** [comment]
If you find yourself with some free time - could you let me know how I invoke a closure that I unwrap?  I probably missed it in the documentation, but I'd like to make a custom C function that receives a function + active env, evaluates it, and returns it.

If I could get past that, I think I can come up with something interesting for applying the same concept in a forked pid or a thread etc.

I can't find anything on invoking a callee, so I've been trying to tinker with janet_dostring but again, can't figure out how to get the active ENV in my running thread/VM to give as arg1 of the janet_dostring (obviously deinit + init in the function I am externing my .so file causes a segfault)

**Comment by bakpakin** [comment]
Sure, you want one of `janet_call`, `janet_pcall`, or `janet_continue`. WIth the use case you have described, I think you want `janet_call`. This simply calls a function on the current fiber with the current env.

```c
Janet janet_call(JanetFunction *fun, int32_t argc, const Janet *argv);
```

Just FYI, the current env can be gotten like so:

```c
JanetFiber *currentFiber = janet_current_fiber();
JanetTable *currentEnv = currentFiber->env;
```

**Comment by ahungry** [comment]
Ok, I think this is what I needed (I love open source - took a peek at circlet code for the handler):

```
 static Janet my_fn (int32_t argc, const Janet *argv) {
   janet_fixarity (argc, 1);
   JanetFunction *func = janet_getfunction (argv, 0);
   JanetFiber *fiber = janet_fiber (func, 64, 0, NULL);
   Janet out;
   JanetFiberStatus status = janet_continue (fiber, janet_wrap_nil (), &out);

   if (status != JANET_STATUS_PENDING) {
     janet_stacktrace (fiber, out);
   }

   return out;
 }
```

Or something roughly like that - to receive a user defined fn scope and eval it.

**Comment by ahungry** [comment]
Oh, I should have refreshed first, yes, your suggestion saves me a ton of trouble as well.

Now to tinker with a not-terrible way to do this in the background.

To avoid passing around / registering globals on the C side (to make slots for pending function call resolution) would something like a callback work?

Where I do the following workflow:

1. Receive two functions to process in my custom my-fn cfunction.
2. Run a pthread in my-fn that receives the 2 fns as args.
3. When first fn is done computing (assume, something slow, like a sleep (10), the evaluation result stored in "out" from my last comment then becomes the first argument to the second function.
4. In the Janet side the 2nd function would usually involve some side-effect (setting something in the global state that other things are watching in a spin-loop etc.).

If so - what would the "invoke second function with the evaluation result of first function" look like on the C side?

**Comment by ahungry** [comment]
https://github.com/ahungry/janet-code/blob/master/mymod.c#L143

I came up with something that works for me (well, nearly a complete solution) using fork + mmap for shared memory for a trivial future/realize solution.

Pthreads obviously did not turn out great - the thread child segfaulted and panicked no matter what I did to try to share the env from the primary thread (and obviously fork without shared mem has no easy way to get the return value of the expression back to the parent).

**Comment by ahungry** [comment]
It works well:

```
         (import build/mymod :as p)

         (defn sleep-future [n]
           (p/future
            (fn []
                (os/sleep n)
                n)))

         (defn test-futures []
           (let [futures (map sleep-future (range 10))]
             (os/sleep 5)
             # Now, half of them should be resolved.                                                                                                                     
             (map p/realize futures)
             ))

         (test-futures)
```

And it produces the results as expected - first 5 are resolved to their evaluation results, while the last 4 are still in PENDING status.

Thanks a ton for the help and guidance - I'm going to polish up "mymod" to be a parallel module for GNU/Linux at least (the only thing maybe not standard is mmap ANON option, but I just hardcoded to 0x20 vs included the GNU C linker flag (how do I do custom C flags btw?)

**Comment by ahungry** [comment]
Also, this is another nice test - similar to Promise.all in javascript:

```
         (defn futures-pending?
           "See if there are any futures pending in the list."
           [futures]
           (> (count (fn [x] (= :PENDING (p/realize x))) futures) 0))

         (defn realize-all [futures]
           (while (futures-pending? futures)
             (os/sleep 0.05))
           (map p/realize futures))

         (defn test-realize-all []
           (let [futures (map sleep-future (range 5))]
             (realize-all futures)))

         # Will resolve in 4 seconds, not in 10. :)                                                                                                                      
         (test-realize-all)
```

**Comment by bakpakin** [comment]
Nice progress, that was quick!

>how do I do custom C flags btw?

In the project.janet file, you can include custom cflags with the `:cflags` key. Something like

```clojure
(declare-native
  :name "mymod"
  ...
  :lflags [;default-lflags "-lpthread"]
  :cflags [;default-cflags "-Werror"])
```

The hardest part about the Janet API is getting the memory managment correct. A direct wrapper around pthreads is pretty much guranteeded to segfault because you can't share memory, and the closures themselves are GCed, and thus can't be shared!

Any method of threading using pthreads needs to serialize *everything* before sending it to a new thread. Luckily, Janet provides the `marshal` function (janet_marshal from C) for doing just that. Fork, however, has no such problem :).

**Comment by bakpakin** [comment]
Referencing issue #79 here, more discussion there.
