### ISSUE TITLE
Changelog incorrectly lists changes as being part of v1.35.2 

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#1491]
The changelog currently lists the following changes as being part of v1.35.2:

https://github.com/janet-lang/janet/blob/828e0a07cd5ac8be0ead09a3320667043ea08ea0/CHANGELOG.md?plain=1#L16-L18

These changes were added by f62539ad55e19dac1c14b4c63b75f49f48709ee4 and 4835ecb950acc66286eed5fa7e933b0170309468 respectively which came after the release of v1.35.2 (see [tag](https://github.com/janet-lang/janet/commits/v1.35.2/)). These changes should be moved into the unreleased section.

**Comment by sogaiu** [comment]
Good catch.
