### ISSUE TITLE
Consider line feed in the shell as a clear line indicator

### ISSUE THREAD

**Issue by rivten** [janet-lang/janet#1493]
Hello all !

I'm creating this issue, but it might be more of a proposal as I'm not entirely sure that this is without any unforeseen consequences.

## Context

I'm using [vim-slime](https://github.com/jpalardy/vim-slime) from vim for REPL-driven development. When I send some text from vim to another terminal running the Janet REPL (let's say the text "(+ 1 1)") then the tool sends to the repl "(+ 1 1)\n" (with a line feed added).

From most other REPL I've tried (Clojure, Python), this seems to be caught and consider as a new line. But not in Janet.

## Proposal

In `src/mainclient/shell.c`, in the `switch` case of the function `static int line()`, add a case for 10 (line-feed in ascii decimal), and do the same execution as for case 13 (carriage return in ascii decimal). This would just also clear the REPL line and evaluate the line when receiving a line feed from stdin.

I've tried and this fixed my use case. I can create a small PR if you think this is a good idea to add in the codebase and does not have any other consequences I might have not thought of.

Best.

**Comment by bakpakin** [comment]
The current implementation in shell.c is designed to allow multi-line copy paste. I would say that that is a more useful feature. For vim-slime or other such tools that use the CLI as a programmatic interface, use `janet -s`.

**Comment by rivten** [comment]
Completely missed this command-line parameter. Indeed it works perfectly on my end ! Sorry for the oversight and have a great day :)
