### ISSUE TITLE
`build_win.bat dist` output contains "The system cannot find the file specified"

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet#1495]
With c82fd106 (and likely before), I've noticed that here, `build_win.bat dist` invocation output contains:

```
"The system cannot find the file specified".
```

It looks like this comes from:

```
copy janet.def dist\janet.def
```

That line seems to have been added in [this commit](https://github.com/janet-lang/janet/commit/b10aaceab07963a4123747b87fd669c24f275166).

Looking at the cloned janet repository directory after building (e.g. after invoking `build_win.bat` successfully), I don't see `janet.def`.  May be I'm doing something wrong?

Perhaps there is nothing to be concerned about here but FWIW.

**Comment by bakpakin** [comment]
I don't think we really need janet.def anymore, it's an artifact from msvc to declare exported symbols. I think the better thing to do is just drop that from the build process.

Not an expert on this, but I would check microsoft documentation: https://learn.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-def-files?view=msvc-170

Basically, all exported symbols in Janet should be using `__declspec(dllexport)` (that is what the macro JANET_API resolves to on windows), so from the above documentation it is implied we don't need it.
