### ISSUE TITLE
Convenient math operators

### ISSUE THREAD

**Issue by katomuso** [janet-lang/janet#1507]
What do you think about adding `//` and `**` operators which can be used instead of writing `(math/floor (/ x y))` and `(math/pow x y)`? Floor division is often used in algorithms, so it will be especially nice to have it.

**Comment by bakpakin** [comment]
Use `div` for floored division. As far as "operators", no such thing in lisp. There is a macro for infix syntax here - https://github.com/janet-lang/spork/blob/master/spork/infix.janet for more things as well, which would probably be a better place for such things.

**Comment by katomuso** [comment]
> Use `div` for floored division. 

Thanks, somehow I missed that.

> As far as "operators", no such thing in lisp. There is a macro for infix syntax here - https://github.com/janet-lang/spork/blob/master/spork/infix.janet for more things as well, which would probably be a better place for such things.

I've used the word "operators" in a general sense. https://en.wikipedia.org/wiki/Operator_(mathematics)
