### ISSUE TITLE
Mingw compilation error

### ISSUE THREAD

**Issue by Miguel-hrvs** [janet-lang/janet#1511]
The problem is that mingw is using int32_t for JanetAtomicInt instead of long.

src/core/state.c: In function 'janet_interpreter_interrupt_handled':
src/core/state.c:75:26: error: passing argument 1 of '_InterlockedDecrement' from incompatible pointer type [-Wincompatible-pointer-types]
   75 |     InterlockedDecrement(&vm->auto_suspend);
      |                          ^~~~~~~~~~~~~~~~~
      |                          |
      |                          volatile int32_t * {aka volatile int *}
C:/msys64/mingw64/include/psdk_inc/intrin-impl.h:1692:51: note: expected 'volatile long int *' but argument is of type 'volatile int32_t *' {aka 'volatile int *'}

**Comment by bakpakin** [comment]
How are you building Janet? We do have some Mingw tests in our CI so I'm a bit confused on how this is happening.

**Comment by Miguel-hrvs** [comment]
From tic80 ci

**Comment by bakpakin** [comment]
So I checked the TIC80 source code, I believe you are on version 1.34? The latest janet should have a fix for this - on windows, Janet atomics are exposed as long instead of int32. Please make sure you are using the latest release of Janet.

**Comment by Miguel-hrvs** [comment]
I'll check with latest

**Comment by Miguel-hrvs** [comment]
Weird, with v1.36 I get this error: src/core/capi.c: In function 'janet_atomic_inc':
src/core/capi.c:550:12: error: implicit declaration of function 'InterlockedIncrement' [-Wimplicit-function-declaration]
src/core/capi.c: In function 'janet_atomic_dec':
src/core/capi.c:560:12: error: implicit declaration of function 'InterlockedDecrement' [-Wimplicit-function-declaration]
src/core/capi.c: In function 'janet_atomic_load':
src/core/capi.c:570:12: error: implicit declaration of function 'InterlockedOr' [-Wimplicit-function-declaration]

**Comment by bakpakin** [comment]
Took a deeper look at this, and noticed that TIC-80 uses a custom build of Janet that is single threaded. This causes us to, on windows, not include windows.h for you.

With this fix, I'm able to build TIC-80 with Janet on windows-mingw - https://github.com/bakpakin/TIC-80/actions/runs/11284749144/job/31386437246

> I'll check with latest. Yep, we are in v1.34 because 1.36 had problems with winxp builds I think.

My guess is that this is related to the inclusion of SRWLock and some networking code for the ev module - since TIC-80 is single threaded, this shouldn't be totally necessary on windows. from (in janet) src/core/

**Comment by bakpakin** [comment]
Fix is here: https://github.com/janet-lang/janet/commit/43a68dcd2a48474383e7457c2b8a1b869ea08cfa

While we are here though, I would like to make sure that windows XP is working to for Janet since they are probably related.

@Miguel-hrvs let me know if XP is still an issue.

**Comment by Miguel-hrvs** [comment]
Thanks, mingw and msvc 2019 now build great. Wonder why winxp still fails.

**Comment by bakpakin** [comment]
Ok, more looking around, there is no reason to use Interlocked* functions at all unless 1. we are on windows _and_ we are using MSVC.

This change use MSVCs compiler intrinsics when needed, and on mingw will use GCCs intrinsics, meaning we don't need to include any thing. https://github.com/janet-lang/janet/commit/d10c1fe759307071e16ab6c162db8bc82bcb70ef

Also tried it out with TIC-80, looks like it builds now on winxp too: https://github.com/bakpakin/TIC-80/actions/runs/11301442227/job/31435854576

@Miguel-hrvs feel free to close if this works for you. These changes will make it into the next release of Janet.

**Comment by Miguel-hrvs** [comment]
Perfect, now it builds in winxp too. Thank you, I'll close the issue.
