### ISSUE TITLE
Mismatch between timeout behavior and docstrings of some net/* functions?

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet#1523]
The docstring for `net/read` [currently has this bit](https://github.com/janet-lang/janet/blob/6535d72bd409eaeb01ee069d7a4b0e1fd46209c7/src/core/net.c#L847):

> Takes an optional timeout in seconds, after which will return nil.

In my testing, I don't observe this behavior.  AFAICT, what happens seems to be that instead of returning `nil` after the specified timeout, an error occurs.

Here is some sample code that exhibited the behavior here (Linux box):

```janet
(def timeout 1)

(def host "127.0.0.1")
(def port "9898")

#(def s (net/listen host port))
(def s (net/server host port))

(def c (net/connect host port))

(def buf @"")
(var result :some-value)

(def start (os/time))

(try
  (set result (net/read c 1 buf timeout))
  ([e]
   (eprintf "try failed with: %n" e)))

(if (= :some-value result)
  (printf "net/read did not return")
  (printf "net/read result is %n" result))

(printf "%.02f seconds" (- (os/time) start))

(net/close s)
```

I get the following output with https://github.com/janet-lang/janet/commit/6535d72bd409eaeb01ee069d7a4b0e1fd46209c7:

```
try failed with: "timeout"
net/read did not return
1.00 seconds
```

---

It looks to me like the docstring ended up with timeout bits in [this commit](https://github.com/janet-lang/janet/commit/553b4d9428247d90b74732e667216ae062d2f09f) (2020-07-20).

I compiled janet from that commit and tried the code above.  The resulting behavior was that `net/read` seemed to return `nil`:

```
net/read result is nil
1.00 seconds
```

This matches the docstring, so perhaps something has changed between then and now.

---

FWIW, in the same commit, the following `net/*` functions got similar changes to their docstrings regarding timeouts.  Those functions were:

* [net/accept](https://github.com/janet-lang/janet/commit/553b4d9428247d90b74732e667216ae062d2f09f#diff-e53e84f5a54e63680698db90054242017015dfda22e881e7e4f4fc48e2202cb3R801)
* [net/read](https://github.com/janet-lang/janet/commit/553b4d9428247d90b74732e667216ae062d2f09f#diff-e53e84f5a54e63680698db90054242017015dfda22e881e7e4f4fc48e2202cb3R809)
* [net/chunk](https://github.com/janet-lang/janet/commit/553b4d9428247d90b74732e667216ae062d2f09f#diff-e53e84f5a54e63680698db90054242017015dfda22e881e7e4f4fc48e2202cb3R816)
* [net/write](https://github.com/janet-lang/janet/commit/553b4d9428247d90b74732e667216ae062d2f09f#diff-e53e84f5a54e63680698db90054242017015dfda22e881e7e4f4fc48e2202cb3R822)
* [net/send-to](https://github.com/janet-lang/janet/commit/553b4d9428247d90b74732e667216ae062d2f09f#diff-e53e84f5a54e63680698db90054242017015dfda22e881e7e4f4fc48e2202cb3R829)
* [net/recv-from](https://github.com/janet-lang/janet/commit/553b4d9428247d90b74732e667216ae062d2f09f#diff-e53e84f5a54e63680698db90054242017015dfda22e881e7e4f4fc48e2202cb3R836)

I also found that the CHANGELOG for [1.12.1 - 2020-09-07](https://github.com/janet-lang/janet/blob/master/CHANGELOG.md#1121---2020-09-07) had the following:

> Change net/read, net/chunk, and net/write to raise errors in the case of failures.

[This commit](https://github.com/janet-lang/janet/commit/06c268c274972692611a5ae27881adf5cb447ec3) seems to be where the CHANGELOG had that bit added to it.

---

Any hints as to what the intended behaviors are for the six functions when a timeout is specified and the timeout is exceeded?

**Comment by bakpakin** [comment]
So the reason these are errors instead of returning nil is pretty simple - we use the `janet_addtimeout` function internally, which sets an internal flags `JanetTimeout to; to.is_error = 1;`. My guess is that with a lot of changes to the ev module early on, things like this got out of sync with the documentation.

So it's pretty easy to "fix", but it's also easy to update the documentation here, and I'm not sure which is less disruptive. I would think updating the documentation would be less disruptive and possibly break less code, and while returning nil makes certain things easier to write, and exception for a timeout I think is more consistent with the kind of dynamic language that Janet is.

**Comment by bakpakin** [comment]
Yup, looking at `ev/read`, and `ev/write`, those functions have been updated with `error` based timeout behavior, so in this case the documentation just needs updating.

**Comment by sogaiu** [comment]
Thanks for taking a look.

I looked at [a0eeb63](https://github.com/janet-lang/janet/commit/a0eeb630e70a0271d4cd72e153dbb39078ffbcbb) and it looks like five of the six docstrings are updated but not that for `net/read`.

May be it makes sense to make a similar change to `net/read`'s docstring as well?  I'll submit a PR along these lines.
