### ISSUE TITLE
Meson: Cross-compiling returns undefined `main` linker error.

### ISSUE THREAD

**Issue by mbekkomo** [janet-lang/janet#1524]
When trying to cross-build Janet with Meson, it failed to built janet-boot with following linker error.
```
ld: error: undefined symbol: main
>>> referenced by /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/Scrt1.o:(_start)
collect2: error: ld returned 1 exit status
```

**Comment by bakpakin** [comment]
Can you be a little more specific with the reproduction? What OS and architecture are you running for the host and target? What commands were run?

**Comment by mbekkomo** [comment]
For host build, it's x86_64 Linux.
For target, it's Android.
I ran `meson setup . -Db_lto=true`

**Comment by bakpakin** [comment]
The above fix applied to lets me build Janet inside the termux docker container with the following simple termux package build script:

```
TERMUX_PKG_HOMEPAGE=https://janet-lang.org
TERMUX_PKG_DESCRIPTION="Janet is a dialect of Lisp intended for embedding into programs and such"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Komo @mbekkomo"
TERMUX_PKG_VERSION=1.36.0
TERMUX_PKG_SRCURL=https://github.com/janet-lang/janet/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=104aa500d4a43c2c147851823fd8b7cd06a90d01efcdff71529ff1fa68953bb4
TERMUX_PKG_DEPENDS="libandroid-spawn"
```

@mbekkomo, you should be able to use the meson.build file in 5b79b48ae02f5a4c95a8fa671a13bf37d63e37ed to fix the cross compilation, or wait until the next Janet release.
