### ISSUE TITLE
include filename in `error: could not read file` message

### ISSUE THREAD

**Issue by jakobhellermann** [janet-lang/janet#1530]
I was building a project with `janet build` mistakenly instead of `jpm build` and got
```
error: could not read file
  in file/read [src/core/io.c] on line 193
  in chunks [boot.janet] on line 3009, column 24
  in run-context [boot.janet] on line 2653, column 12
  in dofile [boot.janet] on line 3032, column 5
  in cli-main [boot.janet] on line 4645, column 17
```
as a result.

This isn't particularly helpful and it would be neat if the message included the name of the file it tried to read.

Looks like the error comes from https://github.com/janet-lang/janet/blob/83e8aab2897aa2982db48668e85757eef680ea5e/src/core/io.c#L188 which only has access to a `JanetFile`, which doesn't include the filename, only a `FILE*`: https://github.com/janet-lang/janet/blob/83e8aab2897aa2982db48668e85757eef680ea5e/src/include/janet.h#L1248-L1251

So possible solutions could be
1. store the filename the file was opened by in `JanetFile`
2. attempt to find the filename associated to the file descriptor. (could be `/proc/self/fd/NNN` or `F_GETPATH` or `F_GETPATH` or `GetFileInformationByHandleEx` on windows? would need to investigate)
if this is in scope for janet

**Comment by strangepete** [comment]
Giving this the quick eyeball, I'm curious as to why 'build' is passing file/open in boot.janet and instead failing in read_chunk; file/open at least returns the filename in the error

**Comment by sogaiu** [comment]
I think if one does `jpm build` at some point, then a `build` directory may get created.  If subsequently one does `janet build` without removing the `build` directory, one may get:

```
$ janet build
error: could not read file
  in file/read [src/core/io.c] on line 193
  in chunks [boot.janet] on line 3009, column 24
  in run-context [boot.janet] on line 2653, column 12
  in dofile [boot.janet] on line 3032, column 5
  in cli-main [boot.janet] on line 4645, column 17
```

If the `build` directory doesn't exist:

```
$ rm -rf build && janet build
error: could not find file build
  in dofile [boot.janet] on line 3030, column 5
  in cli-main [boot.janet] on line 4645, column 17
```

**Comment by strangepete** [comment]
That is odd because I get the full error message regardless of the directories existence; _on Windows_ 🤨

**Comment by strangepete** [comment]
https://stackoverflow.com/questions/42876210/c-fopen-opening-directories

Seems on linux fopen has a quirk about detecting directories with write mode
