### ISSUE TITLE
cannot build on mac os x

### ISSUE THREAD

**Issue by bentxt** [janet-lang/janet#159]
janet> gmake
Makefile:275: *** target pattern contains no '%'.  Stop.

**Comment by bakpakin** [comment]
On macos, you should build with just `make`. You can get make and a compiler with `xcode-select --install `. If that doesn’t work, what version of macros are you running? CI says the mac builds for clang and gcc work fine.

**Comment by bentxt** [comment]
doesn't work with

/usr/bin/make
/Applications/Xcode.app//Contents/Developer/usr/bin/make
/usr/local/Cellar//make/4.2.1_1/bin/gmake

Error 
---
everytime:
Makefile:275: *** target pattern contains no '%'.  Stop.

This is the line:
275: .PHONY: $(PKG_CONFIG_PATH)/janet.pc

----

specs:
system_profiler SPSoftwareDataType | grep -i version
      System Version: macOS 10.14.6 (18G95)
      Kernel Version: Darwin 18.7.0

**Comment by bentxt** [comment]
is this the same problem?

https://github.com/janet-lang/janet/issues/128

**Comment by bentxt** [comment]
Ok, this particular problem is now solved (at least on my machine ...) 
thanks

**Comment by bentxt** [comment]
Ok, this particular problem is now solved (at least on my machine ...)
thanks
