### ISSUE TITLE
get-in / update-in

### ISSUE THREAD

**Issue by curist** [janet-lang/janet#161]
Can we have these two functions? I find them quite handy at times. A naive impl of get-in
```clojure
(defn get-in
  "get value deep in a ds"
  [ds ks &opt dflt]
  (if (or (empty? ks) (nil? ds))
    (break (or ds dflt)))
  (def r (get ds (first ks)))
  (get-in r (drop 1 ks) dflt))
```

**Comment by bakpakin** [comment]
This seems pretty reasonable to add. We can be more efficient using a loop rather than `(drop)`, though. The above is `O(n^2)` on length of ks.

**Comment by curist** [comment]
Saw they are in latest master, thanks!
