### ISSUE TITLE
Unexpected difference between ->> and -?>>

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#165]
A pipeline which works fine for `->>`, ends with an error for `-?>>`.

Repro:
```
(-?>> [:headers "Cookie"]
      (get-in {:headers {"Cookie" "ho=ho;mo=mo"}}) 
      (string/split ";")  
      (map |(string/split "=" $)) 
      flatten 
      (map string/trim) 
      splice 
      table)

error: expected even number of arguments
  in table
  in _thunk [repl] (tailcall) at (1657:1814)

```

vs

```
(->> [:headers "Cookie"] 
     (get-in {:headers {"Cookie" "ho=ho;mo=mo"}}) 
     (string/split ";") 
     (map |(string/split "=" $)) 
     flatten 
     (map string/trim) 
     splice 
     table)

@{"ho" "ho" "mo" "mo"}
```

It seems that short-circuit version of the threading macro ignores the splice. I tried to find the problem, but it is well beyond my macro mastery.

Just for the clarity, there is unthreaded version: 
```
(table 
  (splice 
    (map string/trim 
      (flatten 
        (map |(string/split "=" $) 
          (string/split ";" 
            (get-in {:headers {"Cookie" "ho=ho;mo=mo"}} 
            [:headers "Cookie"]))))))) 
```

**Comment by pepe** [comment]
Again I am not sure if this is a bug. It is caused by the behaviour of the splice macro outside of the fn args. Without it, and with `(apply table)` it works as it should.

Again feel free to close this issue. I am sorry for the noise.

**Comment by bakpakin** [comment]
The problem is the splice form. With the short-circuit version, we bind each intermediate step to a variable and check if it is not nil. But if you bind the result of `(splice array)` to a binding, the splice is ignored because it only has effect when used a function argument. Splice is really useful but definitely has caveats. It's a bit like multiple return values. Concrete example:

```clojure
(table (splice array)) ;# works
```

```clojure
#; Doesn't work
(if-let [tmp (splice array)]
  (table tmp))
```

**Comment by bakpakin** [comment]
It's a bit weird, but I'm not sure how we would go about "fixing" such a use case. `splice` isn't a function or even a macro, it's a special form, and one that doesn't evaluate to a single expression (the only such form).

**Comment by pepe** [comment]
I can understand it better now, and I do think it is the wrong usage of the `splice` (or better usage on a wrong place).

But again, I learned a lot. Thank you for your explanation.
