### ISSUE TITLE
`getline` doesn't print prompt when being piped 

### ISSUE THREAD

**Issue by curist** [janet-lang/janet#166]
v1
```clojure
#!/usr/bin/env janet
(while true
  (def line (getline "hello> "))
  (if (empty? line) (break))
  (:write stdout line))
```
v2
```clojure
#!/usr/bin/env janet
(while true
  (:write stdout "hello> ")
  (:flush stdout)
  (def line (getline))
  (if (empty? line) (break))
  (:write stdout line))
```
execute like this: `cat rl.janet | ./rl.janet`; v1 won't print out the prompt.
Not sure if that's an expected behavior?

**Comment by bakpakin** [comment]
getline is for user input. It has code for detecting if a tty is present and only printing if so. If you want a line of input from stdin, use `(:read stdin :line)`.

**Comment by curist** [comment]
since that's the intended behavior for `getline`, closing.
