### ISSUE TITLE
Using janet_pcall on a pthread?

### ISSUE THREAD

**Issue by PaulBatchelor** [janet-lang/janet#169]
Hello,

I am writing a program that would periodically a janet function on a pthread using `janet_pcall`. However, whenever I try to do this, I keep getting a segfault.

This small program generally outlines what I hope to accomplish. I'm defining a small function called "hi", and then using `janet_resolve` and `janet_pcall` to find and call this function from C.

```
#include <stdio.h>
#include <pthread.h>
#include <time.h>
#include "janet.h"

static int running = 0;

void * run(void *ptr)
{
    JanetTable *env;
    JanetBindingType result;
    Janet fun;

    env = ptr;
    while (running) {
        result = janet_resolve(env, janet_csymbol("hi"), &fun);

        if (result == JANET_BINDING_DEF) {
            janet_pcall(janet_unwrap_function(fun),
                        0,
                        NULL,
                        &fun,
                        NULL);
        }
        sleep(1);
    }
    return NULL;
}

int main(int argc, char **argv) {
    JanetTable *env;
    pthread_t thread;
    JanetBindingType result;
    Janet fun;

    janet_init();

    env = janet_core_env(NULL);

    janet_dostring(env,
                   "(defn hi () (print \"hello\"))",
                   NULL, NULL);
    running = 1;

    result = janet_resolve(env, janet_csymbol("hi"), &fun);

    if (result == JANET_BINDING_DEF) {
        janet_pcall(janet_unwrap_function(fun),
                    0,
                    NULL,
                    &fun,
                    NULL);
    }

    pthread_create(&thread, NULL, run, env);

    fgetc(stdin);
    running = 0;
    pthread_join(thread, NULL);

    janet_deinit();
    return 0;
}
```

Thanks in advance!

**Comment by bakpakin** [comment]
Janet does not support sharing memory across threads. This means you cannot pass the env to the other thread. The reason for this is that Janet's data structures are not concurrent, and Janet's GC is not concurrent. Also, in the default configuration, Janet has a bit of global state stored in thread-local storage. Instead, you will need to call janet_init for the new thread, and then probably re-run `janet_dostring` to get the source. For the two threads to communicate, some kind of message passing scheme is needed. Such a scheme could be combined with `janet_marshal` and `janet_unmarshal`.

An easier method, especially on linux/posix, is to use `fork`.

**Comment by PaulBatchelor** [comment]
Thank you for the quick reply! This is helpful information. I will consider these options. Is there anywhere I could learn more about `janet_marshal` and `janet_unmarshal`?
