### ISSUE TITLE
SIGSEGV when calling `string/trim` on string with only whitespace

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#174]
When calling `string/trim` on a string which has only white space in it `janet` dies with: `'janet' terminated by signal SIGSEGV (Address boundary error)`

Easy reproduction: 

`(string/trim " ")`

**Comment by pepe** [comment]
I have investigated a little and found that in https://github.com/janet-lang/janet/blob/c5010dffb496a5abd889cf0edb485e736f24c5a7/src/core/string.c#L503 when `left_edge` is smaller than `right_edge` the length is negative and `janet_string` then SIGSEGVes.

A simple fix is: 

```
    if ((right_edge - left_edge) > 0) {
      return janet_stringv(str.bytes + left_edge, right_edge - left_edge);
    } else {
      return janet_stringv(str.bytes, 0);
    }
```

but I guess it will be better to sanitize this in `janet_string`.

**Comment by pepe** [comment]
Also `string/trimr` and `string/triml` are not affected by this bug.

**Comment by bakpakin** [comment]
Good catch. We can probably sanitize other types in a similar way.
