### ISSUE TITLE
invalid os/date month value

### ISSUE THREAD

**Issue by sepisoad** [janet-lang/janet#175]
I think there might be an issue with (os/date) function.

to reproduce the issue run the following code:

```clojure 
(os/date 1388608200)
```

the expected output is:

```clojure
{ :year-day 1 :minutes 30 :month 1 :dst false :seconds 0 :year 2014 :month-day 1 :hours 8 :week-day 4}
```

which is equal to `Wednesday, January 1, 2014 8:30:00 PM GMT`, however the actual output struct is as follows:

```clojure
{ :year-day 1 :minutes 0 :month 0 :dst false :seconds 0 :year 2014 :month-day 1 :hours 0 :week-day 4}
```

as you can see `minutes`, `month`, and `hour`  values are invalid

**Comment by bakpakin** [comment]
How did you determine the expected output? `:year-day` is 0 indexed, so I am seeing `0` for that on my machine (latest master, 44ed2c6).

Output:
```
{ :year-day 0 :minutes 30 :month 0 :dst false :seconds 0 :year 2014 :month-day 0 :hours 14 :week-day 3}
```

On posix, the implementation is `localtime_r`. Perhaps something like `gmtime` is a better choice on linux?

**Comment by bakpakin** [comment]
Changing localtime_r to gmtime_r yields this output:

```
{ :year-day 0 :minutes 30 :month 0 :dst false :seconds 0 :year 2014 :month-day 0 :hours 20 :week-day 3}
```
This should be the correct output. Notice that :hours is 20 to account for PM, and some fields are 0 indexed instead of 1 indexed as they would be formatted in a human readable date, but otherwise the output is correct.

**Comment by sepisoad** [comment]
i did not know about `localtime_t` being zero based, my bad. I'm going to close this issue.

**Comment by bakpakin** [comment]
No worries. It’s not, it is just “corrected” for by the wrapper. The reasoning is that it’s easier to index into an array of week day names, or month names with 0 based indexes. I thought it was more consistent if all ordinal values started at 0.
