### ISSUE TITLE
Anaconda Package

### ISSUE THREAD

**Issue by jguhlin** [janet-lang/janet#178]
It'd be great if there could be an official anaconda package for the latest Janet release (I haven't been able to find it, so I don't think there is one). This way it could be integrated into nextflow/snakemake pipelines and scripts easier. I don't have the time (right now) to try and do it, but it would be really helpful.

Cheers

**Comment by andrewchambers** [comment]
I think this could be better suited as a generic issue around how to support N third party package tools in a consistent way.

One suggestion might just be to have an official /packages repo for people to send package definitions to. This repo could perhaps be automatically kept in sync with the official release tarballs.

**Comment by bakpakin** [comment]
Closing, as I have no intention of maintaining an Anaconda package (although if someone wants to do that, that awesome!). The point above still stands, this should probably be an issue in Anaconda, not here. Not that Anaconda needs/wants a Janet package.
