### ISSUE TITLE
Installing R in Anaconda is taking forever

### ISSUE THREAD

**Issue by kuldeepmore10** [janet-lang/janet#179]
For some reason I had to uninstall anaconda and reinstall. I am trying to install R again, but its taking forever. I started that in the morning (10 am) and it still says installing R (5 pm). I am not using Anaconda prompt but Anaconda Navigator. I have successfully done this before and it didn't take this much time the last time I did it. What do you guys think is the problem?

**Comment by bakpakin** [comment]
Wrong repo?

**Comment by kuldeepmore10** [comment]
Shouldn't that come up with an error message then, rather than going on and on with the installation? I am using navigator so I dont know how to check whether the repo is correct or not? Can you tell me how to check that?

**Comment by bakpakin** [comment]
No, you posted this issue in the wrong repo. Closing.
