### ISSUE TITLE
On clone fail due to ssl issues, jpm becomes unusable

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#188]
In a wiped env without ssl certs, I tried to do jpm install joy, which failed, after setting GIT_SSL_CAINFO in the env, jpm no longer works.
```
fatal: not a git repository (or any of the parent directories): .git                                        
fatal: not a git repository (or any of the parent directories): .git                                        
Error building git repository dependency: cannot open ./project.janet                                       
error: could not find module pkgs:                                                                          
```

**Comment by andrewchambers** [comment]
Was on jpm 1.5.1

**Comment by bakpakin** [comment]
I mean, there is not much I can do about this I think. You can use JANET_PKGKIST to point to http copies of repos

**Comment by andrewchambers** [comment]
No, the problem is the transient temporary error broke my jpm install even after I fixed the problem.

**Comment by bakpakin** [comment]
Ah I see. that’s kind of what jpm clear-cache is for. We should definitely try to nuke the repo directory though if anything fails to clone
