### ISSUE TITLE
jpm respect $CC and friends

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#190]
It seems it would make sense to give this priority over the default, but less than --compiler.

**Comment by andrewchambers** [comment]
One of my main uses is to produce a fully static binary, at the moment it seems I can only do this via making a wrapper script and using --compiler .

**Comment by bakpakin** [comment]
This seems reasonable to me. I had removed it from an earlier version of jpm during a rewrite I think. However, it would make wrapping jpm projects in Makefiles and other unixy build scripts easier.

**Comment by bakpakin** [comment]
Right now, we just support CC and AR. We may want to support ARFLAGS, CFLAGS, LDFLAGS, and LDLIBS. No need to support LD yet as we never call it in jpm.
