### ISSUE TITLE
jpm optionally use host libs

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#194]
The default standard seems to be pkg-conf or pkg-config for non windows machines, it would be nice if jpm libs could be configured to use the system lib. No idea what the solution for windows is. I would recommend we copy whatever rust conventions are in this case, rust deals with the same issue.

In rust many crates have a per dependency option for this configurable in the project metadata.

**Comment by bakpakin** [comment]
The thing is, windows doesn't really have a concept of system libs besides what comes with windows. Programs are responsible for installing whatever they need and being able to tear it down on uninstall (as far as I know. Real windows devs, correct me :)). This is one huge reason I prefer statically linking everything if possible.

**Comment by andrewchambers** [comment]
Yeah, I really like the precedent so far of simple libs that are self contained, it would be nice to keep. The problem comes when I end up with two incompatible sqlite versions in a single application because im using jpm + rust or w.e.

**Comment by andrewchambers** [comment]
@bakpakin Hmm, so in janet-redis I have a linux only semi hack.

**Comment by andrewchambers** [comment]
thinking more, I think this is an issue best dealt with packages themselves, there is the 'meta' problem of shipping a set of functions to facilitate querying the system, so far I have solved that by copy pasting code into each project.janet.

**Comment by andrewchambers** [comment]
Thinking even more, things like autoconf are designed to solve this exact problem, by committing a generated configure script.

Not suggesting we solve the issue like that, but that it can be solved outside of jpm.
