### ISSUE TITLE
printf does not add newline

### ISSUE THREAD

**Issue by Mehgugs** [janet-lang/janet#196]
`printf` should add a trailing newline as the other printing functions which contain `print` do. Perhaps a function `prinf` should be added to keep with the nomenclature?

**Comment by bakpakin** [comment]
This is a simple change that we can add. It will break some code, but so be it, and the fix should be easy.

**Comment by bakpakin** [comment]
I’ve addressed this on the latest master. The change adds both prinf and eprinf, and updates the current variations to print new lines.
