### ISSUE TITLE
indexed? in boot.janet does not consider strings or buffers as indexed.

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#200]
Don't have a stance on this, but I thought I'd bring it to attention as it may be an omission.

**Comment by bakpakin** [comment]
Not an omission. It is to match the C function `janet_indexed_view`, which expects a sequence of Janet values. If you really want to be complete, keywords and symbols can indexed as well.

**Comment by bakpakin** [comment]
Perhaps `(or (indexed? x) (bytes? x))` is what you want?

**Comment by andrewchambers** [comment]
Sure - the main thinking behind making this ticket was that the builtin 'in' function is short for index, but works on all assoc. types , implying all those types are also 'indexed?'. Its a minor inconsistency though, and i doubt it would cause issues.
