### ISSUE TITLE
janet command should handle --help and also reject unknown flags

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#205]
I think handling --help is actually important for new users, for some people that is the first thing they type, and right now that will drop them into a repl unexpectedly.

**Comment by bakpakin** [comment]
This is just a bug cli-main. If a command line arg was seen starting with "-", only the second character was used for the flag, not the rest of the string. This means `--help` was interpreted as `--`, which is a valid flag.

**Comment by andrewchambers** [comment]
thanks :)
