### ISSUE TITLE
Surprising behavior in {string,tuple,array}/slice

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#207]
In python:
```
>>> "hello"[0:-1]
'hell'
```
In janet:
```
>>> (string/slice "hello" 0 -1)
"hello"
>>> (string/slice "hello" 0 -2)
"hell"
```

Note if you grep boot.janet for slice, you will see a few instances of -1 used which seem likely bugs.

**Comment by bakpakin** [comment]
See https://github.com/janet-lang/janet/issues/140. Not a bug, boot.janet is fine.

**Comment by andrewchambers** [comment]
I see, haha, maybe we gotta add a note to the doc string :P

**Comment by andrewchambers** [comment]
@bakpakin would you consider a negative get? I also note that -0 is technically valid in floating point.

**Comment by bakpakin** [comment]
As far as breaking changes go, this one will basically break all code. Also treating -0 differently from 0 is just terrible design. They have the same hash and should be equal.

**Comment by bakpakin** [comment]
As for negative get, I think that's probably an ok addition (not for in). It would defeat some bounds checking for `in`, but for `get` it's probably useful.
