### ISSUE TITLE
Problem with cook/make-native 

### ISSUE THREAD

**Issue by jfcap** [janet-lang/janet#21]
The test `older-than` always fail when f1 or f2 does not exist (which is the case on fresh module build)
```
(defn- older-than
  [f1 f2]
  "Check if f1 is newer than f2. Used for checking if a file should be updated."
  (if is-win true
    (zero? (os/shell (string "[ " f1 " -ot " f2 " ]")))))
```
This simple fix works for me 

```
(defn- older-than
  [f1 f2]
  "Check if f1 is newer than f2. Used for checking if a file should be updated."
  (if is-win true
    (not (zero? (os/shell (string "[ " f1 " -nt " f2 " ]"))))))
```

**Comment by bakpakin** [comment]
Interesting. On my platform (Arch Linux, bash 5.0.0), both version seem to work fine for new builds. I can push a change to fix this, but what platform are you on?

**Comment by jfcap** [comment]
Ok, thanks !
