### ISSUE TITLE
Flag to run script main function with same arguments that jpm binaries expect.

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#211]
It is useful to run scripts directly while developing them to avoid a compilation step, however there is no way to run a main function using the default janet binary in the same way jpm expects a main function.

**Comment by bakpakin** [comment]
Try `janet -l myscriptnoextension -e '(main "arg1" "arg2")'` for now.

**Comment by bakpakin** [comment]
I didn't any new flags, now janet will check for a main function and run it if it exists, so this should work out of the box. If you named something main before at the top level, too bad :(
