### ISSUE TITLE
Pegs need some default patterns bound to keywords

### ISSUE THREAD

**Issue by bakpakin** [janet-lang/janet#214]
It can be tedious to rewrite the same patterns for digits, letters, whitespace, newlines,  etc over and over again. We could bind several common patterns to keywords without needing an explicit grammar to make things easier.

For example, 

```
(peg/match '(some :d) "1234567890")
```

could be used to match a sequence of digits. Currently, this would look something like

```
(peg/match '{:d (range "09") :main (some :d)} "1234567890")
```

Essentially, we would make an implicit outer grammar for use by all grammars. A grammar could overwrite these bindings if they so desired (simply because that's how pegs work right now), but it could make it a lot easier to write compact pegs without a library.

**Comment by pepe** [comment]
I think longer/special keywords would be better, mostly for readability. Like :digits :letters or :.digits :.letters

What do you think?

**Comment by bakpakin** [comment]
> I think longer/special keywords would be better, mostly for readability. Like :digits :letters or :.digits :.letters

For now, I'm only adding the short forms. The main idea here is brevity, and the long forms are not much shorter than the full expressions they replace. It is _very_ easy to add other forms in the future, though.

**Comment by andrewchambers** [comment]
It's also not helpful to claim useful keywords that are likely to occur in a real grammar.

**Comment by pepe** [comment]
Very good points! Thank you.
