### ISSUE TITLE
Amalgamation defaults to .dll native extension

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#215]
This one is a bit tricky to fix, i wonder if we can backpatch the generated core bytecode with a janetconf define...

**Comment by bakpakin** [comment]
Ah, the problem here is that we detect os at compile time, and the amalgamation is build on windows for no particular reason. You can checkout a version that you want and build the amalgamation on non-windows for the correct behavior. I’ll fix this in the next release.

**Comment by bakpakin** [comment]
Should be fixed, all use of `(os/which)` at the top level in boot.janet was removed. Closing.
