### ISSUE TITLE
Compiler arity checks for C functions

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#217]
The compiler is able to check janet functions now, this functionality could be extended to c functions.

**Comment by andrewchambers** [comment]
Extra note:

If the compiler is the one who inserts arity checks and C code can provide arity info
the compiler can just skip arity checks when i knows it is right.

**Comment by bakpakin** [comment]
Closing this as this is unlikely to be added given the current implementation of C functions.
