### ISSUE TITLE
Suggested shorthands for the capi

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#219]
Some shorthand's I think are perhaps missing from the C api that are very common operations.

- Checking if a janet is JANET_ABSTRACT and it's an instance of a specific abstract type, returning the underlying object pointer if it is.
- Checking if a janet is both a keyword, and matches a C string.
- Checking if a janet is both a symbol, and matches a C string.
- Checking if a janet is both a string, and matches a C string.
- Setting a buffer size without initializing the data, because you are about to overwrite it anyway.

**Comment by bakpakin** [comment]
Sorry I didn't get to this sooner. Some of this you can already do.

> Setting a buffer size without initializing the data, because you are about to overwrite it anyway.

`janet_buffer_extra` and `janet_buffer_ensure` might be what you want here. These do require you
to manually update the count field when you are done, though.

> Checking if a janet is both a keyword, and matches a C string

We can add this and the other related functions, but `janet_cstrcmp` is your nest bet for now. It compares an unrapped janet string with a c string, returning 0 if they are the same.

> Checking if a janet is JANET_ABSTRACT and it's an instance of a specific abstract type, returning the underlying object pointer if it is.

Fair point. If you just want to panic if the value is not an abstract, try `janet_getabtract(&myValue, 0, &SomeAbstractType)`
