### ISSUE TITLE
No way to determine if FILE is closed from C api before accessing it. 

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#224]
We can call janet_getfile(janet, &flags),  but once we do so, the definitions of the flags are private to io.c. this means there is currently no safe way to use the FILE returned by janet_getfile .

**Comment by bakpakin** [comment]
I think we can just check if the file has been closed, and return NULL in that case.

**Comment by bakpakin** [comment]
The flag was exposed previously, but the flag names were not. This exposes the flag names.
