### ISSUE TITLE
No way to disable or configure buffering of a FILE

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#225]
Related to #224 , but it would also be nice to be able to just disable the buffer, or set the buffer size from janet code.

**Comment by bakpakin** [comment]
I’m not really sure I want to expose setvbuf or anything like that, as it needs to be called on fresh FILE *s. I think an optional argument to file/open, a size or keyword for sized-buffer/like buffering, would make sense.

**Comment by KrzysztofSzewczyk** [comment]
It could be implemented either as an open flag (e.g. "rwu" - read, write, unbuffered), but the `u` flag needs to be filtered out after the open occurs.

There's also the (way better) possibility of passing third argument to the fopen wrapper signifying the buffer (or `nil` if unbuffered behavior is expected.)

**Comment by andrewchambers** [comment]
I actually think 'setbuf' might be ok. @bakpakin  I guess the reason you must call setvbuf before use is they don't copy any buffered data.

The reason I think a 'setbuf' call is better is so it can be used with stdin/stdout.

**Comment by andrewchambers** [comment]
worth a look: https://git.musl-libc.org/cgit/musl/tree/src/stdio/setvbuf.c

**Comment by KrzysztofSzewczyk** [comment]
setbuf is literally a wrapper over setvbuf, why should we use it? I can't see a gain here.

**Comment by andrewchambers** [comment]
@KrzysztofSzewczyk  I meant, some form of setbuf seems better than having so many constructor functions.

**Comment by KrzysztofSzewczyk** [comment]
setbuf doesn't return the value, so we can't tell whether it succeeded or not.

**Comment by andrewchambers** [comment]
you are missing my point entirely. I never meant setvbuf or setbuf, I just mean some sort of function for setting the buffer.

**Comment by KrzysztofSzewczyk** [comment]
Ah, fine. But changing the buffer after (possibly) there was a write is UB, why would we want it?

**Comment by andrewchambers** [comment]
I think the current C api is sufficient to do this if needed. The janet api can't cover every use case anyway.
