### ISSUE TITLE
I can't make os/execute and os/shell discard stdout and stderr.

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet#238]
I often want to discard stdout and stderr from programs.

**Comment by andrewchambers** [comment]
i have writen two jpm modules to address this:

https://github.com/andrewchambers/janet-process
https://github.com/andrewchambers/janet-sh

**Comment by crocket** [comment]
Can jpm modules be packaged as linux packages? Haskell cabal is specifically built to integrate with linux distributions. I haven't used jpm.

**Comment by andrewchambers** [comment]
Not without you implementing that functionality or sponsoring someone to do it.

**Comment by andrewchambers** [comment]
@crocket To be clear, you can manually build a jpm module, and manually make a linux package.

**Comment by crocket** [comment]
Do janet-process and janet-sh drop stdout and stderr if I don't use them? If stdout is larger than memory and janet doesn't drop it, the computer can run out of memory.

**Comment by andrewchambers** [comment]
If you pass :discard they are written to /dev/null so no memory is wasted. If you use process/spawn with no redirects the file descriptors are shared with the parent and no memory is wasted. If you use process/run and redirect to a buffer, the output is buffered so you need enough memory to hold it.

In the future I will probably add the ability to create a pipe and redirect to that so you can read output line by line if you want, for now that is possible using 'mkfifo myfifo' and (os/open "myfifo") and redirect into that fifo and also read from that fifo.

**Comment by crocket** [comment]
That's good enough.
