### ISSUE TITLE
Support DESTDIR in Makefile.

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet#240]
Because Makefile doesn't support DESTDIR, gentoo linux cannot install it without modification.

**Comment by crocket** [comment]
Forget about this. meson and ninja are the way to go.

**Comment by leahneukirchen** [comment]
Please re-open this, meson e.g. doesnt provide the janet.pc file and is not the default build system.

**Comment by leahneukirchen** [comment]
Just use https://github.com/NetBSD/pkgsrc/blob/5f35ff646609b6f29e317834c5c10fe564c570a8/lang/janet/patches/patch-Makefile ;)

**Comment by bakpakin** [comment]
Thanks for the heads up, should be fixed.
