### ISSUE TITLE
Make it possible to get default JANET_PATH from janet.

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet#245]
I don't want to guess default JANET_PATH in my gentoo linux packages.

I want janet to reveal its JANET_PATH.

**Comment by bakpakin** [comment]
`janet -e '(print (dyn :syspath))'` should do the trick.

This prints the default syspath, which is the value of JANET_PATH janet was compiled with.

**Comment by crocket** [comment]
Are dynamic variables documented?

**Comment by bakpakin** [comment]
Not from in the repl, but the man page for jpm has info on `(dyn :syspath)`

**Comment by bakpakin** [comment]
Typing `(doc)` in the repl will let you see all current dynamic bindings.

**Comment by crocket** [comment]
Cool.
