### ISSUE TITLE
Make it possible to prevent jpm from accessing network.

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet#246]
I don't want it to try to fetch dependencies from the network when it builds janet packages on gentoo linux. To do that, I need an option to prevent jpm from downloading dependencies from the internet.

Linux distribution is going to be responsible for putting dependencies in JANET_PATH.

**Comment by bakpakin** [comment]
Simply don't call `jpm deps`, and nothing will be downloaded for you. If all dependencies are already installed, `jpm build` will work as intended without downloading anything.

**Comment by crocket** [comment]
That's clever. I just call `jpm build` and `jpm install`.
