### ISSUE TITLE
Suggestion: KV api for getting without allocating janet strings.

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#248]
Currently the capi often requires you allocate either a ckeywordv or cstringv before looking up a table entry, when all you wanted to do is lookup a const keyword or string char*. This raises gc pressure more than needed.

**Comment by bakpakin** [comment]
So for keywords (and symbols), creating a an already existing symbol will actually allocate no memory, and therefor not affect GC pressure. Such an API could be added for efficiency, as we need to do essential two lookups in the given use case - one to check if a keyword has already been interned, and one into the table.
