### ISSUE TITLE
multiple definition of `_janet_mod_config' for project depending on both circlet and json

### ISSUE THREAD

**Issue by dfuenzalida** [janet-lang/janet#250]
Hi all, I'm trying to expand on the [littleserver](https://github.com/bakpakin/littleserver/) example to send JSON responses, so I import both `circlet` and `json` at the top of the file (like the last example in the [jpm documentation page](https://janet-lang.org/docs/jpm.html)). It works as expected when running with `janet main.janet`, but I'm getting an error when trying to compile with `jpm build`.

Here's a Gist that contains the source, project file and compilation output: https://gist.github.com/dfuenzalida/ade6f79821e88b05c5014c1e350c90f7

The output of `jpm` is the following:

```
$ jpm --verbose build
generating executable c source...
found native /usr/local/lib/janet/circlet.so...
found native /usr/local/lib/janet/json.so...
compiling and linking build/lserve...
cc -std=c99 -Wall -Wextra -I/usr/local/include/janet -O2 -o build/lserve build/lserve.c /usr/local/lib/janet/circlet.a /usr/local/lib/janet/json.a /usr/local/bin/../lib/libjanet.a -lm -ldl -lrt -lpthread
/usr/local/lib/janet/json.a(json.static.o): In function `_janet_mod_config':
json.c:(.text+0x13f0): multiple definition of `_janet_mod_config'
/usr/local/lib/janet/circlet.a(circlet.static.o):circlet.c:(.text+0xa70): first defined here
collect2: error: ld returned 1 exit status
error: command exited with status 1
  in shell [/usr/local/bin/jpm] (tailcall) on line 224, column 5
  in do-rule [/usr/local/bin/jpm] on line 89, column 5
  in do-rule [/usr/local/bin/jpm] (tailcall) on line 87, column 44
```

I'm using Janet built from sources after cloning the repo, and building the modified littleserver example after running `sudo jpm deps` (no errors there). This issue might be a duplicate of #249 but I wasn't 100% sure.

* Janet version: 1.6.1-dev-0457966
* Platform: Ubuntu 18.04.3 LTS
* C Compiler: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0 (from the `build-essential` package)

**Comment by andrewchambers** [comment]
My first thought is make sure you uninstall and then reinstall the old libs after installing the fixed janet. Don't forget jpm clear-cache too.

**Comment by dfuenzalida** [comment]
Running `sudo make uninstall`, removing the remaining bits on `/usr/local/lib/janet/` then reinstall and run `sudo jpm deps` solved it. Thanks!
