### ISSUE TITLE
Discuss: Protect janet web servers from hash flood attacks

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#253]
http query params, http headers, http form data etc are all DOS avenues against web servers like circlet, halo and pool party workers. The general problem is that crafted input can deliberately cause hash collisions in the builtin table and struct implementation grinding the server to a halt on every table operation.

It seems the standard protection is something like https://en.wikipedia.org/wiki/SipHash which has a public domain implementation we could use.

We could perhaps add a config, or perhaps make it the default depending on performance, to adjust the table hash function to a randomized hash.

**Comment by andrewchambers** [comment]
Nice reference: https://131002.net/siphash/siphash.pdf

**Comment by pepe** [comment]
What about https://github.com/janet-lang/jhydro hashing?

**Comment by andrewchambers** [comment]
The hash function for things like hash tables have different characteristics than the hash functions in libhydrogen.

**Comment by pepe** [comment]
:+1:

**Comment by bakpakin** [comment]
I think this is an ok addition for the language, as hashes for strings, symbols, and keywords are cached, and it certainly seems to be more secure than the current state of things. I think a red-black tree implementation would be good though for this kind of thing. Some kind of janet-datastructures package would be good, for when a very specific data structure is required.

**Comment by andrewchambers** [comment]
Oh I see what you mean, theres no reason the web server needs to return use a normal janet table.

**Comment by bakpakin** [comment]
Siphash has been merged as a mitigation against these kind of attacks, and can be disabled via `JANET_NO_PRF` in janetconf.h

**Comment by andrewchambers** [comment]
Nice, when I get time i will try to get a patch that initializes it in the main client.
