### ISSUE TITLE
Feedback for peg

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#255]
1. When debugging a large peg, sometimes its really hard to know why a given rule failed. This reminded me of this article on a regex debugger https://eigenstate.org/notes/regex-debug . Not sure if it is applicable, or how a trace/step/debug view into pegs would look. But could be quite neat to step/trace a peg.

2. When developing a large peg, sometimes you want to run subrules by hand to test them, this would be much easier if peg/match and/or peg/compile let you specify the entry rule somehow. 

This is possible, though sort of verbose using :
```
(peg/match (freeze (merge large-g {:main ...})))
```

**Comment by bakpakin** [comment]
For testing a subpeg, why not `(peg/match (bigpeg :subrule) "...")`? That should help, I think. If you are compiling the peg ahead of time, the names of given rules is removed at compile time. I don't think it's needed to include that information in the compiled peg, but I suppose it could be useful for debugging.

As for tracing pegs, I think that would be a neat idea. At least, we could show the disassembly in a nice format so people could hopefully understand a bit about what is happening. Stepping maybe harder, but is not out of the realm of possibility.

**Comment by andrewchambers** [comment]
```(peg/match (bigpeg :subrule) "...")``` doesn't work becaues it only extracts the rule key, but not any subrules this rule depends on.

**Comment by sogaiu** [comment]
It's not complete yet, but I've been working on an implementation of `peg/match` in Janet: https://gitlab.com/sogaiu/margaret

It started out as bakpakin's code from [his PEG blog post](https://bakpakin.com/writing/how-janets-peg-works.html) and is evolving from there.

In the process I have started adding a little bit of tracing output.  If it appropriately supports enough of the native version's constructs, may be it could be useful for debugging some PEGs?

(It doesn't quite have enough of the specials to manage the Janet grammar on the website, but I'm hoping to get there soonish.)

**Comment by bakpakin** [comment]
Closing this for now - the original peg debugging script should work correctly.
