### ISSUE TITLE
Discuss: Provide own JANET_FILE instead of stdlib FILE.

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#260]
Pros:
  - Avoid double indirection inherent in FILE api.
  - Ability to implement file/setbuf sensibly.
  - Remove need for file locking.
  - Potentially more accommodating to async.
  - Potentially more accommodating to O_CLOEXEC.

Cons:
  - Implementation complexity.
  - May not be able to accommodate all platforms.
  - The exposed api already references FILE objects as janet_getfile.

Mitigations to cons:
  - We could potentially provide a fallback implementation in terms of FILE.

What do you guys think? Is it a bad idea?

**Comment by pepe** [comment]
I am afraid cons > pros in this case

**Comment by bakpakin** [comment]
Probably not going to happen, closing.
