### ISSUE TITLE
Add more convenient keybindings to REPL

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet#264]
I read [GNU readline](https://en.wikipedia.org/wiki/GNU_Readline) to figure out what key bindings I was missing from [rlrepl](https://github.com/andrewchambers/janet-rlrepl). It's not wise to implement every key binding from GNU readline, but there are some useful key bindings.

* What works, or what is not needed.
  * Ctrl-f and Ctrl-b work fine.
  * Ctrl-y(yank) is not necessary for a minimal REPL.
  * Ctrl-u works fine.
* What doesn't work as expected
  * Ctrl-j on built-in REPL acts differently from Ctrl-j on rlrepl.
* What doesn't work and is desired.
  * Ctrl-k acts weirdly on REPL.
    * Ignore it, or implement it as deleting the line after the cursor.
  * Ctrl-n and Ctrl-p feel more convenient than down arrow and up arrow.
  * Ctrl-w currently doesn't delete a word before the cursor.
  * Alt-d currently doesn't delete a word after the cursor
  * Alt-b currently doesn't move the cursor backward one word.
  * Alt-f currently doesn't move the cursor forward one word.

Another problem is that unused modifier key bindings like `Ctrl-w` insert invisible characters that ruin the REPL.

**Comment by bakpakin** [comment]
Most of these issues should be addressed in the latest master, especially handling of unknown combinations.

**Comment by crocket** [comment]
* I like how `Ctrl-u` on built-in REPL combines `Ctrl-u` and `Ctrl-k` on rlrepl.
* Ctrl-w works differently from rlrepl, but I like built-in REPL's behavior of Ctrl-w better.
* Every keybinding on the issue seems to have been addressed.
* You added `Alt-,` and `Alt-.`. `Alt-,` seems to work fine. `Alt-.` seems to give me an empty line.

**Comment by bakpakin** [comment]
Closing for now. GNU readline has many features and keybindings, all of which we probably shouldn't re-implement.
