### ISSUE TITLE
Calling the same Janet function multiple times from C efficiently ?

### ISSUE THREAD

**Issue by jfcap** [janet-lang/janet#28]
Is there a better way to call a janet function from C when the same function is called multiple times in a loop?

For example this (naive ?) code is working 

```C
static Janet num_vector_ctransform(int32_t argc, Janet *argv) {
  janet_fixarity(argc, 2);
  Janet jarg[2];
  JanetFunction * fun=janet_getfunction(argv,0);
  num_vector * vector = (num_vector *)janet_getabstract(argv,1,&num_vector_type);
  size_t i;
  jarg[2]=argv[1];
  for (i=0;i<vector->size;i++) {
    jarg[0]=janet_wrap_number(vector->data[i*vector->stride]);
    jarg[1]=janet_wrap_number(i);
    vector->data[i*vector->stride]=janet_unwrap_number(janet_call(fun,3,jarg));
  }
  return argv[1];
}
```

... but seems rather "inefficient".

If I compare (basic benchmark) this to the "equivalent" janet function (vector/get, vector/set are cfuns)

```lisp
(defn vector/transform [f v]
  (def size (vector/size v))
  (var i 0)
  (while (< i size)
	 (vector/set v i (f (vector/get v i) i v))
	 (++ i))
  v)
```

the C version is running more than 2 times slower that the janet version (for "big" vectors) ...

I suspect that all the operations behind janet_call may be probably simplified (or not repeated) in such a case ...
(something like "using the same fiber" multiple times in the loop ? ...)
My lack of deep understanding of janet vm prevent me to go further without help ... 

Sorry to bother you with such question.
What bothers me here is not really "performance"  but I just want to better understand janet and avoid writing really "stupid code".

Side question : Is there a better way to ask such question than opening a "issue" ?

Thanks in advance.

**Comment by bakpakin** [comment]
> Side question : Is there a better way to ask such question than opening a "issue" ?

Check out the [#janet IRC channel on freenode](https://webchat.freenode.net/)

---

Janet currently does have a bit of overhead going from C to Janet. This will shrink in the future but may never disappear entirely. When calling a Janet function from C, via janet_call, the vm needs to do some bookkeeping for safety reasons.

* Create or reuse a fiber with the function.
* Use setjmp to catch errors so resources aren't be leaked.
* Update global state to point to the new fiber, mark it as a gc root, etc.
* Enter the VM via the funciton run_vm in vm.c

Altogether, this accounts for some overhead. In the future, I plan on adding a pool for fibers so creating
new fibers will be very fast and is often just reusing old fibers. There are other optimizations that I have been considering that would also remove the need for some of these steps, such as having janet_call run on the current fiber and not create a new fiber at all. This can be difficult, however, as we want to prevent any possibility of resource leaks when extending the vm.

For now, I would not worry about the overhead as it should improve, and just stick to janet_call. I think there is a lot of room to improve the overhead without changing the API. There is also the function janet_continue which lets one resume a fiber, and janet_fiber_reset, which lets you take an old fiber and reinitialize it with a new function. These will be much less convenient than janet_call, though.

Other notes:

`janet_unwrap_*` do not check the type of their arguments. Use

```c
if (janet_checktype(val, JANET_NUMBER)) {
  /* is a number */
} else {
  /* is not a number */
}

```
to check if val is actually a number. The `janet_get*` functions check their arguments and provide nice error messages.

**Comment by jfcap** [comment]
Thanks you for your detailed response.

**Comment by honix** [comment]
Sorry, I don't like irq as it doesn't save message history. I would better prefer use issues for this kind of questions.

**Comment by bakpakin** [comment]
Perhaps a mailing list would be better?

**Comment by bakpakin** [comment]
I guess issues work for now, but I’m not sure that discussion is what github intended them for. Keeping everything centralized on github is convenient though. Perhaps a chat service like gitter would work too.

**Comment by honix** [comment]
Gitter seems a good choice.

**Comment by bakpakin** [comment]
I have started a Gitter channel [here](https://gitter.im/janet-language/community), hopefully this is easier than IRC.

**Comment by jfcap** [comment]
Indeed it's really faster.
My basic benchmark show a ~6X speed improvement !

Now the C version of transform function is 3 times faster then the janet version.
Well done.
