### ISSUE TITLE
How to define C functions under a prefix/namespace?

### ISSUE THREAD

**Issue by PaulBatchelor** [janet-lang/janet#283]
I'm finding myself in a situation where I want to use the API to define a list of Janet C functions under a unified prefix/namespace, like what you can do with the plugin API with something like `(import)`.

I'm currently using `janet_cfuns` to load up said C functions under a given prefix. Looking at the code, it seems like the actual definition uses the local name (sans prefix) and not the "longname". I assume there's a reason for doing it this way:

https://github.com/janet-lang/janet/blob/master/src/core/util.c#L417

Right now, my solution to this is just to write in the prefix manually (this seems to be what has been done for the core library). However, I'm interested in a more elegant solution, if there is one.

Hope this makes sense. Thanks in advance!

**Comment by pepe** [comment]
Hello, not sure I got it right, but you mean something like https://github.com/good-place/tahani/blob/298b71e7447e500787ff2e0f6e416216006fc6e2/tahani.c#L542 ? If not feel free to ignore :-)

**Comment by PaulBatchelor** [comment]
@pepe Close I think? The key difference is that I'm not exactly using the plugin API. Instead of loading a shared object file, I'm embedding everything into one statically linked executable. When I do this, making the call to `janet_cfuns` would not append the "tahani" namespace by default.

**Comment by pepe** [comment]
I am sorry, but I do not understand it fully. I am hopeless C noob :-(

**Comment by PaulBatchelor** [comment]
No worries. The help is still very much appreciated.

**Comment by kiran-kp** [comment]
Was looking for a solution to this as well and found janet_cfuns_prefix from commit fbe903b27712.

**Comment by PaulBatchelor** [comment]
okay this works!  Thanks @kiran-kp for spotting that new feature.
