### ISSUE TITLE
Unknown symbol name

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#288]
With the latest Janet, I am having an issue with symbol name printing from the compiler:

```
➜ janet
Janet 1.7.1-dev-meson  Copyright (C) 2017-2020 Calvin Rose
janet:1:> a
compile error: unknown symbol 4.65795e-310 while compiling repl
```

Sorry for being an everyday complainer :-)

**Comment by bakpakin** [comment]
This is probably related to the changing of janet_formatc, which effects janet_panicf and related functions.

**Comment by pepe** [comment]
Thank you. I will try to look at it.
