### ISSUE TITLE
test failure under Windows 10 on ARM64

### ISSUE THREAD

**Issue by soapdog** [janet-lang/janet#290]
I've managed to compile Janet for Windows 10 on ARM64 by tweaking the `build_win.bat` a bit (so it would copy the VC redist dll). Everything appears to go fine and the resulting binaries are all `aarch64`. When running the test suite, two tests from suite 0 fail:

~~~~
✘  nan key struct ctor

✘  nan key table ctor
~~~~

All the other tests from the other suites pass. Is there any way for me to help debugging this? I have zero experience with Janet, I was just playing around.

**Comment by bakpakin** [comment]
This isn’t really a problem with Janet code, it is probably a problem with C. Janet disallows nil and NaN as keys in tables and structs. The test just tries to construct a table with a NaN key, expecting that the invalid key is ignored. There are a couple assumptions here that may not hold on aarch64 - one is that (/ 0 0) gives NaN, which I think should be the true. The relevant file I guess is src/core/table.c, line 190. This is supposed to ignore NaN keys, but somehow is not.

**Comment by bakpakin** [comment]
Closing as being unable to repro.

**Comment by soapdog** [comment]
@bakpakin,

Sorry for the delay, I found the problem. 

From what I understand, Windows on ARM is Win64 but not x64. The way that the macros work, is that they check to see if it is Win64 and if so they define JANET_NANBOX_64. I don't think JANET_NANBOX_64 is compatible with Windows on ARM64. If I comment it out, rebuild and run the tests again, it all works out.

So I have just sent a PR #454 that makes sure that JANET_NO_NANBOX is defined for ARM targets. With this in place Janet passes all tests on Windows on ARM64.
