### ISSUE TITLE
match hole marker?

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#293]
This behavior is unique and handy:
```
(match [123 345]  [a a] true _ false) => false
(match [123 345]  [a b] true _ false) => true
```

However I wonder if its worth while to have a 'hole' symbol for ignored values. e.g.

```
(match [123 345]  [a a] true _ false) => false
(match [123 345]  [_ _] true _ false) => true
```

I understand this may be confusing and don't mind it being rejected, the current work around is something like:

```
(match [123 345]  [_1 _2] true _ false) => true
```

**Comment by bakpakin** [comment]
This has been added in d3b9b8d4528e45d3f59636656351ad545d26a94b and d3b9b8d4528e45d3f59636656351ad545d26a94b, closing.
