### ISSUE TITLE
Documentation/Semantics: loop :down

### ISSUE THREAD

**Issue by leahneukirchen** [janet-lang/janet#299]
The documentation for loop is a bit imprecise:
```
  	:down - Same as range, but loops in reverse.
```

However,
```
janet:1:> (seq [i :down [10 0]] i)
@[10 9 8 7 6 5 4 3 2 1]
```

I kinda expected I need `[0 10]` first ("same as range"), so this could be clarified.

Also, I wonder if it should not be inclusive actually, because counting down from n to 0 requires the awkward `i :down [n -1]`.

**Comment by leahneukirchen** [comment]
Still a bit rough, but maybe:
```
 	:down - loop over a range, stepping downwards. The object should be two element tuple with a start and (exclusive) end value, and an optional (positive!) step size.
```

**Comment by leahneukirchen** [comment]
For the record, Ruby's `.upto`/`.downto` and Common Lisp `from X to Y`/`from X downto Y` are all inclusive.

Perhaps `upto` could be inclusive, and keep `range` as is?

**Comment by bakpakin** [comment]
Maybe a :range-to and :down-to to be more consistent with names; either way, I think adding fully inclusive ranges to loop makes sense. I'll also use your docstring for :down as well.
