### ISSUE TITLE
Missing POSIX functions: os/readlink, os/getpid

### ISSUE THREAD

**Issue by leahneukirchen** [janet-lang/janet#303]
Wrappers for readlink and getpid can be useful for all kinds of programs.

Probably os/stat should also have a os/lstat equivalent.

If you think this is useful, I'll try writing these myself.

**Comment by andrewchambers** [comment]
Note that POSIX is not the goal as windows and other operating systems should be supported. That being said, I think most operating systems do have links and pids.

@leahneukirchen I think we should make a posix jpm module if what you really intend is to support posix.

**Comment by bakpakin** [comment]
Closed by #319
