### ISSUE TITLE
Footgun or bug? numeric comparison

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#305]
```
(>= (int/s64 0) 10)
true
(>= 0 10)
false
```

**Comment by bakpakin** [comment]
See #272

**Comment by andrewchambers** [comment]
For context, I hit this because my postgres library sometimes returns int64 if the column type is  large values, e.g. "select count(*)" 

Its possible to work around by using casts and being careful or using postgres casts.

**Comment by bakpakin** [comment]
We may want to bring the order functions back for this purpose. The problem is, this also involves an overloaded equality operator, and we may want to bring back the distinction between = and ==, which means that code that uses = will still not always work as expected.

**Comment by andrewchambers** [comment]
I see, like python 'is' or vs '=='.

**Comment by andrewchambers** [comment]
I'll close this and rename the old issue.
