### ISSUE TITLE
readme USE sentence is confusing

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#308]
"Janet makes a good system scripting language, or a language to embed in other programs, like Lua or Guile."

I don't think this reads quite right - it makes it sound like you would embed Janet within a Lua or Guile program.

What about:

Janet makes a good system scripting language, or a language to embed in other programs, similar to Lua or Guile.

**Comment by andrewchambers** [comment]
I'm not convinced using a synonym resolves the ambiguity. I think it needs some sort of additional qualifier.

**Comment by ahungry** [comment]
Janet is  good option for scripting or embeddable language needs (it fulfills the same use cases as other languages in that realm, e.g. Lua or Guile).
