### ISSUE TITLE
Discuss: kwargs inferior to normal destructured table?

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#309]
Consider this:
```
(defn foobar [&keys {:a a :b b}] ...)
(foobar :a 123)
```
```
(defn foobar [{:a a :b b}] ...)
(foobar {:a 123})
```
The first style of kwargs actually seems less composable to me:

Consider the use case of forwarding args:
```
(defn bar [t]
  (foobar ;(flatten (pairs t)))
```
To do the same to the second form, you just need:
```
(defn bar [t]
  (foobar t))
```

If you consider the use case of options:

```
(fn foo [a b &keys options
  (default options {...})])
(foo a b :option 123)
```
```
(fn [a b &opt options
  (default options {...})])
(foo a b {:option 123})
```
I'm again, not really sure of the benefit of &keys.

So my point of discussion:

When is the first style keyword argument better than simply destructuring a table? One thought perhaps is order of argument evaluation is guaranteed with the first form. Otherwise, I can't see much upside.

**Comment by andrewchambers** [comment]
So after more consideration, one use case of &keys is subjectively nicer.

```
(foobar
  :opt-a a
  :opt-a a
  :foo (fn [] ...))
```

```
(foobar {
  :opt-a a
  :opt-a a
  :foo (fn [] ...)})
```

**Comment by bakpakin** [comment]
The point of &keys is just to make it possible to write functions that are shorter. I don't think there is much need to remove it - there maybe some cases where it is desired, and if you don't want to use it, don't.
