### ISSUE TITLE
closure env gc references are very conservative

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#314]
Currently if a closure references a parent env, it keeps all values alive, even values the closure does not reference. I wonder if we can make this more accurate.

One way would be for each FuncDef to have a bitset of referenced upvalue indicies for each environment index. I think that this will allow the garbage collector to skip env values a function cannot possibly be referencing.

**Comment by andrewchambers** [comment]
I am realizing this may interact with marshal/unmarshal in unexpected ways.

**Comment by andrewchambers** [comment]
@bakpakin  This issue has hit me again for a different reason, I am unable to marshal a closure that was created with the current fiber, as it is alive still.

I may be technically uneducated to the issues, but I imagine the compiler needs to treat variables that have been closed over the way way top level vars are treated to resolve this completely.

**Comment by bakpakin** [comment]
Should be mostly fixed in b0d8369534c12853aaf36958ffd042d4634fef19, which is a rather large commit that adds a bitset per FuncDef to keep track of which slots can be referenced as upvalues by other closures. This means we can marshal more closures without pulling in many unneeded references.

**Comment by andrewchambers** [comment]
Nice! thank you so much.

**Comment by andrewchambers** [comment]
I think we can close it, I know multiple overlapping closure still keep an env alive, but that might be as good as we are going to get with the current design constraints.
