### ISSUE TITLE
jpm test does not detect segfaults

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#316]
```
$ jpm test
running test/hermes.janet ...
All tests passed.
```

```
janet ./test/hermes.janet
Segmentation fault (core dumped)
```

**Comment by Duncaen** [comment]
`os/execute` always returns `WEXISTSTATUS`, not sure what the best way would be to return the signal if the process was killed by one.

My first idea was to return `-signal` and the exit status as is.

As alternative  maybe a new flag that makes the return value a tuple of `[status signal]` to allow scripts to handle terminating signals only if they are interested in it and otherwise just return `-1` if there was no exit status.

```patch
From 1722aabb8385d088af752be360f35a38ed99a32d Mon Sep 17 00:00:00 2001
From: Duncan Overbruck <mail@duncano.de>
Date: Tue, 17 Mar 2020 12:59:01 +0100
Subject: [PATCH] return the -SIGNAL if os/execute child did not exit

---
 src/core/os.c | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/src/core/os.c b/src/core/os.c
index 5a674ae..3249710 100644
--- a/src/core/os.c
+++ b/src/core/os.c
@@ -401,7 +401,11 @@ static Janet os_execute(int32_t argc, Janet *argv) {
     }
 
     os_execute_cleanup(envp, child_argv);
-    return janet_wrap_integer(WEXITSTATUS(status));
+    if (WIFEXITED(status))
+        status = WEXITSTATUS(status);
+    else if (WIFSIGNALED(status))
+        status = -WTERMSIG(status);
+    return janet_wrap_integer(status);
 #endif
 }
 
-- 
2.25.1
```

**Comment by Duncaen** [comment]
Another alternative is would be to do what POSIX shell does, but its not really useful and any exit status > 128 is ambiguous.

> The exit status of a command that terminated because it received a signal shall be reported as greater than 128.

The shells (dash in this case) implement:
```
    if (!WIFEXITED(status)) {
#if JOBS
        retval = WSTOPSIG(status);
        if (!WIFSTOPPED(status))
#endif
        {
            /* XXX: limits number of signals */
            retval = WTERMSIG(status);
#if JOBS
            if (retval == SIGINT)
                job->sigint = 1;
#endif
        }
        retval += 128;
    }
```

**Comment by andrewchambers** [comment]
I think doing what most shells do is probably fine. Once you start needing to deal with those signals, another library is probably warranted.

**Comment by bakpakin** [comment]
Agreed, emulating shell behavior here makes sense, although I also like the negative return value for signals. I would rather not add a new flag value.
