### ISSUE TITLE
os/link documentation implies symlinks are the default, this is not the case

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#323]

**Comment by ahungry** [comment]
Hmm

```
       (doc os/link)


           cfunction

           (os/link oldpath newpath &opt symlink)

           Create a symlink from oldpath to newpath. The 3 optional paramater
           enables a hard link over a soft link. Does not work on Windows.
```

Parameter has a typo in it.  

For functions that do not work on an OS as this note mentions, would it be better to have namespaced os?  like `os.posix/link` or `os.linux/link`?

**Comment by andrewchambers** [comment]
Now we are stuck with the unfortunate reality that os/link and os/readlink don't work together.

**Comment by andrewchambers** [comment]
@bakpakin If you wanted to invert the behavior its somewhat possible to do so like this:

```
(os/link x) -> symlink
(os/link x false) -> hardlink
(os/link x true) -> symlink
```

This only breaks the case where the user did not specify explicitly. I would argue there is a higher chance we are fixing a bug than breaking code.

**Comment by andrewchambers** [comment]
I think you convinced me via gitter, breaking this is not a good idea.
