### ISSUE TITLE
What happens when jpm install pulls in remotes with files of the same name?  

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#325]
Given I pull in a repo as such:

```sh
mkdir /tmp/janet-project && cd /tmp/janet-project && mkdir deps
jpm --modpath=$PWD/deps install https://github.com/ahungry/janet-code
```

You can see in deps/ the files I had defined in my janet-code project.janet file are present as top level/not namespaced (various .so / .a / .janet) files.

If I then repeat the jpm install step pointed to a different repository with similarly named files, would they conflict in some way?

**Comment by bakpakin** [comment]
Yes, they will conflict. Jpm doesn’t do conflict resolution at all right now, the idea being that it is really stupid and simple to understand. jpm install just puts all artifacts (.janet and .so files) in the syspath as laid out in your project. jpm deps just runs jpm install for all dependencies recursively.

I recommend putting submodules into a folder that is the name of your git repo, such that they have a unique module name. Also keep in mind a single repo can install as many unrelated modules as it likes - there is no need for the one repo -> one module correlation.

As for reproducible builds, jpm is, err, not there yet. I would like to add lock files at least. I also don’t plan on support for allowing multiple versions of the same package to be installed. 

In light of all this, recommendations/opinions are:
  - don’t rely on too many transitive dependencies that you don’t control - this is usually just good software engineering practice. 
- for your own code, don’t break things up into many micro repos, this increase the size or your depend your graph, which means more chances to break, as we don’t really have semantic versioning. I think some of the original janet packages were in err here.
- use relative imports for submodules in your project. Janet should have good support for them. Relative paths are a form of name spacing that is built into filesystems, so we should just use them.

**Comment by bakpakin** [comment]
To elaborate on point 2, you can still make many small, self contained modules, just put them into one repo with one project.janet

**Comment by ahungry** [comment]
Great advice, thank you

**Comment by rduplain** [comment]
For what it's worth, an enthusiastic +1 to @bakpakin's recommendations/opinions.

Note that `jpm` supports any revision in its `:tag` value within project.janet. This allows you to pin to exact versions of dependencies, even when they are untagged. For example:

```janet
(declare-project
 :name "myprojecct"
 :description "Do something useful."
 :license "MIT"
 :url "https://example.com/"
 :dependencies
 [{:repo "https://github.com/janet-lang/argparse.git" :tag "30acacf"}])
```

**Comment by rduplain** [comment]
For what it's worth, an enthusiastic +1 to @bakpakin's recommendations/opinions.

Note that `jpm` supports any revision in its `:tag` value within project.janet. This allows you to pin to exact versions of dependencies, even when they are untagged. For example:

```janet
(declare-project
 :name "myproject"
 :description "Do something useful."
 :license "MIT"
 :url "https://example.com/"
 :dependencies
 [{:repo "https://github.com/janet-lang/argparse.git" :tag "30acacf"}])
```
