### ISSUE TITLE
What do you think about allowing custom language compilations for special characters (quasiquote / splice)?

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#326]
I think a really great janet feature would be allowing "custom" builds, where we could end up with janet flavors.

If I could set in a config.h or by inline redefining some macro character that was used in the C portion of the codebase, like:

```c
#define SPLICE_CHAR '@'
#define QUASIQUOTE_CHAR '`'`
#define COMMENT_CHAR ';'
```

Then I could build a flavor of janet that allowed more traditional lisp-like syntax for working with macros and splicing results.

The primary benefit would be that years-old tooling that tends to work consistently across many lisps (common lisp, clojure, scheme, emacs lisp) would continue to work against a janet file, without necessitating adding many conditionals/if branches in the associated tooling.

It would be even cooler if such a thing were somehow a per-file setting in janet at the read level, so I could start a janet file with something like:

```clojure
(setdyn :READ_TABLE_COMMENT_CHAR ";")

;; This is a janet file with nothing but a single comment
```

**Comment by bakpakin** [comment]
Honestly, hard pass. More specifically, using # as the comment character let’s us handle shebang likes without a special case. I also thing trying to comply with developer tools here isn’t that important to me - I think many tools can be configured to support Janet, not the other way around. Not to mention, Janet syntax is different enough in other ways that I’m not sure this would really solve many issues. Maybe some examples would help your cause?

That said, whatever floats your boat. You can maintain a patch to do what you need here, I see no reason to add a compiler option - this is the beauty of open source. I think a few lines changed in parse.c would do the trick. You also may need to add an exception for shebang lines if a parser has been newly created if you want to do that.

- As for janet being able to parse different files in different ways, as with racket’s #lang directive, this is already some support for this with the module system. You could, for example, register the .lisp extension with a different module loader so you could import from this file. I will not add this support though. I am confident that supporting multiple similar “flavors” of Janet to fit people’s syntactic preferences is not a good idea.
