### ISSUE TITLE
Difficult to manipulate file permissions

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#331]
The current api provides os/chmod and os/stat . But it is currently very difficult to do an operation such as:  "remove user execute bit"

**Comment by bakpakin** [comment]
Really? You can just set the third character of the permission string to “-“ to clear that

**Comment by andrewchambers** [comment]
What idiom or functions would you recommend for that?

**Comment by andrewchambers** [comment]
I think if there were some function like:

``` (string/replace-indicies mode 0 "-" 5 "-") ``` it would be possible. Currently I'm not quite sure how to get the ease of use you get with normal bit masks.

**Comment by Duncaen** [comment]
A function to convert permissions strings to integer would be good, `os/chmod` already accepts it. 

```clojure
(defn permissions-mode
  "Convert a permissions string into a integer mode"
  [str]
  (var mode 8r000)
  (loop [[k v] :pairs str]
    (when (= v ("rwx" (% k 3)))
      (set mode (bor mode (brshift 8r400 k)))))
  mode)

(assert (= (permissions-mode "rwxrwxrwx") 8r777))
(assert (= (permissions-mode "rwxr-xr-x") 8r755))
(assert (= (permissions-mode "rw-r--r--") 8r644))

(assert (= (band (permissions-mode "rwxrwxrwx") 8r077) 8r077))
(assert (= (band (permissions-mode "rwxr-xr-x") 8r077) 8r055))
(assert (= (band (permissions-mode "rw-r--r--") 8r077) 8r044))
```

Additionally a function to turn modes into permission strings, but I don't really see a use for that.

```clojure
(defn mode-permissions
  "Convert a integer mode into a permissions string"
  [mode]
  (def buf (buffer/new 9))
  (for i 0 9
    (def x (brshift 8r400 i))
    (buffer/push-byte buf (if (= (band mode x) x) ("rwx" (% i 3)) (chr "-"))))
  (string buf))

(assert (= (mode-permissions 8r777) "rwxrwxrwx"))
(assert (= (mode-permissions 8r755) "rwxr-xr-x"))
(assert (= (mode-permissions 8r644) "rw-r--r--"))
```

**Comment by bakpakin** [comment]
These would make sense to add to the os module, and especially as we already have some of this functionality used internally in the os module. That said, these functions seem to work perfectly well.

**Comment by andrewchambers** [comment]
A fair compromise haha.
