### ISSUE TITLE
Empty multiline raw strings ignore newlines

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#334]
```
`
a
`
"a"
```
I expected
```
`
a
`
"\na\n"
```

**Comment by andrewchambers** [comment]
This may be intentional, not really sure so raising it here...

**Comment by bakpakin** [comment]
The first leading and trailing new line in backtick strings are ignored, this is intentional.

**Comment by andrewchambers** [comment]
Ok, sorry about that.
