### ISSUE TITLE
Makefile QA issues? 

### ISSUE THREAD

**Issue by oz123** [janet-lang/janet#335]
While packaging janet for gentoo I noticed a few issues with the Makfile:

```
 * QA Notice: pkg-config files with wrong LDFLAGS detected:
 * /usr/lib64/pkgconfig/janet.pc:Libs: -L${libdir} -ljanet -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 -rdynamic

 * QA Notice: The following shared libraries lack a SONAME
 * /usr/lib64/libjanet.so
```

To fix those I had to apply a patch:
```
--- ./Makefile	2020-02-02 06:35:17.000000000 +0100
+++ ./Makefile	2020-03-17 23:14:26.172766381 +0100
@@ -242,7 +242,7 @@
 	echo "Description: Library for the Janet programming language." >> $@
 	$(JANET_TARGET) -e '(print "Version: " janet/version)' >> $@
 	echo 'Cflags: -I$${includedir}' >> $@
-	echo 'Libs: -L$${libdir} -ljanet $(LDFLAGS)' >> $@
+	echo 'Libs: -L$${libdir} -ljanet' >> $@
 	echo 'Libs.private: $(CLIBS)' >> $@
 
 install: $(JANET_TARGET) build/janet.pc
```

And add a flag to ld:
```
-Wl,-soname,libjanet.so.0
```
The fiags re added via: [append-ldflags](https://github.com/gentoo/gentoo/blob/master/dev-lang/janet/janet-1.7.0.ebuild#L21)

I am not a proficient C developer, so there might be a good reason for why you do things you do.
If there is a good a reason, I would be happy to know what it is, so the package that gentoo has isn't utterly broken.
If this is a valid issue, I would be happy to contribute a patch.

Thanks for your work on Janet!

**Comment by bakpakin** [comment]
I think in this case these patches can be merged upstream, I don't think LDFLAGS is needed in libs, that would seem to just be an error,.Also, soname seems not to be included in the shared library during build. You patches look fine, but for compatibility with the current intended soname of the shared library, I would use `libjanet.so.1` instead of `libjanet.so.0` to match Janet's major version.

Thanks for finding these, I can merge these fixes into master if whatever tool you are using to check pkg-config is satisfied with the following patch (it is preferable to not need append-ldflags):

```
--- a/Makefile
+++ b/Makefile
@@ -146,6 +146,8 @@ build/janet.c: build/janet_boot src/boot/boot.janet
 ##### Amalgamation #####
 ########################
 
+SONAME=libjanet.so.1
+
 build/shell.c: src/mainclient/shell.c
        cp $< $@
 
@@ -165,7 +167,7 @@ $(JANET_TARGET): build/janet.o build/shell.o
        $(CC) $(LDFLAGS) $(CFLAGS) -o $@ $^ $(CLIBS)
 
 $(JANET_LIBRARY): build/janet.o build/shell.o
-       $(CC) $(LDFLAGS) $(CFLAGS) -shared -o $@ $^ $(CLIBS)
+       $(CC) $(LDFLAGS) $(CFLAGS) -Wl,-soname,$(SONAME) -shared -o $@ $^ $(CLIBS)
 
 $(JANET_STATIC_LIBRARY): build/janet.o build/shell.o
        $(AR) rcs $@ $^
@@ -228,8 +230,6 @@ build/doc.html: $(JANET_TARGET) tools/gendoc.janet
 ##### Installation #####
 ########################
 
-SONAME=libjanet.so.1
-
 .INTERMEDIATE: build/janet.pc
 build/janet.pc: $(JANET_TARGET)
        echo 'prefix=$(PREFIX)' > $@
@@ -242,7 +242,7 @@ build/janet.pc: $(JANET_TARGET)
        echo "Description: Library for the Janet programming language." >> $@
        $(JANET_TARGET) -e '(print "Version: " janet/version)' >> $@
        echo 'Cflags: -I$${includedir}' >> $@
-       echo 'Libs: -L$${libdir} -ljanet $(LDFLAGS)' >> $@
+       echo 'Libs: -L$${libdir} -ljanet' >> $@
        echo 'Libs.private: $(CLIBS)' >> $@
 
 install: $(JANET_TARGET) build/janet.pc
```

**Comment by bakpakin** [comment]
All that said, even without these changes the package will work fine - the janet executable does not link to the shared or static library, which are only needed for applications that want to embed a Janet runtime.

**Comment by oz123** [comment]
@bakpakin thanks for the speedy response. These changes indeed pass gentoo's QA.
I would appreciate this if these changes are merged.

**Comment by bakpakin** [comment]
Great, updated in 1d0e86212901eb0bee6990a64e90134448c81704

**Comment by leahneukirchen** [comment]
Sorry to harp more on this: the meson build also needs to be adjusted.

And for distributors, I recommend linking against the library.

Void Linux patches both: https://github.com/void-linux/void-packages/blob/master/srcpkgs/janet/patches/dynlink.patch

**Comment by bakpakin** [comment]
@leahneukirchen  Thanks for the patch, I can merge the soname change.

I won't make the executable link to the library, however, unless there is a good reason besides saving disk space, as there is a performance cost.

**Comment by leahneukirchen** [comment]
Note that my patch uses a two digit soname, but you can adjust that easily.

Since we link all binaries as PIE and use bind-now, I don't think there's a performance difference for us.

**Comment by bakpakin** [comment]
I think going forward, and given the last several releases, it might be better to adopt the two digit sonames in the Makefile and meson.build as in the Void Linux patch, as minor versions make API and ABI breakages.
