### ISSUE TITLE
LSP Implementation

### ISSUE THREAD

**Issue by rafaeldelboni** [janet-lang/janet#342]
Is LSP in the roadmap of the language somehow or a known implementation in development?

**Comment by andrewchambers** [comment]
None that I am aware of, I don't think anyone objects to one, just nobody I have seen worked on it.

**Comment by bakpakin** [comment]
Closing as this is the wrong place for this. Better suited for a separate library or https://github.com/janet-lang/spork

**Comment by sogaiu** [comment]
FWIW, [initial work by @JohnDoneth](https://github.com/JohnDoneth/janet-language-server) was [extended and developed further by @CFiggers](https://github.com/CFiggers/janet-lsp).

There is some further info in [this discussion item](https://github.com/janet-lang/janet/discussions/1305).
