### ISSUE TITLE
Getline arity

### ISSUE THREAD

**Issue by kurayama** [janet-lang/janet#346]
`getline` is being [documented](https://github.com/janet-lang/janet/blob/master/src/core/corelib.c#L647) as having 3 optional arguments, but in the [implementation](https://github.com/janet-lang/janet/blob/master/src/core/corelib.c#L438) the max arity is 2.
The function works due to [a replacement](https://github.com/janet-lang/janet/blob/master/src/mainclient/shell.c#L991), but I've found that when calling `repl` from a different thread while using `jaylib`, the original function is called and throws the following error:

```
in thread <core/thread 0x7FE18140E510>: error: arity mismatch, expected at most 2, got 3
  in getline
  in <anonymous> [boot.janet] on line 2457, column 7
  in run-context [boot.janet] (tailcall) on line 1986, column 5
  in worker [main.janet] on line 9, column 15
```

The same issue was reported by @honix in https://github.com/janet-lang/jaylib/issues/3#issuecomment-591467966

**Comment by bakpakin** [comment]
Thanks for reporting, seems I missed the jaylib mention of it.  Fixed in f5433dcaa4c5db0bc1304ab98832728d8a3a0b26
