### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [janet-lang/janet#35]
Would you like to add more error handling for return values from functions like the following?
- [ftell](http://pubs.opengroup.org/onlinepubs/9699919799/functions/ftell.html "Return a file offset.") ⇒ [cfun_io_fread](https://github.com/janet-lang/janet/blob/b61d1a0a0ec624a3ad6165303687e0921a24c0b5/src/core/io.c#L197)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [janet_memalloc_empty](https://github.com/janet-lang/janet/blob/0726de34ff0b2765d32c064809ced9fae996bd51/src/core/wrap.c#L27)

**Comment by bakpakin** [comment]
Yes, probably a good idea. :+1:

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to [detect every error situation as early as possible](https://github.com/janet-lang/janet/commit/f16100239054b74f6fc52b915c3ea30cde5e558e#diff-4a9cdf8d97c5182252313c7c6887931fL196 "Update candidate")?

-----

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
