### ISSUE TITLE
Proposal: unindent string function/macro

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#356]
I propose something like this:
```

>(do
    (unindent ``
      My file:
        extra-indent
    ``))
"My file:\n  extra-indent"
```

Things I am unsure about:

- If this should be a function or macro or both (unindent* ?).
- What the final name should be, indented, unindent unindented?

I feel like indent adjusted string literals are an underrated feature and incredibly useful for a lot of use cases, (especially text generation). Even jpm might benefit during it's C code generation. Adding to core likely means it will be implemented in C instead of PEG, which may be a performance boon.

**Comment by andrewchambers** [comment]
I'm not incredibly attached this proposal, just putting the idea out there.

**Comment by pepe** [comment]
I think it is a good idea. Not sure it belongs to the core.

**Comment by andrewchambers** [comment]
Hmm, maybe I can make an 'undent' package or something. I suppose I can (use) it.

**Comment by bakpakin** [comment]
Here is how such a macro/function could look

```
(defn undent*
  "Unindent a string"
  [x]
  (def [leading-whitespace] (peg/match '':s* x))
  (def indent (last (string/split "\n" leading-whitespace)))
  (if (and indent (not= indent ""))
    (let [y (string/replace-all (string "\n" indent) "\n" (string/replace indent "" x))]
      # Remove trailing newline to mimic long string newline omission.
      (if (= (chr "\n") (last y))
        (slice y 0 -2)
        y))
    x))

(defmacro undent
  "Unindent a string literal"
  [x]
  (if (string? x) (undent* x) [undent* x]))
```

Not really necessary to have both a function and a macro, but here it is for the sake of efficiency.
```

**Comment by andrewchambers** [comment]
Nice, we can try it out. My main worry is the extra parens and form outweigh the extra code clarity it brings. It would work well with cuddled mode .

**Comment by andrewchambers** [comment]
A data point:

```
(defn init-pkgstore
  []
  ...
          (def cfg
            (string
              "{\n"
              "  :mode :multi-user\n"
              "  :authorized-group \"wheel\"\n"
              "  :sandbox-build-users [\n"
              "    \"hermes_build_user0\"\n"
              "  ]\n"
              "}\n"))

          (spit (string path "/etc/hermes/cfg.jdn") cfg))
```

Becomes:

```
(defn init-pkgstore
  []
  ...
          (def cfg
            (undent `
              {
                 :mode :multi-user
                 :authorized-group "wheel"
                 :sandbox-build-users [
                   "hermes_build_user0"
                 ]
              }
            `))

          (spit (string path "/etc/hermes/cfg.jdn") cfg))
```

**Comment by andrewchambers** [comment]
A weakness to this approach is interpolation doesn't work so well, as the initial undentation is forgotten if you split the string.

**Comment by bakpakin** [comment]
Shouldn’t be hard to make the macro and functions variadic which should solve the problem - interpolate then unindnent

**Comment by pepe** [comment]
I just yesterday found someplace where I was like: where is my undent fn/macro. So I am getting back my previous comment.

**Comment by pepe** [comment]
Closed in 0fe5c67

**Comment by pepe** [comment]
Dedent is a great name BTW

**Comment by andrewchambers** [comment]
I have some concerns with the current form being a runtime construct.

**Comment by bakpakin** [comment]
Closing, as this has been moved out of the core again - I've decided against adding this for 1.9.0.
