### ISSUE TITLE
Array get out of bounds access fails 

### ISSUE THREAD

**Issue by apreiml** [janet-lang/janet#362]
According to documentation and expamles an out of bound access will return `nil`.

I tried the example and it failed:

```
janet:6:> (def arr @[:a :b :c :d])
@[:a :b :c :d]
janet:7:> (arr 100)
error: expected integer key in range [0, 4), got 100
  in _thunk [repl] (tailcall) on line 7, column 1
```

Version: 1.8.1-f7ee8bd

**Comment by bakpakin** [comment]
This has changed on purpose and the documentation needs to be updated.

There are two ways to index into arrays, one is the old behavior and one is the new behavior

```
(arr 100) # -> will error
(in arr 100) # -> equivalent, also will error (in short for index)

(get arr 100) # -> nil
(get arr 100 :default) # -> :default
```

**Comment by apreiml** [comment]
Ok, I can update the documentation if you want me to. But can you explain why you would choose `in` over `get`?

**Comment by bakpakin** [comment]
It gives you the option of doing automatic bounds checking which is often useful - it is essentially like an `assert` with no extra runtime cost.
