### ISSUE TITLE
Code formatter (jfmt?)

### ISSUE THREAD

**Issue by candidtim** [janet-lang/janet#365]
This is a suggestion to add a Janet code formatter to the roadmap (in a same vein as gofmt, black [python], etc.).

**Comment by andrewchambers** [comment]
I'd love one too. Feel free to sponsor it's development to help get the ball rolling.

**Comment by oakmac** [comment]
A while ago there was some discussion in the Clojure community around making such a tool. These links may be useful for research / discussion / ideas here:

- https://clojureverse.org/t/clj-commons-building-a-formatter-like-gofmt-for-clojure/3240
- https://tonsky.me/blog/clojurefmt/
- https://github.com/clj-commons/formatter/issues/9

In particular, I think the suggested approach from Tonsky would work well with Janet.

**Comment by andrewchambers** [comment]
Great news, there is a new formatter library:

https://raw.githubusercontent.com/janet-lang/spork/master/spork/fmt.janet
