### ISSUE TITLE
Doc has issue

### ISSUE THREAD

**Issue by kwccoin** [janet-lang/janet#366]
If run one example in the doc (https://janet-lang.org/docs/syntax.html)  it cannot be run as it is actually lisp function

`janet:12:> @{(1 2 3) (4 5 6)}
compile error: 1 expects 1 argument, got 2 on line 12, column 3 while compiling repl`

just like if you run (1 2 3).

**Comment by bakpakin** [comment]
Yes it cannot be run. However, it can be parsed. There are some situations where you would want to use this form inside of quote, for example.

**Comment by kwccoin** [comment]
My problem is that it is in the first page of really trying the language.  Not a good impression that one see a sample that can’t run.  Bad front page meant a lot to people.

**Comment by bakpakin** [comment]
Again, this is showing data structures, not working code. These forms are technically all valid Janet and can be quoted
