### ISSUE TITLE
Unable to match against tuple with raw symbol

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#367]
```
(match [] ['unquote _] nil)
compile error: unknown symbol unquote on line 13, column 1 while compiling repl
```

**Comment by bakpakin** [comment]
This isn't really a bug, it's just we overload a normal tuple in patterns to attach predicates (which may be surprising - perhaps something like array literals could be used instead).

Without sugar, this is

```
(match []
  [(quote unquote) _] nil)
```
So you are trying to bind `quote` to nil the first element as long as the predicate expression `unquote` is truthy. Which then results in a compilation error.

**Comment by andrewchambers** [comment]
Ah I see, I suspected it was something like this, but it didn't quite click.
