### ISSUE TITLE
Add functions to create uninterned symbols

### ISSUE THREAD

**Issue by kryptine** [janet-lang/janet#368]
`Janet 1.8.1-5b6b9f1 Copyright (C) 2017-2019 Calvin Rose
janet:1:> (def x (gensym))
_000000
janet:2:> (= x '_000000)
true`
Expected: `(= x '_000000)` should return `false`.
Suggestion: Distinguish between interned and uninterned symbols like Common Lisp or attach metadata to symbols so that symbols with the same display string can be unequal if they have different metadata

**Comment by pepe** [comment]
I am not sure why you consider this behaviour incorrect. Can you please elaborate a little?

**Comment by leahneukirchen** [comment]
In Scheme, gensym have no written representation, to avoid clashes.

**Comment by pepe** [comment]
Aha. Thank you very much!

**Comment by bakpakin** [comment]
Although not as strong a guarantee as in Common Lisp, gensyms are guaranteed to be unique from _existing_ symbols. This is sufficient to write hygienic macros.

It would be easy to make gensyms uninterned, though, for more general usage.

**Comment by kryptine** [comment]
@bakpakin In which case you should make uninterned symbols an option to the gensym function for compatibility with existing code.

**Comment by bakpakin** [comment]
That seems like unneeded complexity

**Comment by bakpakin** [comment]
That seems like unneeded complexity. If preserving the old less general behavior was actually important, I would just create a new function. This seems in bad taste to me, though.

**Comment by kryptine** [comment]
@bakpakin No, the new behavior is not more general, it's less general because there are fewer possible implementations of it (it imposes more constraints on implementations). Code already using `gensym` is fine with the current guarantees so there is no need to retroactively interpret it to mean something different.

**Comment by bakpakin** [comment]
In this case, closing, as the current gensym works fine for its intended purpose.
