### ISSUE TITLE
string/slice and Unicode

### ISSUE THREAD

**Issue by candidtim** [janet-lang/janet#369]
`string/slice` appears to be not Unicode-aware - it slices the string as a sequence of bytes. For example:

    (string/slice "aéc" 1 2) 

returns `\xC3` instead of `é`.

Is it an intended behavior or a bug? If it is an intended behavior, is there a Unicode-aware `string/slice` version?

**Comment by bakpakin** [comment]
This is by design. Strings in Janet are byte sequences, not Unicode text. This is simpler,    faster, more robust and more general than abstraction of a sequence of code points.

**Comment by candidtim** [comment]
I understand it. However, there is also a need to be able to interpret them as a Unicode sequence, because otherwise it limits greatly their usage or makes it inconvenient in many scenarios (as in the example above). Would it make sense to add, in addition to the current `string` module, a dedicated set module or a set of functions to support the Unicode-aware text manipulation?

**Comment by pepe** [comment]
For utf-8 there is this small lib https://github.com/crocket/janet-utf8/blob/master/utf8.janet I am using for encoding and decoding. Everything else is just simple algorithms.

I was also sure we need Unicode in the core (as Czech lang has lots of accents), but in the end, I found out I do not. It is easier for me to solve a problem with simple, fast implementation than to have part of the core doing everything. If you have any higher needs, there are several high-quality C libs for Unicode, which would not be that hard to wrap. 

Just my 2 cents tho :-).
