### ISSUE TITLE
Leaking of file descriptors to child processes

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#374]
Currently any use of the thread module can easily leak file descriptors on POSIX systems:

Suppose you have thread one:

```
(while true
  (os/execute "do-work"))
```

And another thread:

```
(while true
  (def passf (os/temp))
  (get-passwd f)
  (def conn (connect-to-database t))
  (slurp "secret-data"))
```

The problem is os/execute calls posix_spawn, while file/temp, fopen and other calls do not open file descriptors with the CLOEXEC flag set, instead setting after a delay it later or not at all..

This combination means secret file descriptors or pipes can be leaked to child processes.

**Comment by andrewchambers** [comment]
Arguably the developer should be aware of this. I mitigate this in my process library by doing a well known hack, attempting to close all open file descriptors after fork.

**Comment by andrewchambers** [comment]
I spoke with some people and apparently fopen might be getting an :e flag to cover this case in a backwards compatible way.

**Comment by leafgarland** [comment]
Commit dc3e9fb breaks the build on mac as `SOCK_CLOEXEC` is unidentified. I guess it could be done using `fcntl` same as #375, which does build on mac.

Also, I think that the `SOCK_CLOEXEC` flag should be used with the `type` argument, not the `protocol` argument to `socket()`?

**Comment by bakpakin** [comment]
@leafgarland Thanks for the fix, but I just moved the fcntl stuff into make_stream.
