### ISSUE TITLE
Duplicate fcntl include

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#377]
https://github.com/janet-lang/janet/blob/79c31397489dd37fa5eaca80a318077a415691d7/src/core/io.c#L36

It seems to me just duplicate.

**Comment by andrewchambers** [comment]
I opened a PR for this.

**Comment by bakpakin** [comment]
PR merged, thanks.

**Comment by pepe** [comment]
I am still afraid to patch C code :-). Thanks @andrewchambers
