### ISSUE TITLE
More flags for significantly non-POSIX systems

### ISSUE THREAD

**Issue by sorenbug** [janet-lang/janet#379]
The three I'm thinking of:
- `JANET_NO_PROCESSES`: No `popen`/`pclose`, `exec`, or `stdin`/`stdout` for systems that do not have the POSIX notion of a process.
- `JANET_NO_MKTIME_UTC`: Already enabled for Solaris, this is for systems that don't have `mgtime`.
- `JANET_NO_SYMLINKS`: Already enabled for Windows, other systems that use FAT/NTFS don't have symlinks.

I've tried to do this myself to get Janet working on the Nintendo Switch but I haven't had much luck doing so safely and correctly. I figured having specific flags for the things I need to disable/panic on would be a better option than putting `#ifndef __SWITCH__` everywhere, but I still can't build/preprocess the Amalgamation for compiling to Switch.

As far as I can understand it, it's neigh-impossible to build the Amalgamation by cross-compiling, especially with [the Makefile rules for Switch](https://github.com/switchbrew/switch-examples/blob/master/templates/sysmodule/Makefile). However, the Amalgamation _itself_ cross-compiles fine if proceses, mgtime, and symlinks are disabled.

**Comment by bakpakin** [comment]
I am a bit confused on why you want to disable panic - do you mean all panics, or just a top-level panic? The former is impossible and unlikely to be supported, the latter certainly could be configurable but is not currently so.

As for adding more configuration options for compatibility, that seems reasonable. Other platforms like UWP would also benefit from these additions.

**Comment by sorenbug** [comment]
Sorry, I didn't make that sentence too clear.

The operations that I want to disable _I think_ should be panicked on, and not fully removed like `REDUCED_OS` makes.

**Comment by bakpakin** [comment]
> The operations that I want to disable I think should be panicked on, and not fully removed like REDUCED_OS makes.

Not sure why you think this is the case - this just in general seems like a great way to postpone errors. This was done in a few places to make generation of certain things easier, but this is something I would like to remove.

Top level panics can be addressed after this patch with JANET_TOP_LEVEL_SIGNAL, which does not need to print to stdout.  However, there are several built inf functions like print, eprint, and debug/stacktrace which access stdout or stderr directly.

**Comment by bakpakin** [comment]
Closing this issue for now - several options have been added, and a separate Makefile variable HOSTCC has been added for cross compilation purposes, along with a few others. This make cross compilation work with the Makefile, although meson is possibly better suited for this.
