### ISSUE TITLE
Default build with debug symbols

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#380]
I think it would be nice if by default makefile and also jpm built with -g debug symbols. Users should be able to strip them after the fact, but leaving them on has some nice results.

- My [where-defined](https://github.com/andrewchambers/janet-where-defined/) module will work in more cases by default.
- Valgrind reports will be more pleasant.
- We may be able to implement a statistical profiler.

**Comment by bakpakin** [comment]
Problems:
- That module only works on GNU compatible compilers, it is not even posix AFAIK.
- Large increase in binary sizes - about +200% for Janet.

The argument that users can strip the symbols afterwards is a bit silly - they can similarly add the symbols in the first place. As for getting locations in C files, I'm not yet convinced this is the best way to go - We can also do things with macros and avoid the overhead of including _all_ debug symbols. For example, prefix function declarations we want to track with a macro that internally uses __FILE__ and __LINE__, which is cross platform.

To build janet with debug symbols, `CFLAGS=-g make` should do the trick. I know in the lisp world it is common to leave debug symbols in programs, but I don't think it should be the default for Janet.

**Comment by andrewchambers** [comment]
> they can similarly add the symbols in the first place.

This is not true, as you currently need to patch every jpm dependency by hand to do this.
