### ISSUE TITLE
Discuss: merge 'jpm load-lockfile' with 'deps'

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#382]
I kind of feel like ``` jpm deps ``` and ```jpm load-lockfile``` provide overlapping functionality. Usually if a lockfile is present, that is what you would want to use. This may be confusing for people not familiar with both commands.

Some ideas:

``` jpm deps ``` - Take from lockfile if present, otherwise install latest.
``` jpm deps --latest ``` - Always take latest that satisfies current project.janet
``` jpm deps --from-lockfile F ``` - Take from a specific lockfile.

**Comment by bakpakin** [comment]
No, this is something I really don't want to add - they are distinct operations and should therefor have distinct commands.In fact, I think using a lockfile for a library is mistake - the lockfile may be useful for CI. Specifically, I don't like the idea of `jpm deps` doing sometimes one thing, sometimes another thing.
