### ISSUE TITLE
jpm needs a way to add -l flags to the end of the link command.

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#387]
Basically annoying C link order stuff means '-larchive' or w.e. must be *after* the .o files. Currently adding -llib to :lflags puts them at the beginning. Some versions of gcc seem to fix the link order themselves, others do not.

**Comment by bakpakin** [comment]
This is addressed with the new :libs option in jpm. Libs are much like lflags, but are now put at the end of the of the command line arguments. 

This is important to distinguish - typical makefiles have LDFLAGS and LDLIBS to distinguish this use case.

Unfortunately this change is slightly backwards incompatible. 

We should probably revise this change for backwards compatibility - such as keeping the old behavior for lflags and making a new option for non library linker flags.

**Comment by andrewchambers** [comment]
Ah ok, I wasn't aware of this change.

**Comment by bakpakin** [comment]
Should be fixed, so closing for now.
