### ISSUE TITLE
Proposal: string/rfind (or findr)?  

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#389]
This operation is actually pretty common, especially for operations trimming paths. A fast path to do it efficiently might be nice.

**Comment by bakpakin** [comment]
There is a hack to do this with pegs and negative lookahead (look behind) - see https://github.com/janet-lang/path/blob/master/path.janet#L11 for an example to extract a file extension.

**Comment by andrewchambers** [comment]
Closing for now.
