### ISSUE TITLE
format string %M inserts "..."

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#390]
```
Janet 1.9.0-dev-a73ba56  Copyright (C) 2017-2020 Calvin Rose
janet:1:> (printf "%M" (macex1 '(with [a b c])))
(do (def a b) (do (def _000000 (...)) (def _000001 (...)) (c a) (if (...) _000001 (...))))
```

**Comment by bakpakin** [comment]
M still limits recursion. Try %.99M

**Comment by andrewchambers** [comment]
Ah I see. Is there a documentation page on all the valid formats and how to use them? I feel like I've learned them in an adhoc way so maybe I missed a doc page.

**Comment by bakpakin** [comment]
Not directly, although since these patterns correspond to janet_panicf, this page has all of the escapes: https://janet-lang.org/capi/writing-c-functions.html
