### ISSUE TITLE
Discrepancy in official grammar.

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#391]
According to https://janet-lang.org/docs/syntax.html a symbol or keyword can contain "|". The grammar states that the symchars consume trailing |.

This is currently not the case in the parser:
```
janet:3:> '(foo|bar)
(foo (short-fn bar))
janet:4:> '[:foo|bar]
[:foo (short-fn bar)]
```

**Comment by andrewchambers** [comment]
This has been resolved.

**Comment by andrewchambers** [comment]
@bakpakin I think it probably also makes sense  to allow | within symbols. Currently : is allowed in symbols for example.

**Comment by bakpakin** [comment]
The difference is the pipe character is analogous to quote, unquote, etc. which are prefix characters and not allowed in symbols. It would be stranger if it was allowed in symbols.
