### ISSUE TITLE
Infinite loop with `:range [0 5 -1]]`

### ISSUE THREAD

**Issue by oz123** [janet-lang/janet#394]
```
:range [0 5 -1]]
```

Calling `(loop [i :range [0 5 -1]] (print i))` results in :
```
janet:19:> (loop [i :range [0 5 -1]] (print i))
0
-1
-2
-3
-4
-5
-6
-7
-8
-9
-10
-11
-12
-13
....
```
Yes, it's my own fault that I "break the rules" the documentation for `:range` is quite clear. Nevertheless, I expect some syntax error and not an infinite loop.

**Comment by pepe** [comment]
It is not a syntax error. But definitely loop's `:range` verb should work same as `(range 0 5 -1)` which returns `@[]` so loop won't run at all.

And you know sometimes infinite loop is what you want :-).
