### ISSUE TITLE
Infinite while loop given certain "and" call in condition plus function literal in body

### ISSUE THREAD

**Issue by jnewman314** [janet-lang/janet#400]
The following results in an infinite loop:
```lisp
(while (and false false)
    (print (fn [] ))
)
```

I would expect this loop not to run at all, but instead it prints an infinite series of functions.

Notes:

* `and false true` doesn't trigger it, but `and true false` does
* It only seems to trigger if the `while` body involves a `fn` literal in some way. Calling out to a `defn`'d function works fine, even if that function uses `fn` literals itself

**Comment by bakpakin** [comment]
Thanks for reporting - this was do to a code path in while loops when the body instantiates a closure - The issue was that the conditional was compiled incorrectly in this case due to a tainted variable that should have been reinitialized. Fixed in 7a84fc4742351d7be33b64bd276d03f43e379499
