### ISSUE TITLE
Odd lifetime of quoted array (compiler constant folding issue or something?  Closure scoping?)

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#404]
```
       (defn copyhelper [x y]
         (if (empty? x)
           y
           (copyhelper (drop 1 x) (array/push y (first x)))))

       (defn copytest [x] (copyhelper x (quote @[])))
       (defn copytest2 [x] (copyhelper x (quote @[])))

       # Same array being mutated each call                                                                                             
       (copytest [1 2 3]) # @[1 2 3]                                                                                                    
       (copytest [1 2 3]) # @[1 2 3 1 2 3]                                                                                              
       (copytest [1 2 3]) # @[1 2 3 1 2 3 1 2 3]                                                                                        

       # A new wrapping defn has caused a new array with same behavior                                                                  
       (copytest2 [1 2 3]) # @[1 2 3]                                                                                                   
       (copytest2 [1 2 3 1 2 3]) # @[1 2 3]                                                                                             

       # However, doing a new fn each time does not cause this - it causes                                                              
       # one single array to be mutated over and over even on different closure                                                         
       # returns                                                                                                                        
       (defn accumulator-factory []
         (fn [n]
           (->> (array/push '@[] n)
                (reduce + 0))))

       (def f (accumulator-factory))
       (f 2) # 2                                                                                                                        
       (f 2) # 4                                                                                                                        
       (def g (accumulator-factory))
       (g 10) # 14   
```

**Comment by ahungry** [comment]
Thanks to the participants in gitter that identified and discussed on this topic tonight

**Comment by pyrmont** [comment]
For ease of future reference, the discussion begins [here](https://gitter.im/janet-language/community?at=5ec349630f31e03a30737a70).

**Comment by ahungry** [comment]
I think the behavior is not intuitive and atypical of most languages to have a persistent lifetime/scope of a variable without being explicit about it in some way, so I assume this is likely an optimization of some inlining vs this being a particular language feature.

I couldn't find any matches on `'@[]` in the janet source (I was trying to see if there was a test case identifying if this was intentional), so I think perhaps a test case should be added in the positive or negative, and if in the positive, perhaps add to the doc repo as what you'd call this feature.

**Comment by bakpakin** [comment]
This is completely intentional and not a bug - the quote form is doing exactly as specified. quote evaluates to exactly its argument, no constructor or reinterpreting happening. In fact, I would consider the “expected” behavior to be a bug, where new arrays are not created. If you quote something, you get that _exact_ value. Changing this behavior would create lots of corner cases and is IMO a bad idea.

**Comment by ahungry** [comment]
The documentation had stated:

```
(quote x)

Evaluates to the literal value of the first argument. The argument is not compiled and is simply used as a constant value in the compiled code. Preceding a form with a single quote is shorthand for `(quote expression)`. 
```

The literal "value" of `@[]` is always `@[]` right?  But in this scenario, it is not - it is evaluating to a literal "place" and the value within the place is being mutated by further actions.

Should the doc be fixed?

**Comment by ahungry** [comment]
literal: " reproduced word for word : exact, verbatim" - doesn't seem very exact to me that the user would see @[], but get @[1 2 3]

**Comment by bakpakin** [comment]
Since arrays are not immutable, they are the same value, even if the content changes, the behavior is the same for buffers and tables. This also matches the equality semantics for these types - two arrays are equal if they have the same location in memory, and that is it.

**Comment by ahungry** [comment]
Thanks for the post-close comment and explanation, I appreciate it

**Comment by bakpakin** [comment]
This is actually par for the course for lisp - the same is true for Common Lisp, although they leave it as undefined behavior. https://stackoverflow.com/questions/23002279/bizarre-quoted-list-example-from-on-lisp. The reasoning here is pretty much the same, although Janet _guarantees_ that the same value will be used.
