### ISSUE TITLE
Cannot build emscripten on macos

### ISSUE THREAD

**Issue by xmclark** [janet-lang/janet#41]
On macos High Sierra,

1. clone repo
2. `brew install emscripten`
3. Restart IDE
4. `make emscripten`

```
➜  janet git:(master) make emscripten
emcc -std=c99 -Wall -Wextra -Isrc/include -O2 -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap"]' -s ALLOW_MEMORY_GROWTH=1 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -DJANET_BUILD="\"44e31ca\"" -o build/core/abstract.bc -c src/core/abstract.c
shared:WARNING: LLVM version appears incorrect (seeing "10.0", expected "6.0")
shared:CRITICAL: fastcomp in use, but LLVM has not been built with the JavaScript backend as a target, llc reports:
===========================================================================
(no targets could be identified: [Errno 2] No such file or directory)
===========================================================================
shared:CRITICAL: you can fall back to the older (pre-fastcomp) compiler core, although that is not recommended, see http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
shared:ERROR: failing sanity checks due to previous llvm failure
make: *** [build/core/abstract.bc] Error 1
```

What should I do next?

**Comment by bakpakin** [comment]
Maybe try removing some flags in the Makefile, like `-s AGGRESIVE_VARIABLE_ELIMINATION=1`. I'm not entirely sure what the problem is, and you may have better luck with emscripten if you get directly from their webpage or via the emsdk rather than homebrew.

**Comment by xmclark** [comment]
Yes it would seem that installing emscripten is a bit more involved 😢 . I will try to see if I can get it working in the next few hours.

**Comment by xmclark** [comment]
I was able to get it working by following the instructions on emscripten website:
https://emscripten.org/docs/getting_started/downloads.html

It builds the wasm which is great! I am going to see if I can get the repl working on [wasmer](https://wasmer.io/).

@bakpakin would you be interested in adding the wasm + js on official janet releases in the future? It would be nice to be able to just download the wasm without building it first.

**Comment by bakpakin** [comment]
Yeah, I'll try to get that working for the next release

**Comment by Zireael07** [comment]
Any word on the official wasm+js release?

**Comment by bakpakin** [comment]
This has been removed from the official build, but works just fine generally - the build system has changed to always build the amalgamated build, which makes using emscripten no more difficult than compilgin an simple emscripten C program. See https://github.com/janet-lang/janet-lang.org/ for en example Makefile that builds an emscripten build. I'm not providing an official emscripten build because there are simply too many ways one might embed Janet into a webpage.
