### ISSUE TITLE
Negative look captures in PEGs

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#412]
When I read the PEG documentation and look at the test suite, it looks to me like I should be able to do something like this:

```
(peg/match ~(* "a" (> -1 "a") "b") "abc")
```

and it should match. It doesn't but this hack does:

```
(peg/match ~(* "a" (not (> -1 (not "a"))) "b") "abc")
```

Is this a bug?

My use-case for this is in my [Musty](https://github.com/pyrmont/musty) library. I have a rule that I want to match if the character before the start of the current index was a newline ([source](https://github.com/pyrmont/musty/blob/e1a821940072a5ae5ddc9d3cb2ae6d1bdba41468/src/musty.janet#L127)). At the moment, I'm using the hack to achieve this.

**Comment by bakpakin** [comment]
Yes, this should be a bug. What's happening here is the look ahead is "moving the cursor" when it shouldn't. The `not` hack fixes it because `not` correctly prevents the cursor from being moved.

**Comment by pyrmont** [comment]
Awesome 👍 Thanks for fixing this so quickly!
