### ISSUE TITLE
When will a stable http/https client be available

### ISSUE THREAD

**Issue by gaberger** [janet-lang/janet#413]
Would love to replace my Clojure/GraalVM native-image CLI tools with Janet but must have a stable http/https client interface

**Comment by statianzo** [comment]
Check out https://github.com/joy-framework/http

**Comment by andrewchambers** [comment]
@gaberger when enough people sponsor it.

**Comment by andrewchambers** [comment]
Or try something like: https://github.com/sepisoad/jurl

**Comment by sogaiu** [comment]
Haven't tried it myself, but there is also: https://github.com/pauldub/janet-http-client

**Comment by bakpakin** [comment]
Closing as there are several options, and this is outside the scope of the Janet language.
