### ISSUE TITLE
meson/ninja build/install doesn't generate a shared library with the `-dev` suffix

### ISSUE THREAD

**Issue by sorenbug** [janet-lang/janet#424]
https://github.com/janet-lang/janet/blob/4077822e37531a36a34ae2a467b888ecb2cc360b/meson.build#L172-L177
```
meson.build:175:0: ERROR: Invalid Shared library version "1.10.1-dev". Must be of the form X.Y.Z where all three are numbers. Y and Z are optional.
```

I didn't know if this was intended behavior, and if not, the recommended fix, so I'm opening an issue for it.

**Comment by bakpakin** [comment]
This should be fixed, this was an error when version bumping. This also failed CI.
