### ISSUE TITLE
When embedding, how to get parse errors?

### ISSUE THREAD

**Issue by cmaughan** [janet-lang/janet#426]
Calling janet_dostring with the following:
(foo 1)
returns error state of DEBUG, and the Janet* out contains 'nil'

Inside the dobytes function there appears to be parser errors, but I'm not sure how they are surfaced to the caller?  There is a 'JanetCompileResult' in there, which contains the correct error, but it is only a temporary.

What is the recommended way of compiling an arbitrary section of janet code and getting an error for what went wrong?

**Comment by bakpakin** [comment]
`janet_do_bytes` is meant to wrap together parsing, compiling, and executing Janet source code. If you just want to parse and compile, you will need to create a parser, parser source code, and then compile it.

```c
#include <janet.h>

const char *src = "(foo 1)";

int main() {

  // parsing
  JanetParser parser;
  janet_parser_init(&parser);
  for (char *c = src; *c; c++) {
    janet_parse_consume(&parser, (uint8_t) *c);
    // Optionally check if janet_parser_status(&parser) == JANET_PARSE_ERROR for parse errors
  }
  janet_parser_eof(&parser);
  Janet ast = janet_parser_produce(&parser);
  
  // compiling
  JanetTable *environment  = janet_core_env(NULL);
  JanetCompileResult result = janet_compile(ast, environment, "name-of-source-file.janet");
  if (result.status == JANET_COMPILE_OK) {
    printf("ok!\n");
  } else {
    printf("error!\n");
  }
}
```

**Comment by cmaughan** [comment]
I can certainly do that, although it feels odd to me that dobytes doesn't just return any and all errors as a result of calling it....

**Comment by bakpakin** [comment]
I have added a fix to return the first error in `*out` as a Janet value (which will usually wrap a JanetString, although not always). If the return status is non-zero, then the returned value is an error, otherwise it is the evaluation of the last form.

In a related note, if you want to disable printing to stderrr, you could do do something like the following now:

```
#include <janet/janet.h>
int main() {
    janet_init();
    JanetTable *env = janet_core_env(NULL);
    Janet ret;
    janet_setdyn("err", janet_wrap_false()); // stderr off
    int status = janet_dostring(env, ")))", NULL, &ret);
    janet_setdyn("err", janet_wrap_nil()); // stderr on
    if (status) {
        janet_eprintf("err: %v\n", ret);
    } else {
        janet_eprintf("ok: %v\n", ret);
    }
    janet_deinit();
}
```

**Comment by cmaughan** [comment]
That looks great to me, thanks :)
