### ISSUE TITLE
Document the C API

### ISSUE THREAD

**Issue by bakpakin** [janet-lang/janet#43]
Janet has a defacto C API defined by all functions exposed in janet.h, but they are not well documented. These functions need to be documented in a way that is readable for people who are trying to embed Janet.

Some options for writing this documentation are Doxygen or handwritten documentation. I'm leaning towards Doxygen for the C API doc, as it does C documentation out of the box and we really only need to make public facing docs for one file, janet.h

**Comment by andrewchambers** [comment]
I have never found doxygen docs good or readable, my 2 cents, copy lua.

**Comment by bakpakin** [comment]
Interesting, thanks for the input. Not that experienced with doxygen, just seemed like a standard for C based projects. A handwritten doc generator would also integrate with the website better.

**Comment by PaulBatchelor** [comment]
I suggest going the more handwritten route as well. In addition to lua, the SQLite approach to API documentation is worth studying as well.

**Comment by bakpakin** [comment]
So there has actually been a good bit of work on this in the last several versions done here. Check [here](https://janet-lang.org/capi/index.html) for more info. Closing this issue, but this doesn't mean docs are done.
