### ISSUE TITLE
Problem with large number precision

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#446]
First off, I noticed on the Janet samples for Rosetta Code factorial, any of them with a factorial of 1e3 would give a return value of "inf" (not correct).

As I began to play with large numbers (I assume these are all floats and not actually ints at all) I observe some logical incorrectness:

     (let [bignum 1000000000000000000000000000000000] (= bignum (+ 1 bignum)))                                                        

       true

a large number that isn't actually "inf" can't be equal to itself + 1
@bakpakin ^ any idea?

       (let [bignum 1000000000000000000000000000000000] (= bignum (+ 1e17 bignum)))                                                     

       false
       (let [bignum 1000000000000000000000000000000000] (= bignum (+ 1e16 bignum)))                                                     

       true

it would appear after some precision point anything afterwards is disregarded, resulting in false comparison results.

I think bignum should be handled in a separate module or package, or baked in for non-float based numbers (no decimal points), or else numbers exceeding the precision that can be properly handled should trigger errors.

What do you think?

**Comment by bakpakin** [comment]
Janet numbers are IEEE754 double precision floating point numbers, and as such follow al of the semantics these numbers obey. Which includes limited precision. This will not change.
