### ISSUE TITLE
janet libpath issue

### ISSUE THREAD

**Issue by nate** [janet-lang/janet#450]
## Description

OS: macOS Catalina 10.15.5

When installing janet via homebrew on macOS (`brew install janet`) I am unable to build a binary.

```
$ cat main.janet
(defn main [& args]
  (print args))
$ jpm quickbin main.janet my-bin
generating executable c source...
compiling and linking my-bin...
clang: error: no such file or directory: '/usr/local/Cellar/janet/1.10.1/lib/janet/libjanet.a'
error: command exited with status 1
  in shell [/usr/local/bin/jpm] (tailcall) on line 134, column 5
  in do-rule [/usr/local/bin/jpm] (tailcall) on line 253, column 26
```

The file `libjanet.a` exists at `/usr/local/Cellar/janet/1.10.1/lib/libjanet.a` but libpath includes an extra path segment.

Homebrew install janet via the mesos+ninja build system and you can see where this path segment gets added on to the libpath here: https://github.com/janet-lang/janet/blob/master/meson.build#L260

The homebrew `jpm` also is already patched with [tools/patch-jpm.janet](https://github.com/janet-lang/janet/blob/master/tools/patch-jpm.janet) and includes the following text, which also shows the incorrect lib path:

```
# Inserted by tools/patch-jpm.janet
(defn- install-paths [] @{:binpath "/usr/local/Cellar/janet/1.10.1/bin" :libpath "/usr/local/Cellar/janet/1.10.1/lib/janet" :headerpath "/usr/local/Cellar/janet/1.10.1/include"})
```

## Workarounds

* symlink `/usr/local/Cellar/janet/1.10.1/lib/libjanet.a` to `/usr/local/Cellar/janet/1.10.1/lib/janet/libjanet.a`
* run jpm with the correct libpath `jpm --libpath=/usr/local/Cellar/janet/1.10.1/lib ...`
* set JANET_LIBPATH env var `JANET_LIBPATH=/usr/local/Cellar/janet/1.10.1/lib jpm ...`

I'm not sure of any secondary effects of changing the libpath so I'm using the symlink solution.

**Comment by bakpakin** [comment]
This seems to be an issue with the meson installation. This is fixed on master and should be fixed for the next release on homebrew.

**Comment by nate** [comment]
Confirmed fixed, thanks!
