### ISSUE TITLE
incorrect use of standard environment variables in Makefile

### ISSUE THREAD

**Issue by slashfoo** [janet-lang/janet#451]
In the makefile, the use of at least two variables MANPATH and PKG_CONFIG_PATH breaks calls to `make` when a defined in the environment and set to a well-formed value as expected by `man` and `pkg-config`.

Please consult `man 1 man` for the mention of MANPATH, and `man 1 pkc-config` for the mention of PKG_CONFIG_PATH. Both of these variables are expected to contain a list of zero or more directories separated by a `:` (colon) in the same way that `PATH` is expected to.

Both of these variables, when defined to a value as expected by the respective software breaks the make of janet, or at least produces unexpected results. Setting these variables to an empty string (which is a valid value) does not solve the problem.

A workaround to this would be to use:
`env -u MANPATH -u PKG_CONFIG_PATH ...`
prefixing the calls to `make`

**Comment by bakpakin** [comment]
These environment variables have been prefixed with `JANET_` to avoid conflict with these standard environment variables. This should hopefully prevent breakages in standard environments.

**Comment by slashfoo** [comment]
Thanks for addressing this so promptly.

Cheers!
