### ISSUE TITLE
Unmarshal bug?

### ISSUE THREAD

**Issue by nate** [janet-lang/janet#452]
https://gist.github.com/nate/a2be972997ca5666374da9d949b37cdc

When running this code I'm getting:

```
janet top level signal - "expected type string, got :>"
janet top level signal - "expected type string, got :>"
janet top level signal - "expected type string, got :>"
janet top level signal - "expected type string, got :>"
janet top level signal - "expected type string, got :>"
janet top level signal - "expected type string, got :>"
```

One message for each thread that spawns, seemingly right at the moment the thread spawns. This code works fine in a single-threaded context, though.

@andrewchambers and I did some debugging of the issue and he thinks it might be an issue with unmarshaling with threads. There's a non-macro version of the `sh` call (`(sh/run* ["git" "-C" dir "pull" :> buf :> [stderr stdout]])`) that also exhibits the issue so it doesn't seem to be related to the macro.

Thoughts on what might be happening?

**Comment by andrewchambers** [comment]
For some more context:

I feel like unmarshal is altering the behavior of janet-sh's internal functions somehow, especially because it works fine without threads.

**Comment by bakpakin** [comment]
Thanks for reporting, the issue seemed to be an error in marshaling files which sometimes corrupted the output of marshal. The given example now works correctly.
