### ISSUE TITLE
spy debugging macro

### ISSUE THREAD

**Issue by thiru** [janet-lang/janet#458]
Hey, not sure if you're open to adding new functions or macros to the core.  One I use quite heavily in Clojure is `spy` (from the Timbre library).  Here's a naive implementation.  I can put this into a pull request if that's easier and you're open to this.

```
(defmacro spy
  "Pretty-print `obj` and return it."
  [obj]
  (with-syms [$evaled]
    ~(let [,$evaled ,obj]
       (pp ,$evaled)
       ,$evaled)))
```

**Comment by andrewchambers** [comment]
There is an equivalent already called tracev.

**Comment by thiru** [comment]
Yes it would in fact.  Thank you!
