### ISSUE TITLE
Meson build issue on Debian

### ISSUE THREAD

**Issue by fancycade** [janet-lang/janet#459]
Hi there! Loving Janet so far. 

Recently I have been running into an issue when building with meson on Debian (only tested on Debian).

```
The Meson build system
Version: 0.49.2
Source dir: /root/janet-1.11.3
Build dir: /root/janet-1.11.3/build
Build type: native build
Project name: janet
Project version: 1.11.3
Native C compiler: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library m found: YES
Library dl found: YES
Dependency threads found: YES 
Configuring janetconf.h using configuration

meson.build:182:0: ERROR:  Tried to access compiler for unspecified language "c".
```
I've been able to work around it by patching the meson.build like so:

```
native_cc = meson.get_compiler('c', native: true)
#cross_cc = meson.get_compiler('c', native: false)
if native_cc.has_argument('-fvisibility=hidden')
  extra_native_cflags = ['-fvisibility=hidden']
else
  extra_native_cflags = []
endif
#if cross_cc.has_argument('-fvisibility=hidden')
#  extra_cross_cflags = ['-fvisibility=hidden']
#else
#  extra_cross_cflags = []
#endif
extra_cross_cflags = []
```

Basically commenting out cross_cc, however this is certainly not ideal, so I figured I would file a bug report.

**Comment by bakpakin** [comment]
What meson version do you have? This seems more to do with the version or configuration of meson that debian ships with, and less to do with Janet. Still, it might be best to target a lower version of meson if debian is shipping something outdated. I can confirm everything builds properly with Meson (version 0.54.3) on Arch Linux, and whatever version is default on OpenBSD, as we test with Meson in the CI.

**Comment by bakpakin** [comment]
Just pushed a fix the should fix the issue as it should be equivalent to your patch when meson.is_cross_build() is false. If it does fix the issue, I think we can close this.

**Comment by fancycade** [comment]
Thanks for taking care of this. Tested it out and it seems to be good to go.
