### ISSUE TITLE
janet build shows error "could not read file"

### ISSUE THREAD

**Issue by strika** [janet-lang/janet#464]
I installed Janet a few days ago. Everything worked fine for a couple of days, but since today I can't build any projects - my own or examples such as [Little Server](https://github.com/bakpakin/littleserver).

I see the following when I run `janet build`:

```
littleserver|master > janet build
error: could not read file
  in file/read
  in chunks [boot.janet] on line 2378, column 24
  in run-context [boot.janet] on line 2147, column 12
  in dofile [boot.janet] on line 2390, column 5
  in cli-main [boot.janet] on line 2850, column 9
```

The REPL is working fine:

```
littleserver|master > janet
Janet 1.11.3-9afcec77 linux/x64
repl:1:> (+ 1 2)
3
repl:2:> 
```
I'm using Pop!_OS, which is based on Ubuntu:

```
littleserver|master > lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

Do you know what the problem could be? How can I provide more information? Thank you.

**Comment by andrewchambers** [comment]
You want 'jpm build' not janet 'build'

**Comment by strika** [comment]
Well... I feel stupid now, but perhaps it's good that this issue exists as a reference for other like-minded people. :smiley: Thank you!

**Comment by andrewchambers** [comment]
Don't feel bad, I've used janet for a while and have definitely made the same mistake.
