### ISSUE TITLE
learn x in y minutes for Janet

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#465]
I'd like to submit an article for Janet to the [learnxinyminutes site](https://learnxinyminutes.com/). Here's what I've written so far:

<http://www.unexpected-vortices.com/janet/learn-janet-in-y-minutes.html>

Would it be ok if I submit that for inclusion there? Any feedback on it? I'm only just learning Janet, and the doc is necessarily brief, as the site is meant for whirlwind/scenic tours of languages, to give quick overviews and whet potential user's appetites.

I just realized I haven't yet added an example of `case` and `when`. I'll have to poke and fiddle around tomorrow to get examples for those.

I see that [rouge](https://github.com/rouge-ruby/rouge) now supports Janet, but I don't know what the [learnxinyminutes processor](https://github.com/adambard/learnxinyminutes-docs) uses.

**Comment by andrewchambers** [comment]
I would consider adding match statements and also different base numbers:

```
# Octal number
8r10 => 8 decimal

# Pattern matching
(match x
  [x _] x
  true :b
  {:bar baz} baz
  (x (number? x)) :number
  _ false)

```

**Comment by sogaiu** [comment]
Nice :)

Some observations follow:

* `var` was mentioned before `def` without explanation, but I suppose that's cleared up soon enough...

* Possibly worth mentioning this style of destructuring?

https://github.com/janet-lang/janet/blob/master/src/boot/boot.janet#L865

* Minor typo: `both foor arrays/tuples` -- may be meant `for`?

* The following bit seems to have 2 errors (delimiter type and closing paren for let):
```
(def t [:a "ahh" :b "bee" :c "sea"])
(let [{:a a :b b} t]
  (print a b) # ahhbee
```
May be you want:
```
(def t {:a "ahh" :b "bee" :c "sea"})
(let [{:a a :b b} t]
  (print a b)) # ahhbee
```
At least, it didn't work for me in the original form :)

* Although one can use `map` to do things like:
```
(map print words)
```
May be the return value would be a bit confusing?

* For case and when, here are a couple of usages:

https://github.com/sogaiu/janet-peg/blob/130374e74686a83e25b963b2ee770744db859615/janet-peg/rewrite.janet#L144
https://github.com/sogaiu/janet-peg/blob/130374e74686a83e25b963b2ee770744db859615/janet-peg/fs.janet#L43

**Comment by uvtc** [comment]
Ok. Thanks Andrew and sogaiu. Made those updates and a few more.

I've temporarily marked the comments with `;` and am using pandoc's Clojure syntax highlighting in my own rendered version (hopefully learnxinyminutes will do actual Janet highlighting).

Could you please have another look and let me know if you spot any errors, omissions, or areas that could be improved?

**Comment by uvtc** [comment]
Ok, went ahead and submitted a PR to learnxinyminutes. Thanks for all the help!

**Comment by uvtc** [comment]
The PR was merged, but there's a problem with the syntax highlighter used by learnxinyminutes and the article is not being displayed. See https://github.com/adambard/learnxinyminutes-docs/issues/4000 .

**Comment by uvtc** [comment]
Closing this because the article is up and readable now, even though it currently uses python syntax highlighting.

**Comment by sogaiu** [comment]
May be this is a link for it?

https://learnxinyminutes.com/docs/janet/
