### ISSUE TITLE
Primed variable names

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#467]
There may be a few things going on here. Maybe a bug as well?

I added my own trailing comments:

~~~
Janet 1.11.3-9afcec7 linux/x64
repl:1:> (def foo 33)
33
repl:2:> foo
33
repl:3:> (def foo' 44)  # I'm intending this to mean "foo prime", `foo'`.
44
repl:4:> foo'
44
repl:5:> foo
foo                  # Wait, what?? I'm expecting 33. Why is it printing the symbol here?
repl:6:> foo
44                   # Wait, why is it a number this time? And why was `foo` touched when I defined `foo'`?
repl:7:> 'foo'
foo                  # Again, it seems to be ignoring the prime (trailing single quote mark).
repl:8:> 'foo
(quote foo)          # Oh, this is different than above... (?)
~~~

Sorry, I think I may be mixing a few potential issues all together in the above.

But is the above intended behavior?

Thanks.

**Comment by sogaiu** [comment]
This looks like a bug to me.

**Comment by bakpakin** [comment]
Nope not a bug. All prefix characters ignore white space and are left associative, so the example means (def foo '1). foo' is not a valid symbol name.

**Comment by sogaiu** [comment]
Thanks for the explanation.

**Comment by andrewchambers** [comment]
Curious that conjoining keywords is allowed `foo:bar`

**Comment by uvtc** [comment]
Ah, ok, thanks. I see. `(def foo' 1)` == `(def foo '1)`, and

~~~
(= '1 1)            # => true
(= '"this" "this")  # => true
(= ':that :that)    # => true
~~~

If when I'm at the repl I type `foo'`, is the repl is then waiting for me to give it an identifier so it can return that symbol to me? That might explain the following weirdness where I get two different results from typing `foo` at the repl prompt:

~~~
Janet 1.11.3-9afcec7 linux/x64
repl:1:> (def foo 1)
1
repl:2:> foo'
1
repl:3:> foo
foo
repl:4:> foo
1
~~~

**Comment by andrewchambers** [comment]
Yes that is right. the repl is rembering the quotation and applying it on the next input.
