### ISSUE TITLE
jpm C++ support

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#469]
I was just playing around and attempted to build a jpm module using C++ source (.cpp). It seems jpm is unable to understand this. 

What are your thoughts on adding support for cpp source files to jpm? I guess I could also make build rules explicitly and manually and link as a library.

**Comment by bakpakin** [comment]
Honestly, it wouldn't be that difficult to add, and I see no reason why we can't.

**Comment by bakpakin** [comment]
Well that seems to work fairly well. I was able to convert a couple of existing libraries to C++ (the json library) and everything worked fine. It should also work to mix C and C++ in a project, as we will use the C++ linker if any C++ is used.

**Comment by andrewchambers** [comment]
Neat! Just noticed a few CI failures btw.

I think C++ support opens a few interesting library options. Some examples might be QT/Wxwidgets and immutable data structures via https://github.com/arximboldi/immer .

**Comment by bakpakin** [comment]
CI failures have been addressed, I'm closing this out for now. This is not to say that C++ integration is done or final, though.
