### ISSUE TITLE
Building modules packaged with Janet does not work when Janet is not installed in system directory

### ISSUE THREAD

**Issue by tekknolagi** [janet-lang/janet#47]
I am trying to build `numarray.c` from the examples, but it tries to include `janet/janet.h` from the system include path. On my system, Janet is installed in `~/.local/`. As far as I can tell, `build.janet` does not support getting exported `CFLAGS`, nor does it read from the `PREFIX`, so I can't get that file to build.

**Comment by bakpakin** [comment]
I think by default, the correct and easiest thing to do would be to use what include path was set while building Janet (it is assumed here that Janet is installed *somewhere*). Janet already has `module/*syspath*`, which is where it looks for global modules. We could also add something like `module/*headerpath*`, which is where it could look for `janet.h`.

**Comment by bakpakin** [comment]
The latest commits should address this problem. We simply put the header in the library path, and the cook tool adds the correct include flag as needed.
