### ISSUE TITLE
Support hyphens in native library names.

### ISSUE THREAD

**Issue by kixus** [janet-lang/janet#470]
# Introduction
Hyphens are a valid characters for naming files on all popular OS filesystems. Hyphens are also valid characters in native binary and native library artifacts on the system as long as the underlying runtime (Janet in our case) is able to load and execute entry-points in such binaries/libraries. 

Hyphens are typically introduced for naming filesystem artifacts to indicate the source organization/domain/team that publishes such an artifact, along with the name of the destination artifact.  E.g. `mycom-mygreetlib.so` immediately indicates to the system administrator that the company `MyCompany` (with abbreviation `mycom`) has chosen to install its `MyGreet` library (as  `mygreetlib`) on the filesystem during the installation process of such a package.

Hyphens are also required to maintain one-to-one naming correspondence with a development project's official name, its source files and directories, and the artificts it generates on the filesystem as part of its compilation and execution process. Please look at the example code in the following Git/Github project created for illustration - 
https://github.com/kixus/mycom-mygreetlib

# Problem

Unfortunately (as of Janet version 1.11.3) hyphens don't seem to work, when used in conjunction with `declare-native` macro in `project.janet` file.

E.g for the example project, if we include a `declare-native` declaration with a hyphenated `mycom-mygreetlib` native library name in `project.janet` as follows -

```clojure
(declare-native
    :name                   "mycom-mygreetlib"
    :cflags                 (unless (= :windows (os/which)) [ "-pthread" ]) 
    :source                 @["source/main.c" ]
)
```

. . . it results in the following compilation error during `jpm build` -

```bash
$ jpm clean && jpm --verbose build && jpm test && tree build

Deleted build directory.
compiling build/source___main.o...
cc -c source/main.c -pthread -I/opt/local/solus/install/janet/v1.11.3/include/janet -O2 -fPIC -o build/source___main.o
linking build/mycom-mygreetlib.so...
cc -pthread -I/opt/local/solus/install/janet/v1.11.3/include/janet -O2 -o build/mycom-mygreetlib.so build/source___main.o -shared -lpthread
generating meta file build/mycom-mygreetlib.meta.janet...
compiling build/source___main.static.o...
cc -c source/main.c -DJANET_ENTRY_NAME=janet_module_entry_mycom-mygreetlib -pthread -I/opt/local/solus/install/janet/v1.11.3/include/janet -O2 -o build/source___main.static.o
<command-line>: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘-’ token
<command-line>: note: in definition of macro ‘JANET_ENTRY_NAME’
source/main.c:48:1: note: in expansion of macro ‘JANET_MODULE_ENTRY’
   48 | JANET_MODULE_ENTRY(JanetTable *env) {
      | ^~~~~~~~~~~~~~~~~~
error: command exited with status 1
  in shell [/opt/local/solus/install/janet/v1/bin/jpm] (tailcall) on line 134, column 5
  in do-rule [/opt/local/solus/install/janet/v1/bin/jpm] on line 253, column 26
  in do-rule [/opt/local/solus/install/janet/v1/bin/jpm] on line 249, column 44
  in do-rule [/opt/local/solus/install/janet/v1/bin/jpm] (tailcall) on line 249, column 44

```

Note that the primary error is arising out of the invalid C identifier `janet_module_entry_mycom-mygreetlib` being passed onto the `main.c` file during compilation, as the hyphen is not getting sanitized while generating `JANET_ENTRY_NAME` declaration.

Deeper introspection of `jpm` code shows the function `entry-name` uses the `filepath-replace` function, which is OK for sanitizing file names.  However its use leaves behind the hyphen as is due to its use of `filepath-replacer` PEG -

```clojure
;;; JPM source ...

(defn- entry-name
  "Name of symbol that enters static compilation of a module."
  [name]
  (string "janet_module_entry_" (filepath-replace name)))

;;; .....
;;; .....
;;; .....
(def- filepath-replacer
  "Convert url with potential bad characters into a file path element."
  (peg/compile ~(% (any (+ (/ '(set "<>:\"/\\|?*") "_") '1)))))

(defn filepath-replace
  "Remove special characters from a string or path
  to make it into a path segment."
  [repo]
  (get (peg/match filepath-replacer repo) 0))

```

# Workaround 

The `jpm` source indicates that specifying the option `:entry-name` might address the invalid `JANET_ENTRY_NAME` being generated - 

```clojure
;;; project.janet source ...
(declare-native
    :name                   "mycom-mygreetlib"
    :entry-name             "janet_module_entry_mycom_mygreetlib"
    :cflags                 (unless (= :windows (os/which)) [ "-pthread" ]) 
    :source                 @["source/main.c" ]
)
```

However that runs into additional troubles during module loading process, as for some reason `janet.h` file seems to be voiding the definition of `_janet_init`  (I don't understand that part of the source code, but it results in failing to load the `cfuns` table after successfully loading the `mycom-mygreetlib.so` module) -

```C
//// janet.h source ...

#ifndef JANET_ENTRY_NAME
#define JANET_MODULE_ENTRY \
    JANET_MODULE_PREFIX JANET_API JanetBuildConfig _janet_mod_config(void) { \
        return janet_config_current(); \
    } \
    JANET_MODULE_PREFIX JANET_API void _janet_init
#else
#define JANET_MODULE_ENTRY JANET_MODULE_PREFIX JANET_API void JANET_ENTRY_NAME
#endif
```

To the best of my knowledge the problem seems to stem from the following code fragment in `corelib.c` source -

```C
/// corelib.c source ...

JanetModule janet_native(const char *name, const uint8_t **error) {
    char *processed_name = get_processed_name(name);
    Clib lib = load_clib(processed_name);
    JanetModule init;
    JanetModconf getter;
    if (name != processed_name) free(processed_name);
    if (!lib) {
        *error = janet_cstring(error_clib());
        return NULL;
    }
    init = (JanetModule) symbol_clib(lib, "_janet_init");
    if (!init) {
        *error = janet_cstring("could not find the _janet_init symbol");
        return NULL;
    }

```

Basically it returns the error `could not find the _janet_init symbol` (see below for full output).

In other words, the workaround of directly specifying `:entry-name` with a hyphenated native library name DOES NOT WORK.  Here is the full rundown of specifying `:entry-name` and running `jpm build` -

```bash
$ jpm clean && jpm --verbose build && jpm test && tree build

Deleted build directory.
compiling build/source___main.o...
cc -c source/main.c -DJANET_ENTRY_NAME=janet_module_entry_mycom_mygreetlib -pthread -I/opt/local/solus/install/janet/v1.11.3/include/janet -O2 -fPIC -o build/source___main.o
linking build/mycom-mygreetlib.so...
cc -pthread -I/opt/local/solus/install/janet/v1.11.3/include/janet -O2 -o build/mycom-mygreetlib.so build/source___main.o -shared -lpthread
generating meta file build/mycom-mygreetlib.meta.janet...
compiling build/source___main.static.o...
cc -c source/main.c -DJANET_ENTRY_NAME=janet_module_entry_mycom_mygreetlib -pthread -I/opt/local/solus/install/janet/v1.11.3/include/janet -O2 -o build/source___main.static.o
creating static library build/mycom-mygreetlib.a...
ar rcs build/mycom-mygreetlib.a build/source___main.static.o
running test/test.janet ...
error: could not load native build/mycom-mygreetlib.so: could not find the _janet_init symbol
  in native
  in <anonymous> [boot.janet] on line 2408, column 26
  in require-1 [boot.janet] on line 2427, column 18
  in import* [boot.janet] on line 2447, column 15
  in _thunk [test/test.janet] (tailcall) on line 1, column 1

```

Note that the hypnenated module name (.so) successfully gets loaded by the Janet runtime.  However it fails during `janet_init` entrypoint resolution process.  Which means hyphnated modules essentially could be made to work, provided we address the entry point resolution issue.

# Solution

If you agree with the premise of this bug report, and agree that support for hyphenated filesystem artifact names is indeed a valid requirement, here are some hypotethical solutions and/or recommendations -
1.  Define new function `entry-name-replace` with a corresponding PEG `entry-name-replacer` in `jpm` source code that sanitizes hyphens for entry point name only.
2.  Address issue in `janet.h` that fails to define `_janet_init` symbol.
3.  Address issue in `corelib.c` that tries to resolve the above mentiioned symbol after loading the `<module>.so` correctly.

#  Requirements

If you plan to make changes similar to recommendations above, please observe the following requirements for a solution implementation -

1.  The solution must work for all types of generated artificts, both native (.so) libraries on POSIX systems, and also for native binaries if any.
2.  The solution must work for multiple hyphens that may be specified as part of the resulting artifact name.
3.  The solution must work from system installed hyphenated libraries, i.e. after using `jpm install`.
4.  The solution must work to correctly resolve cross-project library dependencies that contain such generated hyphenated artifacts.
5.  The solution must work for other types of installations, e.g. nested filesystem paths for such libraries (if ever supported).
6.  The solution must work existing code that uses `:entry-name` specification in `declare-native` declaration.
7.  The solution must not introduce any severe performance penalties.
8.  Please DO NOT sanitize the underlying generated file names (i.e. replace all hyphens with underscores where it is not necessarily required) as that would impede keeping track of the installed dependencies on a large installation.  I would personally prefer that we sanitize the entrypoint name only  (replace hyphen with underscore),  for the C entrypoint where it is actually required, and not be extended to on-system installed files where a system administrator might want to correlate and/or audit the binaries with respect to their corresponding projects, by inspecting the files on the  underlying installation.

Hope this bug report is describes  the problem in adequate detail, that I happened to encounter while trying to name and use native libraries with Janet. Feel free to ask any questions that you might have.  Thank you.

# System info

Janet - self compiled and installed runtime -

```bash
$ janet -v
1.11.3-meson
```

Host OS - Solus Linux -
```bash
$ lsb_release -a 
LSB Version:	1.4
Distributor ID:	Solus
Description:	Solus
Release:	4.1
Codename:	fortitude
```

Compiler - GNU GCC

```bash
$ gcc --version
gcc (Solus) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by bakpakin** [comment]
> Hope this bug report is describes the problem in adequate detail, that I happened to encounter while trying to name and use native libraries with Janet. Feel free to ask any questions that you might have. Thank you.
Yes, the detail is more than fine.

The first solution you give is probably best - the main reason for using the filepath escaper was I wanted to quickly allow forward slashed in the entry name, but more correct would be escaping any character that is not a valid C identifier. BTW, the entry name is only used in the case of static libraries - for dynamic libraries, you always want to use `_janet_init`. For static libraris, we can't do that becuase mutliple static libraries could be loaded in the same binary, and each one's `_janet_init` would collide.

The issue with setting `:entry-name` not working is a slightly separate issue - we probably don't want to _ever_ override entry-name unless we are building a static library, so we can just add that check in jpm.

Thanks for reporting and doing some digging, I believe someone else has mentioned this issue before in chat.

**Comment by kixus** [comment]
So is the first solution (Define new function `entry-name-replace` with a corresponding PEG `entry-name-replacer` in jpm) likely to be implemented in JPM source code?  Or are you suggesting I need to update and maintain my own copy of JPM (not my first choice)?

**Comment by kixus** [comment]
Besides, how do prevent building of static libraries, and then, how do I prefer loading of dynamic libraries with the module import statement?
Sorry if this is not the best place to ask the questions, but I am not yet a member of Janet chat group.

**Comment by bakpakin** [comment]
It is fixed on the master branch. You can build that latest version or wait until  the next release, which should be soon, as I do approximately monthly releases.

**Comment by bakpakin** [comment]
> Besides, how do we prevent building of static libraries using JPM, and then, how do I my preference to Janet for loading of dynamic libraries with the module import statement, in case both static and dynamic libraries are getting built?

We do not want to prevent anything - import will always import dynamic libraries - the static library is a build artifact that is only used when building standalone executables (by definition, you can't import a static library at runtime).

**Comment by kixus** [comment]
That is awesome.  Thank you for the quick response and the fix. I will look forward to it in the next release.
