### ISSUE TITLE
thread/receive default timeout

### ISSUE THREAD

**Issue by magv** [janet-lang/janet#471]
Hi, folks. The documentation for `thread/receive` says: "If timeout is provided, an error will be thrown after the timeout has elapsed but no messages are received". I take that to mean that with no timeout, `thread/receive` waits forever. This is not the case: it waits for 1 second.

Test case:
```
$ janet
Janet 1.12.1-15e05b69 linux/x64
repl:1:> (varfn worker [parent] (pp (thread/receive)))
<function worker>
repl:2:> (var t (thread/new worker))
<core/thread 0x55AE6258A510>
repl:3:> in thread <core/thread 0x7F3FC40038E0>: error: timeout after 1.000000 seconds
  in <cfunction>
  in worker [repl] on line 1, column 28
```

So, what's the expected behavior? Either the documentation or the implementation is wrong.

**Comment by bakpakin** [comment]
In this case the documentation is wrong - the function was updated to wait for one second. To wait forever, pass `math/inf` as the wait parameter.

**Comment by magv** [comment]
I see. Thanks.
