### ISSUE TITLE
getline and ctrl-c, weird niche behaviour

### ISSUE THREAD

**Issue by ceigey** [janet-lang/janet#473]
Hi all, thank you for this cool language.

I've been playing around with Janet the last couple of days
and noticed a weird behaviour when using getline,
and I wanted to double check if Janet has a particular
way of handling SIGINT cross-platform.

I'm not sure how niche this issue is, as I'm trying it out on
Windows (Native/PowerShell) and on Android (UserLAnd, Ubuntu 18.04 I think),
so not a typical setup.

Here is my example program:
https://github.com/ceigey/textgame-janet-protoype/blob/initial-demo/main.janet

Relevant snippet:

```clojure

(defn getline->string []
  (->> (getline)
       (string)
       (string/trim)))

(defn main-loop []
  (let [input (getline->string)]
    (loop-dispatch input)
    (main-loop)))

(main-loop)

```

The basic premise is that when I use `(getline)`, on Android, using
`ctrl-c` (SIGINT) just supplies the string `cancel` to `getline`, 
so I can never quit the program unless I check for a specific string.
While on PowerShell, I get the expected interrupt behaviour and I exit
the program.

(`ctrl-z` however works as expected on Android, sending `janet`
to sleep where I can use `ps` and `kill`; `ctrl-c` also works for 
for the real Janet REPL even on Android. This behaviour only
surfaces when trying to implement my own fake "REPL").

If nothing comes to mind as to why this might be happening,
that's OK. I'm mostly adding this as an issue to provide
history to this problem. It might simply be that, for some weird reason,
Janet and UserLAnd's terminal are incompatible even though
this is a unique occurrence for me, or something with my
environment led to a bad build.

Extra info:

* Windows version: 1.12.1-2bf5e34
* Ubuntu (Android) version: 1.12.1-local (built from source, aarch64)

---

As a sidenote, I also found I had to use pipe/threading macros
with the piped-into forms wrapped in parentheses, otherwise
they sometimes didn't evaluate properly and steps got "skipped".
E.g. `(->> input (fn1) (fn2))`  rather than `(->> input fn1 fn2)`.
Not sure if it's worth making a separate issue about at all.

**Comment by bakpakin** [comment]
This is intentional - there were some changes a while back that make the default getline on posix platforms capture ctrl-C and return the keyword :cancel - this was to make the repl behave more like other shells, although I'm not sure this is great behavior (we want to make Ctrl-C clear the current expression in the Repl, including previously, already entered lines, so we need the application to handle it somehow).

Janet rolls it's own getline, there is not strange SIGINT handling problem here. `kill -9` will work fine on the application, although your terminal might go a bit wonky.

**Comment by bakpakin** [comment]
You can use the default/shell getline functionality by passing the -s flag to janet on startup.

```
janet -s
```

**Comment by ceigey** [comment]
Thank you for the explanation, that makes a lot of sense in retrospect.  I guess then I need to be matching against types instead of just trying to read the raw input first.

I also guess, ironically, in this case the Android containerised version of Ubuntu is working as expected while Powershell/Windows in general does its own thing when you hit ctrl-C. So then I guess if I wanted to make this little demo game multiplatform I'd need to then find a different way to "cancel" input.

Well, in the meantime I'll mark this as closed, thanks again!
