### ISSUE TITLE
Deep equality and immutable/mutable types

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#474]
At present, `deep=` treats immutable and mutable types as not being equal even if they share the same structure. In other words:

```janet
(deep= [1] @[1]) # => false
(deep= @[1] @[1]) # => true
```

This is a result of the type equality check done at the beginning of the `deep-not=` function:

https://github.com/janet-lang/janet/blob/b91fe8be5ac4fb5bd7f1580cea53b8b1637f71c2/src/boot/boot.janet#L1874-L1880

This seems counterintuitive to me. I would expect that a tuple and an array that have the same structure are equal for the purposes of `deep=`.

Was this a conscious decision? I can submit a patch to `boot.janet` that would treat immutable and mutable types as equal if they share the same structure if this is something that would be acceptable.

**Comment by andrewchambers** [comment]
The current behavior seems correct to me - but I can understand why you might want to check shape equality too... Not sure what I would call that function.

**Comment by pyrmont** [comment]
@andrewchambers made a good point in Gitter that changing `deep=` in the manner described above would be a breaking change. That seems like a good reason not to change the implementation of `deep=`.

The correct solution might be to leave this as a function that users can implement on their own (that's what I [ended up doing]( with Testament `equiv`

**Comment by pyrmont** [comment]
After further consideration, I think this makes sense as something to leave for users to write for themselves.
