### ISSUE TITLE
left-alt+10 and left-alt+13 are being interpreted as cr / lf by reader when inside a string

### ISSUE THREAD

**Issue by kamisori** [janet-lang/janet#476]
While trying to communicate with some device via serial port I discovered that both 0x0a and 0x0d inside a string are being interpreted by the reader as what they are: linefeed and carriage return during evaluation.

Values enclosed in <> should be typed on the numpad while holding the left alt-key

Reproduce by typing in the repl:
(string/bytes "<10>")
(string/bytes "<11>")
(string/bytes "<12>")
(string/bytes "<13>")

Expected behavior:
REPL displays returned value of the given byte such as:
repl:1:> (string/bytes "◙")
(10)
repl:2:> (string/bytes "♂")
(11)
repl:3:> (string/bytes "♀")
(12)
repl:4:> (string/bytes "♪")
(13)

Observed behaviour:
0x0a makes repl behave as if i pressed enter inside the string, both 0x0a and 0x0d return an empty tuple
repl:1:> (string/bytes "◙")
repl:2:(">()
repl:3:> (string/bytes "♂")
(11)
repl:4:> (string/bytes "♀")
(12)
repl:5:> (string/bytes "♪")
()

**Comment by bakpakin** [comment]
Sorry, but to me the expected behavior seems unexpected - do other interactive programs behave this way? You can also try `janet -s` for non-interactive use, although I don't think that would help this case.

**Comment by kamisori** [comment]
I saved it to a file, and used a hexeditor to insert the values I wanted.
I had to put pp around it to make it visible, but otherwise it is still the same code:
(pp (string/bytes "X"))
with X being replaced in the hexeditor with values between 0x00 upto 0x13

I get empty parens on the lines for 0x0a and 0x0d but byte values for the others.

![bytes](https://user-images.githubusercontent.com/293332/94408106-a3bf7600-0174-11eb-9e88-1cb343deffee.png)
[bytes.janet.gz](https://github.com/janet-lang/janet/files/5290898/bytes.janet.gz)

**Comment by bakpakin** [comment]
Ok, I think I understand. Janet's parser reinterprets carriage return and linefeed for windows compatibilty, and to allow breaking a long string over multiple lines without adding newline characters. The same source file, if opened on windows, could have different line endings. We remove line endings from normal strings, which is why you see what you see. If you want the newline characters, use backtick delimiters on the string.
