### ISSUE TITLE
Marshal limits

### ISSUE THREAD

**Issue by kurayama** [janet-lang/janet#48]
What are the current limitations of the `marshal` function?
I’ve tried serializing/deserializing a simple fiber and it works as expected, but if I use functions like `not`, `filter` or `map`, they all error with `no registry value for <cfunction “name”>`.

**Comment by bakpakin** [comment]
The marshal function needs a dictionary to marshal cfunctions and abstract types. The second optional argument to marshal is a table that would map values -> symbols. To then unmarshal the buffer, you need the inverse of this mapping.

For example:

```clojure
(def mapping @{print 'print {"Some" "Value"} 'mytab})

# This won't work, print will fail
(def buf (marshal [1 2 3 4 print]))

# This will
(def buf (marshal [1 2 3 4 print] mapping))
(unmarshal buf (invert mapping))
```
