### ISSUE TITLE
Crash when running packages from jpm

### ISSUE THREAD

**Issue by oz123** [janet-lang/janet#480]
For example:

```
$ joy
error: could not load native /usr/lib/janet/json.so: /usr/lib/janet/json.so: undefined symbol: janet_optbuffer
  in native
  in <anonymous> [boot.janet] on line 2423, column 26
  in require-1 [boot.janet] on line 2442, column 18
  in import* [boot.janet] on line 2462, column 15
  in _thunk [/usr/lib/janet/joy/responder.janet] (tailcall) on line 1, column 1
compile error: unknown symbol json/encode on line 45, column 11 while compiling /usr/lib/janet/joy/responder.janet
error: could not load native /usr/lib/janet/_uri.so: /usr/lib/janet/_uri.so: undefined symbol: janet_cfuns
  in native
  in <anonymous> [boot.janet] on line 2423, column 26
  in require-1 [boot.janet] on line 2442, column 18
  in import* [boot.janet] on line 2462, column 15
  in _thunk [/usr/lib/janet/uri.janet] (tailcall) on line 83, column 1
```

I installed janet via the ebuild (I'm also the creator of the ebuild in gentoo). If I install janet via `make` using the sources from tatr ball I don't see this problem. 
I'm not sure how to fix this issue. Would be happy to get a hint (sorry if this issue is inappropriate).

**Comment by andrewchambers** [comment]
I suspect you will need to uninstall your json library and reinstall it.

This may have been caused by compiling the json plugin against a newer version of janet than is currently installed.

**Comment by oz123** [comment]
WOW! Thanks, that was quick!

**Comment by oz123** [comment]
I think I found the problem:
The makefile create the following link whereas the ebuild does not:
```
ln -svf libjanet.so.1.12.2 /usr/lib64/libjanet.so.1.12
```
Adding this link solved the issue.

**Comment by andrewchambers** [comment]
Interesting, sorry my idea wasn't the right fix, glad you got it working.

**Comment by oz123** [comment]
Well, your response is still worthy! I'm glad to see I'm not alone here.
