### ISSUE TITLE
Question: When is a table kv->value ever not nil?

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#482]
I was profiling janet, and found this janet_dict_find is quite a hot function.

I noticed this condition that checks if kv->value is not JANET_NIL.
https://github.com/janet-lang/janet/blob/ebfa07f8ce492fd0b6511903ba4c0092e5b89314/src/core/util.c#L275

I might not be understanding the janet table, but should this never be true? I thought a table value is always nil if the key is nil.

 I tried to simplify the logic on that assumption, and found my understanding is incorrect, but I'm not totally sure why?

Heres my simplified, but broken implementation:
```
const JanetKV *janet_dict_find(const JanetKV *buckets, int32_t cap, Janet key) {
    int32_t index = janet_maphash(cap, janet_hash(key));
    int32_t i;
    /* Higher half */
    for (i = index; i < cap; i++) {
        const JanetKV *kv = buckets + i;
        if (janet_checktype(kv->key, JANET_NIL) || janet_equals(kv->key, key)) 
            return kv;
    }
    /* Lower half */
    for (i = 0; i < index; i++) {
        const JanetKV *kv = buckets + i;
        if (janet_checktype(kv->key, JANET_NIL) || janet_equals(kv->key, key)) 
            return kv;
    }
    return NULL;
}
```

**Comment by bakpakin** [comment]
When removing values from a table, rather than removing the entire (which could break some probing invariants), we leave a "tombstone" value there, which is a basically saying "there used to be something here, so if you are probing for a key, you aren't done yet" rather than "this is empty, so you are finished probing and nothing was found".

For structs we don't need to do this, though.

**Comment by andrewchambers** [comment]
Thanks for the explanation

**Comment by andrewchambers** [comment]
It makes me wonder if a valid strategy is a bit indicating a table never had any deletions, and selecting the faster search if it has not.
