### ISSUE TITLE
Feature discuss: kv splicing

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#490]
Something I've wanted to do a fair few times, is splice into a table or struct.
```
(def some-peg {
  :a :b
})

(def another-peg {
   ;some-peg
   :c :d
})
```

anyone else think this would be useful? I guess it might not be feasible as it breaks the pair requirements in the parser.

A potential workaround would be something like:
```
{;another-tab ...}
```

**Comment by pepe** [comment]
Well the name of the variables you used, definitely strikes me I need this too. But as you also write, the pair requrements will be lost in table/struct literal, so I am not realy sure if it is feasible.

**Comment by bakpakin** [comment]
There is always the hack

```
{;[] ;my-values}
```

I don't want to break parsing for this, so closing.
