### ISSUE TITLE
buffer/push-string misleading docs and name

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#500]
"Push a string onto the end of a buffer. Non string values will be converted..."

Actually this function does not convert things like numbers. Instead it takes things that can be easily converted to bytes.

Arguably this function is misnamed and should be called something else like 'push or 'push-bytes, though that is not backwards compatible.

**Comment by bakpakin** [comment]
I have updated the docstring to address this, and added a more general function `buffer/push` to make this clear. `buffer/push` can push bytes to the buffer as well, so in almost all cases it should be more ergonomic.
