### ISSUE TITLE
Automatic and deterministic memory management (no garbage collector)

### ISSUE THREAD

**Issue by sirinath** [janet-lang/janet#501]
Can you consider automatic and deterministic memory management like in [Carp](https://github.com/carp-lang/Carp)

**Comment by bakpakin** [comment]
I am very sympathetic to the desire for efficiency, but seems a bit out of scope for the language proper (it would a bit like trying to do the same for Lua or Python - hard and not work well). I also don't really want to add reference counting, as it make writing native modules that much more difficult. As with many of these low-level feature requests, a more realistic way to achieve the assumed goal (fast/resource efficient/low latency programs) would be a separate dialect/language to complement Janet, which would be low-level, no gc, and probably compiled to native code.

See https://github.com/janet-lang/janet/issues/488 for similar question and answer.

Such a project would take a lot of work and could be implemented as a Janet library, but would not live here.
