### ISSUE TITLE
`ev/call`segfaults when there are more arguments for function than its arity

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#504]
Reproduction:

```
> (def f (ev/call inc 1  2 3))

=> Segmentation fault
```
on latest Janet master at the time of writing, stdlib: musl-1.1.24_5, Linux  5.8.18_1 #1 SMP x86_64 GNU/Linux

**Comment by bakpakin** [comment]
Fixed in a3f98091c43eba53cf41bf195147f991f4fa6259, which labels the wrong issue.
