### ISSUE TITLE
PEG repeat combining pattern has surprising behavior

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#518]
When trying to combine more than one pattern, it seems to that count is for every matched part of the subpattern.

Repro:

```
(peg/match '(repeat 10 (+ ':d :s)) "1 2 3 4 5 6 7 8 9 0")
=> @["1" "2" "3" "4" "5"]

(peg/match '(repeat 20 (+ ':d (? :s))) "1 2 3 4 5 6 7 8 9 0")
=> nil

(peg/match '(repeat 19 (+ ':d (? :s))) "1 2 3 4 5 6 7 8 9 0")
=> @["1" "2" "3" "4" "5" "6" "7" "8" "9" "0"]
```

**Comment by sogaiu** [comment]
I guess the expected behavior for:
```
(peg/match '(repeat 20 (+ ':d (? :s))) "1 2 3 4 5 6 7 8 9 0")
```
is:
```
@["1" "2" "3" "4" "5" "6" "7" "8" "9" "0"]
```

FWIW:
```
(peg/match '(repeat 20 (+ ':d (? :s))) "1 2 3 4 5 6 7 8 9 0a")
```
gives:
```
nil
```
as well, so I guess it's not that `0` is right at the end of the string.

**Comment by pepe** [comment]
@sogaiu I am not sure why you think `(peg/match '(repeat 20 (+ ':d (? :s))) "1 2 3 4 5 6 7 8 9 0")` should be `@["1" "2" "3" "4" "5" "6" "7" "8" "9" "0"]`? 


I think `(peg/match '(repeat 10 (+ ':d :s)) "1 2 3 4 5 6 7 8 9 0")` should be  `@["1" "2" "3" "4" "5" "6" "7" "8" "9" "0"]`

**Comment by sogaiu** [comment]
Ah, I think you're right.  My bad :)

**Comment by bakpakin** [comment]
The problem is your peg, not the implementation. I think you meant, `*` instead of `+`.

**Comment by pepe** [comment]
OMG. Thank you very much.
