### ISSUE TITLE
Compiler ignores strange splice

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#519]
```
> (if true ;[1 2 3] 4)
[1 2 3]
```

it seems like the compiler is ignoring the splice when maybe an error makes more sense? I could be understanding this incorrectly.

**Comment by pepe** [comment]
I think splice only work when it is a parameter to function or macro.

**Comment by andrewchambers** [comment]
It was pointed out in the docs that this is explicitly ignored on purpose. I don't know the exact reason, but it is definitely intentional.
