### ISSUE TITLE
issue with chr?

### ISSUE THREAD

**Issue by yvan** [janet-lang/janet#523]
the `chr` [macro](https://janetdocs.com/chr) ([source](https://github.com/janet-lang/janet/blob/cfa9fb6ee4cef2ceda529c043e0970c644100a2f/src/boot/boot.janet#L342)) ([issue](https://github.com/janet-lang/janet/issues/304)) doesn't seem to behave how i expected with tuples? when a string comes from a tuple it gives me an error. 

```
repl:516:> (chr "a")
97
```
ok ^ that's fine.

```
repl:517:> (chr ((tuple "a" "b") 0))
error: (macro) expected string of length 1, got <tuple 0x55A33387C710> on line 517, column 1 while compiling repl
  in chr [boot.janet] on line 346, column 5
```

ok ^ not fine. i'm expecting the output to be 97. so let's see...

```
repl:519:> (type ((tuple "a" "b") 0))
:string
repl:520:> (type "a")
:string
repl:526:> (length ((tuple "a" "b") 0))
1
repl:528:> (length "a")
1
```
both are strings of length 1, seems ok.

```
repl:521:> (and (string? ((tuple "a" "b") 0)) (= (length ((tuple "a" "b") 0)) 1))
true
```

it returns true for the test in chr macro. i think the tuple fails the test in chr because the tuple indexing isn't evaluated when it's passed to chr and so it still has type tuple (not `:string`), throwing an error inside the macro. that is consistent with my understanding of what macros should do, i guess.

should `chr` be a macro? i just wrote my own function, essentially duplicating the macro and it works fine.

```
(defn chrf
  [c]
  (unless (and (string? c) (= (length c) 1))
    (error (string/format "expected string of length 1, got %v" c)))
  (c 0))
```

i'm sure someone will let me know if i'm thinking about this incorrectly.

edit: my understanding of what a macro should do is operate on code, but clearly the idea behind `chr` is to operate on a `:string` data type. obviously in a lisp the distinction isn't so firm, but you'd have a hard time arguing that "a" is code, right?

**Comment by bakpakin** [comment]
`chr` is a macro for efficiency, and only works on string literals because that is really its only purpose. Otherwise just use `(c 0)` or even the `first` function. Janet's compiler is quite dumb (for a variety of reasons, including debugability) and does not inline anything.

That said, we could have the macro expand to `(c 0)` in the case where c is not a string literal. The behavior is a bit strange and it doesn't really need to be like that.
