### ISSUE TITLE
Proposal: os/look-path

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#528]
I propose something like the go function https://golang.org/pkg/os/exec/#LookPath.

This lets you find programs by absolute path, without actually running them and without depending on the 'which' bin. The logic to do this is actually relatively complex, and varies by platform. This could also be ok for a third party module, maybe janet-lang/path ?

**Comment by sogaiu** [comment]
I think a file system library might be nice with this functionality and some bits from jpm (e.g. `rm`, `copy`, `create-dirs`, ...)

**Comment by andrewchambers** [comment]
hmm yeah, perhaps theres enough for a proper external library that depends on path/.

**Comment by swlkr** [comment]
`andrewchambers/path-ultra`?
