### ISSUE TITLE
unmarshal nested fiber

### ISSUE THREAD

**Issue by kurayama** [janet-lang/janet#53]
I get an unmarshal error when running the following script:

```clojure
(def x 
  (fiber/new 
    (fn [] 
      (var y (fiber/new (fn [] (print "1") (yield) (print "2"))))
      )))

(load-image (make-image x))

```

```
error: expected string
  in unmarshal
  in load-image [core.janet] at (48135:48169)
  in _thunk [demo/teste3.janet] (tailcall) at (125:151)
```

In a different test also involving nested fibers (an array of them) I also got a different error but I could not create a minimal reproducing script.

```
rror: invalid reference
  in unmarshal
  in load-image [core.janet] at (48135:48169)
  in _thunk [demo/teste2.janet] (tailcall) at (1772:1799)
```

**Comment by bakpakin** [comment]
I've found and fixed I believe both issues in 1147482e62390de8c147cdbc568c9cdb2a334309 as well as added some test cases. The unmarshaller was not keeping track of already "seen" fibers, like is it supposed to do for all non trivial types.
