### ISSUE TITLE
Improving stacktrace messages for netrepl clients

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#531]
I've recently been using spork's [netrepl](https://github.com/janet-lang/spork/blob/72a304177c6ecc33eb134810147f0522c5d056e6/spork/netrepl.janet) and the [Conjure plugin](https://conjure.fun/) for Neovim and the experience is really fantastic.

## Problem

One of the few areas that isn't so great is the locations given during stacktraces. Here's an example of what you might see if you invoke `(example-fn 5)` (where `example-fn` is defined as `(defn example-fn [f] (f))`:

```text
error: 5 called with 0 arguments, possibly expected 1
  in example-fn [repl] on line 2, column 3
  in _thunk [repl] (tailcall) on line 5, column 1
```

## Issues

There are two issues here.

1. **Wrong filename**: The location of the functions is `"repl"` rather than the name of the file being edited.

2. **Wrong line and column numbers**: The line and column numbers are relative to the the lines that have been sent by the netrepl client rather than the line and column of the file being edited.

## Fixes

1. Fixing the filename can be solved by changing netrepl to support the client sending the value to use for `:source`. This only requires changes to netrepl and not to Janet itself.

2. Fixing the line and column numbers requires changes to `run-context` and `parser/consume`. My understanding is that the line and column numbers are set by the parser when it parses input and then saved in the environment. To provide more useful messages to a netrepl client, a client would need to be able to specify line and column offsets which netrepl would send to `run-context` and which `run-context` would in turn send to `parser/consume`.

## Limitations

Admittedly, this solution doesn't fix all cases. The file and column numbers will be incorrect for forms that were previously evaluated and that have subsequently moved in the file. I don't think there's really a good way to fix this, though.

Does this approach sound reasonable? Are there reasons to prefer doing something else?

**Comment by bakpakin** [comment]
Allowing the client to set the source file sounds reasonable. And a much simpler way to fix the line number issue is to expose a function to set line and column offset in the parser. Since we can now pass a parser into run-context, this would let netrepl manually set line and column location by using it's own parser instance rather than a default generated by run-context. For example, allow `parser/where` to also set the parser location with `(parser/where p line col)`.

**Comment by pyrmont** [comment]
@bakpakin Yep, that makes sense. Have added a PR to address.
