### ISSUE TITLE
janet -r to run script and then drop me into the repl?

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#534]
I'm trying to get `janet` to run a script and then drop me into the repl afterwards, such that I can then manually test functions in my script. (This would be analogous to lua's `-i` option.)

It looks like `janet` provides the `-r` option for this, but it's not working for me. For example, I've got a foo.janet file:

~~~
(def x 3.5)

(defn foos
  "docstring goes here"
  [n]
  (+ n 5))
~~~

And I try to run it with `-r` but it doesn't work as I'd expect.

~~~
$ janet -r foo.janet 
Janet 1.12.2-local linux/x64 - '(doc)' for help
repl:1:> x
compile error: unknown symbol x while compiling repl
repl:2:> (foos 2)
compile error: unknown symbol foos on line 2, column 1 while compiling repl
~~~

Maybe I'm misunderstanding what `janet`'s -r is for? The docs say, "Enter the repl after running all scripts".

My plan further on is to get real repl-driven development working with Emacs, but failing that it seems like it would be handy to be able to manually test functions inside modules in the way described above (that is, like Lua's `-i`) --- though maybe Janet already provides a better way to do that?

**Comment by uvtc** [comment]
I see that the Janet man page says:

~~~
       -r     Open a REPL (Read Eval Print Loop) after executing all sources. By default, if Janet
              is called with no arguments, a REPL is opened.

~~~

Does "executing all sources" imply that I should pass source file names to `janet`?

**Comment by uvtc** [comment]
This is on Debian.

**Comment by uvtc** [comment]
Getting help from gitter, I see that this works:

~~~bash
janet -e '(import foo)' -r foo.janet
~~~

and then I can access things by prefixing with `foo` (ex `foo/x`, `(foo/foos 2)`).

But simply doing `janet -r foo.janet` does *not* let me access using the prefix. Is it by-design that the `-e '(import foo)'` on the command line is required?

**Comment by pepe** [comment]
Not sure, but I think that this is not loading your script into the environment.  But you can use `-l` for this purpose:

```
janet -l ./foo
```

**Comment by uvtc** [comment]
Oh! Yes, I see that that works. As does:

    janet -l foo

(no `./`)

So, then, regarding `-r`: If I run `janet -r foo.janet`, are the contents of foo.janet in any way related to or available in the resulting repl?

**Comment by pepe** [comment]
I think (and I could be wrong) that script is only compiled and ran, without loading it into the repl environment. But I can be terribly wrong here :).

**Comment by pyrmont** [comment]
@uvtc If you run:

```shell
janet -l foo
```

Janet will attempt to load a module with the standard extensions (`.janet`, `.so`, etc) from the default paths (including the current working directory). If it finds a library, it will load the library into the environment without a prefix and then start the REPL.

From this point, you have access to the public bindings made in `foo.janet` as if you had loaded it from the REPL directly with `(import foo :prefix "")`.

**Comment by uvtc** [comment]
@pyrmont , thanks. And I see what you mean about, after a `janet -l foo`, you can use the local names, like `x`, rather than the longer `foo/x`. Makes sense I suppose, since you're using the module directly right there from the command line.

I'm not sure, but it might be of use to include a note in the janet man page explaining a little more how to use and rationale for using the `-r` and `-l` options. (Maybe even a note about `-e '(import foo)'`?)

Do you happen to know if `janet -l foo` checks the cwd first or does it check the syspath first? I'll have to try this (though out of time tonight). (Whereas, I see that `janet -l ./foo` sticks to the cwd only.)

**Comment by pyrmont** [comment]
@uvtc You can see the code being executed in `boot.janet`:

https://github.com/janet-lang/janet/blob/cae4f1962914e27aba3d40aa650ac1e63c3c5a9b/src/boot/boot.janet#L3216-L3218

It works the same way that evaluating `(import <arg>)` would work. `import*` in this case is just the function version of the `import` macro.

**Comment by bakpakin** [comment]
Yes, running the script does not load into an environment. The -l option or the -e option is what you want here.

**Comment by uvtc** [comment]
Ah. I understand now. The `-r` option does not take any args (in `janet -r foo.janet`, foo.janet is not being passed as an arg to the `-r` flag).

The `-r` option simply tells `janet` to enter the repl after it's done running the script you passed it: `janet foo.janet` runs the script and exits, but `janet -r foo.janet` runs the script and then creates a repl and puts you into it.
