### ISSUE TITLE
Windows: jpm.bat is pointing to a file with wrong filename

### ISSUE THREAD

**Issue by littleli** [janet-lang/janet#536]
I've spotted that release artifacts for Windows, both 64 bit and 32 bit contains a `jpm.bat` file with this content:

```
@echo off
@rem Wrapper around jpm

janet "%~dp0\jpm.janet" %*
```

The issue here is `jpm.janet` does not exist and there is `jpm` (without extension only). 
I also checked the Linux artifact (*.tar.gz) and there is also file without extension - but that's completely appropriate  I guess.

This `jpm.bat` would work (but see below)
```
@echo off
@rem Wrapper around jpm

janet "%~dp0\jpm" %*
```

But !  ...

In `*.msi` artifacts Windows installer is not affected and there is `jpm.janet` file present, so there is something done in addition during packaging process.

**Comment by bakpakin** [comment]
Yes, during MSI installation jpm (which is the name on non-windows platforms) is changed to jpm.janet. I think scoop could ignore this file and just generate what is need - we just need `jpm` to call `janet path/to/jpm`.

**Comment by littleli** [comment]
I actually use files from `.msi` artifact and the generated `jpm.bat` so I'm not running into this. I just noticed the difference when I was evaluating what to use for the scoop manifest.

**Comment by littleli** [comment]
I failed to add janet to the official scoop bucket. I have no will to wrestle with maintainers. My attempt is available in [my personal bucket](https://github.com/littleli/Scoop-littleli) for those who are interested:
