### ISSUE TITLE
Hash for tuples (arrays) results in a lot of collisions and significant slow down for tables, distinct, etc

### ISSUE THREAD

**Issue by felixr** [janet-lang/janet#538]
> TLDR; `janet_array_calchash()` produces a lot of collisions causing slow down for anything using the hashed

 
I notice my (ugly) solution to day 22 of the Advent of Code  was quite slow, so I profiled it and noticed a lot of time spent in `janet_equal()`. Since my code (see below) does not do many direct comparisons I assumed it had to do with the table lookups. So I had a look at the hash function and replaced it with [Python's hash function for tuples](https://github.com/python/cpython/blob/63298930fb531ba2bb4f23bc3b915dbf1e17e9e1/Objects/tupleobject.c#L406). The speed up was significant.

My solution and `(distinct tuples)` with ~1.5M distinct tuples were suddenly both **~5x faster**. 

Output of running the code (below) without and with my patch:

```
janet solve.janet
Completed in 9.00 seconds
(distinct) completed in 17.00 seconds
Number of hash collisions: 115405 (7.70%)

janet_opt solve.janet
Completed in 2.00 seconds
(distinct) completed in 3.00 seconds
Number of hash collisions: 294 (0.02%)
```

```clojure
(def txt "2 31 14 45 33 18 29 36 44 47 38 6 9 5 48 17 50 41 4 21 42 23 25 28 3\n26 16 27 12 49 32 19 46 37 15 10 30 11 24 1 40 7 8 43 34 20 35 22 39 13")
 
(defn get-input []
  (->> 
    (string/split "\n" txt)
    (map (partial string/split " "))
    (map (fn [arr] (keep scan-number arr)))))
                
(def all-seen @[])
(var collect false)

(var winning-hand nil)
(defn play [[pa pb]]
  (def seen @{})
  (var ret nil)
  (var winner nil)
  (while (and (not (empty? pa)) (not (empty? pb)))
    (set winner nil)
    (set ret nil)
    (let [ca (first pa)
          cb (first pb)
          curr (tuple ;pa "|" ;pb)
          prev? (get seen curr)]
      (put seen curr true)
      (if collect
        (array/push all-seen curr))
      (if prev? 
        (set ret :p1)
        (do
          (array/remove pa 0 1)
          (array/remove pb 0 1)
          (if (and (<= ca (length pa)) (<= cb (length pb)))
            (do
              (set winner (play [(array/slice pa 0 ca) (array/slice pb 0 cb)])))
            (if (> ca cb)
              (set winner :p1)
              (set winner :p2)))))
      (if (= winner :p1)
          (array/concat pa [ca cb])
          (array/concat pb [cb ca]))
      (if ret (set winner ret))
      (if (empty? pa)
        (set ret :p2)
        (if (empty? pb) (set ret :p1)))
      (if ret (break))))
  (set winning-hand (tuple ;pa ;pb))
  (or ret winner))

(def start (os/time))
(play (get-input))
(printf "Completed in %.2f seconds" (- (os/time) start))

(set collect true)
(play (get-input))

(def start (os/time))
(def num-tuples (length (distinct all-seen)))
(printf "(distinct) completed in %.2f seconds" (- (os/time) start))

(def num-hashes (length (distinct (map hash all-seen))))

(printf 
  "Number of hash collisions: %d (%0.2f%%)" 
  (- num-tuples num-hashes) 
  (* 100 (- 1 (/ num-hashes num-tuples))))
```

**Comment by felixr** [comment]
Not python's hash but another one that is quite commonly used and simpler:
https://github.com/felixr/janet/commit/c1e1fd111e6844f7698f582eab8408a2fa0ecdb2

Has in this case even fewer collisions.


Also, I forgot to say: this is obviously just one example where a different hashing function leads to a speed up. I don't know whether this change would better in all cases. When I have some more time (xmas?), I can try to get a more balanced view on this. But I have a hunch a different hash function will be a good change.

**Comment by andrewchambers** [comment]
In your janet config can you try with JANET_PRF 1 enabled? this uses a stronger hash function.

**Comment by andrewchambers** [comment]
@felixr slightly off topic, but setting -flto in CFLAGS really helps this benchmark for me.

```
Completed in 1.00 seconds
(distinct) completed in 1.00 seconds
Number of hash collisions: 251 (0.02%)
```

**Comment by felixr** [comment]
### JANET_PRF
> In your janet config can you try with JANET_PRF 1 enabled in your janetconf.h file, this uses a stronger hash function for the base hash, though i guess improvements to tuple hash might still be useful.

I looked at JANET_PRF, but it seems to only change the hash for strings (and symbols) and did not have an effect.

###  Link Time Optimization (`-flto`)

Using `-flto` had indeed a great impact. But only for my patched version. 

### An even worse example

While testing I also managed to make my test case even worse for the existing hash function:

```
janet_lto_opt solve.janet 
Completed in 1.00 seconds
(distinct) completed in 2.00 seconds
Number of hash collisions: 282 of 1498748 (0.02%)

janet_lto_orig solve.janet 
Completed in 15.00 seconds
(distinct) completed in 65.00 seconds
Number of hash collisions: 446764 of 1498748 (29.81%)

janet_lto_prf_orig  solve.janet
Completed in 17.00 seconds
(distinct) completed in 68.00 seconds
Number of hash collisions: 446764 of 1498748 (29.81%)
```

This is by changing `curr (tuple ;pa "|" ;pb)` to `curr (tuple ;pa 64 ;pb)`.

### Faster using strings as keys

Using strings as keys instead of tuples has the same speed up as changing the hash function. Meaning the hashing works well for strings but not for tuples with small numbers.
 
Changing `curr (tuple ;pa "|" ;pb)` to `curr (string/from-bytes ;pa 64 ;pb)` makes it also fast:

```
janet_lto_prf_orig  solve.janet
Completed in 3.00 seconds
(distinct) completed in 2.00 seconds
Number of hash collisions: 246 of 1498748 (0.02%)
```

**Comment by andrewchambers** [comment]
> but it seems to only change the hash for strings (and symbols) and did not have an effect.
Ah, my mistake haha.

**Comment by bakpakin** [comment]
Seems that the current number (integer) hashing is quite bad and this probably more of an issue that any particular hash function. We should probably address that before going and adding more and more complicated hash functions for tuples and other recursive data structures.1
