### ISSUE TITLE
Invalid fiber when deserializing

### ISSUE THREAD

**Issue by kurayama** [janet-lang/janet#54]
Using the following example:
```clojure
(defn sync [& coros]
  (var coros (map fiber/new coros))
  (var done false)

  (while (not done)
    (set coros (filter (fn [coro]
      (resume coro)
      (= (fiber/status coro) :pending)) coros))

    (if (> (length coros) 0) (yield) (set done true))))

(var x 
  (fiber/new 
    (fn [] (sync
      (fn []
        (print "1")
        (yield)
        (print "2"))
      (fn []
        (print "1")
        (yield)
        (print "2")
        (yield)
        (print "3"))))))

(resume x)

(load-image (make-image x))
```

If I don't call `(resume x)`, the fiber is able to be serialized/deserialized, if I call it I get the following error:

```
error: invalid fiber
  in unmarshal
  in load-image [core.janet] at (48009:48043)
  in _thunk [demo/test4.janet] (tailcall) at (490:516)
```

**Comment by bakpakin** [comment]
@kurayama Thanks for finding all of these marshalling bugs.

The marshalling code is a bit complicated as it needs to marshal fibers, function environments, and cyclic object graphs. I've pushed a few commits to try and simplify it a bit and make the error messages a little better, or at least let me write better error messages in the future.

By writing better error messages, I found the error as simply a reference to the wrong variable. 9d60e8b3430ecee3533b8e9371e76c9c8d806647 should fix it.
