### ISSUE TITLE
(during `make install`): fatal: not a git repository

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#544]
Installing on GNU/Linux into the default /usr/local location.

I downloaded the 1.13.1 tar.gz, unpacked into my ~/opt, ran `make` and `make test`, then as root ran `make install` and got:

~~~
fatal: not a git repository (or any of the parent directories): .git
build/janet tools/patch-jpm.janet jpm build/jpm "--libpath=/usr/local/lib" "--headerpath=/usr/local/include/janet" "--binpath=/usr/local/bin"
chmod +x build/jpm
~~~

Regardless though, the install seemed to work fine.

Experimenting, ran `make install` a second time, and that time the "fatal" line was still there, but the two lines below it (see above) were no longer there.

Not sure if this is a bug, or exactly what it's doing with/to `jpm`, but reporting it here since it seems like a `make install` should not contain "fatal" in its output if it's successful.

**Comment by sogaiu** [comment]
I think what you are seeing there is the result of the command that gets executed in this line:
```
JANET_BUILD?="\"$(shell git log --pretty=format:'%h' -n 1 || echo local)\""
```
( https://github.com/janet-lang/janet/blob/master/Makefile#L30 )

I'm not much of a shell script person, but the `|| echo local` at the end may cause `JANET_BUILD` to have a value of `local` if the preceding part (the git command) fails.

So long story short, it's probably nothing to worry about?

**Comment by bakpakin** [comment]
Yes, nothing to worry about, but we could hide stderr to make this clearer.
