### ISSUE TITLE
Request clarficiation of behavior for `accumulate` peg special

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet#547]
Given:
```
 (peg/match ~(sequence (capture "a" :hi)
                       (backref :hi)
                       (backref :hi))
             "aaa")
 # => @["a" "a" "a"]
```
I was surprised by the behavior of:
```
 (peg/match ~(sequence (accumulate (sequence (capture "a" :hi)
                                             (backref :hi)))
                       (backref :hi))
             "aaa")
 # => nil
```
Based on my reading of the website docs for the peg specials, I would have thought that the match would succeed, but it looks like the last `backref` does not.

Looking at peg.c I see: https://github.com/janet-lang/janet/blob/665b1e68d5b53cb294f7752c5e7c8f40f8d9fec9/src/core/peg.c#L382-L391

So it looks like in line 391, `cap_load` is called with `cs` returned from line 382.  I guess that means that tags created in `accumulate` don't outlive `accumulate` so-to-speak.

Is this the intended behavior?

**Comment by sogaiu** [comment]
I guess `group` is similar:
```
(peg/match ~(sequence (sequence (position :hi)
                                (backref :hi))
                      (backref :hi))
            "000")
# => @[0 0 0]

(peg/match ~(sequence (group (sequence (position :hi)
                                       (backref :hi)))
                      (backref :hi))
            "000")
# => nil
```
https://github.com/janet-lang/janet/blob/665b1e68d5b53cb294f7752c5e7c8f40f8d9fec9/src/core/peg.c#L409-L422

The `cap_save` and `cap_load` appear to surround `peg_rule` as in the case of `accumulate`.

**Comment by bakpakin** [comment]
Captures are implemented as a stack, and some combinators will pop captures from the stack - the fact that a capture is referenced by backref or has a tag does not change that. This is why `accumulate` and `group` get rid of the tagged capture and cause backref to fail (as you have pointed out).

One interesting solution to these issues is two use separate stacks for tagged captures and normal captures.
Combinators like accumulate and group could then reset the normal capture stack on success, but keep the tagged capture stack as is. On match failure, you would still reset both stacks though.

**Comment by sogaiu** [comment]
I tried out the new version on 4 projects that have a fair bit of use of `peg/match` and all of the tests still pass :)
