### ISSUE TITLE
Suggestion: docs need a table of contents

### ISSUE THREAD

**Issue by anentropic** [janet-lang/janet#561]
"Documentation" link on the Janet homepage links to:
https://janet-lang.org/docs/index.html

It just starts in as "page 1" of the docs, with next/previous links at the bottom.  It seems like the only way to browse the docs is to read it in order, page by page?

It would be useful for `index.html` to have a Table of Contents, linking directly to all the pages in the docs.

**Comment by anentropic** [comment]
Oh..

What I thought was a "back button" in the top left of the page opens out a menu panel with the table of contents in it.

This is quite obscure, and I think the icons normally work the other way around (i.e. show the "hamburger" icon to indicate you can open a menu and "arrow" or "x" to close it)

**Comment by uvtc** [comment]
I know at one point @bakpakin changed the default to always show the docs nav menu.

**Comment by bakpakin** [comment]
Website related issues should go to https://github.com/janet-lang/janet-lang.org/issues
