### ISSUE TITLE
Docs/source arity mismatch

### ISSUE THREAD

**Issue by dracconi** [janet-lang/janet#566]
Some functions (still ?) have different arity than declared in docstrings.

net/flush
https://github.com/janet-lang/janet/blob/master/src/core/net.c#L583

and I feel like I've seen at least another one somewhere else.

Is this intended? Which one is correct?

**Comment by pepe** [comment]
The `net/flush` is definitely a bug, as intended use `(net/flush stream)` errors on arity mismatch. PR won't be that hard. And it is definitely worth to go through all the instances and do them in one swoop. 

If you know about other examples, please can you add them to this issue?

**Comment by dracconi** [comment]
`debug/break` also shows similar behavior (wants 3 instead of 2), I've just remembered now.
I guess it is possible that there are other functions like that.

**Comment by bakpakin** [comment]
Thanks for finding this - net/flush is not an oft used function and it's signature is indeed a bug.
