### ISSUE TITLE
Allow negative index for get

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#575]
Should `get` allow negative indices (to indicate items with respect to their location from the tail end of the indexed object)?

@sogaiu pointed out to me that to get the `n`'th from the end of an array `arr`, this works:

    (get arr (- (length arr) n))
    # for example, the third item from the end
    (get arr (- (length arr) 3))

but it would be very convenient to instead write:

    (get arr -3)

Should it work likewise for strings?

See also #207 .

Would implementing this cause a problem, given that `get` returns `nil` when an index is out of bounds?

**Comment by uvtc** [comment]
I notice that some other functions that operate on indexed objects allow the negative indices (`array/insert`, and `array/slice`).

**Comment by pepe** [comment]
I am not sure the simplicity of `get` is a good price for this. I always use `array/slice` when I need this stuff. 

But in the linked issue, it is said it is possible and "probably useful," so ...

**Comment by andrewchambers** [comment]
I think it throws away some error detection in favor of convenience, it might be a valid trade off to consider.

**Comment by pyrmont** [comment]
Isn't `in` ([API](https://janet-lang.org/api/index.html#in)) available if you want to know if the index is out of bounds?

**Comment by andrewchambers** [comment]
Yes, thats a good point.

It is worth nothing this is also a backwards incompatible change. Consider a loop that decrements a counter until get returns nil.

**Comment by skuzzymiglet** [comment]
Perhaps we could have a new function for this (for compatibility and clarity). Maybe `index` (can't think of a clear name :))?

**Comment by uvtc** [comment]
I just noticed [in the docs](https://janet-lang.org/docs/data_structures/index.html) it says:

> "Similar to the `get` function and added in v1.5.0, the `in` function also get values contained in a data structure but will throw errors on bad keys to arrays, tuple, and string-likes. You should prefer `in` going forward as it can be used to better detect errors. For tables and structs, in behaves identically to `get`."

So, it sounds like `get` should not receive any changes, since `in` is preferred anyway. And, as @andrewchambers points out, it is backwards incompatible.

Closing this issue.
