### ISSUE TITLE
table/clone doesn't make a deep copy

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#576]
The docs for `table/clone` say:

"Create a copy of a table. Updates to the new table will not change
the old table, and vice versa."

Is the following a bug?

~~~clojure
repl:82:> (def t @{:a @[33 44] :b "hi"})
@{:a @[33 44] :b "hi"}

repl:83:> (def t2 (table/clone t))
@{:a @[33 44] :b "hi"}

repl:84:> (put (t :a) 1 99)
@[33 99]

repl:85:> t
@{:a @[33 99] :b "hi"}

repl:86:> t2
@{:a @[33 99] :b "hi"} #; Yikes! Docs said updates to one table wouldn't change the other.
~~~

**Comment by pyrmont** [comment]
I don't think this is a bug. The update of the array `@[33 44]` is not updating either `t` or `t2`; it's updating the value that is in those tables.

**Comment by uvtc** [comment]
Is the docstring accurate? The docstring suggests to me that `table/clone` does a deep clone.

**Comment by pyrmont** [comment]
I think it's easy to misread it but strictly speaking accurate. The `put` function in your example is not updating the table, it is updating the value in the table.

That said, if something is strictly speaking accurate but nevertheless causes confusion, that seems bad to me. A change to the docstring that mentions that it does not perform a deep clone (or that delineates more clearly between updates to the table itself versus the keys and values in the table) seems like a good idea to me.

**Comment by pepe** [comment]
I have an issue with this before, but getting why the array update like this, updates it in both tables, actually helped me understand data structures in Janet better. 

The note to the docs, though, will be appropriate.
