### ISSUE TITLE
Range function with negative step

### ISSUE THREAD

**Issue by quan-nh** [janet-lang/janet#58]
Currently Janet don't support range with negative step, I think it could be nice to have it :D
```clj
$ janet
Janet 0.4.0-235019e

> (range 10 0 -1)
@[]
```

**Comment by bakpakin** [comment]
Good point. For the time being, try `(seq [i :down [10 0]] i)`

**Comment by bakpakin** [comment]
I've added a negative step to range, so now it's pretty similar to python's range.

```clojure
Janet 0.4.0-624be87  Copyright (C) 2017-2019 Calvin Rose
janet:0:> (range 10 0 -1)
@[10
  9
  8
  7
  6
  5
  4
  3
  2
  1]
```

**Comment by quan-nh** [comment]
oh wow it's quite fast. Let me check it out!
