### ISSUE TITLE
Set data structures

### ISSUE THREAD

**Issue by quan-nh** [janet-lang/janet#59]
Currently the only way to have this is use keys from `table` data structures with unused values.

Is there any plan to support Set data structure in the core?

**Comment by bakpakin** [comment]
Probably not as a core data structure, although it would be possible to add one as an abstract type. Abstract types cannot emulate all of the features of built in types right now, such as length, hash, equality, call, and print methods, but I would consider adding some of these features to the abstract type interface.

All that said, I think there is benefit to using a few core data structures - enough for many use cases, but few enough that generic functions will work without modification on them.

You could of course also do something like:

```clojure

(defn make-set 
  [& els]
  (let [tab @{}]
    (each el els (put tab el true))
    (table/to-struct tab)))

(make-set :a :b :c)
# -> {:c true :a true :b true}
```

**Comment by quan-nh** [comment]
oops, I don't know about `abstract types`, what do we already have for now?

**Comment by bakpakin** [comment]
Abstract types are native C types, you would have to write your own in C. I would recommend using tables, though.

**Comment by mdwhatcott** [comment]
The [package index](https://github.com/janet-lang/pkgs/blob/master/pkgs.janet) references [janet-set](https://github.com/MikeBeller/janet-set), an implementation of set types in Janet.

> Janet-set uses janet-abstract (https://github/mikebeller/janet-abstract.git) in order to create a new abstract type directly in Janet. This allows us to "hook" into get/put/tostring/next so that our sets will support length calls, normal Janet iteration, and print out in a sensible way.
