### ISSUE TITLE
Indented text in docstrings breaks (doc)

### ISSUE THREAD

**Issue by yumaikas** [janet-lang/janet#595]
To reproduce, evaluate this via Janet.

    (defn myfunc 
    ```
        Indented text in multiline strings breaks doc.
    ```
    [] nil)
    
    (pp (doc myfunc))

**Comment by sogaiu** [comment]
I reproduced with 4 spaces.

Didn't seem to happen here with 2, 3, or 5 spaces.

**Comment by bakpakin** [comment]
Fixed in bd2e3350632a5aae0e25d9613dc3f6c4e49722f3.
