### ISSUE TITLE
support for module docstring?

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#598]
I think it would be useful to be able to document a module as a whole with its own module-level docstring.

In gitter, @bakpakin mentioned 

> I think it would be better to use a dyn for that, i.e `(setdyn :doc "My docstring")` at the top level. This adds a :doc key to the module table.

If, at the top of a module, if there were a backticked longstring there, would it make sense to interpret that as the above `(setdyn :doc ...)`? Or is that too much magic? It's not too much extra trouble to write out the `setdyn` call --- especially considering that the docstring itself would probably be at least a paragraph, but the setdyn call isn't obvious.

I tried just putting a longstring at the top of a test module, and (as I'd expect) Janet doesn't complain about it.

**Comment by subsetpark** [comment]
@pyrmont thinking on this, if there were module-level docstrings, one could also optionally "untangle" the functions from different modules in the Documentarian docs, printing module-doc/function docs sequentially. Ultimately of course you could imagine something like [ex_doc](https://github.com/elixir-lang/ex_doc)

**Comment by pepe** [comment]
I would use the top-level `setdyn`.

**Comment by subsetpark** [comment]
Though yes, in reference to the above question, I'd be very happy to explicitly `setdyn` rather than relying on magic.

**Comment by uvtc** [comment]
If, in my foos.janet file, I have:

~~~
(setdyn :doc ```This is my docstring.

It is your usual, run-of-the-mill docstring.

Bye.
```)

(defn do-stuff
  [x]
  (print (string "in do-stuff, " x)))
~~~

And, from the shell I do:

~~~
~/temp$ janet
Janet 1.13.1-local linux/x64 - '(doc)' for help
repl:1:> (import foos)
@{foos/do-stuff @{:private true} _ @{:value <cycle 0>}}
repl:2:> (foos/do-stuff 3)
in do-stuff, 3
nil
repl:3:> (doc foos)
symbol foos not found.
nil
~~~

How can I read that module-level doc?

**Comment by pepe** [comment]
Oh. I do not if or how it should work. It was pure: what I would like to see.

**Comment by subsetpark** [comment]
@uvtc you wouldn't get it through `import`. As of right now, you would do something like this: 

scratch.janet
```
(setdyn :doc "This is a module doc")
```

repl:
```
repl:1:> (require "/env")
@{useful-value @{:source-map ("env.janet" 1 1) :value "OM"} :doc "Docstring for module" :current-file "env.janet" :source "env.janet"}
```

Which would make that available to an application like Documentarian which called `require` or `dofile`. 

On the other hand, to make `(doc)` understand that value would require a change to the Janet stdlib itself.

**Comment by uvtc** [comment]
Oh, I see. I can `(require "foos")` and then `(print (foos :doc))` to get that module's doc.

Would it make sense for `doc` to special-case module-level docs, such that, for a module you've already imported, it would do something like:

~~~clojure
(let [m (require (string (quote some-mod)))]
  (print (m :doc)))
~~~

for you?

I think it would be very natural to import a module and then do `(doc that-module)` to get the gist of it.

**Comment by pyrmont** [comment]
Building on @uvtc's suggestion, I submitted a PR that would support `(doc <module>)`. I didn't think a call to `(doc)` should load code, so I search `module/cache` rather than use `(require)`. What do you all think?

**Comment by pepe** [comment]
The PR is merged :tada: so I guess you can close this @uvtc.

**Comment by uvtc** [comment]
Woot!
