### ISSUE TITLE
math/pi

### ISSUE THREAD

**Issue by tankf33der** [janet-lang/janet#61]
suite4.janet can pass only 10 of 22 tests on SPARC.
it cant pass this trivial assert for example:
```
(assert (= (string (buffer/format @"" "pi = %6.3f" math/pi)) "pi =  3.142") "%6.3f")
```

SPARC:
```
janet:50:> (buffer/format @"" "pi = %6.3f" math/pi)
@"pi =  3.141"
janet:91:> 
```

LINUX:
```
Janet 0.4.0-4a2d4f5  Copyright (C) 2017-2019 Calvin Rose
janet:0:> (buffer/format @"" "pi = %6.3f" math/pi)
@"pi =  3.142"
janet:41:>
```

**Comment by bakpakin** [comment]
Ok, this is certainly due to either a buggy implementation of printf in solaris or a different default rounding mode (maybe round to 0?). There really isn't much we can do about this other than remove the check, or investigate setting the rounding mode on solaris, if that is indeed the issue.
