### ISSUE TITLE
Remove value from table

### ISSUE THREAD

**Issue by Arteneko** [janet-lang/janet#617]
Hello, I've been searching on both janetdocs and the janet-lang website, but couldn't find anything...

Is there a way to remove a value from a table (ideally freeing the allocated memory along the way, or marking it for freeing)?

I see that [the C code for `table`](https://github.com/janet-lang/janet/blob/master/src/core/table.c#L171-L185) has something to do that, but I cannot seem to find the janet keyword bound to that.

**Comment by pepe** [comment]
Just put nil under the key, so it is not referenced and GCed later.

**Comment by uvtc** [comment]
Yes, `(put some-tbl :some-key nil)` does it. Arrays/tuples can have `nil`s in them, but tables/structs cannot.
