### ISSUE TITLE
file/open - Missing flag or misleading docs

### ISSUE THREAD

**Issue by Saikyun** [janet-lang/janet#618]
Docs claim that there is a `:n`-flag, but when trying to use it:

```
Janet 1.14.2-meson macos/x64 - '(doc)' for help
repl:1:> (file/open "a" :n)
error: invalid flag n, expected w, a, or r
  in file/open
  in _thunk [repl] (tailcall) on line 1, column 1
```

Not sure if the flag is useful (one could just run `(when (not f) (error "..."))`), so I'm not sure if the docs or the code needs to be changed. :)

Using `with` though, the above method doesn't work, because `with` seems to run `(:close nil)` when erroring. So not sure how to avoid that. :)

**Comment by pepe** [comment]
I guess there needs to be some other flag (e.g. :r :w). 

You can definitely throw your own error :-). 

Usage with `with` does not make sense for me.

**Comment by sogaiu** [comment]
It seems the order of the flags might matter?
```
repl:2:> (file/open "a" :nr)
error: invalid flag n, expected w, a, or r
  in file/open
  in _thunk [repl] (tailcall) on line 2, column 8
```
```
repl:3:> (file/open "a" :rn)
error: failed to open file a: No such file or directory
  in file/open
  in _thunk [repl] (tailcall) on line 3, column 8
```

**Comment by sogaiu** [comment]
Haven't really used `with`, but wonder if this might work:
```
(with [f (file/open "a" :r)
         |(when $ (:close $))]
  :smile)
```

**Comment by Saikyun** [comment]
New docs makes sense to me. :) Thanks.
