### ISSUE TITLE
feature request: apropos function

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#619]
Would like to be able to search the list of all built-in function names (including the ones in the standard/built-in modules) for a fragment of a function name. As in:

~~~
$ janet
repl> (apropos "env")

  * curenv
  * debugger-env
  * env-lookup
  * make-env
  * root-env

  * fiber/getenv
  * fiber/setenv

  * os/environ
  * os/getenv
  * os/setenv

repl>
~~~

Clojure has something like this, but returns a list of names, rather than pretty-printing them out.

I think this would make it easier to learn one's way around the Janet functions. It helps new users who encounter:

~~~python
repl> (doc push)
nil
# Wait, how do I push onto an array?
repl> (apropos "push")

  * array/push
  * buffer/push

repl>
~~~

See also `man apropos` (eg, try, `$ apropos who`).

**Comment by sogaiu** [comment]
Not sure if this is quite what you're looking for, but have you tried:
```
repl:1:> (doc "push")

    Bindings:

    array/push buffer/push buffer/push-byte buffer/push-string
    buffer/push-word

    Dynamics:



    Use (doc sym) for more information on a binding.

nil
```

**Comment by uvtc** [comment]
Wow! Ooof, I'm sorry to say I didn't even try that first (assuming `doc` only did one thing). Thanks, @sogaiu .

I'll add an example to JanetDocs. Closing this issue.
