### ISSUE TITLE
Temple is broken with latest Janet

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#621]
I am creating an issue here cause it is clearly dependent on the Janet version. But maybe Temple needs a simple fix, in which case I will be happy to move it to `spork` repo.

Anyway, after 72ec89df Temple stopped rendering any text, which is not in the Janet code blocks. Simple reproduction: 

`(import spork/temple) ((temple/create "Temple") {})` => `nil`

I guess it could be related to the parser changes introduced in this commit.

**Comment by bakpakin** [comment]
Yes, parser/insert was broken, has been fixed. Thanks for finding.

**Comment by pepe** [comment]
Thank you very much for fixing it, it works perfectly indeed.

The bug had one very nice consequence for me, as I went on to study Temple more to see what could be wrong. And I think I finally got it (I know), and many things are much clearer for me, not only about the Temple but about the parsing/compiling stuff and module loaders.
