### ISSUE TITLE
Integer hashing performance regression

### ISSUE THREAD

**Issue by leahneukirchen** [janet-lang/janet#625]
Before 2ec12fe0, creating a hash of a few hundred thousand numbers was pretty fast:

Elapsed time: 0.0191133 seconds
Elapsed time: 0.0166576 seconds
Elapsed time: 0.0131128 seconds
Elapsed time: 0.0202494 seconds
Elapsed time: 0.0245321 seconds

After (and on HEAD =  ff24143f54e69), it gets really slow:

Elapsed time: 0.00921917 seconds
Elapsed time: 0.0966475 seconds
Elapsed time: 1.35149 seconds
Elapsed time: 5.0998 seconds
Elapsed time: 9.01904 seconds

<details>
<summary>sample code</summary>

```
(defmacro timeit
  ```Time the execution of `form` using `os/clock` before and after,
  and print the result to stdout.  returns: result of executing `form`.
  Uses `tag` (default "Elapsed time:") to tag the printout.```
  [form &opt tag]
  (default tag "Elapsed time:")
  (with-syms [start result end]
    ~(do
       (def ,start (os/clock))
       (def ,result ,form)
       (def ,end (os/clock))
       (print ,tag " " (- ,end ,start) " seconds")
       ,result)))

(timeit
 (do
   (def squares @{})
   (for i 0 40_000
     (set (squares (* i i)) true))))

(timeit
 (do
   (def squares @{})
   (for i 0 50_000
     (set (squares (* i i)) true))))

(timeit
 (do
   (def squares @{})
   (for i 0 60_000
     (set (squares (* i i)) true))))

(timeit
 (do
   (def squares @{})
   (for i 0 70_000
     (set (squares (* i i)) true))))

(timeit
 (do
   (def squares @{})
   (for i 0 80_000
     (set (squares (* i i)) true))))
```

</details>

**Comment by bakpakin** [comment]
Hmm, I guess trying to be too clever here is not worth it. It is probably best to remove this code.
