### ISSUE TITLE
string/trim functions

### ISSUE THREAD

**Issue by quan-nh** [janet-lang/janet#63]
Can we add the string/buffer `trim` `triml` `trimr` into core. I see currently it's missing.

**Comment by bakpakin** [comment]
We could add this, it's use is common enough to be warranted as part of the core.

For trim implemented with pegs:

```clojure
(def- trimmer (peg/compile
  '{:space " "
    :no-space (if-not :space 1)
    :main (* (any :space) '(any (* (any :space) (some :no-space))))}))

(defn trim [str]
  (if-let [matches (peg/match trimmer str)]
    (matches 0)))
```

Implementing triml and trimr would be a good exercise.

**Comment by quan-nh** [comment]
I think space could be any white-space characters, so for peg `:space (+ " " "\t" "\n" "\v" "\f" "\r")`

**Comment by bakpakin** [comment]
Added in 232ea22dc55be28366b56147fd80ccff8ec1de46.
