### ISSUE TITLE
jpm support other VCS

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#631]
I think the lockfile and also jpm file format is heavily biased towards git. Not sure the best approach to address this, but perhaps at a minimum the lockfile format should have a :kind field or something to disambiguate.

**Comment by bakpakin** [comment]
Agreed. I think it would be good to start with something simple like tarball support, but to add more artifact types it becomes needed to start bundling binary code into jpm, or rely on the user having a variety of binaries on their system. On posix it is fine to assume core utils I think, but windows is a different story.

**Comment by andrewchambers** [comment]
I might be wrong, but i think windows 10 might come with tar now.

**Comment by sogaiu** [comment]
This sort of thing?

https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows/
https://techcommunity.microsoft.com/t5/containers/tar-and-curl-come-to-windows/ba-p/382409

**Comment by pyrmont** [comment]
An alternative to adding a `:kind` key, would be to use the kind of the artefact as the key:

```janet
# current
:dependencies [{:repo "https://github.com/joy-framework/joy" :tag "0.5.2"}]

# proposed
:dependencies [{:git "https://github.com/joy-framework/joy" :tag "0.5.2"}
               {:tar "https://example.org/dep.tar"}]
```

If you have a struct with conflicting keys (e.g. both `:git` and `:tar` are defined), `jpm` could quit with an error. `jpm` could continue to treat a plain string as a URL to a Git repository. `:repo` could be deprecated but continue to resolve to a Git repository for backwards compatibility reasons.

As for supporting different tools, `jpm` could attempt to use the tool associated with the type of artefact (e.g. `tar` for `:tar`) and if it's not available, quit with an error.

**Comment by bakpakin** [comment]
@pyrmont jpm now supports a `:type` tag and can get tarballs as well as git repositories.

**Comment by pyrmont** [comment]
@bakpakin I'm looking at [janet-lang/jpm](https://github.com/janet-lang/jpm) and `resolve-bundle` looks like it supports:

```
# dictionary
{:repo "https://example.org/dep.tar" :type :tar}

# string
{"tar::https://example.org/dep.tar"}
```

Is that right?
