### ISSUE TITLE
`varfn` can result in a prefixed function name

### ISSUE THREAD

**Issue by subsetpark** [janet-lang/janet#634]
This is a weird edge case; it's a consequence of how `defn foo ...` expands to `(def foo (fn foo ...))`.

Here's two modules:

```
# a.janet
(varfn f [] :one)
```

```
# b.janet
(import /a)
(varfn a/f [] :two)
```

`a` defines a variable function, and then `b` mutates the reference that `a/f` points to. 

We can see a log of activity here:

```
repl:1:> (import /a)
repl:2:> (a/f)
:one
repl:3:> (import /b)
repl:4:> (a/f)
:two
```

As we'd expect, `b` is able to change the behaviour of `f` when called from any environment, even if `f` had already been imported.

However, there is one unfortunate side effect of the second `varfn` call:

```
repl:5:> (disasm a/f)
{:max-arity 0 :constants @[:two] :name "a/f" :defs @[] :vararg false :environments @[] :arity 0 :slotcount 2 :bytecode @[(lds 0) (ldc 1 0) (ret 1)] :sourcemap @[(2 1) (2 1) (2 1)] :source "b.janet" :min-arity 0}
```

The second `varfn` call created a function with the fully-prefix name. 

It's a bit of a double bind. The function is bound to `a/f` within the second module, so that is of course how it needs to refer to it in order to mutate the reference. However, because `def` and `fn` are both given the same parameter, that same symbol - `a/f` - is used as the new name of the function.

**Comment by bakpakin** [comment]
I don't really consider this much of an issue - the name of a function is basically not used except for debugging. Arguably, this could help distinguish which instance of the varfn we are using.

**Comment by subsetpark** [comment]
Suits me... @bakpakin if you want to tag this wontfix I can close. Good to have as documentation.
