### ISSUE TITLE
jpm silently ignores build errors

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#638]
In a shell without go installed `jpm install https://github.com/andrewchambers/poolparty` fails to install poolparty (the failure is expected)... But it seems like janet is ignoring and hiding build errors, the build and also the install has failed, the jpm exit code is still 0.
```
[nix-shell:~]$ jpm install https://github.com/andrewchambers/poolparty
cloning repository https://github.com/andrewchambers/poolparty to /tmp/derp/.cache/https___github.com_andrewchambers_poolparty
Cloning into '/tmp/derp/.cache/https___github.com_andrewchambers_poolparty'...
remote: Enumerating objects: 1142, done.
remote: Counting objects: 100% (1142/1142), done.
remote: Compressing objects: 100% (707/707), done.
remote: Total 1142 (delta 441), reused 1058 (delta 358), pack-reused 0
Receiving objects: 100% (1142/1142), 2.20 MiB | 1.73 MiB/s, done.
Resolving deltas: 100% (441/441), done.
no dependencies found

[nix-shell:~]$ echo $?
0
```

If I manually clone poolparty and run jpm install, then I correctly see the error. os/execute failed to build poolparty
because go was not installed.

```
[nix-shell:~/src/poolparty]$ jpm install
("go" "build" "-mod=vendor" "-o" "./build/poolparty" "./cmd/poolparty/main.go"): No such file or directory
  in os/execute
  in shell [/nix/store/vg73iml2g4ihmcczsc5gljhqbm8jh1kh-janet-1.15.2/bin/jpm] (tailcall) on line 141, column 12
  in do-rule [/nix/store/vg73iml2g4ihmcczsc5gljhqbm8jh1kh-janet-1.15.2/bin/jpm] on line 262, column 26
  in do-rule [/nix/store/vg73iml2g4ihmcczsc5gljhqbm8jh1kh-janet-1.15.2/bin/jpm] on line 258, column 44
  in do-rule [/nix/store/vg73iml2g4ihmcczsc5gljhqbm8jh1kh-janet-1.15.2/bin/jpm] (tailcall) on line 258, column 44
```

**Comment by pepe** [comment]
I can confirm the same behavior here.

**Comment by sogaiu** [comment]
Confirmed here too.

Possibly obvious, but FWIW, this line appears to be executed: 
https://github.com/janet-lang/janet/blob/master/jpm#L170-L171

but this one doesn't appear to be reached:
https://github.com/janet-lang/janet/blob/master/jpm#L173

So what's in between is:
```
 (def res (os/execute args :p))
```

**Comment by bakpakin** [comment]
So an investigation yields that this has nothing to do with the event loop or even os/execute - there seems to be an issue where errors are being swallowed when wrapped with a combination of `try` and `with-dyns`. Still looking into it

**Comment by andrewchambers** [comment]
That explains why it I saw nothing on valgrind or with thread sanitizer. Also explains why it was so reproducible, thanks for investigating.
