### ISSUE TITLE
The to PEG combinator doesn't work with -1

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#640]
I am not sure if the [documentation](https://janet-lang.org/docs/peg.html) needs to be updated but the `to` PEG combinator doesn't work if the pattern is `-1`.

## Input

```janet
(peg/match ~'(to -1) "foo")
```

## Expected

```janet
@["foo"]
```

## Actual

```janet
nil
```

**Comment by sogaiu** [comment]
Not sure if it breaks other things, but assuming the behavior described by pyrmont is desirable, changing `peg.c` line 299 from:
```
            if (text >= s->text_end) {
```
to:
```
            if (text > s->text_end) {
```
seems to work for the specific case mentioned.

(https://github.com/janet-lang/janet/blob/master/src/core/peg.c#L299)

**Comment by pepe** [comment]
Maybe it is just me, but I would be happy to have this functionality, as it is a very common operation in my PEGs to match everything till the end of the string.

**Comment by pyrmont** [comment]
Thanks @bakpakin!
