### ISSUE TITLE
Proposed: move `path` into standard library

### ISSUE THREAD

**Issue by subsetpark** [janet-lang/janet#645]
I know we generally want to follow a policy of keeping the stdlib small and moving common utilities into spork, but I want to propose violation of that rule: I think that `path` is useful enough, and theoretically close enough to the functionality of `os/`, that it should be in the standard library.

In particular, I think it's *extremely* useful for writing `project.janet` files. Especially for native libraries that need to pass in cflags and include directories, it would be very nice to write these in as OS-agnostic a way as possible. This includes being able to create directory paths. It would be convenient for me as a library writer to be able to use path's directory join logic without having to add dependencies for the project.janet file.

**Comment by sogaiu** [comment]
I would like to hear why it was not included originally (and continued to be left out).

**Comment by bakpakin** [comment]
I still don't plan on adding this. It might be reasonable to include that path stuff in the core but I really want to resist the urge to dump everything into the core.

As for creating directory paths, just use unix style paths. Windows supports it. The path stuff is more the exception to the rule when you either can't use unix paths or don't want to.

As for why is was left out, it is simply not required by any other parts of the core distribution (originally). You could also ask why any other particular functionality was left out.

**Comment by sogaiu** [comment]
Thanks for the explanation, very much appreciated.

**Comment by andrewchambers** [comment]
it should be noted that project.janet files can use dependencies that they declare for themselves already.

**Comment by bakpakin** [comment]
Closing as WNF.
