### ISSUE TITLE
Add `JANET_NO_THREADS` macro for consistency

### ISSUE THREAD

**Issue by skuzzymiglet** [janet-lang/janet#647]
When building, it's much easier to use a `JANET_NO_*` macro on the command line than to edit config.h

What do you think of adding a JANET_NO_THREADS macro? This would also be consistent with `JANET_NO_PEG` etc.

**Comment by bakpakin** [comment]
Because there is already a macro JANET_SINGLE_THREADED that can be defined for that. This ends up doing a bit more than just disabling the thread library though, so perhaps a similar macro could be added.

**Comment by bakpakin** [comment]
This has been added recently, in anticipation of the deprecation and removal of the threads module.
