### ISSUE TITLE
Moving core functionality into modules

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#652]
## Problem

Janet exposes all core functionality via the environment loaded at boot.¹ This essentially requires all core functionality to be added to `boot.janet` and bloats the `janet` binary.

A consequence of this is that functionality that might be useful to come as part of the Janet installation is either moved into a separate tool (in the case of `jpm`) or a separate dependency (in the case of spork). Neither approach provides a good user experience. In the former approach, this functionality cannot be used by other modules (as discussed in #601). In the latter approach, a separate dependency must be installed.

¹ I think this is wrong technically but I believe is consequentially the same as how things work at present. Happy to correct if anyone wants to rephrase.

## Possible Solution

My suggestion would be to:

1. extract functionality into `.janet` files saved into the repository at `src/modules`;
2. copy these modules at installation into a `core/` subdirectory of the directory pointed to by `JANET_PATH`;
3. add a module loader that searches the `JANET_PATH` directory used at installation (as opposed to the directory `JANET_PATH` points to at a later time).

These modules could then be called like so:

```janet
(import core/jpm)
```

This would require adding a non-dynamic binding to `boot.janet` to save the `JANET_PATH` directory used at installation. Currently that value is saved to the dynamic binding `:syspath` but that binding can be overwritten.

## Alternatives

* You could skip the third step above. Unfortunately, that solution will break if the user sets `JANET_PATH` to be a location different to that used at installation. I happen to do this so that I can keep modules local to the project I'm working on.

**Comment by andrewchambers** [comment]
Not sure which functionality you are referring to other than just having a jpm.janet module installed along side the default install?

**Comment by pyrmont** [comment]
I confess the term 'core functionality' here is a bit loose. I had in mind, two things:

1. Current functionality which is useful to have available with the standard installation (e.g. the int module or the tarray module) but which is not something you want loaded in every default environment. The proposal here would make selective loading easier.

2. Future functionality which it might reasonably be decided should be part of the standard installation (e.g. the jpm stuff) but which would bloat `boot.janet`.

**Comment by bakpakin** [comment]
Moving a stuff into a module really just means it would be a separate library, and could be packaged as such. As for the typedarray stuff, I agree that that really doesn't need to be in the core library, and TBH I think the design there is a bit heavyweight and there aren't many users of it that I know of.

Otherwise though, there really isn't a lot of reason for me to move things like the 'int' module out of the core.
Lastly, as far as making parts of the core library in Janet loadable as modules, that runs counter to making Janet  easy to embed in other programs (via janet.c and janet.h).

As far as 'standard' stuff goes, I am not going to distribute a standard library of modules _alongside_ janet, but common useful functionality has been moving into spork.

**Comment by pyrmont** [comment]
@bakpakin Sorry, I'm a bit confused. In a [comment](https://github.com/janet-lang/janet/issues/601#issuecomment-763215671) to #601, you wrote:

> Yeah, if anything I would like to start slimming down boot.janet, not adding 1000 lines of code.
> 
> That said, I agree that it would be nice if jpm could be used as a normal module and not just a script.

If you're not going to have some kind of module-like system for certain functionality, how can the functions in `jpm` be made available in a module-like manner?
