### ISSUE TITLE
Feature request: function to run and get output from command-line program

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#659]
My understanding is that if I want to grab the output of a command-line program like `date` or `find . -name '*.txt'`, I need to do something like this:

~~~clojure
(defn shell-out
  [cmd]
  (let [x (os/spawn cmd :p {:out :pipe})
        s (:read (x :out) :all)]
    (:wait x)
    s))

(def date-string (shell-out ["date"]))
(def txt-files   (shell-out ["find" "." "-name" "*.txt"]))
~~~

(adapted from [discussion](https://github.com/janet-lang/janet/discussions/654)).

Though @andrewchambers pointed out to me that it doesn't throw an error if the command fails to return 0.

It would be convenient if Janet provided such a function. I can't think of a better name for it ... I think Perl calls theirs `system`. Python's is `subprocess.check_output`.

**Comment by uvtc** [comment]
This came up because I didn't know about `os/mktime` and was trying to use `date` to convert a date-string to seconds-since-epoch.

So, I see that maybe the lesson for me is, find the right function instead of rushing to shell out. :)

**Comment by pepe** [comment]
I think the issue is real, but I do not see any problem using `os/spawn`, as these operations tend to be async anyway. Well, not for the `date` :).

Also, I usually use them often enough to create macro tailored for the use case in the places I need them.

Anyway, I feel the issue is safe to close.
