### ISSUE TITLE
string/match function

### ISSUE THREAD

**Issue by jfcap** [janet-lang/janet#66]
I've ported Lua string.match function to janet. 
(It was not a lot of work, mostly copy/paste)
I know we have pegs, and it's really great and powerful.
But for basic pattern matching, I've always found that simple lua style regex are very handy.

```
janet:210:> (string/match "hello janet 123" "(%w+)%s*(%w+).-(%d+)")
@["hello" "janet" "123"]
```

If you are interested the patch is here :

https://github.com/jfcap/janet.git (branch string-match)

The code needs probably some cleanup (useless unsigned/signed char conversions, ...)
Not sure it must be included in core (an extern module can do the job).

This can be adapted to "upgrade" the string/find function.

**Comment by jfcap** [comment]
I've ported Lua string.match function to janet. 
(It was not a lot of work, mostly copy/paste)
I know we have pegs, and it's really great and powerful.
But for basic pattern matching, I've always found that simple lua style regex are very handy.

```
janet:210:> (string/match "hello janet 123" "(%w+)%s*(%w+).-(%d+)")
@["hello" "janet" "123"]
```

If you are interested the patch is here :

https://github.com/jfcap/janet.git (branch string-match)

The code needs probably some cleanup (useless unsigned/signed char conversions, ...)
Not sure it must be included in core (an extern module can do the job).

This can be adapted to "upgrade" the string/find function.

**Comment by bakpakin** [comment]
Pretty neat, although I'm not sure we need both patterns and pegs - I think packaging this as an external module would make sense. I'm all for embedding DSLs in janet, but I think having too many is a mistake for the core.

Something could be done to make pegs less verbose, such as including some default character classes and a shortest match operator, which I think might help with 75% of the problems of pegs when compared to Lua patterns (more verbose, missing some non greedy features that must be emulated in pegs).

```clojure
(peg/match ~(* '(some :w) (any :s) '(some :w) (any- 1 '(some :d))) "hello janet 123")
```

**Comment by jfcap** [comment]
> but I think having too many is a mistake for the core.
Ok, this makes sense to me.
