### ISSUE TITLE
Optimisation: nested immutable constants

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#667]
```
(defn f [v]
  (def constants {:a 1 :b 2 :c [1 2 3]})
  (get constants v))
```

Currently janet does not store the struct in the function constant table even though it probably could, unsure how expensive such recursive checks would be for the compiler.

**Comment by pyrmont** [comment]
If Janet did this, would the following present any challenges?

``` janet
(defn f [v]
  (while (def c (function-that-returns-immutable-ds))
    (do-something)))
```

**Comment by andrewchambers** [comment]
No because (function-that-returns-immutable-ds-or-nil) is not a constant so the substitution would not be applied.

**Comment by andrewchambers** [comment]
Small note, the user can quite easily apply this themselves with comptime.

**Comment by bakpakin** [comment]
This should be quite doable, and I don't think would add any extra passes to the compiler - the compiler already understands the constant of a "constant" slot, so would just need to check that, when compiling a tuple or struct literal, a constant could be inline if all arguments are themselves constant slots.

**Comment by andrewchambers** [comment]
done afaik
