### ISSUE TITLE
Documentation for latest release is broken

### ISSUE THREAD

**Issue by maacl** [janet-lang/janet#678]
Please see for instance https://janet-lang.org/syntax.html which returns:

`<div xmlns="http://www.w3.org/1999/xhtml" class="line"><span class="html-tag">&lt;Code&gt;</span><span>AccessDenied</span><span class="html-tag">&lt;/Code&gt;</span></div>`

**Comment by pepe** [comment]
Hello. The link should be https://janet-lang.org/docs/syntax.html, where is the one you mentioned? 

Also, this issue would be better on the https://github.com/janet-lang/janet-lang.org/ repository.

**Comment by maacl** [comment]
Feel free to move the issue. I followed the https://janet-lang.org/introduction.html on this page https://github.com/janet-lang/janet#installation

**Comment by andrewchambers** [comment]
Yep, definitely a bug in the docs, thank you :)

**Comment by sogaiu** [comment]
I've made an issue at the janet-lang.org repository: https://github.com/janet-lang/janet-lang.org/issues/114

In my testing so far, I am getting different results depending on the browser I used...

**Comment by sogaiu** [comment]
As mentioned above ( https://github.com/janet-lang/janet/issues/678#issuecomment-813431348 ), the link in the section: https://github.com/janet-lang/janet#installation
points at: https://janet-lang.org/introduction.html

Visiting that link leads to erroneous links showing up.

Perhaps that link (the one in the Installation section) should be instead: https://janet-lang.org/docs/index.html as visting this link gives better behaving links.

If so, may be there is an issue with this repository's README.

**Comment by pepe** [comment]
I guess it was fixed by e367ecf806ca6235c286a11367be27a2ab6982c8 please @maacl can you confirm it?

**Comment by maacl** [comment]
Still broken.

**Comment by pepe** [comment]
Hmm, that's weird. For me, the link in the repo is fixed, and all the following navigations too.

**Comment by pyrmont** [comment]
I confirm it's broken for me. The link in the README in master is to `https://janet-lang.org/docs/introduction.html`. It should be `https://janet-lang.org/docs/index.html`. I have submitted a PR to fix it.

**Comment by pepe** [comment]
My bad, I clicked on the wrong link in the README. @pyrmont is indeed right. My apologies to @maacl for pinging :(.
