### ISSUE TITLE
possible bug in tuple/type

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#679]
~~~python
(def t1 '("a" "b"))
(pp (tuple/type t1)) # :parens

(def t2 ["a" "b"])
(pp (tuple/type t2)) # :parens (?)
~~~

Should `t2` print as `:brackets`?

**Comment by uvtc** [comment]
Note, I haven't found a need for `tuple/type`, but just noticed it [in the docs](https://janet-lang.org/docs/syntax.html), tried it out, ran across this behavior, and so created this issue here.

**Comment by sogaiu** [comment]
@uvtc I don't think this is a bug in `tuple/type`.

At the REPL:
```
$ janet
Janet 1.15.5-dev-2802e662 linux/x64 - '(doc)' for help
repl:1:> ["a" "b"]
("a" "b")
```

I think what we're seeing is evidence of something happening via the REPL.

Compare with:
```
$ janet
Janet 1.15.5-dev-2802e662 linux/x64 - '(doc)' for help
repl:1:> (parse "[`a` `b`]")
["a" "b"]
```

My current sense is that it is because of `compile`: https://github.com/janet-lang/janet/blob/master/src/boot/boot.janet#L2158

```
$ janet
Janet 1.15.5-dev-2802e662 linux/x64 - '(doc)' for help
repl:1:> (dyn :pretty-format)
"%.20Q"
repl:2:> (setdyn :pretty-format "%.40M")
"%.40M"
repl:3:> (disasm (compile '["a" "b"]))
{ :arity 0
  :bytecode @[(ldc 0 0) (ret 0)]
  :constants @[("a" "b")]
  :defs @[]
  :environments @[]
  :max-arity 2147483647
  :min-arity 0
  :name "_thunk"
  :slotcount 1
  :vararg false}
```

Note that the associated value for `:constants` contains a paren tuple and not a square bracket tuple.

On a side note, if you want a square bracket tuple at the REPL, other ways include:
```
$ janet
Janet 1.15.5-dev-2802e662 linux/x64 - '(doc)' for help
repl:1:> (tuple/brackets "a" "b")
["a" "b"]
repl:2:> (type (tuple/brackets "a" "b"))
:tuple
repl:3:> (tuple/type (tuple/brackets "a" "b"))
:brackets
repl:4:> '["a" "b"]
["a" "b"]
repl:5:> (tuple/type '["a" "b"])
:brackets
```

**Comment by uvtc** [comment]
Thanks, @sogaiu .

To avoid any confusion, I save that code in a file and ran the file.

Note, I'm not looking for a way to get tuples to display with square brackets in the repl. I just thought I may have stumbled upon a bug.

Since you mention `parse`, I've got no idea why `x` below displays in square brackets in the repl:

~~~clojure
repl:1:> (def x (parse "[`a` `b`]"))
["a" "b"]

repl:2:> x
["a" "b"]

repl:3:> (type x)
:tuple
~~~

I'm probably misunderstanding the point of `tuple/type`. I can't see a reason why I would need or want to know whether my tuple was written `["a" "b"]` or `'("a" "b")` in source code. :)

Also I don't see what `tuple/brackets` is doing:

~~~clojure
repl:11:> (def y (tuple/brackets 4 5 6))
[4 5 6]

repl:12:> (def z [4 5 6])
(4 5 6)

repl:13:> (= y z)
true
~~~

Thanks for your thoughts!

**Comment by sogaiu** [comment]
Regarding, `tuple/type`, I think the docs are pretty helpful:

> Checks how the tuple was constructed.

That's one of its main purposes IIUC.

Regarding what "constructed" means here, continuing in the docstring there is:

> Will return the keyword :brackets if the tuple was parsed with brackets, and :parens otherwise.

The code above that references `parse` seems consistent with this statement.

`parse` is a wrapper around using the built-in `parser/*` functions so the docstring applies to both the wrapper and typical usage of `parser/*` IIUC.

`parse` gives back a square bracket tuple if it is passed a string like `"[:a :b]"`, for example.  One can use `tuple/type` to check that `parse` created a square bracket tuple.

At the REPL when one types in the string `[:a :b]` and presses "Enter", the REPL:

1) parses (often called something like `read` elsewhere) a string to create a Janet data structure
2) the Janet data structure is then compiled to Janet byte code
3) the bytecode is executed in another fiber
4) the result of execution is "printed"

In step 2, our square bracket tuple becomes a paren tuple IIUC.

**Comment by bakpakin** [comment]
Yes, as is mentioned above this is by design. The whole notion of tuple types seems a bit strange and it was just so we could have a little bit more syntactic variety and tuple constructor literals. Outside of things like the compilers and pretty printing, tuples of either type are considered equal. A bracket tuple will construct a parenthesized tuple, which should be considered the default.

**Comment by sogaiu** [comment]
On a historical note, due to #1073, the code example mentioned in [this comment](https://github.com/janet-lang/janet/issues/679#issuecomment-815372918), now ends differently:

```janet
(def y (tuple/brackets 4 5 6))
# =>
[4 5 6]

(def z [4 5 6])
# =>
(4 5 6)

(= y z)
# =>
false
```
