### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#68]
Something that made me avoid lua in the past as a configuration language was lack of string interpolation, perhaps it is something you would consider in the core reader, though I suppose it can be done as a macro, feel free to close this if it's something you thought about.

**Comment by bakpakin** [comment]
String interpolation is probably best done by a macro, in the traditional lisp way.

You can usually get pretty dense code with just normal strings and the string function though.

```clojure
(def world "earth")
(def text (string "Hello, "world"!"))
```
