### ISSUE TITLE
table/from-pairs and struct/from-pairs as the inverse of pairs.

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet#683]
I want to construct a table or a struct from a list of pairs. For now, I just write

```
(reduce (fn [acc [k v]]
          (put acc k v))
        @{}
        pairs)
```

to turn a list of pairs into a table.

**Comment by pyrmont** [comment]
Perhaps Janet could add an `into` function similar to Clojure's ([docs](https://clojuredocs.org/clojure.core/into))? That function can be used to achieve the same effect:

```clj
(into {} [[:a "a"] [:b "b"]])
;;=> {:a "a", :b "b"}

**Comment by sogaiu** [comment]
Slightly translating that Clojure into Janet might be the following?
```
(into @{} [[:a "a"] [:b "b"]])
# => @{:a "a" :b "b"}
```

**Comment by uvtc** [comment]
Since Janet already has a `pairs` function for going one way, maybe a `from-pairs` function (or possibly `table/from-pairs`) would be nice and symmetrical for going the other way.

**Comment by sogaiu** [comment]
I'm curious about the sorts of situations that are leading to having pairs of things.

Any examples?

**Comment by andrewchambers** [comment]
I think a simple one is wanted to filter a table based on keys and values then collect the results again.

**Comment by crocket** [comment]
@sogaiu https://github.com/crocket/buku-fzf/blob/9b2b42a6859e50c98f78ea470032a5cae9274757/main.janet#L42-L71

**Comment by sogaiu** [comment]
@crocket  Thanks!

It looks like in that case that the result of doing a peg capture (i.e. an array) is a sort of pair: https://github.com/crocket/buku-fzf/blob/9b2b42a6859e50c98f78ea470032a5cae9274757/main.janet#L63-L65

**Comment by sogaiu** [comment]
@andrewchambers So if it's a table, one can go the route of changing the existing table (or not), but for a struct presumably a new one would get built.  Does that sound right?

FWIW, for the simple case of a "subset" based on keys, Clojure has `select-keys`:
```
(select-keys {:a 1 :b 2 :c 3} [:a :c])
;;=> {:c 3, :a 1}
```

**Comment by pepe** [comment]
Not to hijack the `pairs` party, but here is my `select-keys` https://git.sr.ht/~pepe/marble/tree/master/item/marble/init.janet#L34

**Comment by skuzzymiglet** [comment]
Doesn't `(table ;(flatten [[:a :b] [:c :d]]))` do this? (`[[:a :b] [:c :d]]` being the pairs)

**Comment by sogaiu** [comment]
Yes.  yumaikas' example at the following does a similar thing: https://janetdocs.com/flatten

**Comment by andrewchambers** [comment]
flatten is actually a problem if any of the elements of the pairs are themselves tuples or arrays.

**Comment by sogaiu** [comment]
Oh good point.

**Comment by skuzzymiglet** [comment]
@bakpakin I see you implemented this. Should this issue be closed?
