### ISSUE TITLE
A function that eats a single key press.

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet#689]
I want to implement `Press any key...` in my command line applications.

**Comment by bakpakin** [comment]
Will not add to the core - you should read up on the posix terminal APIs or modify some existing code. Essentially, you need to put the terminal in raw mode first and then do success reads from stdin a character at a time.

**Comment by crocket** [comment]
janet already has [rawmode function](https://github.com/janet-lang/janet/blob/f4c9064b79d5b32fd74e5ddf25266356c22dd53b/src/mainclient/shell.c#L162-L179). Wouldn't it be a good idea to expose this in core API?

**Comment by bakpakin** [comment]
This rawmode function is part of shell.c, not part of the core. shell.c is not compiled into libjanet and is just extra code to make the native janet repl a little nicer.
