### ISSUE TITLE
Feature request: importable/namespaced root env functions

### ISSUE THREAD

**Issue by subsetpark** [janet-lang/janet#691]
This feature request was inspired by [the most recent release of Gleam](https://gleam.run/news/gleam-v0.15-released/), which includes the same sort of feature.

Every so often I find myself shadowing a function from the root environment in my code. Here's an example:

```
(defadv slurp 2 ...)
```

Later, when I call `slurp`, it doesn't do what I expect. 

Now, this unexpected behaviour itself is probably impossible to avoid in a Lisp-1. But in order to get around it I need to amend the code: 

```
(def root-slurp slurp)
(defadv slurp 2 ...)
(def file (root-slurp "some file"))
```

It would be nice if I could instead write 

```
(defadv slurp 2 ...)
(def file (root/slurp "some file"))
```

In order to access the original stdlib definition of slurp.

If we followed the example set in gleam, it would be something like this:

```
(import janet)

...

(defadv slurp 2 ...)
(def file (janet/slurp "some file"))
```

Though of course the name of the module it's imported under could be anything you liked.

In the example of Elixir, the equivalent would be:

```elixir
defn tl() do
  "what an odd function"
end

[2] = Kernel.tl([1, 2])
```

Without having to import Kernel - but in the case of Elixir, every module in the path is available without having to import it.

**Comment by bakpakin** [comment]
This is already available you just need to do it yourself.

```
(merge-module (curenv) root-env "janet/")
```
