### ISSUE TITLE
min and max do not use polymorphic compare

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#693]
I don't know if this should be the case or not, It is kind of confusing.

**Comment by andrewchambers** [comment]
not really sure if im a fany of polymorphic math at all anymore, it kind of muddies a lot of water.

**Comment by subsetpark** [comment]
I think the idea is that you should use `extreme` with the `compare` functions instead.

**Comment by andrewchambers** [comment]
Yes, but why are some functions polymorphic but others aren't? its just error prone.

**Comment by bakpakin** [comment]
Closing this as a WNF - for better or worse, it is not something I feel needs to be changed. Doing comparisons between numbers of different types is often a problem anyway, or at least unnecessary.
