### ISSUE TITLE
Feature request: ability to compile Janet to many other languages, especially WebAssembly

### ISSUE THREAD

**Issue by elimisteve** [janet-lang/janet#696]
...so that Janet can run anywhere and use libraries from any one ecosystem at a time!

Wax does this, and is very similar to Janet: https://github.com/LingDong-/wax

**Comment by pepe** [comment]
Just my two cents, but I really enjoy the simplicity of the C-written core, which I guess would be lost. 

Wax looks like a very different language implementation to me.

**Comment by bakpakin** [comment]
Yeah, this will not be added as it is way out of scope. If it were to be implemented, it would be as a separate library and it would be a bit difficult to preserve all Janet semantics in every host language while still being performant in the host language.
