### ISSUE TITLE
Feature request: match on prototype in `match` / table destructuring in general

### ISSUE THREAD

**Issue by subsetpark** [janet-lang/janet#699]
Match is really effective for structural pattern matching, like so:

```
(match {:foo :bar :baz :quux}
  {:baz something} something)
=> :quux
```

Sort of the last structural component to tables, that is not currently matchable, is the prototype of the table. It would be really awesome if I could do something like this:

```
(match obj
  {:_proto (@ KnownPrototype) :baz something} something)
=> :quux
```

That is, match on the prototype in the same way that I match on other fields.

**Comment by bakpakin** [comment]
Would something like `(match obj @{:_name :MyType :baz something})` work as well? I guess it is not enforced that a prototype has a name, but it is a convention that would work fairly well.

**Comment by subsetpark** [comment]
It would work, and is actually what I’ve settled on for now. Though of course it’s trivially possible to collide names, whereas equality with another table is unambiguous.

**Comment by andrewchambers** [comment]
match supports arbitrary predicates too i guess, though quite verbose.
