### ISSUE TITLE
Execution does not stop on script parse error 

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#70]
```
(print "hello"))
(print "world")
```
```
$ janet test.janet
hello
parse error in ./tools/test.janet around byte 17: unexpected delimiter
world
```

**Comment by bakpakin** [comment]
Thanks, I actually just pushed a change that should follow the expected behavior. As discussed on Gitter, the `-p` flag brings back the old behavior.

Change in commit 2a5234b390125b7878c27fbe565217f2d8d42864

**Comment by andrewchambers** [comment]
thank you. :)
