### ISSUE TITLE
Fiber without environment ends with segmentation fault in `ev/go`

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#701]
By this report https://lists.sr.ht/~pepe/good-place/%3C20210519142803.47ab7cea%40Denis.localdomain%3E, I came across the issue where the trolley segfaults when the fiber is created without the environment and put on the `ev`:

```
(import trolley)
(def f (fiber/new (fn []
           (trolley/router {"/:id" print}))))
(ev/go f)

=> terminated by signal SIGSEGV (Address boundary error)
```

Yet when I inherit or set the prototype of the new fiber, it works fine:

```
(import trolley)

(def f
  (fiber/new
    (fn []
      (trolley/router {"/:id" print})) :p))
(ev/go f)
```

I can replicate it only with the [trolley](https://git.sr.ht/~pepe/trolley) code, but I guess it is probably some deeper issue.

**Comment by bakpakin** [comment]
Should be fixed in 2db7945d6f6672648f56dfad1b5cab990c3aa562 - there was a NULL pointer dereference when a default grammar wasn't set.

**Comment by bakpakin** [comment]
Thanks for finding this @pepe , please verify the fix works and close the bug.

**Comment by pepe** [comment]
I am on it, sir!

**Comment by pepe** [comment]
Indeed it works as expected, one down. Thank you very much.
