### ISSUE TITLE
Can't build when using top level `ev/chan` due to unable to marshal core/channel

### ISSUE THREAD

**Issue by saikyun** [janet-lang/janet#710]
Am on `Janet 1.16.1-87f8fe14 linux/x64`

`main.janet`
```
(def c (ev/chan 1))

(defn main [& args]
  (pp c))
```

`project.janet`
```
(declare-project
  :name "chan")

(declare-executable
  :name "chan"
  :entry "main.janet")
```

```
jpm build
generating executable c source...
error: try to marshal unregistered abstract type, cannot marshal <core/channel 0x56054A7DB030>
  in marshal
  in <anonymous> [/usr/local/bin/jpm] on line 748, column 20
  in do-rule [/usr/local/bin/jpm] on line 273, column 26
  in do-rule [/usr/local/bin/jpm] (tailcall) on line 269, column 44
  in _thunk [/usr/local/bin/jpm] on line -1, column -1
  in cli-main [boot.janet] on line 3559, column 39
```

**Comment by sogaiu** [comment]
Here's a repository for my attempt at reproducing: https://github.com/sogaiu/janet-marshal-channel

**Comment by andrewchambers** [comment]
Not totally sure, but it might be that channels in certain states are too complicated to marshal, but an unused or newly constructed channel seems like a simpler case.

**Comment by Saikyun** [comment]
I guess a solution is to create a var and set it inside main instead then. That feels a bit off though.

**Comment by pepe** [comment]
I would recommend to read https://janet-lang.org/docs/jpm.html Creating an executable.

**Comment by sogaiu** [comment]
That does have a nice summary -- here's a [direct link](https://janet-lang.org/docs/jpm.html#Creating-an-executable).

Perhaps one of the things being referred to is:

> It's important to remember that code at the top level will run when you invoke jpm build, not at executable runtime. This is because in order to create the executable, we marshal the main function of the app and write it to an image. In order to create the main function, we need to actually compile and run everything that it references, in the above case mylib1 and mylib2.

**Comment by pepe** [comment]
@sogaiu, thank you! I was on the phone and have not found the way how to copy anchor href.

**Comment by Saikyun** [comment]
I understand why this happens, but the question is does it have to happen or should (fresh) channels be marshallable?

**Comment by pepe** [comment]
I am not sure, but abstract C types can't be marshaled, open files or streams works the same. And there is no big difference between fresh and used channels I guess.

**Comment by sogaiu** [comment]
@pepe Isn't it the case that if appropriate things are defined for an abstract C type, it can be marshaled?

At least that was my impression looking at this: https://github.com/janet-lang/janet/blob/master/src/include/janet.h#L1049-L1050

**Comment by andrewchambers** [comment]
@pepe they can be marshalled, files are different because they point to OS state that can't be marshalled, lots of other C types can be marshalled.

The difference between a fresh and used channel is a fresh one is not tied up in an active event loop so does not need to marshal the state of the event loop to resume.

**Comment by pepe** [comment]
@sogaiu I bet it can, but I was talking about the current state.

@andrewchambers, you know better than anyone that this stuff is above my expertise, yet I guess fresh channel is already tied to the `ev` as it can be used straight away without any more initialization. I could be wrong tho.

Anyway I think, this is not that big issue and needs just a small adjustment on the side of the programmer.

**Comment by Saikyun** [comment]
Imo the issue arises when you're new and have no clue why this error occurs. I don't think it's strange that someone would put a global `ev/chan` somewhere. Perhaps it could at least give an error message that shows which line the `ev/chan` is called.

**Comment by bakpakin** [comment]
I would argue it doesn't really make sense to be able to marshal channels since at any given moment they also contain information about which fibers are waiting on them. I suppose we could just marshal the capacity and all of the values in the channel though. Or perhaps only allow marshalling an empty channel for this specific use case of initialization.

**Comment by Saikyun** [comment]
Would it be possible then to show where in the code the marshalling breaks?
I think either solution would be fine.

Den lör 24 juli 2021 19:54Calvin Rose ***@***.***> skrev:

**Comment by LeviSchuck** [comment]
I encountered this today. Here's the lldb backtrace of a top level thread-chan

```
Process 72713 launched: '/usr/local/bin/janet' (arm64)
Process 72713 stopped
* thread #2, stop reason = EXC_BAD_ACCESS (code=1, address=0x48)
    frame #0: 0x000000010000fff0 janet`janet_to_string_b(buffer=0x000000016fe857b8, x=Janet @ 0x000000016fe85480) at pp.c:246:22
   243 	        case JANET_FUNCTION: {
   244 	            JanetFunction *fun = janet_unwrap_function(x);
   245 	            JanetFuncDef *def = fun->def;
-> 246 	            if (def->name) {
   247 	                const uint8_t *n = def->name;
   248 	                janet_buffer_push_cstring(buffer, "<function ");
   249 	                janet_buffer_push_bytes(buffer, n, janet_string_length(n));
Target 0: (janet) stopped.
(lldb) bt
* thread #2, stop reason = EXC_BAD_ACCESS (code=1, address=0x48)
  * frame #0: 0x000000010000fff0 janet`janet_to_string_b(buffer=0x000000016fe857b8, x=Janet @ 0x000000016fe85480) at pp.c:246:22
    frame #1: 0x000000010000fd4c janet`janet_description_b(buffer=0x000000016fe857b8, x=Janet @ 0x000000016fe854d0) at pp.c:316:5
    frame #2: 0x0000000100008598 janet`janet_formatbv(b=0x000000016fe857b8, format="expected type %T, got %v", args="\xa2\n\U00000004\U00000010\U00000004") at pp.c:841:21
    frame #3: 0x0000000100002b90 janet`janet_panicf(format="expected type %T, got %v") at capi.c:82:5
    frame #4: 0x000000010004a198 janet`janet_asserttype(x=Janet @ 0x000000016fe85820, t=JANET_STRING) at marsh.c:699:9
    frame #5: 0x00000001000498fc janet`unmarshal_one_def(st=0x000000016fe86b08, data="\xce(/usr/local/lib/janet/db/sqlite/sql.janet\xda\U0000000f\xda/\xd7", out=0x000000016fe85b78, flags=131079) at marsh.c:843:13
    frame #6: 0x00000001000242d0 janet`unmarshal_one(st=0x000000016fe86b08, data="\xcd", out=0x00000001003c6520, flags=131078) at marsh.c:1268:20
    frame #7: 0x00000001000499d0 janet`unmarshal_one_def(st=0x000000016fe86b08, data="\xd7", out=0x000000016fe86028, flags=131077) at marsh.c:860:24
    frame #8: 0x00000001000242d0 janet`unmarshal_one(st=0x000000016fe86b08, data="\xcd", out=0x000000010038d5b0, flags=131076) at marsh.c:1268:20
    frame #9: 0x00000001000499d0 janet`unmarshal_one_def(st=0x000000016fe86b08, data="\xd7", out=0x000000016fe864d8, flags=131075) at marsh.c:860:24
    frame #10: 0x00000001000242d0 janet`unmarshal_one(st=0x000000016fe86b08, data="\xcd\U00000002\xba", out=0x000000010036ab00, flags=131074) at marsh.c:1268:20
    frame #11: 0x00000001000499d0 janet`unmarshal_one_def(st=0x000000016fe86b08, data="\xd7", out=0x000000016fe86988, flags=131073) at marsh.c:860:24
    frame #12: 0x00000001000242d0 janet`unmarshal_one(st=0x000000016fe86b08, data="\xcd", out=0x000000016fe86c20, flags=131072) at marsh.c:1268:20
    frame #13: 0x0000000100012078 janet`janet_unmarshal(bytes="\xd7", len=23447, flags=131072, reg=0x0000000000000000, next=0x000000016fe86e48) at marsh.c:1442:32
    frame #14: 0x000000010001b934 janet`janet_go_thread_subr(args=JanetEVGenericMessage @ 0x000000016fe86ee0) at ev.c:2734:24
    frame #15: 0x0000000100019ca0 janet`janet_thread_body(ptr=0x00000001007a0190) at ev.c:1967:20
    frame #16: 0x0000000199873878 libsystem_pthread.dylib`_pthread_start + 320
```
