### ISSUE TITLE
Error during dofile "breaks" environment?

### ISSUE THREAD

**Issue by Saikyun** [janet-lang/janet#711]
It seems that when creating an environment, then using it with a `dofile` that errors, you can't use that environment anymore.
Am on `Janet 1.16.1-87f8fe14 linux/x64`

## To reproduce

create a file with error in it
```
echo 'aoeu' > erronous.janet
```

copy paste into janet repl
```
(def env (make-env))

#### this works

(try (do (fiber/setenv (fiber/current) env)
       (pp (eval-string "1")))
  ([err fib]
    (debug/stacktrace fib err)))

(try (do (fiber/setenv (fiber/current) env)
       (pp (eval-string "aoe1")))
  ([err fib]
    (debug/stacktrace fib err)))

(try (do (fiber/setenv (fiber/current) env)
       (pp (eval-string "1")))
  ([err fib]
    (debug/stacktrace fib err)))

#### dofile causes env to break

(try (pp (dofile "erronous.janet" :env env))
  ([err fib]
    (debug/stacktrace fib err)))

(try (do (fiber/setenv (fiber/current) env)
       (pp (eval-string "1")))
  ([err fib]
    (debug/stacktrace fib err)))
```

yields
```
1
error: compile error: unknown symbol aoe1
  in compile-error [boot.janet] (tailcall) on line 2364, column 37
  in eval1 [boot.janet] on line 2268, column 16
  in run-context [boot.janet] on line 2324, column 13
  in eval-string [boot.janet] on line 2362, column 3
  in <anonymous> [test_stuff.janet] on line 11, column 12
1
error: erronous.janet:1:1: compile error: unknown symbol aoeu
  in dofile [boot.janet] on line 2608, column 7
  in <anonymous> [test_stuff.janet] on line 24, column 10
nil

```

The last `nil` should also be `1`.

**Comment by bakpakin** [comment]
Upon errors, the `:exit` and `:exit-value` dyns are set in an environment. This "breaks" the environment until `:exit` is removed. I suppose we could have run context automatically reset :exit on completion to avoid this behavior, which I suppose is a bit unintuitive.

**Comment by bakpakin** [comment]
Adding `(put env :exit nil)` before the last `try` will prevent this issue and you will see 1 as you expect.

**Comment by Saikyun** [comment]
Might there be a reason to not reset the value? I'm guessing that since you get the error it's at least unavoidable to notice when the `dofile` fails. :)

In my case, I'm "building onto" the same environment over different dofile / eval-string calls, so for me the new behaviour makes the most sense. :)

**Comment by bakpakin** [comment]
The :exit dyn is the mechanism used to signal an early exit, but it is just a flag and not needed after run-context completes.

**Comment by Saikyun** [comment]
All right, cool. Thanks for the change. :)
