### ISSUE TITLE
Windows: os/open creates a stream that only accepts the first write?

### ISSUE THREAD

**Issue by yumaikas** [janet-lang/janet#716]
I'm on a local build of 1.16.1 on Windows 10, and I'm seeing this:

```janet
(def my-file (os/open "file.txt" :wc))
(:write my-file "First Line\r\n")
(:write my-file "Second Line\r\n")
(:write my-file "Third Line\r\n")
(:close my-file)
```

This results in a `file.txt` that only contains `Third Line\r\n`.

**Comment by andrewchambers** [comment]
First line of the example seems to be missing the os/open call.

**Comment by yumaikas** [comment]
Fixed, and I still see the problem.

**Comment by sogaiu** [comment]
I get a similar result with 54d73f67220e9940702b7d99956b6ee7144a10e7 (for a Windows 10 VM).

**Comment by yumaikas** [comment]
Can we get a `bug` tag on this?

**Comment by yumaikas** [comment]
So, digging into things more, it seems that os/open gives us a core/stream, whose `:write` is bound to `ev/write`. Digging into that, it looks like the differences are that ev_machine_write is called when we're on Windows but not on any other os? Why is this?
