### ISSUE TITLE
Add Source Mapping information to native Janet Modules

### ISSUE THREAD

**Issue by yumaikas** [janet-lang/janet#720]
We're adding support for adding source-map information to Native Janet modules written in C. Soon, @bakpakin will be adding a couple of macros to make that easy.

Here we'll be tracking the effort to port the various parts of the standard library.

- [x] src\core\array.c
- [x] src\core\asm.c
- [x] src\core\buffer.c
- [x] src\core\compile.c
- [x] src\core\corelib.c
- [x] src\core\debug.c
- [x] src\core\ev.c
- [x] src\core\fiber.c
- [x] src\core\inttypes.c
- [x] src\core\io.c
- [x] src\core\marsh.c
- [x] src\core\math.c
- [x] src\core\net.c
- [x] src\core\os.c
- [x] src\core\parse.c
- [x] src\core\peg.c
- [x] src\core\string.c
- [x] src\core\table.c
- [x] src\core\thread.c
- [x] src\core\tuple.c
- [x] src\core\typedarray.c

**Comment by bakpakin** [comment]
Updated `asm` to use the new macros:

Works as follows:

```c
JANET_CORE_FN(cfun_myfun,
   "(my-mod/my-fn x y z)",
   "Does a thing.") {
    janet_fixarity(argc, 3);
    double x = janet_getnumber(argv, 0);
    JanetTable *y = janet_gettable(argv, 1);
    JanetArray *z = janet_getarray(argv, 2);
    ...
    return janet_wrap_array(z);
}

janet_init_some_core_functions(JanetTable *env) {
   JanetRegExt cfuns[] = {
     JANET_CORE_REG("my-mod/my-fn", cfun_myfn),
     JANET_REG_END
   };
   janet_core_cfuns_ext(env, NULL, cfuns);
}
```

**Comment by bakpakin** [comment]
There are also added macros for use outside of the core library that work in a similar way, `JANET_FN` and `JANET_REG`. These can be used in native modules for source mapping.

**Comment by andrewchambers** [comment]
@bakpakin It might be a good time to add arity information to C functions as an option to this macro.

**Comment by yumaikas** [comment]
Just an fyi, @ogdenstudios is planning on helping out, as part of an effort to get familiar with both Janet and C

**Comment by ogdenstudios** [comment]
Excited to help out and learn a bit! Should I hold off until the arity information is added to this macro?

**Comment by yumaikas** [comment]
I think we're good to keep going. The arity info is already recorded in the function name docstring, and doing more with that information it a task for another time, IMO.

**Comment by sogaiu** [comment]
May be it makes sense if folks mention the specific files they are going to work on.

**Comment by sogaiu** [comment]
FWIW, I suggest looking for files that require less changes when starting to work on this.

**Comment by yumaikas** [comment]
I'm working on `ev.c`, myself, since I was just in there.

**Comment by ogdenstudios** [comment]
I was planning to just start alphabetically with `array.c` if no one else has claimed it yet.

**Comment by sogaiu** [comment]
Whatever works for you folks.

Possibly obvious, but I think it might not be bad to check the following things:

* use `(doc some-relevant-function-name)` to verify a location shows up for one of the relevant functions.  For example, for `compile.c`, once I made changes, I got this:
```
repl:1:> (doc compile)


    cfunction
    src/core/compile.c on line 945, column 1

    (compile ast &opt env source lints)

    Compiles an Abstract Syntax Tree (ast) into a function. Pair the 
    compile function with parsing functionality to implement eval. 
    Returns a new function and does not modify ast. Returns an error 
    struct with keys :line, :column, and :error if compilation fails. 
    If a lints array is given, linting messages will be appended to the 
    array. Each message will be a tuple of the form (level line col 
    message).


nil
```
    Note the line below `cfunction` mentions a source file location.
    
* `make test` passes (right now it fails on master for other reasons)

**Comment by sogaiu** [comment]
I'm planning to look at `tuple.c`.

**Comment by bakpakin** [comment]
> @bakpakin It might be a good time to add arity information to C functions as an option to this macro.

First we need a mechanism for passing arity to the compiler for c functions in a useful way (to get the compile-time arity functionality). As far as eliding arity checking at runtime I expect that will essentially just be noise.

**Comment by sogaiu** [comment]
Going to look at `thread.c` next (though I hear it's going to be removed before long?).

**Comment by sogaiu** [comment]
Looking at `table.c`.

**Comment by yumaikas** [comment]
So, the following code will verify that all cfunctions in a given module have source-mapping info
```janet
(defn all-cfuns-have-source-info [mod-prefix] 
 (not (not (all |($ :source-map)
  (as-> (all-bindings) it
   (filter |(string/has-prefix? mod-prefix $) it)
   (map dyn it)
   (filter |(= :cfunction (type ($ :value))) it))))))

(all-cfuns-have-source-info "ev/")
```

**Comment by yumaikas** [comment]
@sogaiu Could you check off the ones you have PRs open for?

**Comment by yumaikas** [comment]
Unless I get completely behind, I plan on trying to tackle math.c next

**Comment by sogaiu** [comment]
I tried checking stuff off of the list at the top, but it didn't work for me.

Thanks for the handy function.

Will look at `string.c` next.

**Comment by sogaiu** [comment]
Thinking to work on `parse.c` next.

**Comment by sogaiu** [comment]
Mmm `os.c` looks like fun.  Will look at that.

**Comment by sogaiu** [comment]
Thinking to look at `net.c` next.

**Comment by sogaiu** [comment]
Have my :eye: on `marsh.c`.

**Comment by sogaiu** [comment]
Next up `io.c`.

**Comment by sogaiu** [comment]
Will try `inttypes.c`.

**Comment by sogaiu** [comment]
Trying `fiber.c`.

**Comment by sogaiu** [comment]
Looking at `debug.c`.

**Comment by sogaiu** [comment]
Considering `corelib.c`.

**Comment by sogaiu** [comment]
Looking at `buffer.c`.

**Comment by sogaiu** [comment]
I heard via yumaikas that @ogdenstudios was ok if we went ahead with `array.c`, so I'll do that.

**Comment by yumaikas** [comment]
So, pulling from master, and building, I don't see a single cfunction that doesn't have source mapping metadata, so I am calling this issue complete!

**Comment by pepe** [comment]
Great work!
