### ISSUE TITLE
Custom print method for abstract types.

### ISSUE THREAD

**Issue by bakpakin** [janet-lang/janet#73]
Abstract types cannot currently control how they print in the repl (what they return from the describe function). It would be nice to be able to override the default print functionality with custom printing functionality for debugging. This way, something like:

```
(int/s64 "123")
```

could display as

```
<core/s64 123>
```
or the like.

**Comment by jfcap** [comment]
I guess you mean something like :

```C
/* Defines an abstract type */
struct JanetAbstractType {
    const char *name;
    int (*gc)(void *data, size_t len);
    int (*gcmark)(void *data, size_t len);
    Janet(*get)(void *data, Janet key);
    void (*put)(void *data, Janet key, Janet value);
    void (*marshal)(void *p, JanetMarshalContext *ctx);
    void (*unmarshal)(void *p, JanetMarshalContext *ctx);
    void (*tostring)(void *p, JanetBuffer * buffer);
};
```

This will be very helpful.

**Comment by bakpakin** [comment]
I've just added and pushed a tostring method for abstract types, so now integer types can't print out a string representation.
