### ISSUE TITLE
Adding source mapping macros to handle the last vestiges of JDOC

### ISSUE THREAD

**Issue by yumaikas** [janet-lang/janet#742]
So, the last place using JDOC is the various quickasm functions (like +, %, etc) in corelib.c. 

I think we could add a macro or two and get those switched over as well, and then we can eliminate usage of JDOC, and mark it as deprecated, with a warning to people that use it in their native modules.

**Comment by bakpakin** [comment]
JDOC is not a public macro, so we can just remove it whenever.

**Comment by yumaikas** [comment]
Ah, ok. I thought I'd used it in some of my code, but maybe I'd just defined my own JDOC, because I didn't understand what it was meant for.
