### ISSUE TITLE
Symbol not found with the latest Janet and native modules

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#745]
When I use Janet after 6f1695ecd4ad85562719288096a92ce32e43d6d4 running `jpm test` in `janet-lang/json` fails with:

```
compiling json.c to build/json.o...
linking build/json.so...
generating meta file build/json.meta.janet...
compiling json.c to build/json.static.o...
creating static library build/json.a...
running test/suite0.janet ...
test/suite0.janet:4:10: compile error: unknown symbol json/decode
```

The issue is not isolated to this library, a similar result  Iget with at least https://github.com/andrewchambers/janet-uri

**Comment by yumaikas** [comment]
So, from what I can see, it seems that the new `janet_cfuns_sm` and `janet_cfuns` are different from the old `janet_cfuns` when it comes to export prefixes. When I change the tests to use `json/json/encode` and  `json/json/decode`, they work.

**Comment by yumaikas** [comment]
Makes me suspect that `:as` or something else isn't handled correctly?

**Comment by sogaiu** [comment]
FWIW, it looks like replacing [`janet_cfuns`](https://github.com/janet-lang/janet/blob/master/src/core/util.c#L471-L485) with an older version (from https://github.com/janet-lang/janet/commit/6f1695ecd4ad85562719288096a92ce32e43d6d4) makes things work (verified on Linux and Windows).

**Comment by pepe** [comment]
For me 7e5f2264806c41a02d1117b4ddff009f74af560a fixes the issue, thank you very much @bakpakin. I am closing this.
