### ISSUE TITLE
The string/join behavior on a non-string array

### ISSUE THREAD

**Issue by soulawaker** [janet-lang/janet#746]
Is it intentional for `string/join` to prone error?

```
repl:10:> (string ;@[0 2 4 6])
"0246"
repl:11:> (= (string ;@[0 2 4 6]) (string/join @[0 2 4 6]))
error: item 0 of parts is not a byte sequence, got 0
  in string/join
  in _thunk [repl] (tailcall) on line 11, column 24
```

**Comment by sogaiu** [comment]
According to `(doc string/join)`:

> Joins an array of strings into one string, optionally separated by a separator string sep.

`@[0 2 4 6]` is not an array of strings IIUC:
```
(type (first @[0 2 4 6]))
# => :number
```

**Comment by uvtc** [comment]
@soulawaker , note:

~~~python
(def nums [0 2 4 6])

(string ;nums)  # -> "0246"

(map string nums)  # -> @["0" "2" "4" "6"]

(string/join (map string nums) "-")  # -> "0-2-4-6"
~~~

**Comment by soulawaker** [comment]
IMHO we don't have to use `string` in `string/join` if it is no harm to allow same behavior.

**Comment by sogaiu** [comment]
It's true that `string/join` can also handle arrays of some other things -- symbols, keywords, and buffers:
```
(string/join @['a :b "c" @"x"])
# => "abcx"
```

IIUC, [the current implementation of `string/join`](https://github.com/janet-lang/janet/blob/7e5f2264806c41a02d1117b4ddff009f74af560a/src/core/string.c#L488-L529) depends on [`janet_bytes_view`](https://github.com/janet-lang/janet/blob/7e5f2264806c41a02d1117b4ddff009f74af560a/src/core/util.c#L671-L683) which seems to work only for strings, symbols, keywords, and buffers.

**Comment by bakpakin** [comment]
Yes, this is intentional and will not change.
