### ISSUE TITLE
gensym behavior between 1ef6db1 and 61769c8

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet#753]
It looks like since https://github.com/janet-lang/janet/commit/1ef6db16eda21f4b8cbb73682dcd388e36fe1202 , `gensym` is not behaving like:
```
/* Generate a unique symbol. This is used in the library function gensym. The
 * symbol will be of the format _XXXXXX, where X is a base64 digit, and
 * prefix is the argument passed. No prefix for speed. */
```
Example:
```
Janet 1.17.0-dev-61769c8f linux/x64 - '(doc)' for help
repl:1:> (gensym)

repl:2:> (type (gensym))
:symbol
```
The return value of `(gensym)` is not visible on my terminal.

Examined under gdb it looked like the leading byte was 0.

`gensym_counter` used to be initialized like this: https://github.com/janet-lang/janet/commit/1ef6db16eda21f4b8cbb73682dcd388e36fe1202#diff-25c765d33445b0e34add62c8093ae0f902e5c87ec602c591c71e644e5b858c2aL198

Since the commit above, it looks like `janet_vm.gensym_counter` is filled with 0 bytes: https://github.com/janet-lang/janet/commit/1ef6db16eda21f4b8cbb73682dcd388e36fe1202#diff-25c765d33445b0e34add62c8093ae0f902e5c87ec602c591c71e644e5b858c2aR46

The following seems to work in light testing here:
```

/* Initialize the cache (allocate cache memory) */
void janet_symcache_init() {
    janet_vm.cache_capacity = 1024;
    janet_vm.cache = janet_calloc(1, (size_t) janet_vm.cache_capacity * sizeof(const uint8_t *));
    if (NULL == janet_vm.cache) {
        JANET_OUT_OF_MEMORY;
    }
    const uint8_t gensym_counter[8] = {'_', '0', '0', '0', '0', '0', '0', 0};
    memcpy(janet_vm.gensym_counter, gensym_counter, sizeof(gensym_counter));
    janet_vm.cache_count = 0;
    janet_vm.cache_deleted = 0;
}
```

**Comment by saikyun** [comment]
I tried sogaiu's fix, and it works for me. :)

**Comment by saikyun** [comment]
Thanks!
