### ISSUE TITLE
Bug in treating fibers as streams (eg generate): `nil` at the end

### ISSUE THREAD

**Issue by subsetpark** [janet-lang/janet#755]
I found this as I was developing janet-streams, but it seems to be an issue with the standard library as well, because the `generate` macro exhibits the same behaviour.

Because expressions like `loop` and `each` evaluate to `nil`, any fiber that uses looping constructs will have an extra `nil` at the end after all of the values have been yielded. Here's a trivial example:

```
repl:62:> (def s (generate [x :in [1 2 3]] x))
<fiber 0x55912F820C70>
repl:63:> (resume s)
1
repl:64:> (resume s)
2
repl:65:> (resume s)
3
repl:66:> (resume s)
nil
repl:67:> (resume s)
error: cannot resume fiber with status :dead
  in _thunk [repl] (tailcall) on line 67, column 1
```

I would expect to reach the "status :dead" result one line earlier; instead, I get the three values in the data structure *followed by the nil* that's returned by the underlying `loop`. 

Theoretically, we could imagine that we would say, "look for `nil` and treat it like an EOF" - but of course, that means that you could never use `generate` with any data structure already containing meaningful `nil`s.

---

One potential fix for this, given the current primitives, would be to do some jiggery pokery where we take the data structure, slice off the last value, iterate-and-yield through the first part, and then return the last outside of the loop.

However, in addition to being rather gross, that would be impossible to apply to an existing fiber!

Instead, it seems like it would be best to be able to emit a `:dead` signal. Right now I can debug, yield, and error inside of a fiber, but I don't think I can manually say "this fiber should die here".

---

Edit: @bakpakin , in the Matrix chat, offered the "opposite" approach: instead of introducing a new signal that would immediately kill a fiber, you could also adjust the yield semantics of fibers, so that they *only* yield that which has been explicitly `yield`ed, instead of both what is `yield`ed and the final expression.

**Comment by pepe** [comment]
The second approach, yield only on yield, looks better to me.

**Comment by bakpakin** [comment]
Ok, so when iterating fibers with 'next', they already behave correctly. I should have checked this before merging the fiber aware additions to take and take-while, but just use next and get on fibers to iterate them and the behavior is already correct

**Comment by bakpakin** [comment]
Macros like each, and loop will also work correctly on generators.

**Comment by pepe** [comment]
Good to know.
