### ISSUE TITLE
Two ways to bind symbols that Flycheck doesn't know about

### ISSUE THREAD

**Issue by subsetpark** [janet-lang/janet#758]
I'm finding a couple ways to introduce symbols into the environment that flycheck doesn't know about. This result in false positive "unknown symbol" errors when running `janet -k`, which don't crop up when running effectful Janet.

# merge-module
This is actually the recommended way to bind the root environment under the `janet/` namespace, found in another issue in this repo:
`(merge-module (curenv) root-env "janet/")`

This results in the binding of the symbol (among others) `janet/match`, but flycheck mode flags that as unknown.

# evaling a macro 
This one is tough. It's obviously not really possible to judge whether a specific `eval` call is effectful or not. So I'd be interested to know if there are alternative idioms to what I've come up with. Here's a simplified example:

```
(defn- my-defn-form
 [fn-name]
 ~(defn ,fn-name [] :ok))
(eval (my-defn-form 'a-new-fun))
```

I have a macro which emits a whole bunch of defs and defns. However, to bootstrap the root of the object hierarchy, I `eval` those defn forms one-by-one as they're defined, so they're in place when the macro is actually called.

This obviously results in a `defn` being called, but also obviously that is never encountered because `eval` is not flycheck-safe.

Is there another way to evaluate these forms as though they were called by macro, so that flycheck can see the resulting code?

**Comment by bakpakin** [comment]
Yeah, the reality is that we can't possibly know every possible way a symobol is evaluated. The built-in flychecker has some heuristics to get around this, and conforming macros can follow this pattern to behave as exected.

Any macro that begins with `def` will be evaluated, so `my-defn-form` would be renamed to `defn-my-form`. Alternatively, we could add support for some metadata like `:define-type-macro` to hint to signal to the flychecker that this macro has no side effects besides adding definitions to the current environment, so would be considered "safe" to evaluate during flychecking.

**Comment by bakpakin** [comment]
As far as merge-module, I don't really recommend this for a number of reasons. It will create dupl.icates of symbols in the current namespace. However, this is lisp, so do as you please. I guess we could also add a macro `(flycheck-safe & forms)` that would just blindly evaluate the forms while fly checking, but this strikes me as an easy way out that would litter library code with a mostly useless macro.

**Comment by subsetpark** [comment]
> Any macro that begins with def will be evaluated, so my-defn-form would be renamed to defn-my-form. Alternatively, we could add support for some metadata like :define-type-macro to hint to signal to the flychecker that this macro has no side effects besides adding definitions to the current environment, so would be considered "safe" to evaluate during flychecking.

I don't think that applies in this case. `my-defn-form` is a function which returns some bare AST; I then have to `eval` the AST in order to actually effect the defn. So there's no macro being called one way or the other. It's just evaling a sexp which happens to correspond to a macro.

Again, this definitely doesn't feel like the best way to do it, so if you have an alternative suggestion for how to:

- have some logic that is responsible for generating a `defn` form, for use in a macro
- in a special case, evaluate that same defn *outside* of any macros

I am all ears!

**Comment by bakpakin** [comment]
I would need to see the code, I don't understand why eval is needed. I suspect `upscope` or `defglobal` or similar would work better.

Example:

```
(def defmany
   "Defines many things."
   [name & more]
   ~(upscope
        (def ,(symbol name "-thing1") 1)
        (def ,(symbol name "-thing2") 2)
        (defn ,(symbol name "-function") [x] x)))
```

```
