### ISSUE TITLE
JPM: error: No such file or directory: /usr/local/lib/janet/.cache

### ISSUE THREAD

**Issue by glyh** [janet-lang/janet#764]
Error message:
```
error: No such file or directory: /usr/local/lib/janet/.cache
  in os/mkdir
  in mkdir [/usr/bin/jpm] on line 209, column 3
  in install-git [/usr/bin/jpm] (tailcall) on line 870, column 3
  in _thunk [/usr/bin/jpm] on line -1, column -1
  in cli-main [boot.janet] on line 3559, column 39
```
I've installed through AUR: janet-lang-bin

This can be manually solved by 
```shell
sudo mkdir /usr/local/lib/janet/.cache -p
```
Maybe the jpm should add -p to the mkdir command

**Comment by sogaiu** [comment]
Have you reported to the maintainer of the AUR package?

It looks like @ngrunwald may be the maintainer of that package: https://aur.archlinux.org/packages/janet-lang-bin/

There is another package maintained by @GrayJack https://aur.archlinux.org/packages/janet-lang/ -- no idea if it would act differently, but may be it's worth trying?  

Compiling janet doesn't typically take very long so if this other package works better for you may be it's worth considering?

**Comment by glyh** [comment]
The `janet-lang-git` also doesn't seem to work well: 
```
could not find module jpm/cli:
    /usr/lib/janet/jpm/cli.jimage
    /usr/lib/janet/jpm/cli.janet
    /usr/lib/janet/jpm/cli/init.janet
    /usr/lib/janet/jpm/cli.so
  in require-1 [boot.janet] on line 2671, column 20
  in import* [boot.janet] on line 2710, column 15
  in _thunk [/usr/bin/jpm] (tailcall) on line 2, column 1
```
But the `janet-lang` package seems work well. 
I'm going to report to them, thanks a lot.

**Comment by sogaiu** [comment]
@glyh wrote:

> The `janet-lang-git` also doesn't seem to work well:
> 
> ```
> could not find module jpm/cli:
>     /usr/lib/janet/jpm/cli.jimage
>     /usr/lib/janet/jpm/cli.janet
>     /usr/lib/janet/jpm/cli/init.janet
>     /usr/lib/janet/jpm/cli.so
>   in require-1 [boot.janet] on line 2671, column 20
>   in import* [boot.janet] on line 2710, column 15
>   in _thunk [/usr/bin/jpm] (tailcall) on line 2, column 1
> ```

I looked at the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=janet-lang-git) for it and IIUC it doesn't account for the fact that [`jpm` is not currently in the master branch](https://github.com/janet-lang/janet/commit/230b73466373a30e37a35030244ca2b9a11c6a5b) -- it is currently living in a [separate repository](https://github.com/janet-lang/jpm/).  IIUC, how jpm is going to be distributed is not yet resolved.

> I'm going to report to them, thanks a lot.

Thanks!

**Comment by ngrunwald** [comment]
Hello, FYI I just pushed a new release of the package janet-lang-bin on AUR fixing the cache dir problem and also adding janet header file to allow jpm to compile. Follow up there if any problems remain!

**Comment by GrayJack** [comment]
> The `janet-lang-git` also doesn't seem to work well:

I updated to include jpm master branch locally, but I forgot to push, that was weeks ago, sorry for that. Any further problems happens, please, feel free to report in the AUR page
