### ISSUE TITLE
`assert` macro alternative

### ISSUE THREAD

**Issue by saikyun** [janet-lang/janet#765]
I noticed today that `assert` always evaluates the error part (since it's a function). I would have expected it to be a macro. Now it's not very nice to generate error information since it can be really slow (I did string/format on a big table, and it took me a while to find the problem :smile:). If not changing `assert`, then I wonder if it might make sense with an alternative `assert`-macro. Not sure what that would be called though.

**Comment by sogaiu** [comment]
Sort of related, but I noticed when looking through janet's tests, that `assert` is redefined there: https://github.com/janet-lang/janet/blob/c94d7574bc6ce1058a8a4251d172455f5678f6fb/test/helper.janet#L8-L20

**Comment by sogaiu** [comment]
Just a joke, but may be if there were to be a version which doesn't necessarily evaluate everything it could be called `assert?` ;)

**Comment by saikyun** [comment]
Here's an implementation:
```
(defmacro assertm
  ``
  Like `assert` but doesn't evaluate `err` unless `check` fails.
  ``
  [check &opt err]
  (with-syms [v]
    ~(let [,v ,check]
       (if ,v
         ,v
         (error ,(if err err "assert failure"))))))

(assertm true (print "yeah"))
# doesn't print "yeah"
(assertm false (print "yeah"))
# prints "yeah"
```

**Comment by andrewchambers** [comment]
@saikyun It seems your implementation evaluates err twice.

**Comment by saikyun** [comment]
It does? It only prints once when I try it in a repl. Note that the `if err
err` part runs during macroexpabsion. :)

Den fre 13 aug. 2021 13:11andrewchambers ***@***.***> skrev:

**Comment by andrewchambers** [comment]
ah, My bad.

**Comment by bakpakin** [comment]
I don't thinking making `assert` a macro would actually break much code, it might be worth considering making using @saikyun's macro for the main implementation.

**Comment by saikyun** [comment]
Thanks! :)
