### ISSUE TITLE
Janet SIGSEGV with `thread-chan` as fiber supervisor

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#766]
With this code https://github.com/pepe/janet-playground/blob/sigsegv-thread-chan/playground/eventures.janet#L76, when I invoke `janet -l /playground/eventures -e "(thread-chan-supervisor 16)"` I got: `'janet -l /playground/eventures…' terminated by signal SIGSEGV (Address boundary error)`

**Comment by sogaiu** [comment]
So I cloned and switched to the `sigsev-thread-chan` branch (commit was 634ba62) and tried:
```
$ janet -l /playground/eventures -e "(thread-chan-supervisor 16)"
```
Output here was:
```
done
done
done
done
done
done
done
done
done
done
done
done
done
done
donedone


```
FWIW, the Linux kernel here is 5.4.135 something.

**Comment by pepe** [comment]
Hmm, my Linux is 5.13.9_1, same Janet indeed. The strange thing about this is that when I put the function in the file without anything else, it does not SIGSEGV.

**Comment by pepe** [comment]
@sogaiu, thank you for the test! So it could be a problem with my setup.

**Comment by sogaiu** [comment]
I'll give it a try on another machine.

**Comment by sogaiu** [comment]
Some further trials.

In a VM with Manjaro (21.1.0), kernel version 5.10.53 something, I get similar results.

In a VM with an Ubuntu (20.04) installation, kernel version 5.4.0 something, I get similar results.

It's possible I've not followed the directions correctly of course :)

**Comment by sogaiu** [comment]
For reference, with e552757 I now get the following output:
```
$ janet -l /playground/eventures -e "(thread-chan-supervisor 16)"
done
done
done
done
done
done
done
done
(@"UIjH")
(@"UIjH")
(:ok <fiber 0x555587BF45E0>)
done
(:ok <fiber 0x555587BEF8B0>)
(@"\xC0\xC9@\xA9")
(@"\xC0\xC9@\xA9")
(:ok <fiber 0x555587C41A90>)
(:ok <fiber 0x555587C41CC0>)
(@"\x1A\x1E~B")
(@"\x1A\x1E~B")
(:ok <fiber 0x555587CDE460>)
(:ok <fiber 0x555587CDE690>)
(@"\x06\xE7\0\x17")
done
(@"\x06\xE7\0\x17")
(:ok <fiber 0x555587D7B8F0>)
(:ok <fiber 0x555587D7BB20>)
(@"\xEF\xEA\x8C\\")
(@"\xEF\xEA\x8C\\")
(:ok <fiber 0x555587E13AB0>)
(:ok <fiber 0x555587E13CE0>)
(@"z\x81\xC9\x97")
(@"z\x81\xC9\x97")
(:ok <fiber 0x555587EB14B0>)
done
done
(:ok <fiber 0x555587EB16A0>)
(@"\xEE\x93\x15>")
(@"\xEE\x93\x15>")
(:ok <fiber 0x555587F0A740>)
done
donedone

(:ok <fiber 0x555587F0BF30>)
(@"xK\xC5\xC5")
(@"xK\xC5\xC5")
(:ok <fiber 0x555587E0ECE0>)
done
(:ok <fiber 0x555587E0EF80>)
```
