### ISSUE TITLE
Janet SIGSEGV when taking from the threaded channel in another thread

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#767]
This is a follow-up to #766, which https://github.com/janet-lang/janet/commit/e552757edcaf8805deec82cdf740504e8f563785 solves. When I change the function to https://github.com/pepe/janet-playground/blob/sigsegv-thread-chan/playground/eventures.janet#L76 and execute `janet -l /playground/eventures -e "(thread-chan-supervisor 32)"` it again crashes with `'janet -l /playground/eventures…' terminated by signal SIGSEGV (Address boundary error)`. For the smaller number of threads, it works or errors with:
```
error: invalid abstract type
  in ev/take [src/core/ev.c] on line 1055
  in _thread [playground/eventures.janet] on line 90, column 14
```

**Comment by pepe** [comment]
I did some more testing, and the problems are intermittent. In five invocations, about two go wrong.

**Comment by sogaiu** [comment]
For `32` (and for various values down through `10`) I seem to get things like:
```
$ janet -l /playground/eventures -e "(thread-chan-supervisor 32)"
Got random string @"\x80\xFF\x8Fe"
Thread finished
Got random string @"\xE4\xE2\xFB\xE3"
Got random string @"\xBBm\x07\x95"
Thread finished
Thread finished
Got random string @"\x8B\v\xE2^"
Got random string @"f\xAB\nu"
Thread finished
Thread finished
Got random string @"\x18\xC5\x93\x11"
Got random string @"(e\xE94"
Thread finished
Got random string @"\xE8\x1A\xEA\x17"
Thread finished
Got random string @"\x88\xAB\t\xEF"
Thread finished
Got random string @"\x8C\xF4\xFB\xAC"
Thread finished
Segmentation fault (core dumped)
```
For `9` and below I typically get something like:
```
$ janet -l /playground/eventures -e "(thread-chan-supervisor 9)"
Got random string @"G\xABP\e"
Got random string @"\x9B0\xECP"
Thread finished
Got random string @"\x08f3\xCD"
Thread finished
Thread finished
Got random string @"d\x1F\xE3\xD9"
Thread finished
Got random string @"\x11\xF2\xA9C"
Got random string @"\xDCA\x8B\xDA"
Thread finished
Thread finished
Got random string @"\xEC\x95\xC5\xDB"
Got random string @"\xEAQ=\x12"
Thread finished
Got random string @"\xAFL%\xBB"
Thread finished
Thread finished
```
I have seen `error: invalid abstract type` at `11`, but it doesn't happen often.

**Comment by pepe** [comment]
It definitely looks like my musl-void linux is much more susceptible to this kind of errors. Thank you for the testing @sogaiu!

**Comment by bakpakin** [comment]
A lot of these issues seem to come from the complexity for having an abstract type that is supposed to be able to be safely used between threads (not copied, used with a lock). These abstract types need to be reference counted rather than GCed because they are not owned by any particular interpreter heap. I think I may try to built support for this directly into certain abstract types to solve this issue because it is turning out to be very tricky.

**Comment by pepe** [comment]
If you have anything I can help with, I would be glad.

**Comment by pepe** [comment]
With the latest master (at c8827424e7acf0822e695c661c2570522aadef7b) is not having this problem, even with very high threads count. I will wait for a little and close this issue, if no one objects. Thank you!

**Comment by sogaiu** [comment]
I tried with c882742 and didn't notice any issues.

The highest thread count I tried was `1024`.

**Comment by pepe** [comment]
@sogaiu, thank you very much, sir! I am closing this.
