### ISSUE TITLE
No Linux binary in v1.17.0 release

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#769]
Previous releases of Janet (e.g. [v1.16.1](https://github.com/janet-lang/janet/releases/tag/v1.16.1)) included a Linux binary. The release for [v1.17.0](https://github.com/janet-lang/janet/releases/tag/v1.17.0) only includes Windows binaries.

I use the Linux binary for in GitHub Workflows I have for testing ([example](https://github.com/pyrmont/testament/blob/ce2c6308fdfbd344d2c17b2712f02bbc1fb69bf3/.github/workflows/build.yml)) and for my [Heroku buildpack](https://github.com/pyrmont/heroku-buildpack-janet).

Was the decision to remove it intentional? Is it possible to add it back?

**Comment by bakpakin** [comment]
Yes, unfortunately this was because travis CI was retired. It would be good to set up linux binary blob building for sourcehut, although that still won't get us macos builds of course.
