### ISSUE TITLE
Module search path

### ISSUE THREAD

**Issue by jfcap** [janet-lang/janet#77]
```
janet:100:> (print ((module/find "path/to/mymod") 1))
could not find module path/to/mymod:
    ./path/to/mymod.janet
    ./path/to/mymod/init.janet
    /usr/local/lib/janet/path/to/mymod.janet
    /usr/local/lib/janet/path/to/mymod/init.janet
    ./path/to/mymod.so
    ./path/to/mymod/mymod.so
    /usr/local/lib/janet/path/to/mymod.so
    /usr/local/lib/janet/path/to/mymod/mymod.so
    ./path/to/mymod.jimage
    ./path/to/mymod.mymod.jimage  <--   ??
    /usr/local/lib/janet/path/to/mymod.jimage
    /usr/local/lib/janet/path/to/mymod/mymod.jimage
    path/to/mymod
nil
```

I suppose `./path/to/mymod.mymod.jimage` is not what's intended
this should probably be `./path/to/mymod/mymod.jimage`

Beyond this, is it not more logical to replace `.../mymod/mymod.so` with something like `.../mymod/init.so` and `.../mymod/mymod.jimage` with `.../mymod/init.jimage` (to be consistent with `.../mymod/init.janet` ) ?

My proposal :  

```
(def module/paths
  "The list of paths to look for modules. The following
  substitutions are preformed on each path. :sys: becomes
  module/*syspath*, :name: becomes the last part of the module
  name after the last /, and :all: is the module name literally.
  :native: becomes the dynamic library file extension, usually dll
  or so. Each element is a two element tuple, containing the path
  template and a keyword :source, :native, or :image indicating how
  require should load files found at these paths."
  @[["./:all:.janet" :source]
    ["./:all:/init.janet" :source]
    [":sys:/:all:.janet" :source]
    [":sys:/:all:/init.janet" :source]
    ["./:all:.:native:" :native]
    ["./:all:/init.:native:" :native]
    [":sys:/:all:.:native:" :native]
    [":sys:/:all:/init.:native:" :native]
    ["./:all:.jimage" :image]
    ["./:all:/init.jimage" :image]
    [":sys:/:all:.jimage" :image]
    [":sys:/:all:/init.jimage" :image]
    [":all:" :source]])

**Comment by bakpakin** [comment]
Yes, that's definitely a typo, as I have never used that code path. Your proposal looks good.

The `.../mymod/mymod.so` we should probably keep though. I believe lua does it that way, and I would prefer to keep it that way. For a janet source file, you can always look inside to see what it is, but for a binary file, it should be described by the name, especially if files are moved around.

**Comment by jfcap** [comment]
What does worry me is the "double search"

```
/usr/local/lib/janet/path/to/mymod.so
/usr/local/lib/janet/path/to/mymod/mymod.so
```
The first one is IMO mandatory but I don't see good reason for the second.
(I don't think Lua do that).
 My proposal is to replace the second one by
``` 
/usr/local/lib/janet/path/to/mymod/init.so`
```
or simply remove it.

**Comment by bakpakin** [comment]
Huh, you're right, Lua doesn't do that. I guess we can remove it then, as I don't really like `init.so`.

**Comment by jfcap** [comment]
Ok
