### ISSUE TITLE
Search order in module/paths

### ISSUE THREAD

**Issue by jfcap** [janet-lang/janet#78]
since 59c69e6 the search order for modules has changed

```
janet:15:> module/paths
@[(":all:" :source)  
  ("./:all:.janet" :source)
  ("./:all:/init.janet" :source)
  (":sys:/:all:.janet" :source)
  (":sys:/:all:/init.janet" :source)
  ("./:all:.:native:" :native)
  ("./:all:/:name:.:native:" :native)
  (":sys:/:all:.:native:" :native)
  ("./:all:.jimage" :image)
  (":sys:/:all:.jimage" :image)]
```

`(":all:" :source)` is now on top.

This breaks simple janet call like :

```
$ janet build
error: could not read file
  in file/read
  in chunks [boot.janet] at (48371:48392)
  in run-context [boot.janet] at (43128:43141)
  in require [boot.janet] at (48757:49283)
  in import* [boot.janet] at (49871:49890)
  in _thunk [init.janet] at (2377:2428)

$ ls
build  build.janet  html.janet  install.janet  manifest.janet  README.md  test.janet
```
because the `./build` directory is found before the `./build.janet` local script.

Is this the intended behaviour ?

**Comment by jfcap** [comment]
Actually, the underlying problem is probably in `module/find` function.
The `fexists` test should fail for directories . This is not the case in current implementation based on `file/open` test.

**Comment by bakpakin** [comment]
Hmm, I changed the order originally because I had a script `./mendoza`, which when I tried to run, called `./mendoza.janet` in the same directory. I ended up just changing the script name, anyways.

This actually just seems like a problem with file open. You can open a directory with `file/open`, but it seems like you can't read from it. Weird thing, seems like using `:r+` to open should help. https://stackoverflow.com/questions/42876210/c-fopen-opening-directories

**Comment by jfcap** [comment]
Replacing `fexists` function in boot.janet by something like 

```
(defn fexists [fname] 
  (let (stat (os/stat fname)) 
    (when (and stat (= (stat :mode) :file)) fname)))
```
should do the job .

**Comment by bakpakin** [comment]
In normal user code it's probably better to use `(= :file (os/stat path :mode))` to check if a file exists, but I want `boot.janet` to work if the `os` module is mostly disabled (this is turned on with `-DJANET_REDUCED_OS`.

**Comment by bakpakin** [comment]
It seems using `:r+` breaks when you can't write to the file due to permission issues. I guess `os/stat` it is, then.

**Comment by bakpakin** [comment]
The latest should now work using `(os/stat)`, with a fallback that uses `file/open` but tries to read a byte from the file first if the reduced os is enabled. The behaviors are a subtly different, but should work very well. I have tested both of the versions `make test-install` and they seem to work.
