### ISSUE TITLE
Nonblocking connect? What stops us currently from doing it?

### ISSUE THREAD

**Issue by llmII** [janet-lang/janet#788]
Looking at the line here in [net.c](https://github.com/janet-lang/janet/blob/e3e01466ee2f209785f878559003d67385ab2eb3/src/core/net.c#L422) it would seem that this is wanted but not yet done? I'm wondering why it isn't. I figure it's not done currently because an issue was come across when trying and am wondering what it may take to make this happen.

**Comment by bakpakin** [comment]
The main issue is async DNS - allow of this code was in place before we had a good mechanism for making calls on a separate thread, although this could now be added with some of the ev C API functions.

Some platforms expose async DNS directly, so ideally we would also take advantage of that.

**Comment by llmII** [comment]
By async DNS, where a platform doesn't expose this, you mean we'd pop DNS requests out to a thread at runtime and send results back and forth over a channel? If so... how many threads? Or maybe I've misunderstood (in which case please correct my idea as to this).

I'm curious as to how it was done with [wahern/cqueues](https://github.com/wahern/cqueues) but some of the code there is difficult for me to wrap my mind around except at moments of extreme enlightenment.

**Comment by bakpakin** [comment]
Exactly, yeah. The main issue is that `getaddrinfo` is blocking, and each OS has a different way to do async getaddrinfo (linux/glibc has `getaddrinfo_a`, windows has https://docs.microsoft.com/en-us/windows/win32/api/windns/nf-windns-dnsquery_a, and I'm not sure about other systems but most would have something.

We could also just farm out to threads - Janet has some utilties so that you don't need to create channels to make a single C level call on a separate thread, but ideally we could use the OS's native APIs for this.

**Comment by llmII** [comment]
> Exactly, yeah. The main issue is that `getaddrinfo` is blocking, and each OS has a different way to do async getaddrinfo (linux/glibc has `getaddrinfo_a`, windows has https://docs.microsoft.com/en-us/windows/win32/api/windns/nf-windns-dnsquery_a, and I'm not sure about other systems but most would have something.

Odd question - is linux/musl a target? That said, doing async DNS however the OS provides for it would be awesome but having to accomodate an API per system (so far I think support is for NetBSD, FreeBSD, OpenBSD, MacOS, Linux, Windows) would be astonishingly hard to get correct most likely. I wouldn't mind giving it a try but I'm not even sure if all the supported systems actually have an async dns API (Does *BSD?). Which might would bring us to a "roll your own" (I mean, may as well if we're going to write one, use it under all OS's, keeps things on one path vs "xyz has subtle bug"). 

> We could also just farm out to threads - Janet has some utilties so that you don't need to create channels to make a single C level call on a separate thread, but ideally we could use the OS's native APIs for this.

Native API's would be far more ideal than using threads for sure.

Oddly enough, saw your reply and got to thinking... Normal DNS is over UDP, Janet supports UDP, could probably write a DNS packet parser directly in Janet. Then it becomes a "wait, the code depends on code that is Janet land to operate". The other thing that becomes obvious is something like I briefly self discussed in #786 ... where one needs a way for fibers to signal other fibers to wake up because the event is complete from within Janet. Then turn it around and consider doing it all in C (more complex) but then my question ends up, can we make fibers in C and have the event loop signal them like we do in Janet. I'd definitely have to read the codebase more. The other thing we could is patch every `janet_loop1_impl` to look for events on the UDP sockets the core library registers and read those and then somehow hand over the DNS result to `net/connect`  to complete a connection (might mean tracking every socket created by Janet and splitting it into address resolution and socket opening phases.

To top it all off, that's also me making a ton of assumptions. For instance, what if getaddrinfo calls when given a NULL port actually find a free port for your application to use for an outgoing connection... now we have to do the "find a free port ordeal". I'd definitely have to read up more on what getaddrinfo does outside of resolving a hostname to an IP but if it does that that greatly intensifies complexity for sure.

Of all the paths mentioned, you know of 2 native provided API's for async DNS, do you know of one for MacOS or *BSD? I wouldn't be surprised if either took the route of "not important" or "library can provide" sadly. I wouldn't want to work on this and it only support 2 systems out of all supported systems.

**Comment by bakpakin** [comment]
linux/musl isn't currently a target, currently we rely on POSIX apis almost exclusively, with a scattering of IDEFS for various compilers, etc - I try not to use any glibc extensions, so musl should jsut work (if not, open bug/feature request).. We really only test with gcc and clang with glibc on linux though.

Custom DNS over UDP is totally possible, although probably best lives in a separate package. `getaddrinfo` and the berkely socket interface may be crufty, but is very flexible and can support things beyond IP. Trying to reimplement all that in the core seems a bit too big for something of Janet's size, although I don't think a full DNS parser would be that difficult.

> To top it all off, that's also me making a ton of assumptions. For instance, what if getaddrinfo calls when given a NULL port actually find a free port for your application to use for an outgoing connection... now we have to do the "find a free port ordeal". I'd definitely have to read up more on what getaddrinfo does outside of resolving a hostname to an IP but if it does that that greatly intensifies complexity for sure.

Was playing around with adding a `bindport` option as well, was stress testing on windows. Certainly some limitations, but seemed to work somewhat. Was not able to pass in bindhost and bindport in all cases, though.

> Then turn it around and consider doing it all in C (more complex) but then my question ends up, can we make fibers in C and have the event loop signal them like we do in Janet.

Yes, there would be a couple of ways to do this. The `ev` module works with state machines internally, driven by events from kqueue, epoll, IOCP, etc from a single file descriptor. On receiving an event, the state machine can either schedule a fiber and mark itself for completion, or do some work and wait for another event. You can do the entire DNS query in C within the Janet event loop, never going into the interpreter ideally.

**Comment by llmII** [comment]
> linux/musl isn't currently a target, currently we rely on POSIX apis almost exclusively, with a scattering of IFDEFS for various compilers, etc - I try not to use any glibc extensions, so musl should jsut work (if not, open bug/feature request).. We really only test with gcc and clang with glibc on linux though.

I wouldn't mind testing it, that said, FreeBSD is my daily driver so it'd likely end up fairly neglected beyond a few random tests here/there, so I figure it'd probably be best to wait for someone who will be a bit more consistent with it.

> Custom DNS over UDP is totally possible, although probably best lives in a separate package. `getaddrinfo` and the berkely socket interface may be crufty, but is very flexible and can support things beyond IP. 

Do you forsee supporting things beyond IP (TCP & UDP) in Janet core? There's a couple of things that might make this difficult. Let's say someone wanted to add STCP (non-core), the issue would be how do they create the socket *and* get it onto the event loop? Is `janet_listen` and `janet_unlisten` exported? Can further states be added to the way things are stepped in `janet_loop_impl` (meaning piggybacking off of `net/read` and `net/write`)? To do it externally you almost need to deal directly with sockets where maybe things would look like:

``` clojure
(def s (net/socket opts))
(ext-net/stcp s)
(net/connect opts)
```

And it would probably mean keeping track internally of "what is Janet core sockets" and what is "externally managed but event loop driven sockets".

All that to say that if one is just trying to support IP (TCP & UDP) in core, making it async by having one's own DNS resolver (that potentially falls back to getaddrinfo [synchronous] when asked to figure out things about a socket that would be outside of those parameters) might wouldn't be *that bad*.

> Was playing around with adding a `bindport` option as well, was stress testing on windows. Certainly some limitations, but seemed to work somewhat. Was not able to pass in bindhost and bindport in all cases, though.

What cases might those have been? Curious, especially since am unsure why one typically would need this for outgoing connections.

> Yes, there would be a couple of ways to do this. The `ev` module works with state machines internally, driven by events from kqueue, epoll, IOCP, etc from a single file descriptor (every state machine (or "JanetListenerState") has one file descriptor it gets events from). On receiving an event, the state machine can either schedule a fiber and mark itself for completion, or do some work and wait for another event. You could do the entire DNS query in C within the Janet event loop, never going into the interpreter ideally.

Seems the idea wasn't quite far off after all as to how to handle DNS requests, the only thing would probably be the need to add a new state to indicate "resolving address" preconnect then step the state with that information being known (somehow). I believe right now the state machine does something like "CONNECT -> READ/WRITE -> CLOSE" (purposefully excluding error states which sort of short circuit to "CLOSE" for simplicity.

The key is adding a "PRECONNECT" state that can somehow pass forward the address resolution in a consumable format. Would have to look how information is passed between state transitions, since "PRECONNECT -> CONNECT" would basically exist prior to OS event loops (again simplifying a bit).

**Comment by pepe** [comment]
Just FYI, @bakpakin, my main Janet dev machine is musl void Linux, and I have never had any problems compiling and running Janet here, so I guess you are right in your assumption.

**Comment by llmII** [comment]
The more I look into it, the less ideal it seems to use `getaddrinfo_a` or similar (limitations with regards as to _what_ is to be resolved such as can't handle MX lookups).

The further I look into it, I start to believe writing one from scratch is a NIH ordeal and would be quite the expenditure of time when there are already solid solutions out there for doing this in an event loop. The thing that keyed me off to this is that we'd need to implement a parser for each RR type of interest, in addition to a packet parser that not only handles DNS, but EDNS as well (both packing for sending, and unpacking for receipt). It's definitely a complex task to implement as part of the Janet project.

That would seem to mean using threads. One idea is for Janet users to simply hand a socket off to a thread(pool) for connect in Janet code (not in the C source) then hand the socket back down to the thread that intends to use it when connection is successful.

Another idea, and probably unwanted too as it would import a ton of code from some other project (thousands of lines), or have a build time (possibly optional) dependency on some other project, is to make use of some other library (think [wahern/dns](https://github.com/wahern/dns) or possibly c-ares (mentioned for the sake of an alternative). The plus side of wahern/dns is it provides for a way to use your own event loop, so no "are we dealing with setjmp/longjmp/callback-hell" code. The downside is EDNS support is not finished (maybe EDNS isn't needed after all), but seems partially supported (I think what it means is that certain EDNS response types would need the user of the code to create their own parser for said response type).

Yet another idea, is simply create one specifically for Janet, but don't include EDNS support (which may be a step backwards from `getaddrinfo` and friends, but seemingly works "just fine" in general?).

Maybe the best approach is to just say that "connection is synchronous, but if you provide your own address resolution and pass a "do-not-block" flag we'll let you do it async anyway (with the caveat it's on the user to handle "I issued a connect, but turns out it didn't actually succeed and I got an error that the socket was closed").

**Comment by bakpakin** [comment]
So it has been a while, but I think the consensus here is that we will be better off leaving connection as synchronous by default. I think having an external package for async DNS isn't all that bad as you could have a function that would just resolve names to IP addresses. This would be a good fit for spork, as I think we could do this without adding any dependencies beyond libc and OS apis. 

The point about a "no-block" flag is interesting, if we could do that simply it may be a good addition.

**Comment by zevv** [comment]
I have started a simply but functional async resolver library in pure Janet; this does not rely on `getaddrinfo()` or any other host-specific APIs but instead implements the DNS protocol and talks directly to the DNS servers.

I must admit I have not read or written much Janet code up to now, so I might have made stupid mistakes or messed up on the  idioms; I'd be more than happy to receive any reviews of the code.

https://github.com/zevv/janet-dns/tree/master
