### ISSUE TITLE
Undefined Behavior in push_traversal_node

### ISSUE THREAD

**Issue by marler8997** [janet-lang/janet#795]
This issue was found while trying to compile janet with zig cc (see https://github.com/ziglang/zig/issues/9701).

It looks like the `push_traversal_node` function in `value.c` performs pointer arithmetic on a `NULL` pointer, which in C is undefined behavior.  The following is the offender:

```c
    if (janet_vm.traversal + 1 >= janet_vm.traversal_top) {
```

The reason this gets caught when using `zig cc` is because it enables ubsan (undefined behavior santization) by default, i.e. `-fsanitize=undefined`.

I'm not certain what the best solution here is.  Here are some options:

1. modify all code that performs pointer arithmetic on nullable pointers to check for `NULL` first
2. cast the pointer to `size_t` before performing arithmetic on it
3. in this case you could initialize the pointer to a non-null value by pre-allocating the buffer and just never set it to null
4. set the pointer to some dummy non-null value, then turn that special value into `NULL` when calling `realloc`

**Comment by bakpakin** [comment]
Hmm, yeah it should be easy to add a NULL check to the condition as well. We will also need to redo the size calculation to avoid any arithmetic with NULL.

**Comment by bakpakin** [comment]
Should be fixed, Please verify and close @marler8997

**Comment by marler8997** [comment]
It looks like this instance of UB has been fixed.  I believe I'm still hitting another instance of UB but I will create another issue for that.
