### ISSUE TITLE
Mechanism to pin Janet runtime in project.janet

### ISSUE THREAD

**Issue by dbready** [janet-lang/janet#798]
Is there a blessed way to indicate an explicit/minimal/maximal version of Janet which should be used for an application? Not necessarily enforced, but at least something that could be checked to confirm compatibility.

It seems there have been few (any?) breaking changes that would necessitate a setting, but it helps my anxiety if I knew I could pin code to a specific release.

Something as simple such as:

```lisp
(declare-project
  :name "fooapp"
  :janetlang “>1.17.0”)
```

**Comment by bakpakin** [comment]
Currently, you could just add an assert for janet/version being what you need. Could be nice to have a declarative way to do it.

**Comment by pyrmont** [comment]
This issue should probably be [transferred](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) to the [janet-lang/jpm](https://github.com/janet-lang/jpm) repository.
