### ISSUE TITLE
Macro issue (maybe?)

### ISSUE THREAD

**Issue by llmII** [janet-lang/janet#802]
Say I have the following code:
``` clojure
(defn fixing*
  []
  (def name 'fixable)
  ~(def ,name "fixed?"))

(defmacro fixing
  []
  (fixing*))

(fixing)
fixable
# Output in comments
# <function fixing*>
# <function fixing>
# "fixed?"
# "fixed?"
```

So the macro works. But lets change it up a bit, a macro with arguments.
``` clojure
(defn fixing*
  [name]
  ~(def ,name "fixed?"))

(defmacro fixing
  [name]
  (fixing* name))

(fixing 'fixable)
fixable
# Output in comments
# <function fixing*>
# <function fixing>
# "fixed?"
# 105
```

For the life of me, battling at it for over 2 days in a myriad of ways, I cannot understand why even this which is super simplified results in the value of it being 105. I did do my best to get it down into the smallest example possible. 

Reasoning:
`macex` on `fixing*` results in `(def fixable "fixed?")` so it would be assumed that the expression yielded, is what's evaluated.

**Comment by pepe** [comment]
I guess it is a destructuring in the works, `(macex '(fixing 'fixing))` returns `(def (quote fixing) "fixed?")` so you are binding `f` (first char of the string) to `quote` (check its value in the repl) and `i` (second char of the string) to your symbol `fixing`. Or the other way around :-D. When called `(fixing fixable)` it works as expected.

**Comment by llmII** [comment]
Ah, you're right, it's rebinding quote... no wonder I keep having to restart the repl because things seem way off and execute differently on a new one.

So calling it without a quoted symbol works.

What I've been trying to do, without any success is say there are 2 implementations of `pp` (pretty print) (except imagine it's for a lot of different functions in an implementation, vs a single function which might be done other ways in a trivial manner). We'll call implementation 1 `funny/pp` and implementation 2 `comedic/pp` (again, I suck at names for things in examples).

What I'm trying to do is have a macro that says something like, if mood is funny create a binding to funny/pp as _pp. Then the rest of the code doesn't have to repeat the "if mood" part and just do an outright call to _pp.

I've went through so many iterations of this with no success trying to operate on a quoted tuple with `(each to-be-bound realnames (macro to-be-bound)` where the tuple is a quoted tuple like `'(short-name1 short-name2)`.

I'll try again and see if I can get things to where they're not attempting to mess with quoted symbols, but if there's any insights on basically having a macro create a name, where it takes a name (say "pp") and modifies it to be "_pp" and binds it to "funny/pp", and bind a function to it I'd appreciate the help.

**Comment by pepe** [comment]
I am not really sure, I can understand what you need. Would you mind showing me the hypothetical code snippet and its outputs? And maybe start a GH discussion, because this is clearly not an issue with Janet :-).
