### ISSUE TITLE
flycheck breaks :export true

### ISSUE THREAD

**Issue by saikyun** [janet-lang/janet#804]
When using `flycheck` on a file that makes use of a module that has `:export true`, it seems to make the exported symbols `nil`.

test.janet
```
(import spork/path :as p :export true)
```

test-export.janet
```
(use ./test)

(defn wat
  []
  (pp (p/abspath? "aoeu")))
```

test-flycheck.janet
```
### if you remove the call to flycheck, it won't break
(flycheck "./test-export.janet")

(use ./test-export)

(wat)
```

In terminal:
```
janet test-flycheck.janet
expected integer key in range [0, 4), got nil
  in wat [test-export.janet] on line 5, column 7
  in _thunk [test-flycheck.janet] (tailcall) on line 5, column 1
```

**Comment by bakpakin** [comment]
Yeah, flycheck is polluting the module cache with a partial environment, only really meant for flychecking. Not sure what the best solution here is, but probably flycheck should somehow not mess with the module cache.

**Comment by saikyun** [comment]
Ah all right, maybe I'm not using it for the right thing. Tried using it to
validate files before dofile'ing them (as to not eval half files and some
other reasons).

But it's no big deal, for now I just ignore import/use forms and it solves
the problem for me. Just wanted to bring it up in case it was
unintentional. :)

Den tis 14 sep. 2021 23:00Calvin Rose ***@***.***> skrev:
