### ISSUE TITLE
Correct way of using janet_wrap_array

### ISSUE THREAD

**Issue by lucasemmoreira** [janet-lang/janet#805]
Hi there, 

I am trying to use janet c api on ncurses and I am not getting what I expected.

I tried to define the function as such on the c file

```c
static Janet jgetyx(int32_t argc, Janet *argv){
  janet_fixarity(argc, 1);
  WINDOW *win = (WINDOW *) janet_getpointer(argv, 0);
  int y, x; 
  getyx(win, y, x);
  int *yxpos[2] = {y, x};
  return janet_wrap_array((JanetArray *) &yxpos);
}
```

And I called the defined function like so

```janet
(nc/mvwprintw win 2 2 (string (get info 1) " " (get info 0)))
```

But my result was

```
          this is the header─┐
          │this is a box     │
          │ 4.64148e-310 3.458
          46e-323            │
          │                  │
          │                  │
          │                  │
          │                  │
          │                  │
          └──────────────────┘
```

I expected to have the values on the second line of the box, but instead I got the memory address for what it seems... My rusty knowledge of c cannot bring me any closer to the solution...

Could anyone help me?

The code can be found [here][1] on `test/term-info.janet`.

Thx!

  [1]: https://git.sr.ht/~lucasemmoreira/janet-ncurses/tree/feature/win-info

**Comment by llmII** [comment]
> ```c
> static Janet jgetyx(int32_t argc, Janet *argv){
>   janet_fixarity(argc, 1);
>   WINDOW *win = (WINDOW *) janet_getpointer(argv, 0);
>   int y, x; 
>   getyx(win, y, x);
>   int *yxpos[2] = {y, x};
>   return janet_wrap_array((JanetArray *) &yxpos);
> }

As to array, it should probably be something like [this](https://github.com/janet-lang/janet/blob/4d746794cccbde10b91e9e3a6082c18ba6a39871/src/core/net.c#L339-L348)

``` c
int y, x;
getyx(win, y, x);
JanetArray *arr = janet_array(2);
janet_array_push(arr, janet_wrap_integer(y));
janet_array_push(arr, janet_wrap_integer(x));
return janet_wrap_array(arr);
```

**Comment by sogaiu** [comment]
On a side note, I noticed the other day, the `<something>_test.c` files in [`src/boot`](https://github.com/janet-lang/janet/tree/da2c1be49c8407856a705278d2261e9734f8ea6c/src/boot).

For the current case, parts of [`array_test.c`](https://github.com/janet-lang/janet/blob/da2c1be49c8407856a705278d2261e9734f8ea6c/src/boot/array_test.c#L31-L36) (for the array portions) and parts of [`table_test.c`](https://github.com/janet-lang/janet/blob/da2c1be49c8407856a705278d2261e9734f8ea6c/src/boot/table_test.c#L35) (for `janet_wrap_integer`) seemed relevant.

**Comment by lucasemmoreira** [comment]
@llmII worked like a charm! thank you!

@sogaiu that is really cool! I have never checked that folder, thanks for the tip!
