### ISSUE TITLE
`(defn fun* [] ())` when displayed with `doc` shows as `(fun)` instead of `(fun*)`

### ISSUE THREAD

**Issue by llmII** [janet-lang/janet#809]
As per title, markdown issue?

In an REPL do:
```
(defn fun* [] ())
(doc fun*)
```

Output is:
```
Janet 1.17.1-468a31f5 freebsd/x64 - '(doc)' for help
repl:1:> (defn fun* [] ())
<function fun*>
repl:2:> (doc fun*)


    function
    repl on line 1, column 1

    (fun)


nil
repl:3:> 
```

**Comment by bakpakin** [comment]
Yes, `*` is considered to be a delimiter for italics in markdown, and the doc formatter does not do any look ahead for parsing. We probably should consider removing the first line from markdown semantics when printing or something similar.
