### ISSUE TITLE
Make C api linkable

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#81]
When using nanboxes lot's of the user facing API is not linkable, this is a problem when calling janet functions from non C languages which generally don't support macros, only external C functions.

I hit this problem while using rust's bindgen program to write a janet module, where most of the wrap and unwrap functions are not usable.

I think it is possible to have linkable symbols and inlined functions with some changes.

**Comment by bakpakin** [comment]
We could either provide function versions of API macros, or simply replace the macro versions with functions. The latter is cleaner, but I'm not sure how reliably all C compilers support LTO (the overhead of a function call for such a primitive operation seems unacceptable). Clang, GCC, and MSVC will probably support it well on most architectures.

**Comment by bakpakin** [comment]
The latest master should have made most of the API functions linkable, including all of the wrap/unwrap functions. This works as now the previously macro only API definitions have a function version of the same name, which wraps the macro. When linking to non-C languages, you should get the function version, but if you have a C preprocessor, you will get the macro version. This is a standard technique, discussed here https://softwareengineering.stackexchange.com/questions/159846/why-does-the-c-library-use-macros-and-functions-with-same-name

**Comment by bakpakin** [comment]
I haven't directly tested this with bindgen, but I believe it should work :crossed_fingers:
