### ISSUE TITLE
`defglobal` in `do` special form.

### ISSUE THREAD

**Issue by soulawaker** [janet-lang/janet#813]
`defglobal` works in `do` but a defined symbol can't be used in. Also same in `let`.
It seems that it's a bug. 

```clojure
(do (def t1 @[])
      (array/push t1 'ok))
@[ok]

(do (defglobal "t2" @[])
      (array/push t2 'ok))
compile error: unknown symbol t2
```

**Comment by bakpakin** [comment]
This is not a bug, this is how incremental compilation works. `t2` will not be available until the next top level form.

**Comment by soulawaker** [comment]
@bakpakin Thanks you. I'm happy with the author's direct explanation.:+1:  IMHO maybe other curious bystanders also be happy if this commentary be placed somewhere in doc.
