### ISSUE TITLE
kqueue ABSTIME under FreeBSD (ev/sleep) dislikes timers that expire before being mapped into the kqueue.

### ISSUE THREAD

**Issue by llmII** [janet-lang/janet#819]
What I believe is happening, is that ABSTIME is in milliseconds... and 0 milliseconds (or slightly more) being mapped in as $now+$interval in absolute time has already occured by time the kqueue has the event mapped into it, and it gives an invalid argument error to ev.

Basically, every `(ev/sleep 0)` fails.

The solution... only ever use intervals with kqueue. It means a subtraction operation occurs every timeout that is mapped into the kqueue. The only place where this would remain slightly special is NetBSD where it's invalid for there to be an interval below 1 millisecond.

I'll probably work on this some tomorrow, I have a fix, just it is really a simple hack at the moment and causes compiler warnings. The fix would need to be tested against NetBSD, FreeBSD, and OpenBSD (and depend on CI for the MacOS test).

**Comment by kevans91** [comment]
if NetBSD and OpenBSD are already OK with it, I don't see any reason off-hand that we (FreeBSD) can't clamp the timer back up to 0 and expire it immediately... that'd take a while to get into a release that's usable for you all, of course.

**Comment by llmII** [comment]
@kevans91 - OpenBSD and NetBSD don't even support ABSTIME actually. FreeBSD is the only BSD that I know of with ABSTIME support in kqueue. Clamping ABSTIME to 0 when absolute time is in the past would be awesome, and I'd go out on a limb and guess this isn't the first time this has been encountered, where a timeout is so near term that putting it into kqueue results in an invalid argument error. Determining at runtime that "this time, whilst valid and in the future as of now, will remain such after a syscall" is probably an impossibility for userland software.

My statements as to ABSTIME with NetBSD and OpenBSD may be incorrect if changes have occured within about a month.

I'd also note that NetBSD doesn't support ABSTIME, but with intervals in timers, the minimum interval is 1ms. I'm unsure if with intervals OpenBSD or NetBSD support higher resolution timers than milliseconds.

**Comment by kevans91** [comment]
So, looking at our implementation of NOTE_ABSTIME again: https://cgit.freebsd.org/src/tree/sys/kern/kern_event.c?id=f66b9b40f403f7c30fec3c4ceed93c6e8fafa8ac#n801 -> if you're really just converting a relative 0/positive time to abstime, then we shouldn't hit an EINVAL for that unless the system clock has adjusted past that point. That's still not ideal to have some arbitrary restriction like that, but I wonder if there's something else going on here.

**Comment by llmII** [comment]
@kevans91 - Basically, say we do `(ev/sleep 0)` (or, acquire a timer that expires *right now*). By time we submit now, in absolute time milliseconds, to the kqueue, in a timer filter, the timer is already expired, invalid. It's also likely this is the case up to an arbitrary number of milliseconds per system dependent upon system load as well (say the process collects it's time at t0, is preemptively interrupted, and comes back at t0+2ms, the timer's absolute time has already expired). The only way to acquire short ABSTIME timers and be sure they work correctly is to resolve time atomically at the point where the event is submitted (as in, no time can pass between resolving the timer, and kqueue determining if the time is invalid or not), or to always acquire timers that are at least a few (insert arbitrary time amount) from whatever the time is at the point of acquisition.

When I worked with the kqueue code originally I actually assumed ABSTIME was clamped down to "now" if the timer submitted was for a past time, and I ran tests and seemed correct (guess my machine wasn't properly loaded to obviate the issue at that time perhaps, or something else that I can't account for).

**Comment by kevans91** [comment]
Sorry, I kind of mis-spoke there; what I was trying to say is that you're correct, it will get clamped down, but these values are internally made relative to the boot time. The only way to hit this in typical usage looks to be if you got excessively unlucky and the system clock was adjusted forward (e.g., by ntpd) enough that the `newtime - uptime` is after the point the timer was set for.

**Comment by llmII** [comment]
What I meant was we are/were operating on absolute times (Janet operates in those). So in the kqueue code for FreeBSD in Janet we just passed the absolute time in to the timer as an absolute time. Only under NetBSD/OpenBSD did we ever convert an absolute time into an interval.

If you're saying my assumption was correct, that when an absolute time from the past is submitted, it gets clamped to "now" and kevent treats it as a 0 timeout then I may have to wonder what other thing(s) I did wrong to get this issue consistently occuring in the test suite the other day.

**Comment by kevans91** [comment]
> If you're saying my assumption was correct, that when an absolute time from the past is submitted, it gets clamped to "now" and kevent treats it as a 0 timeout then I may have to wonder what other thing(s) I did wrong to get this issue consistently occuring in the test suite the other day.

What kind of environment was it running in? (FreeBSD version + architecture) We did have a bug on architectures with 32-bit pointers that would've more generally messed up absolute timeouts exceeding 32-bit range: https://cgit.freebsd.org/src/commit/sys/kern/kern_event.c?id=59dafcde62708ec98b756142bfc6e3387ac87082 -- the fix for this is present in 13.0, but not yet in 12.1 (it will be in 12.2).

I've staged a change including tests to FreeBSD: https://people.freebsd.org/~kevans/kq.diff -> only the `test_abstime_preboot()` test was failing without the associated kernel change applied, though, and `test_abstime_postboot()` is explicitly generating a timeout for one second in the past.

**Comment by llmII** [comment]
@kevans91 
```
uname -a
FreeBSD lmartin92-dev 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
```

Don't think I'd have encountered 32bit errors. 

The change you're referencing has already been committed or is that a change to be merged at some point?
Either way, your changes applied, and preboot only failing, I really do wonder how I managed to get EINVAL within Janet's test suite. I mean, with you having applied and tested your changes, I haven't done any application of your changes to my system.

**Comment by kevans91** [comment]
Pending change- I've submitted it for review here: https://reviews.freebsd.org/D32230

I'll see if I can reproduce this, though, independent of that... I've not been successful yet with our `main` branch and janet-lang/janet checked out at e1ec0d13ae55cd0d1f0b14033fe00bd063b9981c. I note that suite 9 takes a whole 3 seconds longer (mostly from the earlier os/spawn stuff) on FreeBSD 12.2 than it does on `main`, which is interesting.

**Comment by llmII** [comment]
@kevans91 - I never tested FreeBSD 12.2 so I never saw that... I only saw the quick side on FreeBSD 13. There's also recent changes to the kqueue code and the test suite. The new kqueue code doesn't use timers, but the timeout per kevent call. The test suite now tries something that causes it to hang (line 155 for about 20 to 30 lines in suite 0009). If one adds (ev/sleep 5) as the last call inside the with's, it does not hang at all. I am at a loss of sorts for what's going on there too.
