### ISSUE TITLE
BSD + MacOS hang

### ISSUE THREAD

**Issue by bakpakin** [janet-lang/janet#822]
The a slight change in suite 9 for peername localname seems to have exposed a hang using kqueue on BSDs in CI, both on GitHub and in Sourcehut - see 504411eade2860d3a51482ea4eb2dda1e7999317

I expect that something is happening here with handling concurrent reads and writes on the same file descriptor - not sure if this is an issue with the kqueue implementation, or with BSD in general.

To summarize:
- We need to verify if this happens when janet is built without kqueue support
- If kqueue is the issue, identify and fix our implementation. If BSD is the issue, figure out what events we are missing or skipping causing a concurrent read and write on the same stream to hang.

**Comment by llmII** [comment]
Verified under FreeBSD that without kqueue the test does not hang.

Trying adding (ev/sleep 5) to keep the `:close` from happening too quick at the end of each side of the names testing (client and server) causes it to work... I'm wondering if the gc is dropping the connection out before the connections are finalized in kqueue or something?

**Comment by llmII** [comment]
``` clojure
(repeat 20

  (defn check-matching-names [stream]
    (def [my-ip my-port] (net/localname stream))
    (def [remote-ip remote-port] (net/peername stream))
    (def msg (string my-ip " " my-port " " remote-ip " " remote-port))
    (def buf @"")
    (ev/gather
      (net/write stream msg)
      (net/read stream 1024 buf))
    (def comparison (string/split " " buf))
    (assert (and (= my-ip (get comparison 2))
                 (= (string my-port) (get comparison 3))
                 (= remote-ip (get comparison 0))
                 (= (string remote-port) (get comparison 1)))
            "localname should match peername"))

  # Test on both server and client
  (defn names-handler
    [stream]
    (defer (:close stream)
      (check-matching-names stream)))
  (with [s (net/server "127.0.0.1" "8000" names-handler)]
    (defn test-names []
      (with [conn (net/connect "127.0.0.1" "8000")]
        (check-matching-names conn)
        (ev/sleep 5))
    (test-names)
    (test-names)
    (ev/sleep 5)))
```

Note where the `(ev/sleep 5)`s are, and that this causes it to work...

With the ev code, is it possible to close a socket without removing tied events? I'm unsure if closing a socket should trigger a read/write event either, there may be some other event I need to test against as well perhaps.

**Comment by llmII** [comment]
From the man page (for EVFILT_READ):
```
			     If	the read direction of the socket has shutdown,
			     then the filter also sets EV_EOF in flags,	and
			     returns the socket	error (if any) in fflags.  It
			     is	possible for EOF to be returned	(indicating
			     the connection is gone) while there is still data
			     pending in	the socket buffer.
```

For EVFILT_WRITE:
```
                         filter	will set EV_EOF	when the reader	disconnects,
			 and for the fifo case,	this will be cleared when a
			 new reader connects.  Note that this filter is	not
			 supported for vnodes or BPF devices.
```

The kqueue code looks like it checks for error primarily, and if there is, skips all read/write (this could be an error that the socket is closed though an event is listened for against it?). If that's the case then it's skipping reading whatsoever which could cause the hang (that fiber's waiting to get something back, and has effected no timeout). However, the error isn't getting propagated up it seems perhaps? Otherwise the check against filters could possibly be ordered incorrectly?

I'll try checking  for EV_ERROR separately without a shortcut to JANET_ASYNC_EVENT_ERR per filter, but not on the EV_EOF, which means I'm assuming JANET_ASYNC_EVENT_HUP will empty read buffers if there are any data buffered in the socket.

**Comment by llmII** [comment]
With the change I had, checking error per, instead of overall, I'm not certain how it turned out, made a few local changes and finally stuck a printf to see the events kqueue was giving and saw I was infinite looping, no idea if it were due to local changes or the original change.

I decided to stick the printf into master and got:
```
EVFILT_READ: -1 EVFILT_WRITE: -2
 filter: -2, flags: 0, is_err? 0, is_eof? 0
```

and then it hung. No error, no eof, event was write, but hung.

Still investigating.

**Comment by llmII** [comment]
Well, I was wrong, it infinite loops with write event being seen, not a read event at all seen. Might be a difference between the test code in the suites and that I extracted the failing names test and had it just do it once instead of on repeat.

**Comment by llmII** [comment]
I would also note that the loop1_impl is being called repeatedly. It's not an infinite loop on the for statement inside of it.

**Comment by llmII** [comment]
Removing `(ev/gather ...` makes this work too, so for some reason it's like it's trying the write fiber repeatedly...

Swapping the read and write within the gather fixes things as well. Something gets it stuck trying to write for some reason though...

**Comment by llmII** [comment]
It looks as if net/read never gets called, that things get stuck at write and every time the event loop opens up it just jumps back to the write event -

```
EVFILT_READ: -1 EVFILT_WRITE: -2
 filter: -2, flags: 0, is_err? 0, is_eof? 0 event# 0 count 2
DONE=1: 0 0 0 0
EVFILT_READ: -1 EVFILT_WRITE: -2
 filter: -2, flags: 0, is_err? 0, is_eof? 0 event# 1 count 2
DONE=1: 0 0 0 0
```

Is basically what's on repeat.

This is the names test being pulled out and ran in an REPL with some debug printf's in the code.

It almost seems like the write call never gets completed and marked as complete and so every time the event loop opens up, it's just being told it can write, even though the write probably actually already completed possibly.

**Comment by llmII** [comment]
So, checking some more, I added a "want read" or "want write" to the janet_listen for kqueue - we get his sequence of wants
```
want read
want write
want read
want write
want write
want read
want write
```

The back to back write wants almost makes me wonder if somehow 2 writes are being issued and the second write is what keeps getting a retry and hangs in an infinite loop basically.

**Comment by llmII** [comment]
Outputs under kqueue are as below:

test3 (no ev/gather):
```
want write
want read
ident: 8, event: write, data: 49032, error: 0, eof: 0, fflags: 0, event count: 2
ident: 7, event: read, data: 1, error: 0, eof: 0, fflags: 0, event count: 2
want read
want write
ident: 8, event: write, data: 49002, error: 0, eof: 0, fflags: 0, event count: 2
ident: 9, event: write, data: 49032, error: 0, eof: 0, fflags: 0, event count: 2
want read
ident: 8, event: write, data: 49032, error: 0, eof: 0, fflags: 0, event count: 3
ident: 9, event: write, data: 49002, error: 0, eof: 0, fflags: 0, event count: 3
ident: 9, event: read, data: 30, error: 0, eof: 0, fflags: 0, event count: 3
comparing
Closing stream!
ident: 8, event: write, data: 49032, error: 0, eof: 0, fflags: 0, event count: 2
ident: 8, event: read, data: 30, error: 0, eof: 32768, fflags: 0, event count: 2
comparing
Closing stream!
Closing stream!
done
```
test2 (read before write):
```
want read
want read
want read
want write
ident: 7, event: read, data: 1, error: 0, eof: 0, fflags: 0, event count: 2
ident: 8, event: write, data: 49032, error: 0, eof: 0, fflags: 0, event count: 2
want read
want read
want write
ident: 8, event: write, data: 49002, error: 0, eof: 0, fflags: 0, event count: 3
ident: 9, event: read, data: 30, error: 0, eof: 0, fflags: 0, event count: 3
ident: 9, event: write, data: 49032, error: 0, eof: 0, fflags: 0, event count: 3
ident: 8, event: write, data: 49002, error: 0, eof: 0, fflags: 0, event count: 3
ident: 9, event: read, data: 30, error: 0, eof: 0, fflags: 0, event count: 3
ident: 9, event: write, data: 49002, error: 0, eof: 0, fflags: 0, event count: 3
comparing
Closing stream!
ident: 8, event: write, data: 49032, error: 0, eof: 0, fflags: 0, event count: 2
ident: 8, event: read, data: 30, error: 0, eof: 0, fflags: 0, event count: 2
comparing
Closing stream!
Closing stream!
done
```
test (truncated, same as in suite):
```
want read
want write
want read
want write
ident: 7, event: read, data: 1, error: 0, eof: 0, fflags: 0, event count: 2
ident: 8, event: write, data: 49032, error: 0, eof: 0, fflags: 0, event count: 2
want write
want read
want write
ident: 8, event: write, data: 49032, error: 0, eof: 0, fflags: 0, event count: 2
ident: 9, event: write, data: 49032, error: 0, eof: 0, fflags: 0, event count: 2 
... (last 2 lines repeat to infinity)
```
excerpt from truss on the test (truncated, same as in suite):
```
kevent(5,{ 7,EVFILT_READ,EV_ADD|EV_ENABLE,0,0,0x800b57c60 },1,0x0,0,0x0) = 0 (0x0)
kevent(5,{ 8,EVFILT_WRITE,EV_ADD|EV_ENABLE,0,0,0x800b57ce0 },1,0x0,0,0x0) = 0 (0x0)
kevent(5,{ 8,EVFILT_READ,EV_ADD|EV_ENABLE,0,0,0x800b57ce0 8,EVFILT_WRITE,EV_ADD|EV_ENABLE,0,0,0x800b57ce0 },2,0x0,0,0x0) = 0 (0x0)
kevent(5,0x0,0,{ 7,EVFILT_READ,0x0,0,0x1,0x800b57c60 8,EVFILT_WRITE,0x0,0,0xbf88,0x800b57ce0 },64,0x0) = 2 (0x2)
accept(7,NULL,0x0)                               = 9 (0x9)
fcntl(9,F_GETFL,)                                = 6 (0x6)
fcntl(9,F_SETFL,O_RDWR|O_NONBLOCK|O_CLOEXEC)     = 0 (0x0)
getsockname(9,{ AF_INET 127.0.0.1:8000 },0x7fffffffd234) = 0 (0x0)
getpeername(9,{ AF_INET 127.0.0.1:27265 },0x7fffffffd234) = 0 (0x0)
kevent(5,{ 9,EVFILT_WRITE,EV_ADD|EV_ENABLE,0,0,0x800b57da0 },1,0x0,0,0x0) = 0 (0x0)
kevent(5,{ 9,EVFILT_READ,EV_ADD|EV_ENABLE,0,0,0x800b57da0 9,EVFILT_WRITE,EV_ADD|EV_ENABLE,0,0,0x800b57da0 },2,0x0,0,0x0) = 0 (0x0)
```

In all, ident 7 is the listening socket (server), 8 and 9 are the accepted and client socket (not sure which is which though).

truss shows an EVFILT_READ mapped on idents 8 and 9,  and later on... throughout the entire execution up to CTRL+C, you'd see that it only ever triggers the write filter.

The big issue here is, 40932. kqueue can't keep saying "you have the same amount of space to write that you did since the start" every time it signals the write filter if a write has actually been made. The write isn't transitioning to the 30 bytes less stage like it does in the other tests.
