### ISSUE TITLE
SIGSEGV in the ev loop

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#829]
I started to get intermittent sigsegv in production for my web app. I tried the Valgrind and call grind, but I am not really sure what to look for. Interesting (hopefully) part of the Valgrind output, when app crashed once under valgrind:
```
==1894300== Invalid write of size 8
==1894300==    at 0x12E5D8: janet_loop1 (in /usr/local/bin/janet)
==1894300==    by 0x12E92C: janet_loop (in /usr/local/bin/janet)
==1894300==    by 0x14723C: janet_loop_fiber (in /usr/local/bin/janet)
==1894300==    by 0x115BCC: main (in /usr/local/bin/janet)
==1894300==  Address 0x18 is not stack'd, malloc'd or (recently) free'd
==1894300==
==1894300==
==1894300== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==1894300==  Access not within mapped region at address 0x18
==1894300==    at 0x12E5D8: janet_loop1 (in /usr/local/bin/janet)
==1894300==    by 0x12E92C: janet_loop (in /usr/local/bin/janet)
==1894300==    by 0x14723C: janet_loop_fiber (in /usr/local/bin/janet)
==1894300==    by 0x115BCC: main (in /usr/local/bin/janet)
```

It seems that it started after 504411eade2860d3a51482ea4eb2dda1e7999317 but it is very hard to tell. For the above error, I had to spend a lot of time getting it. I also have vgcore file, but Janet was not compiled with debug info, so if I understand it right it is useless.

**Comment by pepe** [comment]
So as always, something not right can make something (being me) better. I have compiled Janet with gdb support and ran the application with it. It luckily sigsegved quite soon so I was able to debug it. The record of the session can be seen here https://paste.sr.ht/~pepe/c82766d68e58b34dad71b44b8848d873045bacf1 

But I am afraid, that my skills are not enough to fix it. If you need any other information, please let me know.

**Comment by pepe** [comment]
Per @sogaiu recommendation, I have created another session record with events pretty printed https://paste.sr.ht/~pepe/73efcc7b52df1544a1ed48d06b0173654f26014f. I hope it helps.

**Comment by bakpakin** [comment]
More helpful would be the application and dependency list that triggers this - it seems to be an event that shouldn't happen - epoll should not be listening on file descriptors that don't have an associated state machine.

**Comment by pepe** [comment]
The fix seems to work. Thank you.
