### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by hgsbart** [janet-lang/janet#833]
Doesn't let you choose the installation folder with the .msi and the .zip files don't have the jpm for native extensions??

**Comment by bakpakin** [comment]
`jpm` is no longer distributed with Janet, instead it can be installed separately.

**Comment by hgsbart** [comment]
@bakpakin and how do I install it

**Comment by bakpakin** [comment]
Jpm can be installed by following the instructions at janet-lang/jpm

**Comment by hgsbart** [comment]
I got this on Windows 11

destdir:
Using install prefix: /usr/local
binpath:
libpath:
manpath:
headerpath:
modpath: (default to JANET_PATH at runtime)
Setting package listing: https://github.com/janet-lang/pkgs.git
Running jpm to self install...
error: invalid configuration binding :headerpath, expected :string, got nil
  in errorf [boot.janet] on line 165, column 3
  in load-config [jpm/config.janet] (tailcall) on line 146, column 7
  in setup [jpm/cli.janet] on line 60, column 7
  in run [jpm/cli.janet] (tailcall) on line 86, column 15
  in _thunk [jpm/cli.janet] (tailcall) on line -1, column -1
  in cli-main [boot.janet] on line 3644, column 17
command failed with non-zero exit code 1
  in os/execute [src/core/os.c] on line 1049
  in do-bootstrap [bootstrap.janet] on line 14, column 3
  in _thunk [bootstrap.janet] (tailcall) on line 26, column 1

**Comment by bakpakin** [comment]
However you installed Janet, there are some environment variables that were not set. JPM needs to know where the Janet headers and shared objects are. If you use the msi installer, these will be set for you. Otherwise, you can set them manually. The env variables you need to set should be documented on the man page, or you can look in make-config.janet around line 15 for the environment variables you would use.

**Comment by hgsbart** [comment]
@bakpakin ok I used the msi and it worked I tried just installing using the .zip and adding it to my path and that was the problem. But the installer doesn't show where janet is being installed, anyway thank you for the help
