### ISSUE TITLE
Better REPL: Replace linenoise with bestline

### ISSUE THREAD

**Issue by elimisteve** [janet-lang/janet#856]
It looks like this might be easy to do! And I would love the much better keyboard shortcut support: https://github.com/jart/bestline#changes

**Comment by sogaiu** [comment]
That looks quite nice.

**Comment by leahneukirchen** [comment]
The highlighting of matching parentheses is super useful.

**Comment by pepe** [comment]
Unicode chars.

**Comment by elimisteve** [comment]
Totally, plus multiline mode is one of the only things that ipython does that I really want in Janet's shell; using the shell history isn't that useful if I want to tweak the definition of a 5-line function and each line is a separate entry in the history!

**Comment by pepe** [comment]
The question here is how much work it would be if it is possible at all.

**Comment by sogaiu** [comment]
Just to clarify -- are there any files apart from: https://github.com/janet-lang/janet/blob/9cc4e48124d36f9b986bc4f1ddf948c76f965ca8/src/mainclient/shell.c that would be affected if implementing this idea?

**Comment by leahneukirchen** [comment]
I'm not sure bestline has that, multiline refers to "showing a long line as multiple lines", I think?

I think we just need to replace line() essentially.

**Comment by bakpakin** [comment]
Not sure I will add any dependencies to the main janet distribution. However, nothing is stopping anyone from making their own shell.c - most of the code in there is just re-implementing parts of linenoise. The only other extra thing is tab completion with bindings in the current environment table.

**Comment by jart** [comment]
Author of bestline here. I've cleared out the two blocking issues your team filed. See https://github.com/jart/bestline/issues/12 and https://github.com/jart/bestline/issues/13 I've been a vocal supporter of Janet (see https://news.ycombinator.com/item?id=28256800) and my team has done a lot of work to help enhance the language. https://github.com/jart/cosmopolitan/issues/114 

It'd be great to see Janet adopt Bestline. It's a perfect fit for a LISP-like language. It gives you readline parity as well as those famous paredit features from Emacs, while remaining BSD-licensed and easily embeddable.

**Comment by jart** [comment]
One more thing worth mentioning. Bestline i18n doesn't require heavyweight dependencies. Even with all the support for non-Western languages, Bestline actually ends up being half as small as Linenoise at the end of the day! Here's the binary analysis to prove it: https://news.ycombinator.com/item?id=28590403 So you actually get a more lightweight experience while at the same time being more inclusive and accommodating to non-Western users.

**Comment by sogaiu** [comment]
bestline definitely looks nice and as someone who does use non-Western stuff I would also like a nicer experience.

However, IIUC, the linenoise code that was originally included was placed within [this file](https://github.com/janet-lang/janet/blob/9cc4e48124d36f9b986bc4f1ddf948c76f965ca8/src/mainclient/shell.c) and then modified a fair bit.  Actually, I don't know how it came to happen, but my guess is that the description above gives the gist of the current state (happy to be corrected).

So to me at least, it's unclear how much work it would be to get bestline integrated -- apart from the point about not increasing the number of dependencies to the project.

Perhaps if an attempt was made outside of Janet first, some of the costs would be clearer.

Just my 2 cents :)

**Comment by andrewchambers** [comment]
I think we could make a jpm installable version of shell.c that uses bestline - I am not totally sure how to convince jpm to use the right flags, but am quite confident it is possible.

**Comment by bakpakin** [comment]
Closing this issues as this is better implemented as an external package or an alternative shell.c

**Comment by sogaiu** [comment]
Only tested lightly, but building worked and calling `getline` worked too :)
