### ISSUE TITLE
size and dependency of an exe created with janet

### ISSUE THREAD

**Issue by kasajian** [janet-lang/janet#862]
On Windows, I'd like to know what is the size of an EXE created with Janet if the EXE contains everything such that nothing else needs to be distributed.   If there's no way to create such an EXE, then the size of the EXE plus all of the dependencies that need to be deployed along with the program.

I don't know what is the fastest way for me to get this information.   I'm assuming no one has published information about this. 
  I'm willing to do the work myself, but I just want to know the best way to go out about this, and most importantly, whether it's achievable.  Looks like it might be.  If someone is willing to take 5 minutes to jot down the steps they would take, that would help me out.

And secondarily, I'd like to know what the overhead is of using Janet as a replacement for JavaScript.   What is the payload overhead -- as it amount of bytes that need to be deployed for a do-nothing JavaScript script.   If Janet doesn't transpile to JS, that's fine, in that case, the total payload required to run under WebAssembly is what I'd be interested in.

**Comment by andrewchambers** [comment]
The size will be similar to the size of the janet.exe that is distributed - for everything else you should probably test it yourself.

**Comment by kasajian** [comment]
okay, so this sounds like it's not doing any transpiling, translation or even tree-shaking.   However small it is, the entire VM needs to be deployed.    I guess I thought this was something diff than it is.

Thanks anyway.

**Comment by uvtc** [comment]
You might get some answers to this on [the forum](https://github.com/janet-lang/janet/discussions).

Would definitely be cool to see a blog post on this. I haven't tried creating an exe yet, though when I do it will probably be with Jaylib embedded.

**Comment by kasajian** [comment]
> it will probably be with Jaylib embedded.

I had to look up what Jaylib / Raylib were, and to my surprised it was originally based on BGI, which I recall using under DOS in  the late 80s.   Even recall porting it to Forth system (another colleague road a Forth in C, and I showed how easy it is to use C libraries by using Borland's library.   Back then, when you coded in C on DOS, you most likely used Turbo C.

But I digress.

**Comment by bakpakin** [comment]
@kasajian If you are looking for something to compile to standalone executables without much of a runtime, Janet will only get you so far. By default, Janet will compile to an interpreter that is about 600 to 700kB with full options, and with the minimal feature set that will be around 200kB (no networking code, built in documentation, source mapping, PEG engine, etc.). You may be able to play with different compiler and linker options to get it smaller. For built-in C functions, there is no treeshaking. However, with jpm (a companion build tool) there is the option to enable tree shaking in all of your interpreted code, as well as not instantiate the entire core library, although at the moment, the bytecode will still be included in the resulting executable.

**Comment by pepe** [comment]
I am also very interested in this use case for Janet. I would be glad for any information on how it goes. If I get to it soon, I will surely pass the information myself.
