### ISSUE TITLE
`import` only uses final name segment for prefix

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#877]
If I have a module`mod-a` that is on one of my import paths, I can import a submodule `submod-b` of `mod-a` by writing:

```janet
(import mod-a/submod-b)
```

However, if I do this, the bindings in the submodule are prefixed with just `submod-b` and not (as I expected) `mod-a/submod-b`.

Is there a reason to do it this way? Having a fully-qualified prefix would seem to provide better encapsulation than only the final name segment.

**Comment by pepe** [comment]
Just my two cents, but I have no problems taking only the last part as a prefix. Especially as I am using `use` a lot and in many places I use the relative imports with../. 

I would say that it is straightforward to specify prefix with `:prefix`  if you do not like the current way.

**Comment by uvtc** [comment]
Consider, if you do:

~~~janet
(import some-proj/util)
(import other-proj/util)

(util/foo "hey")
~~~

If both util modules contain the `foo` function, I get whichever one that was imported last.

That is,

~~~janet
(import other-proj/util)  # changed import order
(import some-proj/util)

(util/foo "hey")
~~~

may result in different behaviour than the previous snippet.

**Comment by uvtc** [comment]
That said, I suppose the easy solution to that one is to always `:prefix` when importing same-named modules. Perhaps `janet` could even warn if one neglects to do that.

**Comment by elimisteve** [comment]
I really like how it works now -- it's very simple and the names aren't too long -- but if Janet prevented name clashes and didn't let your program run, that when prevent what is basically a variable shadowing problem.

@uvtc Janet code allows such a naming clash right now?

**Comment by uvtc** [comment]
@elimisteve , as it stands, it runs fine, no warning, and it's "last one wins".

One thing I keep forgetting is that it's not like Python, where you import a module and then you have some module object around that you can interact with. The module names + slashes in your program are just names mapped to functions from the module. As I understand it, there's no "packages" like in Python. So, in that case, if you import that 2nd `util` module, Janet is just dutifully mapping that next `util/foo` name to that last module's `util`'s `foo` function like it's supposed to.

**Comment by pyrmont** [comment]
I suppose one difficulty with using more of the segments for the prefix would be where you're using relative imports (e.g. from a test file):

```janet
(import ../src/mod-a)
```

Would bindings from this module now be prefixed with `src/mod-a`? How would Janet know to ignore the `src/`?

**Comment by andrewchambers** [comment]
This was deliberately added a while ago as relative imports were quite cumbersome to use without it. I guess there are pros and cons, though I would just use :prefix to manually name anything that conflicts.

**Comment by pyrmont** [comment]
That all makes sense. Thanks for the clarification and the comments everyone.

I'm content with the solution being to use `:prefix` (am I the only one that uses `:as`?) if I want a fully-qualified name.

**Comment by andrewchambers** [comment]
Now that you mention it, I do use :as.

**Comment by sogaiu** [comment]
Me too :)
