### ISSUE TITLE
Regression in hash performance

### ISSUE THREAD

**Issue by felixr** [janet-lang/janet#889]
It is time for Advent of Code again and I am dusting of my Janet skills and noticed that I ran into similar performance issues like last year. Back then I filed #538 and it resulted in #539 which included changes to how numbers are hashed.

Unfortunately it look like it caused some worse performance for pure number hashtables  #625. The consequence was that the change to number hashing was reverted in b168b0758ac2a800c16c01ea8c209ce4b459cdcf. This has improved the benchmark of issue #625 but made my use cases (tables of tuples) very slow again.

So I tried my original hash function again (https://github.com/felixr/janet/commit/91dbb7c175d0a9e4e7ea3bb3a929e3f03458e429), and it is still fast. And for some reason it also does not impact number hashing performance. I assume it is due to the difference in how the number value is used as input.

To check performance I added the #625 benchmark to my test suite and checked performance for various versions:

![image](https://user-images.githubusercontent.com/1200407/144751922-b59d04ec-44a4-46c9-8986-9b814d178907.png)

Highlighted pink is the version before the number hash was reverted. It clearly shows the bad performance reported in #625, but it performs great in `table_with_tuple_keys`. In the cyan highlight we see the performance after the number hashing was reverted; clearly improved performance in `hash_numbers` but  `table_with_tuple_keys` was terribly slow again.

Now, highlighted green we the latest Janet version with my modified hash function. It performs well in both,  `table_with_tuple_keys` and `hash_numbers`.

I will update my benchmarks at https://github.com/felixr/janet-benchmarks with these latest results for more detailed information. But I am already pretty sure the hash function should be changed once again :-)

**Comment by bakpakin** [comment]
It's incredibly easy to come up with hash functions that will fit a particular benchmark, you can just start fudging numbers until a benchmark seems to work (or not work, depending on the goal). When performance starts to really suffer, all it means that there is some hash collisions or clustering that is causing issues with our open hash table implementation for whatever pattern you picked.

Your original has also did some shady stuff that and just casts all janet numbers to integers. I suspect you could get similar results by multiplying the current hash value by a large prime number to reduce collisions inside the hashtable, or something similar.

**Comment by bakpakin** [comment]
To elaborate some more - the original has function was chosen because I'm am confident that it evenly maps the space of valid floating point numbers to 32 bit integers. Now, it does so in a way that perhaps is not ideally "scrambled" so certain patterns may trigger collisions (or more likely, clustering). Changing up the hash function here is not the only solution, there are other ways such as changing the way bucket collisions are handled - currently we use simple linear probing (changing this has other implications but could also improve perf in degenerate cases).

Your original fix improved on particular use case, but then caused a massive slow down on even more trivial case. Simply rerunning your benchmark and seeing that the problem has "gone away" does not inspire confidence.

**Comment by felixr** [comment]
> It's incredibly easy to come up with hash functions that will fit a particular benchmark.
 ##
I agree, and that is why I am running a set of benchmarks and will happily add any additional benchmark to make sure the hash function is not overfit to a particular use case. I also understand that it is better to have a hash function that you understand and can reason about. I am not saying that I have the solution. I just wanted to point out that the currently used hash functions has issues when used to hash integer tuples. Something that comes up quite frequently in my AoC code, but potentially is not much of an issue for more "normal" code. And I completely understand if you say "This is not a use case I care about, just use string keys instead of tuple keys".

> Simply rerunning your benchmark and seeing that the problem has "gone away" does not inspire confidence.

TBH I was surprised to see that "number hash" benchmark was not impacted when I pretty much used the same hash function again. And it would be good to fully understand what's happening. That is also why I did not send a pull request. While this hash functions seems to work for me, it might not be the right choice.

---- 

Problems with the current interaction of `janet_array_calchash()` and `janet_hash()` (for ints) are that is that if the first the first element of the tuple is `0` the hash value will always be `0`. And if a tuple `[n 0]` has the same has as `[n n]`. So a solution might also be a change in `janet_array_calchash()`. 

<details>
  <summary>Example</summary>


```
0 => 01 => 1072693248[0 0] => 0[0 0] => 0[0 1] => 0
[0 2] => 0
[0 3] => 0
[0 4] => 0
[0 5] => 0
[0 6] => 0
[0 7] => 0
[0 8] => 0
[0 9] => 0
[0 0 100] => 0
[0 1 101] => 0
[0 2 102] => 0
[0 3 103] => 0
[0 4 104] => 0
[0 5 105] => 0
[0 6 106] => 0
[0 7 107] => 0
[0 8 108] => 0
[0 9 109] => 0
[0 0] => 0
[1 0] => 1072693248
[2 0] => 1073741824
[3 0] => 1074266112
[4 0] => 1074790400
[5 0] => 1075052544
[6 0] => 1075314688
[7 0] => 1075576832
[8 0] => 1075838976
[9 0] => 1075970048
[0 0] => 0
[1 1] => 1072693248
[2 2] => 1073741824
[3 3] => 1074266112
[4 4] => 1074790400
[5 5] => 1075052544
[6 6] => 1075314688
[7 7] => 1075576832
[8 8] => 1075838976
[9 9] => 1075970048
```

```
#include <janet/janet.h>
int main() {
    janet_init();
    Janet zero = janet_wrap_number(0);
    printf("0 => %d\n", janet_hash(zero));

    Janet one = janet_wrap_number(1);
    printf("1 => %d\n", janet_hash(one));

    Janet values[3];
    values[0] = janet_wrap_number(0);
    values[1] = janet_wrap_number(0);
    const Janet* zero_tuple = janet_tuple_n(values, 2); 
    printf("[0 0] => %d\n", janet_hash(*zero_tuple));

    for (int i = 0; i<10; i++) {
        values[0] = janet_wrap_number(0);
        values[1] = janet_wrap_number(i);
        const Janet* tuple = janet_tuple_n(values, 2); 
        printf("[0 %d] => %d\n", i, janet_hash(*tuple));
    }

    for (int i = 0; i<10; i++) {
        values[0] = janet_wrap_number(0);
        values[1] = janet_wrap_number(i);
        values[2] = janet_wrap_number(i+100);
        const Janet* tuple = janet_tuple_n(values, 3); 
        printf("[0 %d %d] => %d\n", i, i+100, janet_hash(*tuple));
    }

    for (int i = 0; i<10; i++) {
        values[0] = janet_wrap_number(i);
        values[1] = janet_wrap_number(0);
        const Janet* tuple = janet_tuple_n(values, 2); 
        printf("[%d 0] => %d\n", i, janet_hash(*tuple));
    }

    for (int i = 0; i<10; i++) {
        values[0] = janet_wrap_number(i);
        values[1] = janet_wrap_number(i);
        const Janet* tuple = janet_tuple_n(values, 2); 
        printf("[%d %d] => %d\n", i, i, janet_hash(*tuple));
    }
}
```
</details>

**Comment by felixr** [comment]
Some more information, in case it helps:

We get a lot of collision with tuples eg:
```
(map hash [[734 901] [738 632] [746 311] [754 153] [770 37] [786 828] [790 575] [794 409] [802 202] [834 12]]),
# => @[414434270 414434270 414434270 414434270 414434270 414434270 414434270 414434270 414434270 414434270]
```

If you create 1 million tuples with two values between 0 and 1000. More than 60% will have at least one other tuple with the same hash:
```
# frequencies of collision of the tuples [0 0] to [x y] for all x,y in [0 1000]  
     1  65743 
     2  21528 
     3  66863
     4 117211 
     5  35349 
     6    3501 
     7    1732 
     8    1053 
     9      331 
   10       49
```

<details>
  <summary>Code</summary>

```
(def hashs 
    (seq [i :range [0 1000] j :range [0 1000]] 
      [ (hash [i j]) [i j]]))

(def grouped @{})
(each [h tpl] hashs
  (var l (get grouped h))
  (when (nil? l)
    (set l @[])
    (put grouped h l))
  (array/push l tpl))

(pp (frequencies (map |(length (last $0)) (pairs grouped)))) 

(each [k v] (pairs grouped)
  (if (> (length v) 9)
    (pp [k v])))
```
</details>

<details>
  <summary>Examples</summary>

```                               
(414435806 @[(733 965) (737 696) (745 343) (753 169) (769 41) (785 892) (789 639) (793 441) (801 218) (833 13)])
(414565342 @[(734 837) (738 568) (746 279) (754 137) (770 33) (786 892) (790 639) (794 441) (802 218) (834 13)])
(414566878 @[(733 901) (737 632) (745 311) (753 153) (769 37) (785 956) (789 703) (793 473) (801 234) (833 14)])
(414743006 @[(729 984) (733 723) (737 503) (745 249) (761 63) (789 781) (793 520) (801 271) (809 133) (825 34)])
(414846942 @[(728 984) (732 731) (736 495) (744 249) (760 63) (788 901) (792 648) (800 327) (808 165) (824 42)])
(414872542 @[(730 856) (734 595) (738 439) (746 217) (762 55) (790 781) (794 520) (802 271) (810 133) (826 34)])
(414874078 @[(729 920) (733 659) (737 471) (745 233) (761 59) (789 845) (793 584) (801 303) (809 149) (825 38)])
(414905310 @[(730 872) (734 611) (738 431) (746 213) (762 56) (790 797) (794 536) (802 263) (810 129) (826 35)])
(414906846 @[(729 936) (733 675) (737 463) (745 229) (761 60) (789 861) (793 600) (801 295) (809 145) (825 39)])
(414938078 @[(730 888) (734 627) (738 455) (746 225) (762 53) (790 813) (794 552) (802 287) (810 141) (826 32)])
(414939614 @[(729 952) (733 691) (737 487) (745 241) (761 57) (789 877) (793 616) (801 319) (809 157) (825 36)])
(414970846 @[(730 904) (734 643) (738 447) (746 221) (762 54) (790 829) (794 568) (802 279) (810 137) (826 33)])
(414972382 @[(729 968) (733 707) (737 479) (745 237) (761 58) (789 893) (793 632) (801 311) (809 153) (825 37)])
(414975454 @[(727 984) (731 731) (735 495) (743 249) (759 63) (791 776) (795 523) (799 391) (807 197) (823 50)])
....
```

</details>

**Comment by bakpakin** [comment]
This seems to suggest that something is up with the mixing hash we are using for tuple hashes rather than number hashing.

**Comment by bakpakin** [comment]
Ok, doing some looking here, it seems that the issue is that when we has numbers, we indeed don't have many collisions but the numbers are themselves very close together, i.e. 1 may hash to 1, 2 to 2, and so on (not actually values, but the points still stands).

This is a problem when we mix hashes though, as the mixing expression we are using assumes that bits of entropy are evenly distributed, not all in the high or low bits of the value. We can mostly solve this by multiplying an input by a large prime before doing the add and shift we are doing.

Example of the old "mix" function that we used in a few places:

```c
uint32_t janet_hash_mix(uint32_t input, uint32_t more) {
    return input ^ (more + 0x9e3779b9 + (input << 6) + (input >> 2));
}
```

New mix function with 10 times fewer collisions in the given tuple example:

```c
uint32_t janet_hash_mix(uint32_t input, uint32_t more) {
    return input ^ ((more * 2119589369u) + 0x9e3779b9 + (input << 6) + (input >> 2));
}
```

Collision code:

```
(def f @{})
(var collisions 0)
(loop [x :range [0 1000] y :range [0 1000]]
  (def key (hash [x y]))
  (if (in f key) (++ collisions))
  (put f key true))
(print "collisions: " collisions)
```

Could definitely use some better analyses.

**Comment by felixr** [comment]
Yes, makes sense. Structs as keys work fine:

| n | cnt hashs | cnt items | percent items |
|---|--------|--------|--------|
| 1 | 922455 | 922455 | 92.25% |
| 2 | 36791  | 73582  | 7.36%  |
| 3 | 1281   | 3843   | 0.38%  |
| 4 | 30     | 120    | 0.01%  |

and for tuples with your change above:

| n | cnt hashs | cnt items | percent items |
|---|--------|--------|--------|
|  1 |     850807 |     850807 | 85.08% |
|  2 |      67540 |     135080 | 13.51% |
|  3 |       4320 |      12960 | 1.30% |
|  4 |        268 |       1072 | 0.11% |
|  6 |          1 |          6 | 0.00% |
|  5 |         15 |         75 | 0.01% |

BTW, if you use a table (ie ` (hash @{:x x :y y})`) instead of tuples or struct, things seem also off. Did not want to wait for results... But you probably should not use tables as keys anyways

**Comment by pyrmont** [comment]
Wow! I don't know if there are regressions in other code but the change in 545c09e leads to a dramatic increase in performance for my Advent of Code solution. My script for day 5 goes from taking 15 seconds to taking 3 😲

**Comment by felixr** [comment]
Yes, day 5 of AoC was also the one that make me notice how slow table access with tuple keys was,

@bakpakin Thank you for implementing an improvement so quickly. The new way of combining hashes for tuples definitely performs much better. It is still slightly a bit worse for smaller numbers, but it is not such a big issue anymore.

eg:

```
(def f @{})
(var collisions 0)
(loop [x :range [0 1000] y :range [0 1000]]  (def key (hash [x y]))  (if (in f key) (++ collisions)) (put f key true)) 
(print "collisions: " collisions)
# => collisions: 77412
```

vs

```
(def f @{})
(var collisions 0)
(loop [x :range [100000 101000] y :range [100000 101000]]  (def key (hash [x y]))  (if (in f key) (++ collisions)) (put f key true)) 
(print "collisions: " collisions)
# => collisions: 827
```

In my usage I typically hit the tuples with smaller numbers so I personally would be happier if it performed better for smaller numbers, but that might not be the same for everyone else.

**Comment by felixr** [comment]
Again thanks for another improvement. I thought about it a bit and realised counting collisions is not enough to determine performance for the hashtables. Depending on the capacity of the table only the first couple of bits of the hash value are used.
And I think I found a case where the untruncated hash values do not have any collisions but it looks like linear probing hash table degrades to a linked list.

Eg.:

```
(def f @{})
(var collisions 0)
(loop [x :range [0 1000] y :range [0 1000]]  (def key (hash (string x " " y)))  (if (in f key) (++ collisions)) (put f key true)) 
(print "collisions: " collisions)
```

I takes 60 secs to run using HEAD. But with my weird number hash it takes less than a second. This is not saying "my" number hash is the solution; I just use it as comparison of potential performance. I will try to look into this more carefully when I have some time. I think it would be worth instrumenting the dict lookup loop to check how many tries it takes to find the right number. I ran callgrind and janet_equals gets called a magnitude more than expected.  This is the only "evidence" I currently have.

Anyways, I am not expecting you to respond to every example that I find where the performance could be better, but I wanted to share my findings.

**Comment by bakpakin** [comment]
Yes, this is the case for the Knuth multiplicative hash (which I just added to the hashing algorithm) - the higher bits have better quality than the lower bits. We could switch the high bits and the low bits for some improvements in quality.

**Comment by bakpakin** [comment]
For some reason we were removing three bit of entropy when calculating number hashes which didn't help, and reversing those bits after multiplying by a large prime helped some more so we cut off the "bad bits" rather than the "good bits" when mapping to the hash table.

**Comment by pyrmont** [comment]
Is this issue addressed given the subsequent commits?
