### ISSUE TITLE
Unconditional expression for try or context managers.

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#89]
It might be nice to unconditionally do some action after a try exits has an error, but without catching the error.

**Comment by bakpakin** [comment]
What exactly did you have in mind? You can just put your `finally` code after the try. An example would be helpful.

**Comment by andrewchambers** [comment]
```
 ((touch "file.txt") (try (error "doh") :finally (remove "file.txt")))
```
In this case file is unconditionally deleted, even though an error occurs.

**Comment by andrewchambers** [comment]
As discussed on gitter, another alternative is a with macro similar to python context managers. Not sure how it would look.

**Comment by bakpakin** [comment]
You can try the new `with-resource` macro (name may be changed to `with`, but I think this is fine for now). Similar to python's `with` syntax, we can use it to make sure we clean up a resource. The `with-resource` macro expects a binding, constructing expression, and destructor as well as a body.

```clojure
(with-resource [f (file/open "myfile.txt") file/close]
  (print (:read f :all)))
```
The destructor can optionally be omitted, and :close will be used as the destructor.

```clojure
(with-resource [f (file/open "myfile.txt")]
  (print (:read f :all)))
```

If there is an error, the stacktrace can be preserved using the new `propagate` function, which should make this more useful and seamless than was possible before.

**Comment by andrewchambers** [comment]
great additions, thank you .
