### ISSUE TITLE
Unexpected hang when using both types of the channel

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#892]
I noticed that my scripts sometimes fail to exit when I use both `ev/chan` and `ev/thread-chan`. I have found the simplest reproduction:
```
(def c (ev/chan))
(def tc (ev/thread-chan))

(ev/thread
  (fn [] (ev/give-supervisor :a "a") "c")
  nil :n tc)

(ev/go (coro (ev/give-supervisor :b "b")) nil c)

(var i 2)

(while (tracev (pos? i))
  (def m (ev/select c tc))
  (if (= ((last m) 0) :ok) (-- i))
  (pp m))
```
Prints:
```
> janet test.janet
trace [test.janet] on line 12, column 8: (pos? i) is true
(:take <core/channel 0x564088DBD500> (:a "a"))
trace [test.janet] on line 12, column 8: (pos? i) is true
(:take <core/channel 0x564088DBC9E0> (:b "b"))
trace [test.janet] on line 12, column 8: (pos? i) is true
(:take <core/channel 0x564088DBC9E0> (:ok <fiber 0x564088DBE0A0>))
trace [test.janet] on line 12, column 8: (pos? i) is true
(:take <core/channel 0x564088DBD500> (:ok "c"))
trace [test.janet] on line 12, column 8: (pos? i) is false
```
And hangs. Is this correct behavior? 

There is a simple fix by adding `(:close tc)` at the end of the script.

**Comment by sogaiu** [comment]
FWIW, it also happens on Windows with 6d9286a2021196370ae61ade3552f0382dbe9cc7 and the work-around of adding `(:close tc)` works there too.

I found that occasionally the hanging did not happen on a Linux box but usually it does.

**Comment by pepe** [comment]
Thank you very much, @sogaiu, for reminding me about the failure to provide info about my env. It is void-linux:
`uname -a > Linux pan 5.15.6_1 #1 SMP Wed Dec 1 14:05:25 UTC 2021 x86_64 GNU/Linux` with musl libc: `musl-1.1.24_9`.

And for testing on windows. They are highly appreciated.

**Comment by pepe** [comment]
Wow. Thank you very much!
