### ISSUE TITLE
keywords with tild character

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#90]
Should this be possible? currently quotation aborts the keyword parsing, 
for me this is handy, though I admit the use case is not common.
```
:~/src
```

**Comment by bakpakin** [comment]
This is intentional. Keywords and symbol literals can't contain quote characters right now. Using double quotes or backticks is one extra character, if you don't need a keyword but just any byte sequence.

**Comment by andrewchambers** [comment]
yeah, It's because of the way I abuse keywords and symbols in janetsh - for example 

```
echo ~/
```

should be expanded, but the way my macro deals with expansion is with keywords or symbols.  Currently this means I need to do

``` echo $HOME ``` or ``` echo (expand "~/") ```
