### ISSUE TITLE
WASI-based WebAssembly support

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#911]
The Ruby developers are [currently implementing](https://github.com/ruby/ruby/pull/5407/files) support for WebAssembly using WASI. As the Ruby VM has some of the same characteristics that make WebAssembly support difficult as the Janet VM (notably jumps), I thought it might be useful to track how they do things.

**Comment by sogaiu** [comment]
I see `setjmp` and/or `longjmp` mentioned in the following files in the linked PR:

* configure.ac
* eval_intern.h
* gc.c
* vm_core.h
* wasm/GNUmakefile.in
* wasm/runtime.c
* wasm/setjmp.c
* wasm/setjmp.h
* wasm/setjmp_core.S
* wasm/tests/setjmp_test.c

`wasm/setjmp.c` has the following comment at the top:

> This is a WebAssembly userland setjmp/longjmp implementation based on Binaryen's Asyncify.

**Comment by bakpakin** [comment]
Closing this as non-local returns still aren't really available in web assembly. Current work arounds with Emscripten work for now. Much of the other ruby work here is irrelevant and is already implemented in Janet - once proper setjmp/longjmp is available in a webassembly runtime, things should just work. In the meantime, Janet will not include any hacks for this kind of functionality.
