### ISSUE TITLE
Unexpected quasiquote behavior 

### ISSUE THREAD

**Issue by can-lehmann** [janet-lang/janet#919]
I stumbled upon janet today and encountered some unexpected behavior in the following program:

```clojure
(defn test []
  (var x 1)
  (set x ~(,x ()))
  x)

(pp (test))
```

When running it, I would expect to receive the output `(1 ())`, but instead it prints `(() ())`.

Interestingly, entering the function body directly into the REPL prints the expected result `(1 ())`:

```clojure
(upscope
  (var x 1)
  (set x ~(,x ()))
  x)
```

## Bytecode

Running `(disasm test)` returns the following: 

```clojure
{:arity 0
 :bytecode @[(lds 0) (ldi 1 1) (mktup 1) (push2 1 1) (mktup 1) (ret 1)]
 :constants @[]
 :defs @[]
 :environments @[]
 :max-arity 0
 :min-arity 0
 :name "test"
 :slotcount 2
 :source "test.janet"
 :sourcemap @[(1 1) (2 3) (3 10) (3 10) (3 10) (1 1)]
 :vararg false}
```

## Additional Information

Git Commit: 66e0b53cf655c5981d4e9974d354e3f0240290a8

**Comment by bakpakin** [comment]
Thanks for the bug report, looks like a compiler bug were we are erroneously reusing a register in our interpreter. Fix is incoming.
