### ISSUE TITLE
unknown symbol "break" 

### ISSUE THREAD

**Issue by chenjianxin** [janet-lang/janet#92]
version: 0.4
os: win10
janet:520:> (while true
janet:532:(>  (def x (math/random))
janet:555:(>  (if (> x 0.95) (break))
janet:580:(>  (print x))
compile error: unknown symbol "break" at (572:578) while compiling repl

**Comment by bakpakin** [comment]
Make sure you are up to date with Janet, using version 0.5.0 at least

**Comment by chenjianxin** [comment]
OK I am update to ver.0.5 and it works!
