### ISSUE TITLE
Cancelling a fiber while in a channel operation causes process deadlock

### ISSUE THREAD

**Issue by paulsnar** [janet-lang/janet#920]
Repro:

```janet
(def ch (ev/chan))
(def f1 (fiber-fn :e (ev/take ch)))
(ev/go f1)
(ev/sleep 1e-6) # allow f1 to spawn
(ev/give ch nil) # enqueue f1 to be spawned with value
(cancel f1 true) # then cancel f1 while it's still enqueued to spawn
(ev/sleep 1e-6) # then allow the spawn to happen (this happens naturally when the script exits as well)
```

**Expected outcome:** The event loop exits gracefully, regardless of the outcome of the `ev/give`, given that the channel at that point has no blocked readers or writers.

**Observed outcome:** First, spawning of `f1` fails with::

    error: cannot resume fiber with status :error
      in ev/take [src/core/ev.c] on line 947
      in <anonymous> [repl] on line 2, column 22

Second, after that error, the event loop will never exit, given that `f1` never managed to spawn properly, so the event refcount stays at 1. In part this is intentional, given that the same happens with, e.g., `(ev/go (fiber-fn : (ev/take (ev/chan))))` (indirectly related to #847 and #892), but in this case the scheduling explicitly fails partway and makes it impossible to undeadlock even with non-adversarial code.

Checked with Janet 1.20.0 at master (66e0b53).

### Discussion

Actually, this exposes an interesting problem. Given that `ev/give` doesn't invoke the receiving fiber synchronously, there are at least two ways to handle this: upon cancellation, either the spawn gets dropped, and with it the taken value disappears from the channel; or the cancellation doesn't go through, given that the fiber is already queued to be spawned. Of course, it's also possible for `ev/give` to invoke the handler synchronously (i.e., without spawning) to not drop the value, but that also has its limits given that this might cause the handler to suspend the caller's fiber due to I/O.

**Comment by bakpakin** [comment]
This is a very good observation, and generally cancellation with consistent behavior is pretty difficult, thanks for finding this.

> Actually, this exposes an interesting problem. Given that ev/give doesn't invoke the receiving fiber synchronously, there are at least two ways to handle this: upon cancellation, either the spawn gets dropped, and with it the taken value disappears from the channel; or the cancellation doesn't go through, given that the fiber is already queued to be spawned. Of course, it's also possible for ev/give to invoke the handler synchronously (i.e., without spawning) to not drop the value, but that also has its limits given that this might cause the handler to suspend the caller's fiber due to I/O.

I would prefer to avoid launching work synchronously - it is much easier for me to think about giving to a channel as enqueuing work. In this case, the moment ev/give returned, the value had already been assigned to the fiber f1, so semantically it is fine the the `nil` value is essentially lost forever - it has already been "taken" by f1, and then f1 was canceled.

Probably what should have happened is the fiber should have decremented the refcount when it was scheduled, regardless of whether or not it was resumed successfully.

**Comment by bakpakin** [comment]
Also worth noting that what should be used here is `ev/cancel` instead of the normal `cancel` - cancel is more like "resume with error" in that the cancelled fiber is entered as with `resume` on top of the current fiber - `ev/cancel` on the other hand cancels and continues as usual, letting the fiber's supervisor handle the error.

That said, using the normal cancel here shouldn't bork the event loop.

**Comment by paulsnar** [comment]
Thanks for addressing this -- this approach is more sensible, and the reasoning around cancellation semantics makes sense too, given that normally either the cancellation or the `give` spawn would be serialized in the spawn queue anyway.

Right now though the flag is only set when `continue` takes effect, which still allows the double-schedule to happen, though it's harmless in this case and doesn't hang the process:

```janet
(def f (fiber-fn :e))
(ev/go f)
(cancel f "cancelled") # returns the cancelled value and changes fiber state to :error -- should raise error instead
(ev/sleep 1e-6) # attempts to schedule fiber and prints the "cannot resume fiber with status :error" trace
```

**Comment by paulsnar** [comment]
Er, or rather, I believe this might be a disagreement on whether the fiber "becomes" a root fiber when it is scheduled or only when it actually begins running as one. My reading would be that it should begin to be considered a root fiber as soon as it's put on the spawn queue (via `ev/go` or other means,) but the current implementation is reasonable too.

Either way, the root issue as reported is fixed. Thanks!

**Comment by bakpakin** [comment]
The point about being considered a root immediately when scheduled makes sense, we should probably set the flag unconditionally in janet_schedule. The current solution is nice in that it is agnostic to the ev module (except for an improved error message), but setting the root flag earlier makes sense too and is orthogonal.
