### ISSUE TITLE
Maintaining tables/structs insertion order

### ISSUE THREAD

**Issue by thanhnguyen2187** [janet-lang/janet#925]
Hi,

I am doing data serialization and deserialization with Janet, which depends a lot on keeping the order of dictionary (table) insertions. Apparently, we do not have that within Janet and it caused a lot of hardships for me.

```clojure
(def my-table
  {:c 1
   :b 2
   :a 3})
; expected {:c 1 :b 2 :a 3}
; actual {:a 3 :b 2 :c 1}
(pairs my-table)
; expected @[(:c 1) (:b 2) (:a 3)]
; actual @[(:c 1) (:a 3) (:b 2)]
```

Can we let maintaining insertion order for tables/structs become the default behavior? I think it probably is not an important issue nor easy to implement one, but it is an important nicety of the language that people expect, [like the one from Python](https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6).

Thanks!

**Comment by andrewchambers** [comment]
I would suggest maintaining a separate list or key called :order

**Comment by bakpakin** [comment]
For tables maybe, but for structs probably not going to happen. For structs, `{a b c d}` and `{c d a b}` need to be completely equivalent, and it is efficient to be able to loop over the pairs in order for them. Not sure of as good way to do that with insertion ordered structs.
