### ISSUE TITLE
Using janet_dobytes or janet_dostring with os/ commands causes block to fail to evaluate/return

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#926]
Related to: https://github.com/janet-lang/circlet/issues/17 - I have found a similar issue in my bespoke web server implementation - however, it can be distilled down to the following small snippet fail case:

```c
// gcc -Wall -I./amalg ./amalg/janet.c ./src/janet-os-fail.c -o test.bin -lm
#include <janet.h>
#include <string.h>

char *
janet_stuff ()
{
  JanetTable *env;

  janet_init ();
  env = janet_core_env (NULL);

  Janet ret;
  int h = janet_gclock ();

  // This will fail
  // janet_dostring (env, "(do (os/shell \"whoami\") \"bob\")", "fake", &ret);

  // This will succeed
  janet_dostring (env, "(do \"bob\")", "fake", &ret);

  const unsigned char *result;

  if (janet_checktype (ret, JANET_STRING))
    {
      result = janet_unwrap_string (ret);
    }
  else
    {
      fprintf (stderr, "The string was not returned, woops.");
      result = (uint8_t *) "FAILURE";
    }

  janet_gcunlock (h);
  janet_deinit ();

  return (char *) result;
}

int
main (int argc, char *argv[])
{
  char *res = janet_stuff ();

  fprintf (stdout, res);

  return 0;
}

// Sample output
/* ❯ gcc -Wall -I./amalg ./amalg/janet.c ./src/janet-os-fail.c -o test.bin -lm */
/* ❯ ./test.bin */
/* The string was not returned, woops.FAILURE% */
/* mcarter */
/* ❯ gcc -Wall -I./amalg ./amalg/janet.c ./src/janet-os-fail.c -o test.bin -lm */
/* ❯ ./test.bin */
/* bob% */
```

To reproduce the failure, simply swap the janet_dostring() lines so you execute the one with the os/shell call in it.  It will not finish block evaluation and return the string `"bob"` as it should.

Compare to a valid Janet in the REPL, which will reproduce the behavior as expected.  

```janet
(do (os/shell "whoami") "bob")
mcarter
"bob"
```

FWIW, this is under Janet 1.20 built from the tag

**Comment by ahungry** [comment]
Also - it occurs with or without the gclock, so it doesn't appear to be some obscure issue with having gc locked while os/ is executed.

**Comment by ahungry** [comment]
Interestingly enough, if I wrap the os/ call in an `(ev/spawn-thread)`, the problem goes away.

**Comment by bakpakin** [comment]
Functions that use the event loop must have a call to `janet_loop` to run the event loop to completion. I guess the next question would be, should `janet_dobytes` and `janet_dostring` call janet_loop under the hood - they predate the event loop so currently they don't.
