### ISSUE TITLE
0.0 and -0.0 compare as equal but hash differently

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#928]
This breaks the recursive nature of tuple and struct comparison.
```
(= 0.0 -0.0) # true
(= [0.0] [-0.0]) # false
```
I suppose one fix would be to special case the number hash to detect -0 and mask out the sign bit, or mask out the sign bit entirely.

**Comment by bakpakin** [comment]
Have local fix, but AT&T is fixing my internet right now, will push soon. Also due for a minor release.

**Comment by saikyun** [comment]
Thank you! :D
