### ISSUE TITLE
Possible suggestion: return falsey value on file/read EOF :line / :all

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#93]
currently it seems to return empty buffers, which is consistent, but it would be nice to be able to use if-let while reading lines.

Fine with rejecting this, as it is a backwards incompatible change so shouldn't be made lightly.

**Comment by bakpakin** [comment]
I can rationalize file/read with :line or a byte count returning nil if there are no more bytes, but should :all? Using :all, one could see trying to read an empty file and using the resulting buffer. Changing this could result in getting nil instead of a buffer.

Example:
```clojure
(def f (file/open "empty.txt"))
(def buf (:read f :all))
# Expect a buffer, but could be nil with proposed change
(buffer/push-string buf "---")
```
