### ISSUE TITLE
How to make forward declarations in Janet

### ISSUE THREAD

**Issue by clartaq** [janet-lang/janet#933]
Common Lisp has `declaim` and Clojure has `declare` to make forward declarations of functions that appear earlier in program text than their definitions. Does Janet have something similar or a preferred idiom for accomplishing the same thing?

Currently, I am using `varfn`s something like function prototypes in C. It seems a little contrived though.

Is there a better way?

**Comment by uvtc** [comment]
This may be a good question to ask on [the forum](https://github.com/janet-lang/janet/discussions).

**Comment by sogaiu** [comment]
@clartaq If I understood your description correctly, no, I don't think there's currently a significantly diffferent way.

Below are some examples:

* https://github.com/pyrmont/bencodobi/blob/2a52450c040f2e72b019a6bd08f7e75bc5075b2b/src/bencodobi/decoder.janet#L8-L9
* https://git.sr.ht/~subsetpark/ec/tree/c3bd46baec9f52d7598c609d8a7a91571bfe3412/item/src/print.janet#L8
* https://github.com/ahungry/janet-code/blob/78cff9bf40608b1506742af04327111151488980/cyclic.janet#L1

**Comment by clartaq** [comment]
@sogaiu: Thank you for the pointers to examples.

@uvtc: I didn't know about the Discussions area. Next time, I'll use that for similar questions.

I'll close this now since the `varfn` approach seems to be in use elsewhere.
