### ISSUE TITLE
Simulating C's static variables in Janet

### ISSUE THREAD

**Issue by clartaq** [janet-lang/janet#934]
C provides `static` variables that can be declared within a function that uses them. They are initialized at compile time (I believe) and are scoped to the surrounding function. The surrounding function can mutate them and retain the mutated values between invocations.

Does Janet have a similar facility?

I can use global variables, but it would be preferable to keep the data within the only function that uses it. There are idioms that support this in both Scheme and Common Lisp, but they don't seem to work in Janet. (Or at least I have not been able to make them work.)

**Comment by llmII** [comment]
Does something like below work?

``` janet
(var f nil)
(do
  (var static-var 0)
  (defn get-static [] static-var)
  (set f get-static))
(def get-static f)
```

**Comment by clartaq** [comment]
@llmII Thank you.

Both of your examples work, but I was looking for something more like the second. The canonical approach in Scheme is more like your second example and typically illustrated with a counter. A Janet version based on your suggestion is:

```janet
(def counter ((fn []
                (var static-counter 0)
                (fn [] (++ static-counter)))))
```

As a slightly more complicated example, I wanted to translate an old random number generating algorithm from C:

```c
double algo_647_uniform() {
  static int rng_seed = 12345;
  int32_t k = floor(rng_seed/127773);
  int32_t partial = 16807*(rng_seed - k*127773) - k*2386;
  if (partial < 0)
    rng_seed = partial + INT32_MAX;
  else
    rng_seed = partial;

  return rng_seed*4.656612875e-10;
}
```

Based on your answer, I came up with:

```janet
(def rng ((fn []
            (def int32-max 2147483647)
            (var seed 12345)
            (fn [] (let [k (math/floor(/ seed 127773))
                         partial (- (* 16807 (- seed (* k 127773))) (* k 2386))]
                     (if (< partial 0)
                       (set seed (+ partial int32-max))
                       (set seed partial))
                     (* seed 4.656612875e-10))))))
```

I know it doesn't perfectly simulate the 32-bit integer arithmetic of the original, but it gives the same answers for the few hundred or thousand random numbers I need.

I'll close the issue since you showed me how to do it using Janet's existing facilities.
