### ISSUE TITLE
inconsistent use of parenthesis and bracket in error message

### ISSUE THREAD

**Issue by ClaudeM** [janet-lang/janet#944]
Hi,

In the following error message, the range is given with an opening bracket and a closing parenthesis.

```
repl:28:> (def height @[["doug" 12]
repl:29:([> ["anna" 11]
repl:30:([> ["bob" 13]])
@[("doug" 12) ("anna" 11) ("bob" 13)]

repl:39:> (each h height
repl:40:(> (print (h 0) ": " (h 1)))
doug: 12
anna: 11
bob: 13
error: expected integer key in range [0, 1), got 1
  in _thunk [repl] (tailcall) on line 40, column 19
```

Note also that it is saying that 1 is not in the range [0 1]. This is unexpected.

FYI

Thanks.

**Comment by sogaiu** [comment]
I may be off on this but in mathematical notation `[0, 1)` does not include `1`.

Perhaps that was the intent in the message?

**Comment by ClaudeM** [comment]
The message should not violate the principle of least surprise. It should express the error in language a programmer will understand. Smarter people should discuss this, not me (I am not a native English speaker).

Note that the actual error is unexpected: the loop correctly prints the three items in the array and dies for no apparent reason.

**Comment by pepe** [comment]
Well open/closed bounds are nothing special and very handy for any programmer. And true Janet's errors could have been better. 

Anyway the second problem must be something what happened to the array between lines 30 and 39. I am not at the computer ATM. But it seem to me that there was one more element with only one member. But it is indeed speculation. 

Are you able to create simple reproduction code in the file and report the same behavior?

**Comment by ClaudeM** [comment]
Yes, there was an error in an array/push call between the definition and the print loop. Since the range notation follows a convention and it has been explained, I see clearly what I did wrong.

The question becomes, is the average person reading this error message likely to know the range notation convention?

**Comment by sogaiu** [comment]
I don't have a good answer to that question.

For the few countries I have some experience with I believe that the concept of "half-open interval" and the associated notation can get introduced by or in high school -- perhaps in a class that typically is about preparing for a Calculus class. Though may be not everyone who attends high school takes such classes (or learns / retains the relevant content -- I've definitely forgotten a lot :) ).

**Comment by bakpakin** [comment]
To be honest I assumed that a half open interval (and the notation thereof) was a common convention and widely known:

https://en.wikipedia.org/wiki/Interval_(mathematics)

**Comment by uvtc** [comment]
Yup. Standard notation for those in pre-calc.
