### ISSUE TITLE
(partition string)

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#95]
partition is a function with no string definition, that maybe makes sense. I wouldn't mind implementing it, if it is something that is worth supporting.

**Comment by bakpakin** [comment]
You can conveniently do the same thing with pegs efficiently.

```clojure
# Similar to (partition 4 "abcdefghijklmnopqrstuvwxyz")
(peg/match '(any '(between 1 4 1)) "abcdefghijklmnopqrstuvwxyz")
# -> @["abcd" "efgh" "ijkl" ...]
```

**Comment by andrewchambers** [comment]
I suppose I was just surprised that 'map' and 'reduce' supported strings, but 'partition' didn't.
