### ISSUE TITLE
more informative error message if used def instead of defn

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#950]
If the user accidentally types `def` rather than `defn`:

~~~janet
(def foo
  [x]
  (print (* x x)))

(foo 3)
~~~

The error message is:

~~~
$ ./foo.janet 
./foo.janet:6:10: compile error: unknown symbol x
~~~

I think it would be a nice feature if the compiler was able to suggest that the user may have meant to type `defn`.

I notice that if I change it to:

~~~janet
(var x 5)

(def foo
  [x]
  (print (* x x)))

(foo 3)
~~~

the error message is now

~~~
$ ./foo.janet 
./foo.janet:5:1: compile error: could not add metadata to binding
~~~

**Comment by sogaiu** [comment]
I wonder if this could work well as part of a linter.

**Comment by uvtc** [comment]
I see linter linting was brought up in #644 .

**Comment by uvtc** [comment]
Whoops. Linting docs are at https://janet-lang.org/docs/linting.html .

**Comment by sogaiu** [comment]
I was thinking of an external linter program.

IIUC @pepe has [some bits](https://git.sr.ht/~pepe/jakoune/tree/master/item/jakoune/lint.janet) to do some kinds of linting.

A quick way to get an idea of what it currently does is to examine the calls to `emit`, e.g.
```
(emit ;pos "warning" "`tracev`")
```
let's one know that there is at least one `tracev` form in one's program (which perhaps one might not want to commit).

**Comment by sogaiu** [comment]
@uvtc I tried [b4ec168](https://github.com/janet-lang/janet/commit/b4ec16840112871a0384deda9708b8184e2d355f):
```
$ janet
Janet 1.21.2-b4ec1684 linux/x64 - '(doc)' for help
repl:1:> (def foo
repl:2:(>   [x]
repl:3:(>   (print (* x x)))
repl:1:1: compile error: unexpected form - did you intend to use defn?
```

**Comment by uvtc** [comment]
Thanks!

**Comment by sogaiu** [comment]
Just wanted to add that this has helped me on multiple occasions :)
