### ISSUE TITLE
get, in, synonyms

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#953]
In [the docs for data structures](https://janet-lang.org/docs/data_structures/index.html), it says that `in` is newer than `get`, catches more key errors, and should be preferred to `get`.

But the name "get" is symmetric with `put`, and goes nicely with `get-in`, as in:

~~~
get   get-in
put   put-in
~~~

I never think to use `in`, and the data structures docs even describe `get` first, and have more examples for `get`. I think `get` is the better name for this. I'd like to keep using `get` but get the extra benefits of `in`.

What do you think of the possibility of:

 1. Adding a warning that behaviour of `get` will be changing slightly in the future to do exactly what `in` does.

 2. In the future, make `get` and `in` synonyms for the current `in` implementation.

Thanks.

**Comment by bakpakin** [comment]
They are not the same thing, and nothing in the future is changing with them.

On tables and structs they are mostly the same, but different for other types (arrays, tuples, buffers, strings).

**Comment by uvtc** [comment]
Got it. Thanks for the info.
