### ISSUE TITLE
clarification in doc for os/execute

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet#968]
In the docs for `os/execute`, it contains the expression "return-value". What does "return-value" mean in this context? I thought it might be a function name, but I don't see a function named `return-value` anywhere.

**Comment by pepe** [comment]
First I think, the `return-value` is only meaningful for the `os/spawn`. And I guess it means just the value returned by the `os/spawn` call. It is an abstract `core/process` which has some methods and members, try `(keys (os/spawn ["ls"] :p))` to see them.

But I feel, that it could be good to actually separate `os/execute` and `os/spawn` docs to diminish the confusion. What do you think @bakpakin?

**Comment by bakpakin** [comment]
Yes, that is the case. I suppose we could remove the doc string from os/execute since it applies only to os/spawn.
