### ISSUE TITLE
Configuration to disable file/popen

### ISSUE THREAD

**Issue by rick2600** [janet-lang/janet#974]
There is a flag (`JANET_REDUCED_OS`) to disable some functions that allows to execute system commands (ex: `os/shell`).
As `file/popen`  can be used to execute a system command, it is a good idea to have a flag to disable it too.

**Comment by sogaiu** [comment]
FWIW, [`file/popen` has been deprecated](https://github.com/janet-lang/janet/blob/master/CHANGELOG.md#1141---2021-01-18).

**Comment by bakpakin** [comment]
I guess at this point we may want to finally remove it, it has been deprecated for several versions.

**Comment by bakpakin** [comment]
Currently you can disable file/popen with JANET_NO_PROCESSES, but I will remove it in the next release.
