### ISSUE TITLE
Threading macro and partial

### ISSUE THREAD

**Issue by turbohz** [janet-lang/janet#983]
Hi, 

I got little experience with LISP, only some very minor experience with Clojure.

I got stuck with this code (simplified), which I thought should be fine:

> I know that collisions may happen: It's only an example, and I create the table so collisions cannot happen.

```clojure
(defn invert-table [t] (-> t pairs (partial map reverse) from-pairs))
(invert-table { :one 1 :two 2 }) 
; error: expected iterable type, got <function 0x555A9F30D670>
```
After some head scratching, I found how to make it work (I can't say why or if it's expected):

```clojure
; notice the "double" parens in the partial
(defn invert-table2 [t]
	(-> t pairs ((partial map reverse)) from-pairs)
)
(invert-table2 { :one 1 :two 2 })
; @{1 :one 2 :two}
```

I'm using: janet 1.22.1-dev-94c19575 (Arch Linux)

**Comment by turbohz** [comment]
By the way, the `partial` example in the [JanetDocs examples page](https://janetdocs.com/partial) does not work:

```clojure
(defn add17 (partial + 17))
; compile error: unexpected type in destructuring
```

This works:

```clojure
(def add17 (partial + 17))
; <function 0x55E70EA52210>
(add17 3)
; 20
```

**Comment by bakpakin** [comment]
Generally, this kind of thing is better for the discussion page, or the matrix help channel. Also JanetDocs is a separate project from Janet.
Anyway, here is the solution to your problem:

```janet
(defn invert-table
  [t]
  (->> t pairs (map reverse) from-pairs))
```

Not that you would actually ever write this, as Janet has `invert` in the core library which does that same thing but more efficiently.

**Comment by turbohz** [comment]
Oh, it was so obvious... 

I tried to setup and register Matrix, but I couldn't figure that out either. I'll try again.

Thanks for the tips!
