### ISSUE TITLE
Incorrect and misplaced symlinks after installation

### ISSUE THREAD

**Issue by pdobsan** [janet-lang/janet#99]

**Comment by pdobsan** [comment]
Oops, the title went in without the details. Here they come.
(I have just discovered Janet, the language, great project!)

There are some mishaps with the installation, so after install the result looks like:

    % ls /usr/lib/libjanet.so*
    lrwxrwxrwx 1 root root     13 May 15 11:58 /usr/lib/libjanet.so -> libjanet.so.0*
    lrwxrwxrwx 1 root root     21 May 15 11:58 /usr/lib/libjanet.so.0 -> libjanet.so.1.0.0-dev*
    -rwxr-xr-x 1 root root 411016 May 15 11:58 /usr/lib/libjanet.so.1.0.0-dev*
    % 
    % ls /usr/lib/janet
    total 288
    drwxr-xr-x   2 root root   4096 May 15 11:58 ./
    drwxr-xr-x 201 root root 258048 May 15 11:58 ../
    -rw-r--r--   1 root root   1558 May 15 11:58 bars.janet
    -rw-r--r--   1 root root   5890 May 15 11:58 cook.janet
    -rw-r--r--   1 root root   5601 May 15 11:58 highlight.janet
    lrwxrwxrwx   1 root root     85 May 15 11:58 janet.h -> /XXXX/.cache/pikaur/build/janet-lang-git/pkg/janet-lang-git/usr/include/janet.h
    lrwxrwxrwx   1 root root     89 May 15 11:58 janetconf.h -> /XXXX/.cache/pikaur/build/janet-lang-git/pkg/janet-lang-git/usr/include/janetconf.h
    % 
    % ls /usr/include/janet*
    -rw-r--r-- 1 root root 49831 May 15 11:58 /usr/include/janet.h
    -rw-r--r-- 1 root root  1925 May 15 11:58 /usr/include/janetconf.h

    /usr/include/janet:
    total 44
    drwxr-xr-x   2 root root  4096 May 13 22:06 ./
    drwxr-xr-x 426 root root 36864 May 15 11:58 ../

I have attached a [patch](https://github.com/janet-lang/janet/files/3182447/git-diff.txt). Please note that the include files are not symlinked, I think it is not necessary. Here is the new result:

    % ls /usr/lib/{libjanet.so*,janet}
    lrwxrwxrwx 1 root root     13 May 15 14:24 /usr/lib/libjanet.so -> libjanet.so.1*
    lrwxrwxrwx 1 root root     21 May 15 14:24 /usr/lib/libjanet.so.1 -> libjanet.so.1.0.0-dev*
    -rwxr-xr-x 1 root root 411016 May 15 14:24 /usr/lib/libjanet.so.1.0.0-dev*

    /usr/lib/janet:
    total 280
    drwxr-xr-x   2 root root   4096 May 15 14:25 ./
    drwxr-xr-x 201 root root 258048 May 15 14:25 ../
    -rw-r--r--   1 root root   1558 May 15 14:24 bars.janet
    -rw-r--r--   1 root root   5890 May 15 14:24 cook.janet
    -rw-r--r--   1 root root   5601 May 15 14:24 highlight.janet
    % ls /usr/include/janet
    total 100
    drwxr-xr-x   2 root root  4096 May 15 14:25 ./
    drwxr-xr-x 426 root root 36864 May 15 14:25 ../
    -rw-r--r--   1 root root 49831 May 15 14:24 janet.h
    -rw-r--r--   1 root root  1925 May 15 14:24 janetconf.h

**Comment by bakpakin** [comment]
The symlinks are for the `cook` module, which is a little helper tool for building native modules. I agree that it is a bit strange, but it is really helpful for writing native modules that don't require a complicated build system. Also for backwards compatibility, we should probably leave janet.h and janetconf.h at the top level in /usr/include.

I do agree though symlinking into the cache is definitely bad. I think it would be better to just copy the headers there.

**Comment by pdobsan** [comment]
> The symlinks are for the cook module, which is a little helper tool for building native modules. I agree that it is a bit strange, but it is really helpful for writing native modules that don't require a complicated build system.

Well, hmm, ... I would call a build system a bit unusual if it expects header files from /usr/lib/X instead of /usr/include/X

> Also for backwards compatibility, we should probably leave janet.h and janetconf.h at the top level in /usr/include.

You think they are hardwired by anybody instead of just giving (the standard) search path?
Maybe just symlink them up to .. from /usr/include/janet if that is a real concern.

**Comment by bakpakin** [comment]
You are probably right about the standard search path being ok.

For more explanation on the `cook` module, Janet has a default value for `module/*syspath*` set duraing compilation, which on a default install is `/usr/local/lib/janet`. By putting the janet headers in the lib folder, cook can easily find them without needing to do any searching. We could probably just add some more information like `module/*headerpath*` for pointing to the headers.

**Comment by pdobsan** [comment]
I have looked around in `cook.janet` a bit. Now I understand better what the problem is since meanwhile I was trying to fix something in `circlet` and run immediately into the problem with my new install:

    cc -c build/circlet_lib.janet.c  -I/usr/lib/janet std=c99 -Wall -Wextra -fpic -O2 -o build/circlet_lib.janet.o
    build/circlet_lib.janet.c:1:10: fatal error: janet.h: No such file or directory

> We could probably just add some more information like module/*headerpath* for pointing to the headers.

Yes, it should be fixed something like that for generating a compiler command line with `-I/usr/lib/janet` just doesn't feel right.

**Comment by bakpakin** [comment]
Commit f35b5765d62be4ef3466266e31c0182b565695be adds `module/*headerpath*`, and makes `cook` use it for installation.

**Comment by pdobsan** [comment]
Great! I have just reinstalled `janet-lang-git` from AUR and the install and compiling `circklet` worked as expected.

However, there is a minor detail you missed in my Makefile patch `SONAME` should be `libjanet.so.1`
instead of version `0`.

**Comment by bakpakin** [comment]
The so name has been updated, so I'm closing this issue for now. Reopen if there are still some issues.

**Comment by pdobsan** [comment]
> The so name has been updated,

That should be fine, although I don't see the change coming through yet.

**Comment by bakpakin** [comment]
Ah, forgot to push. See 3331f2fa025b76081021ded54e18202ebde82e5b
